--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."VoltageRegulators-DC-DC-SwitchingControllers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Output Configuration",
  "Supplier Device Package",
  "Function",
  "Library Ref",
  "Frequency - Switching",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage - Supply (Vcc/Vdd)",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Synchronous Rectifier",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Topology",
  "Clock Sync",
  "Control Features",
  "Duty Cycle (Max)",
  "Series",
  "Output Phases",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG CTRLR MULT TOP 10UMAX', 
  'MAX669EUB+', 
  'https://www.digikey.com/en/products/detail/analog-devices-inc-maxim-integrated/MAX669EUB/1512593', 
  'Transistor Driver', 
  'Positive, Isolation Capable', 
  '10-uMAX/uSOP', 
  'Step-Up, Step-Up/Step-Down', 
  'MAXIM MAX668 MAX669', 
  '100kHz ~ 500kHz', 
  'MAX669EUB+-ND', 
  'Active', 
  'Analog Devices Inc./Maxim Integrated', 
  '2023-11-01T22:20:11.363', 
  '1', 
  '1.8V ~ 28V', 
  '=Part Number', 
  '1', 
  '-40°C ~ 85°C (TA)', 
  'No', 
  'https://datasheets.maximintegrated.com/en/ds/MAX668-MAX669.pdf', 
  'MAXIM UMAX-10L U10-2', 
  'Datasheet', 
  'DigiKey', 
  'Boost, Flyback, SEPIC', 
  'Yes', 
  'Enable, Frequency Control', 
  '90%', 
  '-', 
  '1', 
  '3.53', 
  'symbols/Power - Switchmode/SCH - POWER - SWITCHMODE - MAXIM MAX668 MAX669.SCHLIB', 
  'Tube', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - MSOP/PCB - LEADED - MSOP - MAXIM UMAX-10L U10-2.PcbLib'
);

INSERT INTO "altium"."VoltageRegulators-DC-DC-SwitchingControllers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Output Configuration",
  "Supplier Device Package",
  "Function",
  "Library Ref",
  "Frequency - Switching",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage - Supply (Vcc/Vdd)",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Synchronous Rectifier",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Topology",
  "Clock Sync",
  "Control Features",
  "Duty Cycle (Max)",
  "Series",
  "Output Phases",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG CTRLR MULT TOP 10UMAX', 
  'MAX669EUB+T', 
  'https://www.digikey.com/en/products/detail/analog-devices-inc-maxim-integrated/MAX669EUB-T/1522269', 
  'Transistor Driver', 
  'Positive, Isolation Capable', 
  '10-uMAX/uSOP', 
  'Step-Up, Step-Up/Step-Down', 
  'MAXIM MAX668 MAX669', 
  '100kHz ~ 500kHz', 
  'MAX669EUB+CT-ND', 
  'Active', 
  'Analog Devices Inc./Maxim Integrated', 
  '2023-11-01T22:20:31.553', 
  '1', 
  '1.8V ~ 28V', 
  '=Part Number', 
  '1', 
  '-40°C ~ 85°C (TA)', 
  'No', 
  'https://datasheets.maximintegrated.com/en/ds/MAX668-MAX669.pdf', 
  'MAXIM UMAX-10L U10-2', 
  'Datasheet', 
  'DigiKey', 
  'Boost, Flyback, SEPIC', 
  'Yes', 
  'Enable, Frequency Control', 
  '90%', 
  '-', 
  '1', 
  '3.60', 
  'symbols/Power - Switchmode/SCH - POWER - SWITCHMODE - MAXIM MAX668 MAX669.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - MSOP/PCB - LEADED - MSOP - MAXIM UMAX-10L U10-2.PcbLib'
);

INSERT INTO "altium"."VoltageRegulators-DC-DC-SwitchingControllers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Output Configuration",
  "Supplier Device Package",
  "Function",
  "Library Ref",
  "Frequency - Switching",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage - Supply (Vcc/Vdd)",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Synchronous Rectifier",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Topology",
  "Clock Sync",
  "Control Features",
  "Duty Cycle (Max)",
  "Series",
  "Output Phases",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG CTRLR MULT TOP 10UMAX', 
  'MAX668EUB+', 
  'https://www.digikey.com/en/products/detail/analog-devices-inc-maxim-integrated/MAX668EUB/948151', 
  'Transistor Driver', 
  'Positive, Isolation Capable', 
  '10-uMAX/uSOP', 
  'Step-Up, Step-Up/Step-Down', 
  'MAXIM MAX668 MAX669', 
  '100kHz ~ 500kHz', 
  'MAX668EUB+-ND', 
  'Active', 
  'Analog Devices Inc./Maxim Integrated', 
  '2023-11-01T22:21:19.253', 
  '1', 
  '3V ~ 28V', 
  '=Part Number', 
  '1', 
  '-40°C ~ 85°C (TA)', 
  'No', 
  'https://pdfserv.maximintegrated.com/en/ds/MAX668-MAX669.pdf', 
  'MAXIM UMAX-10L U10-2', 
  'Datasheet', 
  'DigiKey', 
  'Boost, Flyback, SEPIC', 
  'Yes', 
  'Enable, Frequency Control', 
  '90%', 
  '-', 
  '1', 
  '3.28', 
  'symbols/Power - Switchmode/SCH - POWER - SWITCHMODE - MAXIM MAX668 MAX669.SCHLIB', 
  'Tube', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - MSOP/PCB - LEADED - MSOP - MAXIM UMAX-10L U10-2.PcbLib'
);

INSERT INTO "altium"."VoltageRegulators-DC-DC-SwitchingControllers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Output Configuration",
  "Supplier Device Package",
  "Function",
  "Library Ref",
  "Frequency - Switching",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage - Supply (Vcc/Vdd)",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Synchronous Rectifier",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Topology",
  "Clock Sync",
  "Control Features",
  "Duty Cycle (Max)",
  "Series",
  "Output Phases",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG CTRLR MULT TOP 10UMAX', 
  'MAX668EUB+T', 
  'https://www.digikey.com/en/products/detail/analog-devices-inc-maxim-integrated/MAX668EUB-T/1521543', 
  'Transistor Driver', 
  'Positive, Isolation Capable', 
  '10-uMAX/uSOP', 
  'Step-Up, Step-Up/Step-Down', 
  'MAXIM MAX668 MAX669', 
  '100kHz ~ 500kHz', 
  'MAX668EUB+TCT-ND', 
  'Active', 
  'Analog Devices Inc./Maxim Integrated', 
  '2023-11-01T22:21:37.800', 
  '1', 
  '3V ~ 28V', 
  '=Part Number', 
  '1', 
  '-40°C ~ 85°C (TA)', 
  'No', 
  'https://datasheets.maximintegrated.com/en/ds/MAX668-MAX669.pdf', 
  'MAXIM UMAX-10L U10-2', 
  'Datasheet', 
  'DigiKey', 
  'Boost, Flyback, SEPIC', 
  'Yes', 
  'Enable, Frequency Control', 
  '90%', 
  '-', 
  '1', 
  '3.32', 
  'symbols/Power - Switchmode/SCH - POWER - SWITCHMODE - MAXIM MAX668 MAX669.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - MSOP/PCB - LEADED - MSOP - MAXIM UMAX-10L U10-2.PcbLib'
);

