--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.03 OHM 1% 2/5W 0603', 
  'WSLP0603R0300FEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0300FEA/9755196', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-WSLP0603R0300FEACT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.353', 
  '1', 
  '6081', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'https://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '30 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.32', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '30 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.025 OHM 1% 2/5W 0603', 
  'WSLP0603R0250FEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0250FEA/9755192', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-WSLP0603R0250FEACT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.377', 
  '1', 
  '6082', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'https://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '25 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.35', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  '25 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.015 OHM 1% 0.4W 0603', 
  'WSLP0603R0150FEB', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0150FEB/2695082', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-WSLP0603R0150FEBCT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.393', 
  '1', 
  '6083', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'https://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '15 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.49', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '15 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.06 OHM 1% 2/5W 0603', 
  'WSLP0603R0600FEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0600FEA/9755215', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-WSLP0603R0600FEACT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.413', 
  '1', 
  '6084', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'https://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '60 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.35', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  '60 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.05 OHM 0.5% 2/5W 0603', 
  'WSLP0603R0500DEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0500DEA/9755211', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-WSLP0603R0500DEACT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.433', 
  '1', 
  '6085', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'https://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±0.5%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '50 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.87', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '50 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.03 OHM 0.5% 2/5W 0603', 
  'WSLP0603R0300DEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0300DEA/9755195', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-WSLP0603R0300DEACT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.450', 
  '1', 
  '6086', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'https://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±0.5%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '30 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.85', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '30 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.04 OHM 1% 2/5W 0603', 
  'WSLP0603R0400FEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0400FEA/9755207', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-WSLP0603R0400FEACT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.463', 
  '1', 
  '6087', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'https://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '40 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.28', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '40 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.1 OHM 0.5% 2/5W 0603', 
  'WSLP0603R1000DEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R1000DEA/9755226', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-WSLP0603R1000DEACT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.473', 
  '1', 
  '6088', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'https://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±0.5%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '100 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.62', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '100 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.02 OHM 0.5% 2/5W 0603', 
  'WSLP0603R0200DEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0200DEA/9755187', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-WSLP0603R0200DEACT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.493', 
  '1', 
  '6089', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'https://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±0.5%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '20 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.86', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '20 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.038 OHM 1% 0.4W 0603', 
  'WSLP0603R0380FEB', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0380FEB/2695092', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  'WSLPA-.038CT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.503', 
  '1', 
  '6090', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'https://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '38 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.49', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '38 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.033 OHM 1% 2/5W 0603', 
  'WSLP0603R0330FEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0330FEA/9755201', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-WSLP0603R0330FEACT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.520', 
  '1', 
  '6091', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'https://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '33 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.32', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '33 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.04 OHM 0.5% 2/5W 0603', 
  'WSLP0603R0400DEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0400DEA/9755206', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-WSLP0603R0400DEACT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.537', 
  '1', 
  '6092', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'https://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±0.5%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '40 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.86', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '40 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.075 OHM 0.5% 2/5W 0603', 
  'WSLP0603R0750DEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0750DEA/9755222', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-WSLP0603R0750DEACT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.547', 
  '1', 
  '6093', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'https://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±0.5%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '75 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.53', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  'Active', 
  '75 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.04 OHM 1% 0.4W 0603', 
  'WSLP0603R0400FEB', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0400FEB/2695094', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  'WSLPA-.04CT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.563', 
  '1', 
  '6094', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '40 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.21', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '40 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.018 OHM 1% 0.4W 0603', 
  'WSLP0603R0180FEB', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0180FEB/2695084', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  'WSLPA-.018CT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.580', 
  '1', 
  '6095', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '18 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.36', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '18 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.075 OHM 1% 0.4W 0603', 
  'WSLP0603R0750FEB', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0750FEB/2695102', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-WSLP0603R0750FEBCT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.600', 
  '1', 
  '6096', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '75 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.44', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '75 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.068 OHM 1% 2/5W 0603', 
  'WSLP0603R0680FEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0680FEA/9758297', 
  '0.021" (0.53mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-10029-1-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.613', 
  '1', 
  '6097', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '68 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.32', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '68 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.068 OHM 1% 0.4W 0603', 
  'WSLP0603R0680FEB', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0680FEB/2695100', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  'WSLPA-.068CT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.630', 
  '1', 
  '6098', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '68 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.49', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '68 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.03 OHM 1% 0.4W 0603', 
  'WSLP0603R0300FEB', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0300FEB/2695090', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  'WSLPA-.03CT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.643', 
  '1', 
  '6099', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '30 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.41', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '30 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.033 OHM 1% 0.4W 0603', 
  'WSLP0603R0330FEB', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0330FEB/2695091', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  'WSLPA-.033CT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.653', 
  '1', 
  '6100', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '33 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.49', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '33 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.051 OHM 1% 0.4W 0603', 
  'WSLP0603R0510FEB', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0510FEB/2695097', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  'WSLPA-.051CT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.663', 
  '1', 
  '6101', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '51 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.44', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '51 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.08 OHM 1% 0.4W 0603', 
  'WSLP0603R0800FEB', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0800FEB/2695103', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  'WSLPA-.08CT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.673', 
  '1', 
  '6102', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '80 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.20', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '80 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.01 OHM 1% 0.4W 0603', 
  'WSLP0603R0100FEB', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0100FEB/2695081', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  'WSLPA-.01CT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.683', 
  '1', 
  '6103', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '10 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.32', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '10 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.05 OHM 1% 2/5W 0603', 
  'WSLP0603R0500FEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0500FEA/9758296', 
  '0.021" (0.53mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-10028-1-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.697', 
  '1', 
  '6104', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '50 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.32', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '50 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.047 OHM 1% 2/5W 0603', 
  'WSLP0603R0470FEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0470FEA/9758295', 
  '0.021" (0.53mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-WSLP0603R0470FEACT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.707', 
  '1', 
  '6105', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '47 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.30', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '47 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.022 OHM 1% 2/5W 0603', 
  'WSLP0603R0220FEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0220FEA/9758294', 
  '0.021" (0.53mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-10026-1-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.720', 
  '1', 
  '6106', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '22 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.32', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '22 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.02 OHM 1% 2/5W 0603', 
  'WSLP0603R0200FEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0200FEA/9758293', 
  '0.021" (0.53mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-10025-1-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.730', 
  '1', 
  '6107', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '20 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.32', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '20 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.015 OHM 1% 2/5W 0603', 
  'WSLP0603R0150FEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0150FEA/9758292', 
  '0.021" (0.53mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-10024-1-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.743', 
  '1', 
  '6108', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '15 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.32', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '15 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.01 OHM 1% 2/5W 0603', 
  'WSLP0603R0100FEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0100FEA/9758291', 
  '0.021" (0.53mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-10023-1-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.753', 
  '1', 
  '6109', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '10 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.24', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  'Active', 
  '10 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.066 OHM 1% 0.4W 0603', 
  'WSLP0603R0660FEB', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0660FEB/2695099', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  'WSLPA-.066CT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.773', 
  '1', 
  '6110', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '66 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.24', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '66 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.06 OHM 1% 0.4W 0603', 
  'WSLP0603R0600FEB', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0600FEB/2695098', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  'WSLPA-.06CT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.783', 
  '1', 
  '6111', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '60 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.32', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '60 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.05 OHM 1% 0.4W 0603', 
  'WSLP0603R0500FEB', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0500FEB/2695096', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  'WSLPA-.05CT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.797', 
  '1', 
  '6112', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '50 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.21', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '50 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.02 OHM 1% 0.4W 0603', 
  'WSLP0603R0200FEB', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0200FEB/2695086', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  'WSLPA-.02CT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.807', 
  '1', 
  '6113', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '20 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.35', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '20 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.1 OHM 1% 0.4W 0603', 
  'WSLP0603R1000FEB', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R1000FEB/2695105', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  'WSLPA-.1CT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.820', 
  '1', 
  '6114', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '100 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.27', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '100 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.09 OHM 1% 0.4W 0603', 
  'WSLP0603R0900FEB', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0900FEB/2695104', 
  '0.023" (0.58mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  'WSLPA-.09CT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.840', 
  '1', 
  '6115', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '90 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.44', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '90 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.075 OHM 1% 2/5W 0603', 
  'WSLP0603R0750FEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0750FEA/9758298', 
  '0.021" (0.53mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-10030-1-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.850', 
  '1', 
  '6116', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '75 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.27', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '75 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.1 OHM 1% 2/5W 0603', 
  'WSLP0603R1000FEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R1000FEA/9758300', 
  '0.021" (0.53mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-10032-1-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.863', 
  '1', 
  '6117', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '100 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.17', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '100 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

INSERT INTO "altium"."Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.08 OHM 1% 2/5W 0603', 
  'WSLP0603R0800FEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0603R0800FEA/9758299', 
  '0.021" (0.53mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-10031-1-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2024-08-02T17:42:32.880', 
  '1', 
  '6118', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'http://www.vishay.com/docs/30122/wslp.pdf', 
  'Vishay WSLP0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  '80 mOhms', 
  '0.4W, 2/5W', 
  'WSLP', 
  '0.27', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '80 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - Vishay WSLP0603.PCBLIB'
);

