--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Embedded-Microcontrollers" (
  "Core Processor",
  "Description",
  "Program Memory Type",
  "Part Number",
  "Ram Size",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Number Of I/O",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage - Supply (Vcc/Vdd)",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Speed",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Peripherals",
  "Supplier 1",
  "Mounting Type",
  "Oscillator Type",
  "Series",
  "Price",
  "Library Path",
  "Core Size",
  "Packaging",
  "Part Status",
  "Connectivity",
  "Program Memory Size",
  "Data Converters",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'ARM® Cortex®-M7', 
  'IC MCU 32BIT 2MB FLASH 169UFBGA', 
  'FLASH', 
  'STM32H743AII6', 
  '1M x 8', 
  'https://www.digikey.com/en/products/detail/stmicroelectronics/STM32H743AII6/10326783', 
  '169-UFBGA (7x7)', 
  '131', 
  '169-UFBGA', 
  'ST MICROELECTRONICS STM32H743A(G-I)IX UFBGA169', 
  '497-STM32H743AII6-ND', 
  'Active', 
  'STMicroelectronics', 
  '2026-01-28T14:15:49.580', 
  '1', 
  '1.62V ~ 3.6V', 
  '451', 
  '=Part Number', 
  '-40°C ~ 85°C (TA)', 
  '480MHz', 
  'https://www.st.com/resource/en/datasheet/stm32h743ai.pdf', 
  'STMICRO UFBGA169 7X7', 
  'Datasheet', 
  'Brown-out Detect/Reset, DMA, I2S, LCD, POR, PWM, WDT', 
  'DigiKey', 
  'Surface Mount', 
  'Internal', 
  'STM32H7', 
  '11.10', 
  'symbols/MCU - STM32/SCH - MCU - STM32 - ST MICROELECTRONICS STM32H743A(G-I)IX UFBGA169.SchLib', 
  '32-Bit', 
  'Tray', 
  'Active', 
  'CANbus, EBI/EMI, Ethernet, I2C, IrDA, LINbus, MDIO, MMC/SD/SDIO, QSPI, SAI, SPDIF, SPI, SWPMI, UART/USART, USB OTG', 
  '2MB (2M x 8)', 
  'A/D 36x16b; D/A 2x12b', 
  'DigiKey Link', 
  'footprints/Leadless - BGA/PCB - LEADLESS - BGA - STMICRO UFBGA169 7X7.PcbLib'
);

INSERT INTO "altium"."Embedded-Microcontrollers" (
  "Core Processor",
  "Description",
  "Program Memory Type",
  "Part Number",
  "Ram Size",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Number Of I/O",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage - Supply (Vcc/Vdd)",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Speed",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Peripherals",
  "Supplier 1",
  "Mounting Type",
  "Oscillator Type",
  "Series",
  "Price",
  "Library Path",
  "Core Size",
  "Packaging",
  "Connectivity",
  "Program Memory Size",
  "Data Converters",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'ARM® Cortex®-M7', 
  'IC MCU 32BIT 1MB FLASH 208LQFP', 
  'FLASH', 
  'STM32H743BGT6', 
  '1M x 8', 
  'https://www.digikey.com/en/products/detail/stmicroelectronics/STM32H743BGT6/12337548', 
  '208-LQFP (28x28)', 
  '168', 
  'ST MICROELECTRONICS STM32H743BGTX LQFP208', 
  '497-STM32H743BGT6-ND', 
  'Active', 
  'STMicroelectronics', 
  '2026-01-28T14:16:43.010', 
  '1', 
  '1.62V ~ 3.6V', 
  '452', 
  '=Part Number', 
  '-40°C ~ 85°C (TA)', 
  '480MHz', 
  'https://www.st.com/resource/en/datasheet/stm32h743zg.pdf', 
  'STM LQFP-208 28x28MM UH', 
  'Datasheet', 
  'Brown-out Detect/Reset, DMA, I2S, LCD, POR, PWM, WDT', 
  'DigiKey', 
  'Surface Mount', 
  'Internal', 
  'STM32H7', 
  '11.24', 
  'symbols/MCU - STM32/SCH - MCU - STM32 - ST MICROELECTRONICS STM32H743BGTX LQFP208.SchLib', 
  '32-Bit', 
  'Tray', 
  'CANbus, EBI/EMI, Ethernet, I2C, IrDA, LINbus, MDIO, MMC/SD/SDIO, QSPI, SAI, SPDIF, SPI, SWPMI, UART/USART, USB OTG', 
  '1MB (1M x 8)', 
  'A/D 36x16b; D/A 2x12b', 
  'DigiKey Link', 
  'footprints/Leaded - LQFP/PCB - LEADED - LQFP - STM LQFP-208 28x28MM UH.PcbLib'
);

INSERT INTO "altium"."Embedded-Microcontrollers" (
  "Core Processor",
  "Description",
  "Program Memory Type",
  "Part Number",
  "Ram Size",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Number Of I/O",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage - Supply (Vcc/Vdd)",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Speed",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Peripherals",
  "Supplier 1",
  "Mounting Type",
  "Oscillator Type",
  "Series",
  "Price",
  "Library Path",
  "Core Size",
  "Packaging",
  "Part Status",
  "Connectivity",
  "Program Memory Size",
  "Data Converters",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'ARM® Cortex®-M7', 
  'IC MCU 32BIT 2MB FLASH 208LQFP', 
  'FLASH', 
  'STM32H743BIT6', 
  '1M x 8', 
  'https://www.digikey.com/en/products/detail/stmicroelectronics/STM32H743BIT6/8257848', 
  '208-LQFP (28x28)', 
  '168', 
  '208-LQFP', 
  'ST MICROELECTRONICS STM32H743BITX LQFP208', 
  '497-18562-ND', 
  'Active', 
  'STMicroelectronics', 
  '2026-01-28T14:17:20.193', 
  '1', 
  '1.62V ~ 3.6V', 
  '453', 
  '=Part Number', 
  '-40°C ~ 85°C (TA)', 
  '480MHz', 
  'https://www.st.com/resource/en/datasheet/stm32h743bi.pdf', 
  'STM LQFP-208 28x28MM UH', 
  'Datasheet', 
  'Brown-out Detect/Reset, DMA, I2S, LCD, POR, PWM, WDT', 
  'DigiKey', 
  'Surface Mount', 
  'Internal', 
  'STM32H7', 
  '12.05', 
  'symbols/MCU - STM32/SCH - MCU - STM32 - ST MICROELECTRONICS STM32H743BITX LQFP208.SchLib', 
  '32-Bit', 
  'Tray', 
  'Active', 
  'CANbus, EBI/EMI, Ethernet, I2C, IrDA, LINbus, MDIO, MMC/SD/SDIO, QSPI, SAI, SPDIF, SPI, SWPMI, UART/USART, USB OTG', 
  '2MB (2M x 8)', 
  'A/D 36x16b; D/A 2x12b', 
  'DigiKey Link', 
  'footprints/Leaded - LQFP/PCB - LEADED - LQFP - STM LQFP-208 28x28MM UH.PcbLib'
);

INSERT INTO "altium"."Embedded-Microcontrollers" (
  "Core Processor",
  "Description",
  "Program Memory Type",
  "Part Number",
  "Ram Size",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Number Of I/O",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage - Supply (Vcc/Vdd)",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Speed",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Peripherals",
  "Supplier 1",
  "Mounting Type",
  "Oscillator Type",
  "Series",
  "Price",
  "Library Path",
  "Core Size",
  "Packaging",
  "Connectivity",
  "Program Memory Size",
  "Data Converters",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'ARM® Cortex®-M7', 
  'IC MCU 32BIT 1MB FLASH 176LQFP', 
  'FLASH', 
  'STM32H743IGT6', 
  '1M x 8', 
  'https://www.digikey.com/en/products/detail/stmicroelectronics/STM32H743IGT6/12337726', 
  '176-LQFP (24x24)', 
  '140', 
  'ST MICROELECTRONICS STM32H743IGTX LQFP176', 
  '497-STM32H743IGT6-ND', 
  'Active', 
  'STMicroelectronics', 
  '2026-01-28T14:19:06.817', 
  '1', 
  '1.62V ~ 3.6V', 
  '454', 
  '=Part Number', 
  '-40°C ~ 85°C (TA)', 
  '480MHz', 
  'https://www.st.com/resource/en/datasheet/stm32h743zg.pdf', 
  'STM LQFP-176 24x24MM 1T', 
  'Datasheet', 
  'Brown-out Detect/Reset, DMA, I2S, LCD, POR, PWM, WDT', 
  'DigiKey', 
  'Surface Mount', 
  'Internal', 
  'STM32H7', 
  '10.02', 
  'symbols/MCU - STM32/SCH - MCU - STM32 - ST MICROELECTRONICS STM32H743IGTX LQFP176.SchLib', 
  '32-Bit', 
  'Tray', 
  'CANbus, EBI/EMI, Ethernet, I2C, IrDA, LINbus, MDIO, MMC/SD/SDIO, QSPI, SAI, SPDIF, SPI, SWPMI, UART/USART, USB OTG', 
  '1MB (1M x 8)', 
  'A/D 36x16b; D/A 2x12b', 
  'DigiKey Link', 
  'footprints/Leaded - LQFP/PCB - LEADED - LQFP - STM LQFP-176 24x24MM 1T.PcbLib'
);

INSERT INTO "altium"."Embedded-Microcontrollers" (
  "Core Processor",
  "Description",
  "Program Memory Type",
  "Part Number",
  "Ram Size",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Number Of I/O",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage - Supply (Vcc/Vdd)",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Speed",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Peripherals",
  "Supplier 1",
  "Mounting Type",
  "Oscillator Type",
  "Series",
  "Price",
  "Library Path",
  "Core Size",
  "Packaging",
  "Part Status",
  "Connectivity",
  "Program Memory Size",
  "Data Converters",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'ARM® Cortex®-M7', 
  'IC MCU 32BIT 2MB FLASH 176UFBGA', 
  'FLASH', 
  'STM32H743IIK6', 
  '1M x 8', 
  'https://www.digikey.com/en/products/detail/stmicroelectronics/STM32H743IIK6/7915905', 
  '176+25UFBGA (10x10)', 
  '140', 
  '201-UFBGA', 
  'ST MICROELECTRONICS STM32H743IIKX UFBGA176', 
  '497-17723-ND', 
  'Active', 
  'STMicroelectronics', 
  '2026-01-28T14:19:50.110', 
  '1', 
  '1.62V ~ 3.6V', 
  '455', 
  '=Part Number', 
  '-40°C ~ 85°C (TA)', 
  '480MHz', 
  'https://www.st.com/resource/en/datasheet/stm32h743bi.pdf', 
  'STM UFBGA-176+25 10x10MM A0E7', 
  'Datasheet', 
  'Brown-out Detect/Reset, DMA, I2S, LCD, POR, PWM, WDT', 
  'DigiKey', 
  'Surface Mount', 
  'Internal', 
  'STM32H7', 
  '11.78', 
  'symbols/MCU - STM32/SCH - MCU - STM32 - ST MICROELECTRONICS STM32H743IIKX UFBGA176.SchLib', 
  '32-Bit', 
  'Tray', 
  'Active', 
  'CANbus, EBI/EMI, Ethernet, I2C, IrDA, LINbus, MDIO, MMC/SD/SDIO, QSPI, SAI, SPDIF, SPI, SWPMI, UART/USART, USB OTG', 
  '2MB (2M x 8)', 
  'A/D 36x16b; D/A 2x12b', 
  'DigiKey Link', 
  'footprints/Leadless - BGA/PCB - LEADLESS - BGA - STM UFBGA-176+25 10x10MM A0E7.PcbLib'
);

INSERT INTO "altium"."Embedded-Microcontrollers" (
  "Core Processor",
  "Description",
  "Program Memory Type",
  "Part Number",
  "Ram Size",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Number Of I/O",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage - Supply (Vcc/Vdd)",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Speed",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Peripherals",
  "Supplier 1",
  "Mounting Type",
  "Oscillator Type",
  "Series",
  "Price",
  "Library Path",
  "Core Size",
  "Packaging",
  "Part Status",
  "Connectivity",
  "Program Memory Size",
  "Data Converters",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'ARM® Cortex®-M7', 
  'IC MCU 32BIT 2MB FLASH 176LQFP', 
  'FLASH', 
  'STM32H743IIT6', 
  '1M x 8', 
  'https://www.digikey.com/en/products/detail/stmicroelectronics/STM32H743IIT6/7915904', 
  '176-LQFP (24x24)', 
  '140', 
  '176-LQFP', 
  'ST MICROELECTRONICS STM32H743IITX LQFP176', 
  '497-17722-ND', 
  'Active', 
  'STMicroelectronics', 
  '2026-01-28T14:20:14.770', 
  '1', 
  '1.62V ~ 3.6V', 
  '456', 
  '=Part Number', 
  '-40°C ~ 85°C (TA)', 
  '480MHz', 
  'https://www.st.com/resource/en/datasheet/stm32h743bi.pdf', 
  'STM LQFP-176 24x24MM 1T', 
  'Datasheet', 
  'Brown-out Detect/Reset, DMA, I2S, LCD, POR, PWM, WDT', 
  'DigiKey', 
  'Surface Mount', 
  'Internal', 
  'STM32H7', 
  '11.36', 
  'symbols/MCU - STM32/SCH - MCU - STM32 - ST MICROELECTRONICS STM32H743IITX LQFP176.SchLib', 
  '32-Bit', 
  'Tray', 
  'Active', 
  'CANbus, EBI/EMI, Ethernet, I2C, IrDA, LINbus, MDIO, MMC/SD/SDIO, QSPI, SAI, SPDIF, SPI, SWPMI, UART/USART, USB OTG', 
  '2MB (2M x 8)', 
  'A/D 36x16b; D/A 2x12b', 
  'DigiKey Link', 
  'footprints/Leaded - LQFP/PCB - LEADED - LQFP - STM LQFP-176 24x24MM 1T.PcbLib'
);

INSERT INTO "altium"."Embedded-Microcontrollers" (
  "Core Processor",
  "Description",
  "Program Memory Type",
  "Part Number",
  "Ram Size",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Number Of I/O",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage - Supply (Vcc/Vdd)",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Speed",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Peripherals",
  "Supplier 1",
  "Mounting Type",
  "Oscillator Type",
  "Series",
  "Price",
  "Library Path",
  "Core Size",
  "Packaging",
  "Part Status",
  "Connectivity",
  "Program Memory Size",
  "Data Converters",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'ARM® Cortex®-M7', 
  'IC MCU 32BIT 2MB FLASH 100TFBGA', 
  'FLASH', 
  'STM32H743VIH6', 
  '1M x 8', 
  'https://www.digikey.com/en/products/detail/stmicroelectronics/STM32H743VIH6/10326786', 
  '100-TFBGA (8x8)', 
  '82', 
  '100-TFBGA', 
  'ST MICROELECTRONICS STM32H743V(G-I)HX TFBGA100', 
  '497-STM32H743VIH6-ND', 
  'Active', 
  'STMicroelectronics', 
  '2026-01-28T14:20:59.633', 
  '1', 
  '1.62V ~ 3.6V', 
  '457', 
  '=Part Number', 
  '-40°C ~ 85°C (TA)', 
  '480MHz', 
  'https://www.st.com/resource/en/datasheet/stm32h743ai.pdf', 
  'STM TFBGA-100 8x8MM', 
  'Datasheet', 
  'Brown-out Detect/Reset, DMA, I2S, LCD, POR, PWM, WDT', 
  'DigiKey', 
  'Surface Mount', 
  'Internal', 
  'STM32H7', 
  '10.35', 
  'symbols/MCU - STM32/SCH - MCU - STM32 - ST MICROELECTRONICS STM32H743V(G-I)HX TFBGA100.SchLib', 
  '32-Bit', 
  'Tray', 
  'Active', 
  'CANbus, EBI/EMI, Ethernet, I2C, IrDA, LINbus, MDIO, MMC/SD/SDIO, QSPI, SAI, SPDIF, SPI, SWPMI, UART/USART, USB OTG', 
  '2MB (2M x 8)', 
  'A/D 36x16b; D/A 2x12b', 
  'DigiKey Link', 
  'footprints/Leadless - BGA/PCB - LEADLESS - BGA - STM TFBGA-100 8x8MM.PcbLib'
);

INSERT INTO "altium"."Embedded-Microcontrollers" (
  "Core Processor",
  "Description",
  "Program Memory Type",
  "Part Number",
  "Ram Size",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Number Of I/O",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage - Supply (Vcc/Vdd)",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Speed",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Peripherals",
  "Supplier 1",
  "Mounting Type",
  "Oscillator Type",
  "Series",
  "Price",
  "Library Path",
  "Core Size",
  "Packaging",
  "Connectivity",
  "Program Memory Size",
  "Data Converters",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'ARM® Cortex®-M7', 
  'IC MCU 32BIT 1MB FLASH 100LQFP', 
  'FLASH', 
  'STM32H743VGT6', 
  '1M x 8', 
  'https://www.digikey.com/en/products/detail/stmicroelectronics/STM32H743VGT6/12337710', 
  '100-LQFP (14x14)', 
  '82', 
  'ST MICROELECTRONICS STM32H743VGTX LQFP100', 
  '497-STM32H743VGT6-ND', 
  'Active', 
  'STMicroelectronics', 
  '2026-01-28T14:21:35.900', 
  '1', 
  '1.71V ~ 3.6V', 
  '458', 
  '=Part Number', 
  '-40°C ~ 85°C (TA)', 
  '480MHz', 
  'https://www.st.com/resource/en/datasheet/stm32h743zg.pdf', 
  'ST LQFP-100 14X14MM', 
  'Datasheet', 
  'Brown-out Detect/Reset, DMA, I2S, LCD, POR, PWM, WDT', 
  'DigiKey', 
  'Surface Mount', 
  'Internal', 
  'STM32H7', 
  '8.82', 
  'symbols/MCU - STM32/SCH - MCU - STM32 - ST MICROELECTRONICS STM32H743VGTX LQFP100.SchLib', 
  '32-Bit', 
  'Tray', 
  'CANbus, EBI/EMI, Ethernet, I2C, IrDA, LINbus, MDIO, MMC/SD/SDIO, QSPI, SAI, SPDIF, SPI, SWPMI, UART/USART, USB OTG', 
  '1MB (1M x 8)', 
  'A/D 36x16b; D/A 2x12b', 
  'DigiKey Link', 
  'footprints/Leadless - LQFP/PCB - LEADLESS - LQFP - ST LQFP-100 14X14MM.PCBLIB'
);

INSERT INTO "altium"."Embedded-Microcontrollers" (
  "Core Processor",
  "Description",
  "Program Memory Type",
  "Part Number",
  "Ram Size",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Number Of I/O",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage - Supply (Vcc/Vdd)",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Speed",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Peripherals",
  "Supplier 1",
  "Mounting Type",
  "Oscillator Type",
  "Series",
  "Price",
  "Library Path",
  "Core Size",
  "Packaging",
  "Part Status",
  "Connectivity",
  "Program Memory Size",
  "Data Converters",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'ARM® Cortex®-M7', 
  'IC MCU 32BIT 2MB FLASH 100LQFP', 
  'FLASH', 
  'STM32H743VIT6', 
  '1M x 8', 
  'https://www.digikey.com/en/products/detail/stmicroelectronics/STM32H743VIT6/7809237', 
  '100-LQFP (14x14)', 
  '82', 
  '100-LQFP', 
  'ST MICROELECTRONICS STM32H743VITX LQFP100', 
  '497-17720-ND', 
  'Active', 
  'STMicroelectronics', 
  '2026-01-28T14:22:41.053', 
  '1', 
  '1.71V ~ 3.6V', 
  '459', 
  '=Part Number', 
  '-40°C ~ 85°C (TA)', 
  '480MHz', 
  'https://www.st.com/resource/en/datasheet/stm32h743bi.pdf', 
  'ST LQFP-100 14X14MM', 
  'Datasheet', 
  'Brown-out Detect/Reset, DMA, I2S, LCD, POR, PWM, WDT', 
  'DigiKey', 
  'Surface Mount', 
  'Internal', 
  'STM32H7', 
  '9.97', 
  'symbols/MCU - STM32/SCH - MCU - STM32 - ST MICROELECTRONICS STM32H743VITX LQFP100.SchLib', 
  '32-Bit', 
  'Tray', 
  'Active', 
  'CANbus, EBI/EMI, Ethernet, I2C, IrDA, LINbus, MDIO, MMC/SD/SDIO, QSPI, SAI, SPDIF, SPI, SWPMI, UART/USART, USB OTG', 
  '2MB (2M x 8)', 
  'A/D 36x16b; D/A 2x12b', 
  'DigiKey Link', 
  'footprints/Leadless - LQFP/PCB - LEADLESS - LQFP - ST LQFP-100 14X14MM.PCBLIB'
);

INSERT INTO "altium"."Embedded-Microcontrollers" (
  "Core Processor",
  "Description",
  "Program Memory Type",
  "Part Number",
  "Ram Size",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Number Of I/O",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage - Supply (Vcc/Vdd)",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Speed",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Peripherals",
  "Supplier 1",
  "Mounting Type",
  "Oscillator Type",
  "Series",
  "Price",
  "Library Path",
  "Core Size",
  "Packaging",
  "Part Status",
  "Connectivity",
  "Program Memory Size",
  "Data Converters",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'ARM® Cortex®-M7', 
  'IC MCU 32BIT 2MB FLASH TFBGA', 
  'FLASH', 
  'STM32H743XIH6', 
  '1M x 8', 
  'https://www.digikey.com/en/products/detail/stmicroelectronics/STM32H743XIH6/7915906', 
  '240+25-TFBGA (14x14)', 
  '168', 
  '265-TFBGA', 
  'ST MICROELECTRONICS STM32H743XIHX TFBGA240', 
  '497-17724-ND', 
  'Active', 
  'STMicroelectronics', 
  '2026-01-28T14:24:17.420', 
  '1', 
  '1.62V ~ 3.6V', 
  '460', 
  '=Part Number', 
  '-40°C ~ 85°C (TA)', 
  '480MHz', 
  'https://www.st.com/resource/en/datasheet/stm32h743bi.pdf', 
  'STM TFBGA-240+25 14x14MM A07U', 
  'Datasheet', 
  'Brown-out Detect/Reset, DMA, I2S, LCD, POR, PWM, WDT', 
  'DigiKey', 
  'Surface Mount', 
  'Internal', 
  'STM32H7', 
  '13.19', 
  'symbols/MCU - STM32/SCH - MCU - STM32 - ST MICROELECTRONICS STM32H743XIHX TFBGA240.SchLib', 
  '32-Bit Single-Core', 
  'Tray', 
  'Active', 
  'CANbus, EBI/EMI, Ethernet, I2C, IrDA, LINbus, MDIO, MMC/SD/SDIO, QSPI, SAI, SPDIF, SPI, SWPMI, UART/USART, USB OTG', 
  '2MB (2M x 8)', 
  'A/D 36x16b; D/A 2x12b', 
  'DigiKey Link', 
  'footprints/Leadless - BGA/PCB - LEADLESS - BGA - STM TFBGA-240+25 14x14MM A07U.PcbLib'
);

INSERT INTO "altium"."Embedded-Microcontrollers" (
  "Core Processor",
  "Description",
  "Program Memory Type",
  "Part Number",
  "Ram Size",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Number Of I/O",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage - Supply (Vcc/Vdd)",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Speed",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Peripherals",
  "Supplier 1",
  "Mounting Type",
  "Oscillator Type",
  "Series",
  "Price",
  "Library Path",
  "Core Size",
  "Packaging",
  "Connectivity",
  "Program Memory Size",
  "Data Converters",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'ARM® Cortex®-M7', 
  'IC MCU 32BIT 1MB FLASH 144LQFP', 
  'FLASH', 
  'STM32H743ZGT6', 
  '1M x 8', 
  'https://www.digikey.com/en/products/detail/stmicroelectronics/STM32H743ZGT6/12337682', 
  '144-LQFP (20x20)', 
  '114', 
  'ST MICROELECTRONICS STM32H743ZGTX LQFP144', 
  '497-STM32H743ZGT6-ND', 
  'Active', 
  'STMicroelectronics', 
  '2026-01-28T14:24:48.007', 
  '1', 
  '1.62V ~ 3.6V', 
  '461', 
  '=Part Number', 
  '-40°C ~ 85°C (TA)', 
  '480MHz', 
  'https://www.st.com/resource/en/datasheet/stm32h743zg.pdf', 
  'ST LQFP-144 20X20MM', 
  'Datasheet', 
  'Brown-out Detect/Reset, DMA, I2S, LCD, POR, PWM, WDT', 
  'DigiKey', 
  'Surface Mount', 
  'Internal', 
  'STM32H7', 
  '9.73', 
  'symbols/MCU - STM32/SCH - MCU - STM32 - ST MICROELECTRONICS STM32H743ZGTX LQFP144.SchLib', 
  '32-Bit', 
  'Tray', 
  'CANbus, EBI/EMI, Ethernet, I2C, IrDA, LINbus, MDIO, MMC/SD/SDIO, QSPI, SAI, SPDIF, SPI, SWPMI, UART/USART, USB OTG', 
  '1MB (1M x 8)', 
  'A/D 36x16b; D/A 2x12b', 
  'DigiKey Link', 
  'footprints/Leadless - LQFP/PCB - LEADLESS - LQFP - ST LQFP-144 20X20MM.PCBLIB'
);

INSERT INTO "altium"."Embedded-Microcontrollers" (
  "Core Processor",
  "Description",
  "Program Memory Type",
  "Part Number",
  "Ram Size",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Number Of I/O",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage - Supply (Vcc/Vdd)",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Speed",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Peripherals",
  "Supplier 1",
  "Mounting Type",
  "Oscillator Type",
  "Series",
  "Price",
  "Library Path",
  "Core Size",
  "Packaging",
  "Part Status",
  "Connectivity",
  "Program Memory Size",
  "Data Converters",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'ARM® Cortex®-M7', 
  'IC MCU 32BIT 2MB FLASH 144LQFP', 
  'FLASH', 
  'STM32H743ZIT6', 
  '1M x 8', 
  'https://www.digikey.com/en/products/detail/stmicroelectronics/STM32H743ZIT6/7809238', 
  '144-LQFP (20x20)', 
  '114', 
  '144-LQFP', 
  'ST MICROELECTRONICS STM32H743ZITX LQFP144', 
  '497-17721-ND', 
  'Active', 
  'STMicroelectronics', 
  '2026-01-28T14:25:59.617', 
  '1', 
  '1.62V ~ 3.6V', 
  '462', 
  '=Part Number', 
  '-40°C ~ 85°C (TA)', 
  '480MHz', 
  'https://www.st.com/resource/en/datasheet/stm32h743bi.pdf', 
  'ST LQFP-144 20X20MM', 
  'Datasheet', 
  'Brown-out Detect/Reset, DMA, I2S, LCD, POR, PWM, WDT', 
  'DigiKey', 
  'Surface Mount', 
  'Internal', 
  'STM32H7', 
  '9.76', 
  'symbols/MCU - STM32/SCH - MCU - STM32 - ST MICROELECTRONICS STM32H743ZITX LQFP144.SchLib', 
  '32-Bit', 
  'Tray', 
  'Active', 
  'CANbus, EBI/EMI, Ethernet, I2C, IrDA, LINbus, MDIO, MMC/SD/SDIO, QSPI, SAI, SPDIF, SPI, SWPMI, UART/USART, USB OTG', 
  '2MB (2M x 8)', 
  'A/D 36x16b; D/A 2x12b', 
  'DigiKey Link', 
  'footprints/Leadless - LQFP/PCB - LEADLESS - LQFP - ST LQFP-144 20X20MM.PCBLIB'
);

