--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Capacitors-Aluminum-Polymer-TH" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Lead Spacing",
  "Voltage - Rated",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Ripple Current @ High Frequency",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP ALUM POLY 680UF 20% 6.3V T/H', 
  'PLF0J681MDO1TD', 
  'https://www.digikey.com/en/products/detail/nichicon/PLF0J681MDO1TD/4991252', 
  '0.512" (13.00mm)', 
  'Radial, Can', 
  '0.197" (5.00mm)', 
  '6.3 V', 
  'Radial, Can', 
  'POLARISED CAPACITOR', 
  '493-14102-1-ND', 
  'Active', 
  'Nichicon', 
  '2023-11-12T21:48:42.303', 
  '1', 
  '5757', 
  '=Value', 
  '-55°C ~ 105°C', 
  'General Purpose', 
  'http://nichicon-us.com/english/products/pdfs/e-plf.pdf', 
  'CAP TH ALPOLY D10.00mm S5.00mm H13.00mm', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '6mOhm', 
  'Through Hole', 
  '0.394" Dia (10.00mm)', 
  '2000 Hrs @ 105°C', 
  'PLF', 
  'Polymer', 
  '0.53', 
  '6.3 A @ 100 kHz', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndBox', 
  'Active', 
  '680 µF', 
  '680 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP TH ALPOLY D10.00mm S5.00mm H13.00mm.PCBLIB'
);

