--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Gain Bandwidth Product",
  "Current - Input Bias",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Voltage - Supply, Single/Dual (±)",
  "ComponentLink2Description",
  "Current - Output / Channel",
  "Footprint Path"
)
VALUES (
  'IC OPAMP GP 1 CIRCUIT SOT23-5', 
  'LMP2011MFX/NOPB', 
  'https://www.digikey.com/en/products/detail/texas-instruments/LMP2011MFX-NOPB/1872224', 
  'Rail-to-Rail', 
  '3 MHz', 
  '3 pA', 
  'SOT-23-5', 
  'SC-74A, SOT-753', 
  'TI LMP2011MF DBV', 
  'LMP2011MFX/NOPBCT-ND', 
  'Active', 
  'Texas Instruments', 
  '2024-03-22T21:05:56.700', 
  '1', 
  'General Purpose', 
  '61', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Flmp2011', 
  'TI SOT-23-5 DBV', 
  'Datasheet', 
  '4V/µs', 
  'DigiKey', 
  '930µA', 
  'Surface Mount', 
  '1', 
  '0.12 µV', 
  'LMP®', 
  '1.14', 
  'symbols/Opamp/SCH - OPAMP - TI LMP2011MF DBV.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2.7V ~ 5.25V', 
  'DigiKey Link', 
  '17 mA', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-5 DBV.PCBLIB'
);

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Gain Bandwidth Product",
  "Current - Input Bias",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Voltage - Supply, Single/Dual (±)",
  "ComponentLink2Description",
  "Current - Output / Channel",
  "Footprint Path"
)
VALUES (
  'IC OPAMP GP 1 CIRCUIT SOT23-5', 
  'LMP2011MF/NOPB', 
  'https://www.digikey.com/en/products/detail/texas-instruments/LMP2011MF-NOPB/723287', 
  'Rail-to-Rail', 
  '3 MHz', 
  '3 pA', 
  'SOT-23-5', 
  'SC-74A, SOT-753', 
  'TI LMP2011MF DBV', 
  'LMP2011MF/NOPBCT-ND', 
  'Active', 
  'Texas Instruments', 
  '2024-03-22T21:06:15.617', 
  '1', 
  'General Purpose', 
  '62', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Flmp2011', 
  'TI SOT-23-5 DBV', 
  'Datasheet', 
  '4V/µs', 
  'DigiKey', 
  '930µA', 
  'Surface Mount', 
  '1', 
  '0.12 µV', 
  'LMP®', 
  '1.35', 
  'symbols/Opamp/SCH - OPAMP - TI LMP2011MF DBV.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2.7V ~ 5.25V', 
  'DigiKey Link', 
  '17 mA', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-5 DBV.PCBLIB'
);

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Gain Bandwidth Product",
  "Current - Input Bias",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Voltage - Supply, Single/Dual (±)",
  "ComponentLink2Description",
  "Current - Output / Channel",
  "Footprint Path"
)
VALUES (
  'IC OPAMP GP 1 CIRCUIT 8SOIC', 
  'LMP2011MA/NOPB', 
  'https://www.digikey.com/en/products/detail/texas-instruments/LMP2011MA-NOPB/723286', 
  'Rail-to-Rail', 
  '3 MHz', 
  '3 pA', 
  '8-SOIC', 
  '8-SOIC (0.154", 3.90mm Width)', 
  'TI LMP2011MA D', 
  'LMP2011MA/NOPB-ND', 
  'Active', 
  'Texas Instruments', 
  '2024-03-22T21:06:47.920', 
  '1', 
  'General Purpose', 
  '63', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Flmp2011', 
  'TI SOIC-8 D', 
  'Datasheet', 
  '4V/µs', 
  'DigiKey', 
  '930µA', 
  'Surface Mount', 
  '1', 
  '0.12 µV', 
  'LMP®', 
  '1.14', 
  'symbols/Opamp/SCH - OPAMP - TI LMP2011MA D.SCHLIB', 
  'Tube', 
  'Active', 
  '2.7V ~ 5.25V', 
  'DigiKey Link', 
  '17 mA', 
  'footprints/Leaded - SOIC/PCB - LEADED - SOIC - TI SOIC-8 D.PCBLIB'
);

