--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 2200PF 50V C0G/NP0 1206', 
  'KGM31BCG1H222FM', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGM31BCG1H222FM/9948410', 
  '1206 (3216 Metric)', 
  '50V', 
  'C0G, NP0', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '478-KGM31BCG1H222FMCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2024-03-11T07:10:05.510', 
  '1', 
  '57308', 
  '=Value', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://datasheets.kyocera-avx.com/C0GNP0-KGM.pdf', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'KGM - C0G', 
  '0.037" (0.94mm)', 
  '0.16', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '2200 pF', 
  '2200 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 4.7UF 25V X5R 1206', 
  'KGM31AR51E475KL', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGM31AR51E475KL/9749288', 
  '1206 (3216 Metric)', 
  '25V', 
  'X5R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '478-KGM31AR51E475KLCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2024-03-11T07:10:05.527', 
  '1', 
  '57309', 
  '=Value', 
  '-55°C ~ 85°C', 
  'General Purpose', 
  'https://datasheets.kyocera-avx.com/cx5r-KGM.pdf', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'KGM - X5R', 
  '0.075" (1.90mm)', 
  '0.11', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '4.7 µF', 
  '4.7 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 4.7UF 25V X5R 1206', 
  'KGM31AR51E475KU', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGM31AR51E475KU/563678', 
  '1206 (3216 Metric)', 
  '25V', 
  'X5R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '478-KGM31AR51E475KUCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2024-03-11T07:10:05.540', 
  '1', 
  '57310', 
  '=Value', 
  '-55°C ~ 85°C', 
  'General Purpose', 
  'https://datasheets.kyocera-avx.com/cx5r-KGM.pdf', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'KGM - X5R', 
  '0.075" (1.90mm)', 
  '0.11', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '4.7 µF', 
  '4.7 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 4.7UF 25V X7R 1206', 
  'KGM31AR71E475KU', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGM31AR71E475KU/2208895', 
  '1206 (3216 Metric)', 
  '25V', 
  'X7R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '478-KGM31AR71E475KUCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2024-03-11T07:10:05.557', 
  '1', 
  '57311', 
  '=Value', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://datasheets.kyocera-avx.com/KGM_X7R.pdf', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'KGM - X7R', 
  '0.075" (1.90mm)', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '4.7 µF', 
  '4.7 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 10UF 25V X7R 1206', 
  'KGM31AR71E106KU', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGM31AR71E106KU/6148996', 
  '1206 (3216 Metric)', 
  '25V', 
  'X7R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '478-KGM31AR71E106KUCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2024-03-11T07:10:05.570', 
  '1', 
  '57312', 
  '=Value', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://datasheets.kyocera-avx.com/KGM_X7R.pdf', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'KGM - X7R', 
  '0.075" (1.90mm)', 
  '0.22', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '10 µF', 
  '10 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 10UF 16V Y5V 1206', 
  'CC1206ZFY5V7BB106', 
  'https://www.digikey.com/en/products/detail/yageo/CC1206ZFY5V7BB106/11492384', 
  '1206 (3216 Metric)', 
  '16V', 
  'Y5V (F)', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '13-CC1206ZFY5V7BB106CT-ND', 
  'Active', 
  'Yageo', 
  '2024-03-11T07:10:05.583', 
  '1', 
  '57313', 
  '=Value', 
  '-30°C ~ 85°C', 
  'General Purpose', 
  'https://www.yageo.com/upload/media/product/app/datasheet/mlcc/upy-gphc_y5v_6_3v-to-50v.pdf', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '-20%, +80%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'CC', 
  '0.049" (1.25mm)', 
  '0.04', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '10 µF', 
  '10 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 1000PF 2KV X7R 1206', 
  'CC1206KFX7RDBB102', 
  'https://www.digikey.com/en/products/detail/yageo/CC1206KFX7RDBB102/11491921', 
  '1206 (3216 Metric)', 
  '2000V (2kV)', 
  'X7R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '13-CC1206KFX7RDBB102CT-ND', 
  'Active', 
  'Yageo', 
  'High Voltage', 
  '2024-03-11T07:10:05.620', 
  '1', 
  '57314', 
  '=Value', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://www.yageo.com/upload/media/product/productsearch/datasheet/mlcc/UPY-NP0X7R_HV_1KV-to-3KV_13.pdf', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'CC', 
  '0.057" (1.45mm)', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '1000 pF', 
  '1000 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 10UF 25V X5R 1206', 
  'GRM319R61E106KA12D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GRM319R61E106KA12D/2334876', 
  '1206 (3216 Metric)', 
  '25V', 
  'X5R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '490-5525-1-ND', 
  'Active', 
  'Murata Electronics', 
  '2024-03-11T07:10:45.073', 
  '1', 
  '57315', 
  '=Part Number', 
  '-55°C ~ 85°C', 
  'General Purpose', 
  'https://www.murata.com/~/media/webrenewal/support/library/catalog/products/capacitor/mlcc/c02e.ashx?la=en-us', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'GRM', 
  '0.037" (0.95mm)', 
  '0.14', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Not For New Designs', 
  '10 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 10UF 16V X7R 1206', 
  'GRM31CR71C106KAC7L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GRM31CR71C106KAC7L/965995', 
  '1206 (3216 Metric)', 
  '16V', 
  'X7R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '490-3911-1-ND', 
  'Active', 
  'Murata Electronics', 
  '2024-03-11T07:10:45.217', 
  '1', 
  '57316', 
  '=Part Number', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://www.murata.com/~/media/webrenewal/support/library/catalog/products/capacitor/mlcc/c02e.ashx?la=en-us', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'GRM', 
  '0.071" (1.80mm)', 
  '0.35', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Not For New Designs', 
  '10 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 0.1UF 250V X7R 1206', 
  'GRM31CR72E104KW03L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GRM31CR72E104KW03L/789390', 
  '1206 (3216 Metric)', 
  '250V', 
  'X7R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '490-3542-1-ND', 
  'Active', 
  'Murata Electronics', 
  '2024-03-11T07:10:45.313', 
  '1', 
  '57317', 
  '=Part Number', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GRM31CR72E104KW03-01.pdf', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'GRM', 
  '0.071" (1.80mm)', 
  '0.17', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Not For New Designs', 
  '0.1 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 10000PF 1KV X7R 1206', 
  'GRM31CR73A103KW03L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GRM31CR73A103KW03L/4905626', 
  '1206 (3216 Metric)', 
  '1000V (1kV)', 
  'X7R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '490-12015-1-ND', 
  'Active', 
  'Murata Electronics', 
  '2024-03-11T07:10:45.327', 
  '1', 
  '57318', 
  '=Part Number', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GRM31CR73A103KW03-01.pdf', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'GRM', 
  '0.071" (1.80mm)', 
  '0.15', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Not For New Designs', 
  '10000 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 2200PF 630V X7R 1206', 
  'GRM31BR72J222KW01L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GRM31BR72J222KW01L/789356', 
  '1206 (3216 Metric)', 
  '630V', 
  'X7R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '490-3508-1-ND', 
  'Active', 
  'Murata Electronics', 
  '2024-03-11T07:10:45.343', 
  '1', 
  '57319', 
  '=Part Number', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GRM31BR72J222KW01-01.pdf', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'GRM', 
  '0.049" (1.25mm)', 
  '0.15', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Not For New Designs', 
  '2200 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 0.022UF 250V X7R 1206', 
  'GRM31BR72E223KW01L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GRM31BR72E223KW01L/789384', 
  '1206 (3216 Metric)', 
  '250V', 
  'X7R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '490-3536-1-ND', 
  'Active', 
  'Murata Electronics', 
  '2024-03-11T07:10:45.453', 
  '1', 
  '57320', 
  '=Part Number', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GRM31BR72E223KW01-01.pdf', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'GRM', 
  '0.049" (1.25mm)', 
  '0.15', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Not For New Designs', 
  '0.022 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 1000PF 1KV X7R 1206', 
  'GRM31BR73A102KW01L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GRM31BR73A102KW01L/789342', 
  '1206 (3216 Metric)', 
  '1000V (1kV)', 
  'X7R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '490-3494-1-ND', 
  'Active', 
  'Murata Electronics', 
  '2024-03-11T07:10:45.467', 
  '1', 
  '57321', 
  '=Part Number', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GRM31BR73A102KW01-01.pdf', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'GRM', 
  '0.049" (1.25mm)', 
  '0.18', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Not For New Designs', 
  '1000 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 470PF 1KV X7R 1206', 
  'GRM31BR73A471KW01L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GRM31BR73A471KW01L/2548132', 
  '1206 (3216 Metric)', 
  '1000V (1kV)', 
  'X7R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '490-6503-1-ND', 
  'Active', 
  'Murata Electronics', 
  '2024-03-11T07:10:45.483', 
  '1', 
  '57322', 
  '=Part Number', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GRM31BR73A471KW01-01.pdf', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'GRM', 
  '0.049" (1.25mm)', 
  '0.18', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Not For New Designs', 
  '470 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 10UF 25V X7R 1206', 
  'GRJ31CR71E106KE11L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GRJ31CR71E106KE11L/5321032', 
  '1206 (3216 Metric)', 
  '25V', 
  'X7R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '490-10940-1-ND', 
  'Active', 
  'Murata Electronics', 
  'Soft Termination', 
  '2024-03-11T07:10:45.503', 
  '1', 
  '57323', 
  '=Part Number', 
  '-55°C ~ 125°C', 
  'Boardflex Sensitive', 
  'https://www.murata.com/~/media/webrenewal/support/library/catalog/products/capacitor/mlcc/c02e.ashx?la=en-us', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'GRJ', 
  '0.075" (1.90mm)', 
  '0.16', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Not For New Designs', 
  '10 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 1UF 50V X7R 1206', 
  'GRM31CR71H105KA61L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GRM31CR71H105KA61L/965922', 
  '1206 (3216 Metric)', 
  '50V', 
  'X7R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '490-3908-1-ND', 
  'Active', 
  'Murata Electronics', 
  '2024-03-11T07:10:45.570', 
  '1', 
  '57324', 
  '=Part Number', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://www.murata.com/~/media/webrenewal/support/library/catalog/products/capacitor/mlcc/c02e.ashx?la=en-us', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'GRM', 
  '0.071" (1.80mm)', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Not For New Designs', 
  '1 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 3300PF 1KV X7R 1206', 
  'GRM31BR73A332KW01L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GRM31BR73A332KW01L/789345', 
  '1206 (3216 Metric)', 
  '1000V (1kV)', 
  'X7R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '490-3497-1-ND', 
  'Active', 
  'Murata Electronics', 
  '2024-03-11T07:10:45.643', 
  '1', 
  '57325', 
  '=Part Number', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GRM31BR73A332KW01-01.pdf', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'GRM', 
  '0.049" (1.25mm)', 
  '0.18', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Not For New Designs', 
  '3300 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 10000PF 630V X7R 1206', 
  'GRM31BR72J103KW01L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GRM31BR72J103KW01L/789360', 
  '1206 (3216 Metric)', 
  '630V', 
  'X7R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '490-3512-1-ND', 
  'Active', 
  'Murata Electronics', 
  '2024-03-11T07:10:45.653', 
  '1', 
  '57326', 
  '=Part Number', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GRM31BR72J103KW01-01.pdf', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'GRM', 
  '0.049" (1.25mm)', 
  '0.12', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Not For New Designs', 
  '10000 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 1UF 100V X7R 1206', 
  'GRM31CR72A105KA01L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GRM31CR72A105KA01L/965923', 
  '1206 (3216 Metric)', 
  '100V', 
  'X7R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '490-3909-1-ND', 
  'Active', 
  'Murata Electronics', 
  '2024-03-11T07:10:45.677', 
  '1', 
  '57327', 
  '=Part Number', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://www.murata.com/~/media/webrenewal/support/library/catalog/products/capacitor/mlcc/c02e.ashx?la=en-us', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'GRM', 
  '0.071" (1.80mm)', 
  '0.24', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Not For New Designs', 
  '1 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 4700PF 1KV X7R 1206', 
  'GRM31BR73A472KW01L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GRM31BR73A472KW01L/789346', 
  '1206 (3216 Metric)', 
  '1000V (1kV)', 
  'X7R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '490-3498-1-ND', 
  'Active', 
  'Murata Electronics', 
  '2024-03-11T07:10:45.717', 
  '1', 
  '57328', 
  '=Part Number', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GRM31BR73A472KW01-01.pdf', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'GRM', 
  '0.061" (1.55mm)', 
  '0.19', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Not For New Designs', 
  '4700 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 0.033UF 250V X7R 1206', 
  'GRM31CR72E333KW03L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GRM31CR72E333KW03L/789385', 
  '1206 (3216 Metric)', 
  '250V', 
  'X7R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '490-3537-1-ND', 
  'Active', 
  'Murata Electronics', 
  '2024-03-11T07:10:45.727', 
  '1', 
  '57329', 
  '=Part Number', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GRM31CR72E333KW03-01.pdf', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'GRM', 
  '0.071" (1.80mm)', 
  '0.19', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Not For New Designs', 
  '0.033 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 2.2UF 25V X7R 1206', 
  'GRM31MR71E225KA93L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GRM31MR71E225KA93L/702632', 
  '1206 (3216 Metric)', 
  '25V', 
  'X7R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '490-3368-1-ND', 
  'Active', 
  'Murata Electronics', 
  '2024-03-11T07:10:45.760', 
  '1', 
  '57330', 
  '=Part Number', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://www.murata.com/~/media/webrenewal/support/library/catalog/products/capacitor/mlcc/c02e.ashx?la=en-us', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'GRM', 
  '0.049" (1.25mm)', 
  '0.06', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Not For New Designs', 
  '2.2 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Ceramic-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 1UF 100V X7R 1206', 
  'GRJ31CR72A105KE11L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GRJ31CR72A105KE11L/5321037', 
  '1206 (3216 Metric)', 
  '100V', 
  'X7R', 
  '1206 (3216 Metric)', 
  'CAPACITOR', 
  '490-10945-1-ND', 
  'Active', 
  'Murata Electronics', 
  'Soft Termination', 
  '2024-03-11T07:10:45.800', 
  '1', 
  '57331', 
  '=Part Number', 
  '-55°C ~ 125°C', 
  'Boardflex Sensitive', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GRJ31CR72A105KE11-01.pdf', 
  'CAP 1206_3216 - 0.8MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'GRJ', 
  '0.075" (1.90mm)', 
  '0.11', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Not For New Designs', 
  '1 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1206_3216 - 0.8MM.PCBLIB'
);

