--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Diodes-TVS" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Voltage - Reverse Standoff (Typ)",
  "Unidirectional Channels",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Power Line Protection",
  "Comment",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '1,8V ESD & EOS PROTECTION', 
  'RCLAMP01811PW.C', 
  'https://www.digikey.com/en/products/detail/semtech-corporation/RCLAMP01811PW-C/21371829', 
  '0402 (1005 Metric)', 
  '2-DFN (1x0.6)', 
  '0402 (1005 Metric)', 
  'DIODE TVS UNI', 
  '600-RCLAMP01811PW.CCT-ND', 
  'Active', 
  '1.8V (Max)', 
  '1', 
  'Semtech Corporation', 
  '2023-11-08T21:43:27.403', 
  '1', 
  '11838', 
  'No', 
  '=Part Number', 
  'General Purpose', 
  'https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/3n000000qRGP/yrY3TB2.aHyQ8RtgmOK7PEWBk8.y_My93bjKfszMCAs', 
  '0402', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  'RailClamp®', 
  'Zener', 
  '0.15', 
  'symbols/Diodes/SCH - DIODES - DIODE TVS UNI.SCHLIB', 
  'TapeAndReel', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - 0402.PCBLIB'
);

INSERT INTO "altium"."Diodes-TVS" (
  "Current - Peak Pulse (10/1000µs)",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Breakdown (Min)",
  "Power - Peak Pulse",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Voltage - Clamping (Max) @ Ipp",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Voltage - Reverse Standoff (Typ)",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Power Line Protection",
  "Bidirectional Channels",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Capacitance @ Frequency",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '6A (8/20µs)', 
  '3,3V ESD & EOS PROTECTION', 
  'UCLAMP03351PW.C', 
  'https://www.digikey.com/en/products/detail/semtech-corporation/UCLAMP03351PW-C/21371831', 
  '0402 (1005 Metric)', 
  '3.8V', 
  '40W', 
  '2-DFN (1x0.6)', 
  '0402 (1005 Metric)', 
  'DIODE TVS', 
  '6.5V', 
  '600-UCLAMP03351PW.CCT-ND', 
  'Active', 
  '3.3V (Max)', 
  'Semtech Corporation', 
  '2023-11-08T21:43:34.393', 
  '1', 
  '11839', 
  'No', 
  '1', 
  '=Part Number', 
  '-40°C ~ 125°C (TA)', 
  'General Purpose', 
  'https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/3n000000qPoT/ng0FFZi8ACANWoaqiIO_glB9bbOFnd4tC4a0u4INqfQ', 
  '4.7pF @ 1MHz', 
  '0402', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  'µClamp®', 
  'Zener', 
  '0.13', 
  'symbols/Diodes/SCH - DIODES - DIODE TVS.SCHLIB', 
  'TapeAndReel', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - 0402.PCBLIB'
);

