--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Connectors-RectangularHeadersFemaleSockets" (
  "Description",
  "Insulation Height",
  "Part Number",
  "ComponentLink2URL",
  "Number Of Positions Loaded",
  "Contact Finish Thickness - Mating",
  "Current Rating (Amps)",
  "Number Of Rows",
  "Contact Type",
  "Material Flammability Rating",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Connector Type",
  "Manufacturer",
  "Style",
  "Pitch - Mating",
  "LastUpdated",
  "Minimum Order",
  "Contact Finish - Mating",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Termination",
  "Supplier 1",
  "Fastening Type",
  "Mounting Type",
  "Number Of Positions",
  "Series",
  "Price",
  "Library Path",
  "Contact Finish - Post",
  "Insulation Color",
  "Packaging",
  "Part Status",
  "Contact Length - Post",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CONN RCPT 5POS 0.1 GOLD PCB', 
  '0.197" (5.00mm)', 
  'MDF7-5S-2.54DSA(56)', 
  'http://digikey.com/product-detail/en/hirose-electric-co-ltd/MDF7-5S-2.54DSA-56/H126273-ND/4285081', 
  'All', 
  '8.00µin (0.203µm)', 
  '3A', 
  '1', 
  'Female Socket', 
  'UL94 V-0', 
  '5 PIN', 
  'H126273-ND', 
  'Active', 
  'Receptacle, Bottom Entry', 
  'Hirose Electric Co Ltd', 
  'Board to Board', 
  '0.100" (2.54mm)', 
  '2025-07-25T16:54:26.727', 
  '1', 
  'Gold', 
  '=Part Number', 
  '-35°C ~ 85°C', 
  'https://www.hirose.com/product/document?clcode=&productname=&series=MDF7&documenttype=Catalog&lang=en&documentid=D49417_en', 
  'Hirose MDF7-5S-2.54DSA', 
  'Datasheet', 
  'Solder', 
  'DigiKey', 
  'Push-Pull', 
  'Through Hole', 
  '5', 
  'MDF7', 
  '1.42', 
  'symbols/Connectors/SCH - CONNECTORS - 5 PIN.SCHLIB', 
  'Tin', 
  'Black', 
  'Bulk', 
  'Active', 
  '0.118" (3.00mm)', 
  'DigiKey Link', 
  'footprints/Connector - Hirose/PCB - CONNECTOR - HIROSE - Hirose MDF7-5S-2.54DSA.PCBLIB'
);

