--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 500 OHM 0.25W J LEAD TOP', 
  '3224W-1-501G', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3224W-1-501G/2535284', 
  '±100ppm/°C', 
  '12', 
  'POTENTIOMETER', 
  '118-3224W-1-501GCT-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2023-06-13T21:33:01.867', 
  '1', 
  '353', 
  'Top Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/Product-Datasheets/3224.pdf', 
  'BOURNS TRIMPOT 3224W', 
  'J Lead', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount', 
  'Rectangular - 0.189" x 0.138" Face (4.80mm x 3.50mm)', 
  '500 Ohms', 
  '0.25W, 1/4W', 
  'Trimpot® 3224 - Sealed', 
  '2.18', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '500 Ohms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3224W.PCBLIB'
);

