--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 20 OHM 0.5W PC PIN TOP', 
  '3386P-1-200', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3386P-1-200/2537204', 
  '±100ppm/°C', 
  '1', 
  'POTENTIOMETER', 
  '118-3386P-1-200-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2024-06-02T20:19:53.780', 
  '1', 
  '362', 
  'Top Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/Product-Datasheets/3386.pdf', 
  'BOURNS TRIMPOT 3386P-1', 
  'PC Pins', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Through Hole', 
  'Square - 0.375" x 0.375" Face (9.53mm x 9.53mm)', 
  '20 Ohms', 
  '0.5W, 1/2W', 
  'Trimpot® 3386 - Sealed', 
  '1.18', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'Tube', 
  '20 Ohms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3386P-1.PCBLIB'
);

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 250K OHM 0.5W PC PIN TOP', 
  '3362P-1-254', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3362P-1-254/2536626', 
  '±100ppm/°C', 
  '1', 
  'POTENTIOMETER', 
  '118-3362P-1-254-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2024-06-02T20:19:55.070', 
  '1', 
  '363', 
  'Top Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/Product-Datasheets/3362.pdf', 
  'BOURNS TRIMPOT 3362P-1', 
  'PC Pins', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Through Hole', 
  'Rectangular - 0.275" x 0.260" Face (6.99mm x 6.60mm)', 
  '250 kOhms', 
  '0.5W, 1/2W', 
  'Trimpot® 3362 - Sealed', 
  '0.89', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'Tube', 
  '250 kOhms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3362P-1.PCBLIB'
);

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 30K OHM 0.5W PC PIN TOP', 
  '3362P-1-303LF', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3362P-1-303LF/2536633', 
  '±100ppm/°C', 
  '1', 
  'POTENTIOMETER', 
  '118-3362P-1-303LF-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2024-06-02T20:19:55.093', 
  '1', 
  '364', 
  'Top Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/Product-Datasheets/3362.pdf', 
  'BOURNS TRIMPOT 3362P-1', 
  'PC Pins', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Through Hole', 
  'Rectangular - 0.275" x 0.260" Face (6.99mm x 6.60mm)', 
  '30 kOhms', 
  '0.5W, 1/2W', 
  'Trimpot® 3362 - Sealed', 
  '0.46', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'Tube', 
  '30 kOhms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3362P-1.PCBLIB'
);

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 50 OHM 0.5W PC PIN TOP', 
  '3362P-1-500', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3362P-1-500/2536638', 
  '±100ppm/°C', 
  '1', 
  'POTENTIOMETER', 
  '118-3362P-1-500-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2024-06-02T20:19:55.123', 
  '1', 
  '365', 
  'Top Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/Product-Datasheets/3362.pdf', 
  'BOURNS TRIMPOT 3362P-1', 
  'PC Pins', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Through Hole', 
  'Rectangular - 0.275" x 0.260" Face (6.99mm x 6.60mm)', 
  '50 Ohms', 
  '0.5W, 1/2W', 
  'Trimpot® 3362 - Sealed', 
  '0.89', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'Tube', 
  '50 Ohms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3362P-1.PCBLIB'
);

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 100K OHM 0.5W PC PIN TOP', 
  '3362P-1-104RLF', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3362P-1-104RLF/4697008', 
  '±100ppm/°C', 
  '1', 
  'POTENTIOMETER', 
  '118-3362P-1-104RLFCT-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2024-06-02T20:19:55.150', 
  '1', 
  '366', 
  'Top Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/Product-Datasheets/3362.pdf', 
  'BOURNS TRIMPOT 3362P-1', 
  'PC Pins', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Through Hole', 
  'Rectangular - 0.275" x 0.260" Face (6.99mm x 6.60mm)', 
  '100 kOhms', 
  '0.5W, 1/2W', 
  'Trimpot® 3362 - Sealed', 
  '0.83', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'TapeAndReel', 
  '100 kOhms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3362P-1.PCBLIB'
);

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 1M OHM 0.5W PC PIN TOP', 
  '3296W-1-105RLF', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3296W-1-105RLF/16356636', 
  '±100ppm/°C', 
  '25', 
  'POTENTIOMETER', 
  '118-3296W-1-105RLFCT-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2024-06-02T20:20:13.813', 
  '1', 
  '367', 
  'Top Adjustment', 
  '=Value', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/6130/3296.pdf', 
  'BOURNS TRIMPOT 3296W', 
  'PC Pins', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Through Hole', 
  'Rectangular - 0.375" x 0.190" Face (9.53mm x 4.83mm)', 
  '1 MOhms', 
  '0.5W, 1/2W', 
  'Trimpot® 3296 - Sealed', 
  '1.65', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'TapeAndReel', 
  '1 MOhms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3296W.PCBLIB'
);

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 1K OHM 0.5W PC PIN TOP', 
  '3296W-1-102ALF', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3296W-1-102ALF/2535861', 
  '±100ppm/°C', 
  '25', 
  'POTENTIOMETER', 
  '118-3296W-1-102ALFCT-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2024-06-02T20:20:13.837', 
  '1', 
  '368', 
  'Top Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/product-datasheets/3296.pdf', 
  'BOURNS TRIMPOT 3296W', 
  'PC Pins', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Through Hole', 
  'Rectangular - 0.375" x 0.190" Face (9.53mm x 4.83mm)', 
  '1 kOhms', 
  '0.5W, 1/2W', 
  'Trimpot® 3296 - Sealed', 
  '1.65', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'TapeAndBox', 
  '1 kOhms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3296W.PCBLIB'
);

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 50 OHM 0.5W PC PIN TOP', 
  '3296W-1-500', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3296W-1-500/84481', 
  '±100ppm/°C', 
  '25', 
  'POTENTIOMETER', 
  '118-3296W-1-500-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2024-06-02T20:20:13.853', 
  '1', 
  '369', 
  'Top Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/product-datasheets/3296.pdf', 
  'BOURNS TRIMPOT 3296W', 
  'PC Pins', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Through Hole', 
  'Rectangular - 0.375" x 0.190" Face (9.53mm x 4.83mm)', 
  '50 Ohms', 
  '0.5W, 1/2W', 
  'Trimpot® 3296 - Sealed', 
  '1.94', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'Tube', 
  '50 Ohms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3296W.PCBLIB'
);

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 10 OHM 0.5W PC PIN TOP', 
  '3296W-1-100ALF', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3296W-1-100ALF/2535853', 
  '±100ppm/°C', 
  '25', 
  'POTENTIOMETER', 
  '118-3296W-1-100ALFCT-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2024-06-02T20:20:13.873', 
  '1', 
  '370', 
  'Top Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/product-datasheets/3296.pdf', 
  'BOURNS TRIMPOT 3296W', 
  'PC Pins', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Through Hole', 
  'Rectangular - 0.375" x 0.190" Face (9.53mm x 4.83mm)', 
  '10 Ohms', 
  '0.5W, 1/2W', 
  'Trimpot® 3296 - Sealed', 
  '1.65', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'TapeAndBox', 
  '10 Ohms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3296W.PCBLIB'
);

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 50 OHM 0.5W PC PIN TOP', 
  '3296W-1-500RLF', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3296W-1-500RLF/2535934', 
  '±100ppm/°C', 
  '25', 
  'POTENTIOMETER', 
  '118-3296W-1-500RLFCT-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2024-06-02T20:20:13.880', 
  '1', 
  '371', 
  'Top Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/product-datasheets/3296.pdf', 
  'BOURNS TRIMPOT 3296W', 
  'PC Pins', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Through Hole', 
  'Rectangular - 0.375" x 0.190" Face (9.53mm x 4.83mm)', 
  '50 Ohms', 
  '0.5W, 1/2W', 
  'Trimpot® 3296 - Sealed', 
  '1.65', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'TapeAndReel', 
  '50 Ohms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3296W.PCBLIB'
);

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 50 OHM 0.5W PC PIN SIDE', 
  '3299P-1-500LF', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3299P-1-500LF/1060385', 
  '±100ppm/°C', 
  '25', 
  'POTENTIOMETER', 
  '118-3299P-1-500LF-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2024-06-02T20:20:17.360', 
  '1', 
  '372', 
  'Side Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/Product-Datasheets/3299.pdf', 
  'BOURNS TRIMPOT 3299P', 
  'PC Pins', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Through Hole', 
  'Rectangular - 0.240" x 0.375" Face (6.10mm x 9.53mm)', 
  '50 Ohms', 
  '0.5W, 1/2W', 
  'Trimpot® 3299 - Sealed', 
  '1.61', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'Tube', 
  '50 Ohms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3299P.PCBLIB'
);

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 20 OHM 0.5W PC PIN SIDE', 
  '3299P-1-200LF', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3299P-1-200LF/1088124', 
  '±100ppm/°C', 
  '25', 
  'POTENTIOMETER', 
  '118-3299P-1-200LF-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2024-06-02T20:20:17.367', 
  '1', 
  '373', 
  'Side Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/Product-Datasheets/3299.pdf', 
  'BOURNS TRIMPOT 3299P', 
  'PC Pins', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Through Hole', 
  'Rectangular - 0.240" x 0.375" Face (6.10mm x 9.53mm)', 
  '20 Ohms', 
  '0.5W, 1/2W', 
  'Trimpot® 3299 - Sealed', 
  '1.61', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'Tube', 
  '20 Ohms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3299P.PCBLIB'
);

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 250KOHM 0.5W PC PIN SIDE', 
  '3299P-1-254LF', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3299P-1-254LF/1060384', 
  '±100ppm/°C', 
  '25', 
  'POTENTIOMETER', 
  '118-3299P-1-254LF-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2024-06-02T20:20:17.373', 
  '1', 
  '374', 
  'Side Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/Product-Datasheets/3299.pdf', 
  'BOURNS TRIMPOT 3299P', 
  'PC Pins', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Through Hole', 
  'Rectangular - 0.240" x 0.375" Face (6.10mm x 9.53mm)', 
  '250 kOhms', 
  '0.5W, 1/2W', 
  'Trimpot® 3299 - Sealed', 
  '1.61', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'Tube', 
  '250 kOhms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3299P.PCBLIB'
);

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 100KOHM 0.5W PC PIN SIDE', 
  '3299P-1-104', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3299P-1-104/84317', 
  '±100ppm/°C', 
  '25', 
  'POTENTIOMETER', 
  '118-3299P-1-104-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2024-06-02T20:20:17.400', 
  '1', 
  '375', 
  'Side Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/Product-Datasheets/3299.pdf', 
  'BOURNS TRIMPOT 3299P', 
  'PC Pins', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Through Hole', 
  'Rectangular - 0.240" x 0.375" Face (6.10mm x 9.53mm)', 
  '100 kOhms', 
  '0.5W, 1/2W', 
  'Trimpot® 3299 - Sealed', 
  '2.59', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'Tube', 
  '100 kOhms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3299P.PCBLIB'
);

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 500KOHM 0.25W J LEAD TOP', 
  '3224W-2-504E', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3224W-2-504E/2535299', 
  '±100ppm/°C', 
  '12', 
  'POTENTIOMETER', 
  '118-3224W-2-504ECT-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2024-06-02T20:20:18.650', 
  '1', 
  '376', 
  'Top Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/Product-Datasheets/3224.pdf', 
  'BOURNS TRIMPOT 3224W', 
  'J Lead', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount', 
  'Rectangular - 0.189" x 0.138" Face (4.80mm x 3.50mm)', 
  '500 kOhms', 
  '0.25W, 1/4W', 
  'Trimpot® 3224 - Sealed', 
  '2.18', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'TapeAndReel', 
  '500 kOhms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3224W.PCBLIB'
);

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 200KOHM 0.25W J LEAD TOP', 
  '3224W-2-204E', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3224W-2-204E/2535296', 
  '±100ppm/°C', 
  '12', 
  'POTENTIOMETER', 
  '118-3224W-2-204ECT-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2024-06-02T20:20:18.677', 
  '1', 
  '377', 
  'Top Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/Product-Datasheets/3224.pdf', 
  'BOURNS TRIMPOT 3224W', 
  'J Lead', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount', 
  'Rectangular - 0.189" x 0.138" Face (4.80mm x 3.50mm)', 
  '200 kOhms', 
  '0.25W, 1/4W', 
  'Trimpot® 3224 - Sealed', 
  '2.18', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'TapeAndReel', 
  '200 kOhms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3224W.PCBLIB'
);

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 1M OHM 0.25W J LEAD TOP', 
  '3224W-1-105G', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3224W-1-105G/2535269', 
  '±100ppm/°C', 
  '12', 
  'POTENTIOMETER', 
  '118-3224W-1-105GCT-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2024-06-02T20:20:18.823', 
  '1', 
  '378', 
  'Top Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/Product-Datasheets/3224.pdf', 
  'BOURNS TRIMPOT 3224W', 
  'J Lead', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount', 
  'Rectangular - 0.189" x 0.138" Face (4.80mm x 3.50mm)', 
  '1 MOhms', 
  '0.25W, 1/4W', 
  'Trimpot® 3224 - Sealed', 
  '2.18', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'TapeAndReel', 
  '1 MOhms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3224W.PCBLIB'
);

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 1KOHM 0.5W GULL WING TOP', 
  '3361P-1-102G', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3361P-1-102G/334197', 
  '±100ppm/°C', 
  '1', 
  'POTENTIOMETER', 
  '118-3361P-1-102GCT-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2024-06-02T20:20:19.673', 
  '1', 
  '379', 
  'Top Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/Product-Datasheets/3361.pdf', 
  'BOURNS TRIMPOT 3361P', 
  'Gull Wing', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount', 
  'Rectangular - 0.277" x 0.264" Face (7.04mm x 6.70mm)', 
  '1 kOhms', 
  '0.5W, 1/2W', 
  'Trimpot® 3361 - Sealed', 
  '0.85', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'TapeAndReel', 
  '1 kOhms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3361P.PCBLIB'
);

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 50K OHM 0.5W GW TOP ADJ', 
  '3361P-1-503G', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3361P-1-503G/334202', 
  '±100ppm/°C', 
  '1', 
  'POTENTIOMETER', 
  '118-3361P-1-503GCT-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2024-06-02T20:20:19.693', 
  '1', 
  '380', 
  'Top Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/Product-Datasheets/3361.pdf', 
  'BOURNS TRIMPOT 3361P', 
  'Gull Wing', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount', 
  'Rectangular - 0.277" x 0.264" Face (7.04mm x 6.70mm)', 
  '50 kOhms', 
  '0.5W, 1/2W', 
  'Trimpot® 3361 - Sealed', 
  '0.85', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'TapeAndReel', 
  '50 kOhms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3361P.PCBLIB'
);

