--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."PowerSupplies-BoardMount-DC-DC-Converters" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Voltage - Input (Max)",
  "Current - Output (Max)",
  "Supplier Device Package",
  "Voltage - Input (Min)",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Applications",
  "Footprint Ref",
  "Supplier 1",
  "Voltage - Output 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DC DC CONVERTER 0.9-12V', 
  'MAXM17632AME+T', 
  'https://www.digikey.com/en/products/detail/analog-devices-inc-maxim-integrated/MAXM17632AME-T/12460952', 
  '36V', 
  '1A', 
  '16-eMGA (3x3)', 
  '4.5V', 
  'ANALOG DEVICES MAXM1763x', 
  '175-MAXM17632AME+TCT-ND', 
  'Active', 
  'Analog Devices Inc./Maxim Integrated', 
  '2024-07-27T04:34:21.253', 
  '1', 
  '94', 
  '=Part Number', 
  '1', 
  '-40°C ~ 125°C', 
  'ITE (Commercial)', 
  'MAXIM 16-Pin uSLIC M1633+1', 
  'DigiKey', 
  '0.9 ~ 12V', 
  'Surface Mount', 
  '0.12" L x 0.12" W x 0.06" H (3.0mm x 3.0mm x 1.7mm)', 
  'Himalaya', 
  'Non-Isolated PoL Module', 
  '3.82', 
  'symbols/Power - Switchmode/SCH - POWER - SWITCHMODE - ANALOG DEVICES MAXM1763x.SchLib', 
  'TapeAndReel', 
  'DigiKey Link', 
  'footprints/Leadless - LGA/PCB - LEADLESS - LGA - MAXIM 16-Pin uSLIC M1633+1.PcbLib'
);

INSERT INTO "altium"."PowerSupplies-BoardMount-DC-DC-Converters" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Voltage - Input (Max)",
  "Current - Output (Max)",
  "Supplier Device Package",
  "Voltage - Input (Min)",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Applications",
  "Footprint Ref",
  "Supplier 1",
  "Voltage - Output 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DC DC CONVERTER 3.3V', 
  'MAXM17630AME+T', 
  'https://www.digikey.com/en/products/detail/analog-devices-inc-maxim-integrated/MAXM17630AME-T/12460837', 
  '36V', 
  '1A', 
  '16-eMGA (3x3)', 
  '4.5V', 
  'ANALOG DEVICES MAXM1763x', 
  '175-MAXM17630AME+TCT-ND', 
  'Active', 
  'Analog Devices Inc./Maxim Integrated', 
  '2024-07-27T04:35:16.110', 
  '1', 
  '95', 
  '=Part Number', 
  '1', 
  '-40°C ~ 125°C', 
  'ITE (Commercial)', 
  'MAXIM 16-Pin uSLIC M1633+1', 
  'DigiKey', 
  '3.3V', 
  'Surface Mount', 
  '0.12" L x 0.12" W x 0.06" H (3.0mm x 3.0mm x 1.7mm)', 
  'Himalaya', 
  'Non-Isolated PoL Module', 
  '3.82', 
  'symbols/Power - Switchmode/SCH - POWER - SWITCHMODE - ANALOG DEVICES MAXM1763x.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - LGA/PCB - LEADLESS - LGA - MAXIM 16-Pin uSLIC M1633+1.PcbLib'
);

INSERT INTO "altium"."PowerSupplies-BoardMount-DC-DC-Converters" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Voltage - Input (Max)",
  "Current - Output (Max)",
  "Supplier Device Package",
  "Voltage - Input (Min)",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Applications",
  "Footprint Ref",
  "Supplier 1",
  "Voltage - Output 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DC DC CONVERTER 5V', 
  'MAXM17631AME+T', 
  'https://www.digikey.com/en/products/detail/analog-devices-inc-maxim-integrated/MAXM17631AME-T/12460982', 
  '36V', 
  '1A', 
  '16-eMGA (3x3)', 
  '4.5V', 
  'ANALOG DEVICES MAXM1763x', 
  '175-MAXM17631AME+TCT-ND', 
  'Active', 
  'Analog Devices Inc./Maxim Integrated', 
  '2024-07-27T04:35:44.750', 
  '1', 
  '96', 
  '=Part Number', 
  '1', 
  '-40°C ~ 125°C', 
  'ITE (Commercial)', 
  'MAXIM 16-Pin uSLIC M1633+1', 
  'DigiKey', 
  '5V', 
  'Surface Mount', 
  '0.12" L x 0.12" W x 0.06" H (3.0mm x 3.0mm x 1.7mm)', 
  'Himalaya', 
  'Non-Isolated PoL Module', 
  '3.82', 
  'symbols/Power - Switchmode/SCH - POWER - SWITCHMODE - ANALOG DEVICES MAXM1763x.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - LGA/PCB - LEADLESS - LGA - MAXIM 16-Pin uSLIC M1633+1.PcbLib'
);

