--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."VoltageReference" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Noise - 0.1hz To 10hz",
  "Output Type",
  "Current - Output",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Noise - 10hz To 10khz",
  "Voltage - Input",
  "Comment",
  "Operating Temperature",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Reference Type",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC VREF SERIES SOT23-6', 
  'REF35330QDBVR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/REF35330QDBVR/18111313', 
  '3.8ppmp-p', 
  'Fixed', 
  '10 mA', 
  '12ppm/°C', 
  'SOT-23-6', 
  'TI REF35', 
  '296-REF35330QDBVRCT-ND', 
  'Active', 
  'Texas Instruments', 
  '3.3V', 
  '2024-12-10T08:11:51.817', 
  '1', 
  '0.7ppmrms', 
  '3.55V ~ 6V', 
  '=Part Number', 
  '-40°C ~ 125°C (TA)', 
  'TI SOT-23-6 DBV', 
  '±0.05%', 
  'DigiKey', 
  '2.6µA', 
  'Surface Mount', 
  'Series', 
  '-', 
  '0.93', 
  'symbols/Power - Voltage References/SCH - POWER - VOLTAGE REFERENCES - TI REF35.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-6 DBV.PCBLIB'
);

INSERT INTO "altium"."VoltageReference" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Noise - 0.1hz To 10hz",
  "Output Type",
  "Current - Output",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Noise - 10hz To 10khz",
  "Voltage - Input",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Reference Type",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC VREF SERIES 1.8V SOT23-6', 
  'REF35180QDBVR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/REF35180QDBVR/17394962', 
  '3.8ppmp-p', 
  'Fixed', 
  '10 mA', 
  '12ppm/°C', 
  'SOT-23-6', 
  'TI REF35', 
  '296-REF35180QDBVRCT-ND', 
  'Active', 
  'Texas Instruments', 
  '1.8V', 
  '2024-12-10T08:11:51.853', 
  '1', 
  '0.7ppmrms', 
  '2.05V ~ 6V', 
  '=Part Number', 
  '-40°C ~ 125°C (TA)', 
  'https://www.ti.com/lit/ds/symlink/ref35.pdf', 
  'TI SOT-23-6 DBV', 
  'Datasheet', 
  '±0.05%', 
  'DigiKey', 
  '2.6µA', 
  'Surface Mount', 
  'Series', 
  '-', 
  '0.93', 
  'symbols/Power - Voltage References/SCH - POWER - VOLTAGE REFERENCES - TI REF35.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-6 DBV.PCBLIB'
);

INSERT INTO "altium"."VoltageReference" (
  "Comment",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Footprint Ref",
  "Supplier 1",
  "Series",
  "Library Ref",
  "Price",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Library Path",
  "Manufacturer",
  "Packaging",
  "Part Status",
  "LastUpdated",
  "Minimum Order",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '=Part Number', 
  'IC VREF', 
  'REF35409QDBVR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/REF35409QDBVR/18187756', 
  'TI SOT-23-6 DBV', 
  'DigiKey', 
  '*', 
  'TI REF35', 
  '0.93', 
  '296-REF35409QDBVRCT-ND', 
  'Active', 
  'symbols/Power - Voltage References/SCH - POWER - VOLTAGE REFERENCES - TI REF35.SchLib', 
  'Texas Instruments', 
  'TapeAndReel', 
  'Active', 
  '2024-12-10T08:11:51.870', 
  '1', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-6 DBV.PCBLIB'
);

INSERT INTO "altium"."VoltageReference" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Noise - 0.1hz To 10hz",
  "Output Type",
  "Current - Output",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Noise - 10hz To 10khz",
  "Voltage - Input",
  "Comment",
  "Operating Temperature",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Reference Type",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC VREF SERIES SOT23-6', 
  'REF35360QDBVR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/REF35360QDBVR/18111352', 
  '3.8ppmp-p', 
  'Fixed', 
  '10 mA', 
  '12ppm/°C', 
  'SOT-23-6', 
  'TI REF35', 
  '296-REF35360QDBVRCT-ND', 
  'Active', 
  'Texas Instruments', 
  '3.6V', 
  '2024-12-10T08:11:51.887', 
  '1', 
  '0.7ppmrms', 
  '3.85V ~ 6V', 
  '=Part Number', 
  '-40°C ~ 125°C (TA)', 
  'TI SOT-23-6 DBV', 
  '±0.05%', 
  'DigiKey', 
  '2.6µA', 
  'Surface Mount', 
  'Series', 
  '-', 
  '0.87', 
  'symbols/Power - Voltage References/SCH - POWER - VOLTAGE REFERENCES - TI REF35.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-6 DBV.PCBLIB'
);

INSERT INTO "altium"."VoltageReference" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Noise - 0.1hz To 10hz",
  "Output Type",
  "Current - Output",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Noise - 10hz To 10khz",
  "Voltage - Input",
  "Comment",
  "Operating Temperature",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Reference Type",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC VREF SERIES 1.7V SOT23-6', 
  'REF35170QDBVR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/REF35170QDBVR/18111309', 
  '3.3ppmp-p', 
  'Fixed', 
  '10 mA', 
  '12ppm/°C', 
  'SOT-23-6', 
  'TI REF35', 
  '296-REF35170QDBVRCT-ND', 
  'Active', 
  'Texas Instruments', 
  '1.7V', 
  '2024-12-10T08:11:51.893', 
  '1', 
  '0.7ppmrms', 
  '1.95V ~ 6V', 
  '=Part Number', 
  '-40°C ~ 125°C (TA)', 
  'TI SOT-23-6 DBV', 
  '±0.05%', 
  'DigiKey', 
  '2.6µA', 
  'Surface Mount', 
  'Series', 
  '-', 
  '0.87', 
  'symbols/Power - Voltage References/SCH - POWER - VOLTAGE REFERENCES - TI REF35.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-6 DBV.PCBLIB'
);

INSERT INTO "altium"."VoltageReference" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Noise - 0.1hz To 10hz",
  "Output Type",
  "Current - Output",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Noise - 10hz To 10khz",
  "Voltage - Input",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Reference Type",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC VREF SERIES SOT23-6', 
  'REF35300QDBVR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/REF35300QDBVR/17748383', 
  '3.8ppmp-p', 
  'Fixed', 
  '10 mA', 
  '12ppm/°C', 
  'SOT-23-6', 
  'TI REF35', 
  '296-REF35300QDBVRCT-ND', 
  'Active', 
  'Texas Instruments', 
  '3V', 
  '2024-12-10T08:11:51.913', 
  '1', 
  '0.7ppmrms', 
  '3.25V ~ 6V', 
  '=Part Number', 
  '-40°C ~ 125°C (TA)', 
  'https://www.ti.com/lit/ds/symlink/ref35.pdf', 
  'TI SOT-23-6 DBV', 
  'Datasheet', 
  '±0.05%', 
  'DigiKey', 
  '2.6µA', 
  'Surface Mount', 
  'Series', 
  '-', 
  '0.93', 
  'symbols/Power - Voltage References/SCH - POWER - VOLTAGE REFERENCES - TI REF35.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-6 DBV.PCBLIB'
);

INSERT INTO "altium"."VoltageReference" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Noise - 0.1hz To 10hz",
  "Output Type",
  "Current - Output",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Noise - 10hz To 10khz",
  "Voltage - Input",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Reference Type",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC VREF SERIES 1.25V SOT23-6', 
  'REF35125QDBVR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/REF35125QDBVR/17748313', 
  '3.3ppmp-p', 
  'Fixed', 
  '10 mA', 
  '12ppm/°C', 
  'SOT-23-6', 
  'TI REF35', 
  '296-REF35125QDBVRCT-ND', 
  'Active', 
  'Texas Instruments', 
  '1.25V', 
  '2024-12-10T08:11:51.930', 
  '1', 
  '0.7ppmrms', 
  '1.5V ~ 6V', 
  '=Part Number', 
  '-40°C ~ 125°C (TA)', 
  'https://www.ti.com/lit/ds/symlink/ref35.pdf', 
  'TI SOT-23-6 DBV', 
  'Datasheet', 
  '±0.05%', 
  'DigiKey', 
  '2.6µA', 
  'Surface Mount', 
  'Series', 
  '-', 
  '0.93', 
  'symbols/Power - Voltage References/SCH - POWER - VOLTAGE REFERENCES - TI REF35.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-6 DBV.PCBLIB'
);

INSERT INTO "altium"."VoltageReference" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Noise - 0.1hz To 10hz",
  "Output Type",
  "Current - Output",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Noise - 10hz To 10khz",
  "Voltage - Input",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Reference Type",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC VREF SERIES 1.024V SOT23-6', 
  'REF35102QDBVR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/REF35102QDBVR/17394987', 
  '3.8ppmp-p', 
  'Fixed', 
  '10 mA', 
  '12ppm/°C', 
  'SOT-23-6', 
  'TI REF35', 
  '296-REF35102QDBVRCT-ND', 
  'Active', 
  'Texas Instruments', 
  '1.024V', 
  '2024-12-10T08:11:51.947', 
  '1', 
  '0.7ppmrms', 
  '1.274V ~ 6V', 
  '=Part Number', 
  '-40°C ~ 125°C (TA)', 
  'https://www.ti.com/lit/ds/symlink/ref35.pdf', 
  'TI SOT-23-6 DBV', 
  'Datasheet', 
  '±0.05%', 
  'DigiKey', 
  '2.6µA', 
  'Surface Mount', 
  'Series', 
  '-', 
  '0.93', 
  'symbols/Power - Voltage References/SCH - POWER - VOLTAGE REFERENCES - TI REF35.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-6 DBV.PCBLIB'
);

INSERT INTO "altium"."VoltageReference" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Noise - 0.1hz To 10hz",
  "Output Type",
  "Current - Output",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Noise - 10hz To 10khz",
  "Voltage - Input",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Reference Type",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC VREF SERIES 2.048V SOT23-6', 
  'REF35205QDBVR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/REF35205QDBVR/17394998', 
  '3.8ppmp-p', 
  'Fixed', 
  '10 mA', 
  '12ppm/°C', 
  'SOT-23-6', 
  'TI REF35', 
  '296-REF35205QDBVRCT-ND', 
  'Active', 
  'Texas Instruments', 
  '2.048V', 
  '2024-12-10T08:11:51.963', 
  '1', 
  '0.7ppmrms', 
  '2.298V ~ 6V', 
  '=Part Number', 
  '-40°C ~ 125°C (TA)', 
  'https://www.ti.com/lit/ds/symlink/ref35.pdf', 
  'TI SOT-23-6 DBV', 
  'Datasheet', 
  '±0.05%', 
  'DigiKey', 
  '2.6µA', 
  'Surface Mount', 
  'Series', 
  '-', 
  '0.93', 
  'symbols/Power - Voltage References/SCH - POWER - VOLTAGE REFERENCES - TI REF35.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-6 DBV.PCBLIB'
);

INSERT INTO "altium"."VoltageReference" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Noise - 0.1hz To 10hz",
  "Output Type",
  "Current - Output",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Noise - 10hz To 10khz",
  "Voltage - Input",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Reference Type",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC VREF SERIES 1.6V SOT23-6', 
  'REF35160QDBVR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/REF35160QDBVR/17395030', 
  '3.8ppmp-p', 
  'Fixed', 
  '10 mA', 
  '12ppm/°C', 
  'SOT-23-6', 
  'TI REF35', 
  '296-REF35160QDBVRCT-ND', 
  'Active', 
  'Texas Instruments', 
  '1.6V', 
  '2024-12-10T08:11:51.973', 
  '1', 
  '0.7ppmrms', 
  '1.85V ~ 6V', 
  '=Part Number', 
  '-40°C ~ 125°C (TA)', 
  'https://www.ti.com/lit/ds/symlink/ref35.pdf', 
  'TI SOT-23-6 DBV', 
  'Datasheet', 
  '±0.05%', 
  'DigiKey', 
  '2.6µA', 
  'Surface Mount', 
  'Series', 
  '-', 
  '0.93', 
  'symbols/Power - Voltage References/SCH - POWER - VOLTAGE REFERENCES - TI REF35.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-6 DBV.PCBLIB'
);

INSERT INTO "altium"."VoltageReference" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Noise - 0.1hz To 10hz",
  "Output Type",
  "Current - Output",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Noise - 10hz To 10khz",
  "Voltage - Input",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Reference Type",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC VREF SERIES 1.2V SOT23-6', 
  'REF35120QDBVR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/REF35120QDBVR/17748352', 
  '3.3ppmp-p', 
  'Fixed', 
  '10 mA', 
  '12ppm/°C', 
  'SOT-23-6', 
  'TI REF35', 
  '296-REF35120QDBVRCT-ND', 
  'Active', 
  'Texas Instruments', 
  '1.2V', 
  '2024-12-10T08:11:51.983', 
  '1', 
  '0.7ppmrms', 
  '1.45V ~ 6V', 
  '=Part Number', 
  '-40°C ~ 125°C (TA)', 
  'https://www.ti.com/lit/ds/symlink/ref35.pdf', 
  'TI SOT-23-6 DBV', 
  'Datasheet', 
  '±0.05%', 
  'DigiKey', 
  '2.6µA', 
  'Surface Mount', 
  'Series', 
  '-', 
  '0.93', 
  'symbols/Power - Voltage References/SCH - POWER - VOLTAGE REFERENCES - TI REF35.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-6 DBV.PCBLIB'
);

INSERT INTO "altium"."VoltageReference" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Noise - 0.1hz To 10hz",
  "Output Type",
  "Current - Output",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Noise - 10hz To 10khz",
  "Voltage - Input",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Reference Type",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC VREF SERIES SOT23-6', 
  'REF35250QDBVR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/REF35250QDBVR/17394994', 
  '3.8ppmp-p', 
  'Fixed', 
  '10 mA', 
  '12ppm/°C', 
  'SOT-23-6', 
  'TI REF35', 
  '296-REF35250QDBVRCT-ND', 
  'Active', 
  'Texas Instruments', 
  '2.5V', 
  '2024-12-10T08:11:51.993', 
  '1', 
  '0.7ppmrms', 
  '2.75V ~ 6V', 
  '=Part Number', 
  '-40°C ~ 125°C (TA)', 
  'https://www.ti.com/lit/ds/symlink/ref35.pdf', 
  'TI SOT-23-6 DBV', 
  'Datasheet', 
  '±0.05%', 
  'DigiKey', 
  '2.6µA', 
  'Surface Mount', 
  'Series', 
  '-', 
  '0.93', 
  'symbols/Power - Voltage References/SCH - POWER - VOLTAGE REFERENCES - TI REF35.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-6 DBV.PCBLIB'
);

INSERT INTO "altium"."VoltageReference" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Noise - 0.1hz To 10hz",
  "Output Type",
  "Current - Output",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Noise - 10hz To 10khz",
  "Voltage - Input",
  "Comment",
  "Operating Temperature",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Reference Type",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC VREF SERIES SOT23-6', 
  'REF35500QDBVR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/REF35500QDBVR/16688618', 
  '3.3ppmp-p', 
  'Fixed', 
  '10 mA', 
  '12ppm/°C', 
  'SOT-23-6', 
  'TI REF35', 
  '296-REF35500QDBVRCT-ND', 
  'Active', 
  'Texas Instruments', 
  '5V', 
  '2024-12-10T08:11:52.010', 
  '1', 
  '0.7ppmrms', 
  '5.25V ~ 6V', 
  '=Part Number', 
  '-40°C ~ 125°C (TA)', 
  'TI SOT-23-6 DBV', 
  '±0.05%', 
  'DigiKey', 
  '900nA', 
  'Surface Mount', 
  'Series', 
  '-', 
  '0.93', 
  'symbols/Power - Voltage References/SCH - POWER - VOLTAGE REFERENCES - TI REF35.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-6 DBV.PCBLIB'
);

