--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 4.75KOHM 0.1% 1/10W 0603', 
  'CRT0603-BY-4751ELF', 
  'https://www.digikey.com/en/products/detail/bourns-inc/CRT0603-BY-4751ELF/2564030', 
  '0.024" (0.60mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±25ppm/°C', 
  '0603', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '118-CRT0603-BY-4751ELFCT-ND', 
  'Active', 
  'Bourns Inc.', 
  'Current Sense', 
  '2023-06-29T20:04:06.883', 
  '1', 
  '4643', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.bourns.com/docs/Product-Datasheets/crt.pdf', 
  'STACKPOLE CSR0603', 
  'Datasheet', 
  '±0.1%', 
  'DigiKey', 
  '0.061" L x 0.031" W (1.55mm x 0.80mm)', 
  '4.75 kOhms', 
  '0.1W, 1/10W', 
  'CRT', 
  '0.06', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '4.75 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - STACKPOLE CSR0603.PCBLIB'
);

INSERT INTO "Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 10 OHM 1% 1/10W 0603', 
  'CRT0603-FZ-10R0ELF', 
  'https://www.digikey.com/en/products/detail/bourns-inc/CRT0603-FZ-10R0ELF/4698672', 
  '0.024" (0.60mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±50ppm/°C', 
  '0603', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '118-CRT0603-FZ-10R0ELFCT-ND', 
  'Active', 
  'Bourns Inc.', 
  'Current Sense', 
  '2023-06-29T20:04:06.910', 
  '1', 
  '4644', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.bourns.com/docs/Product-Datasheets/crt.pdf', 
  'STACKPOLE CSR0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.061" L x 0.031" W (1.55mm x 0.80mm)', 
  '10 Ohms', 
  '0.1W, 1/10W', 
  'CRT', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '10 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - STACKPOLE CSR0603.PCBLIB'
);

INSERT INTO "Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 10K OHM 0.5% 1/8W 0805', 
  'CRT0805-DY-1002ELF', 
  'https://www.digikey.com/en/products/detail/bourns-inc/CRT0805-DY-1002ELF/2564158', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±25ppm/°C', 
  '0805', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '118-CRT0805-DY-1002ELFCT-ND', 
  'Active', 
  'Bourns Inc.', 
  'Current Sense', 
  '2023-06-29T20:04:38.647', 
  '1', 
  '4645', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.bourns.com/docs/Product-Datasheets/crt.pdf', 
  'STACKPOLE CSR0805', 
  'Datasheet', 
  '±0.5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '10 kOhms', 
  '0.125W, 1/8W', 
  'CRT', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '10 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - STACKPOLE CSR0805.PCBLIB'
);

INSERT INTO "Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RESTHINFILM 0805 49R9 1% 125MW T', 
  'CRT0805-FZ-49R9ELF', 
  'https://www.digikey.com/en/products/detail/bourns-inc/CRT0805-FZ-49R9ELF/16357366', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±50ppm/°C', 
  '0805', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '118-CRT0805-FZ-49R9ELFCT-ND', 
  'Active', 
  'Bourns Inc.', 
  'Current Sense', 
  '2023-06-29T20:04:38.667', 
  '1', 
  '4646', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.bourns.com/docs/Product-Datasheets/crt.pdf', 
  'STACKPOLE CSR0805', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '49.9 Ohms', 
  '0.125W, 1/8W', 
  'CRT', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '49.9 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - STACKPOLE CSR0805.PCBLIB'
);

INSERT INTO "Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.0025 OHM 2% 0.66W 0805', 
  'PML10EZPGV2L50', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/PML10EZPGV2L50/18674694', 
  '0.017" (0.43mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0508', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-PML10EZPGV2L50CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Current Sense', 
  '2023-06-29T20:04:38.613', 
  '1', 
  '4647', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Metal Element', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/pml-e.pdf', 
  'STACKPOLE CSR0805', 
  'Datasheet', 
  '±2%', 
  'DigiKey', 
  '0.047" L x 0.079" W (1.20mm x 2.00mm)', 
  '2.5 mOhms', 
  '0.66W', 
  'PML', 
  '0.15', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2.5 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - STACKPOLE CSR0805.PCBLIB'
);

INSERT INTO "Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.001 OHM 2/3W 0805 WIDE', 
  'PML10EZPGV1L00', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/PML10EZPGV1L00/4009177', 
  '0.028" (0.70mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-PML10EZPGV1L00CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Current Sense', 
  '2023-06-29T20:04:38.627', 
  '1', 
  '4648', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://d1d2qsbl8m0m72.cloudfront.net/en/products/databook/datasheet/passive/resistor/chip_resistor/pml-e.pdf', 
  'STACKPOLE CSR0805', 
  'Datasheet', 
  '±2%', 
  'DigiKey', 
  '0.049" L x 0.079" W (1.25mm x 2.00mm)', 
  '1 mOhms', 
  '0.667W, 2/3W', 
  'PML', 
  '0.15', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - STACKPOLE CSR0805.PCBLIB'
);

INSERT INTO "Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 1.8K OHM 0.1% 1/8W 0805', 
  'CRT0805-BY-1801ELF', 
  'https://www.digikey.com/en/products/detail/bourns-inc/CRT0805-BY-1801ELF/4698723', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±25ppm/°C', 
  '0805', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '118-CRT0805-BY-1801ELFCT-ND', 
  'Active', 
  'Bourns Inc.', 
  'Current Sense', 
  '2023-06-29T20:04:38.637', 
  '1', 
  '4649', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.bourns.com/docs/Product-Datasheets/crt.pdf', 
  'STACKPOLE CSR0805', 
  'Datasheet', 
  '±0.1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '1.8 kOhms', 
  '0.125W, 1/8W', 
  'CRT', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1.8 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - STACKPOLE CSR0805.PCBLIB'
);

INSERT INTO "Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH POWER LOW OHMIC CHIP RESIST', 
  'LTR18EZPJSR011', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/LTR18EZPJSR011/19530992', 
  '0.027" (0.68mm)', 
  '1206 (3216 Metric)', 
  '2', 
  '0/ +300ppm/°C', 
  '0612', 
  'AEC-Q200', 
  '1206 (3216 Metric)', 
  'RESISTOR', 
  '511-LTR18EZPJSR011CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Current Sense', 
  '2023-06-29T20:05:15.527', 
  '1', 
  '4650', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'STACKPOLE CSR1206', 
  '±5%', 
  'DigiKey', 
  '0.063" L x 0.126" W (1.60mm x 3.20mm)', 
  '11 mOhms', 
  '1W', 
  'LTR', 
  '0.14', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '11 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - STACKPOLE CSR1206.PCBLIB'
);

INSERT INTO "Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RESMETALSTRIP 4T 0612 R005 1% 1W', 
  'CST0612-FC-R005E', 
  'https://www.digikey.com/en/products/detail/bourns-inc/CST0612-FC-R005E/15926891', 
  '0.026" (0.65mm)', 
  '1206 (3216 Metric)', 
  '2', 
  '±200ppm/°C', 
  '1206', 
  'AEC-Q200', 
  '1206 (3216 Metric)', 
  'RESISTOR', 
  '118-CST0612-FC-R005ECT-ND', 
  'Active', 
  'Bourns Inc.', 
  'Automotive AEC-Q200, Current Sense', 
  '2023-06-29T20:05:15.550', 
  '1', 
  '4651', 
  '=Value', 
  '-55°C ~ 170°C', 
  'Metal Element', 
  'https://www.bourns.com/docs/product-datasheets/cst0612.pdf', 
  'STACKPOLE CSR1206', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.120" L x 0.065" W (3.05mm x 1.65mm)', 
  '5 mOhms', 
  '1W', 
  'CST', 
  '0.31', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '5 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - STACKPOLE CSR1206.PCBLIB'
);

INSERT INTO "Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 3.3 OHM 1% 1/2W 1206', 
  '560050332011', 
  'https://www.digikey.com/en/products/detail/würth-elektronik/560050332011/17829908', 
  '0.028" (0.70mm)', 
  '1206 (3216 Metric)', 
  '2', 
  '±100ppm/°C', 
  '1206', 
  '1206 (3216 Metric)', 
  'RESISTOR', 
  '732-560050332011CT-ND', 
  'Active', 
  'Würth Elektronik', 
  'Current Sense', 
  '2023-06-29T20:05:15.567', 
  '1', 
  '4652', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.we-online.com/catalog/datasheet/560050332011.pdf', 
  'STACKPOLE CSR1206', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.122" L x 0.063" W (3.10mm x 1.60mm)', 
  '3.3 Ohms', 
  '0.5W, 1/2W', 
  'WRIS-KSKE', 
  '0.22', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '3.3 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - STACKPOLE CSR1206.PCBLIB'
);

INSERT INTO "Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 5M OHM 1% 2W 2010', 
  'TLR2HWDTE5L00F75', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/TLR2HWDTE5L00F75/9856638', 
  '0.032" (0.80mm)', 
  '2010 (5025 Metric)', 
  '2', 
  '±75ppm/°C', 
  '2010', 
  'AEC-Q200', 
  '2010 (5025 Metric)', 
  'RESISTOR', 
  '2019-TLR2HWDTE5L00F75CT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Current Sense', 
  '2023-06-29T20:05:44.990', 
  '1', 
  '4653', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'https://www.koaspeer.com/pdfs/TLR-2BW-2BP-2HW-3AP-3APS.pdf', 
  'STACKPOLE CSR2010', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.197" L x 0.098" W (5.00mm x 2.50mm)', 
  '5 mOhms', 
  '2W', 
  'TLR', 
  '0.26', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '5 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - STACKPOLE CSR2010.PCBLIB'
);

INSERT INTO "Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.011 OHM 1% 2W WIDE 2010', 
  'LTR50UZPFSR011', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/LTR50UZPFSR011/18674699', 
  '0.029" (0.73mm)', 
  '2010 (5025 Metric)', 
  '2', 
  '0/ +300ppm/°C', 
  '1020', 
  'AEC-Q200', 
  '2010 (5025 Metric)', 
  'RESISTOR', 
  '511-LTR50UZPFSR011CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Current Sense', 
  '2023-06-29T20:05:44.993', 
  '1', 
  '4654', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/ltr-low-e.pdf', 
  'STACKPOLE CSR2010', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.098" L x 0.197" W (2.50mm x 5.00mm)', 
  '11 mOhms', 
  '2W', 
  'LTR', 
  '0.33', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '11 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - STACKPOLE CSR2010.PCBLIB'
);

