--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 3.6V 310MW SOD323F', 
  'PZU3.6B,115', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/PZU3-6B-115/1162988', 
  'SOD-323F', 
  'SC-90, SOD-323F', 
  'DIODE ZENER', 
  '1727-3729-1-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-06-29T20:11:17.733', 
  '1', 
  '4296', 
  '=Part Number', 
  '-65°C ~ 150°C', 
  'https://assets.nexperia.com/documents/data-sheet/PZUXB_SER.pdf', 
  'SOD323F', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  'Surface Mount', 
  '5 µA @ 1 V', 
  'Automotive, AEC-Q100', 
  '0.04', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '310 mW', 
  '1.1 V @ 100 mA', 
  'TapeAndReel', 
  'Active', 
  '3.6 V', 
  '90 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD323F.PCBLIB'
);

