--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 1K OHM 1% 1/20W 0201', 
  'RC0201FR-131KL', 
  'https://www.digikey.com/en/products/detail/yageo/RC0201FR-131KL/17011251', 
  '0.010" (0.26mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0201', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '13-RC0201FR-131KLCT-ND', 
  'Active', 
  'Yageo', 
  'Moisture Resistant', 
  '2023-05-16T19:24:28.750', 
  '1', 
  '77423', 
  '=Value', 
  '-55°C ~ 125°C', 
  'Thick Film', 
  'https://www.yageo.com/upload/media/product/productsearch/datasheet/rchip/PYu-RC_Group_51_RoHS_L_12.pdf', 
  'RES 0201_0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  '1 kOhms', 
  '0.05W, 1/20W', 
  'RC_L', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  'Active', 
  '1 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 63.4K OHM 1% 1/20W 0201', 
  'CRCW020163K4FKED', 
  'https://www.digikey.com/en/products/detail/vishay-dale/CRCW020163K4FKED/1968724', 
  '0.010" (0.26mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0201', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '541-CRCW020163K4FKEDCT-ND', 
  'Active', 
  'Vishay Dale', 
  '2023-05-16T19:24:28.783', 
  '1', 
  '77424', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.vishay.com/docs/20052/crcw0201e3.pdf', 
  'RES 0201_0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  '63.4 kOhms', 
  '0.05W, 1/20W', 
  'CRCW', 
  '0.03', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '63.4 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 100 OHM 0.5% 1/32W 0201', 
  'CPF0201D100RE1', 
  'https://www.digikey.com/en/products/detail/te-connectivity-passive-product/CPF0201D100RE1/4489370', 
  '0.011" (0.28mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '±25ppm/°C', 
  '0201', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '1712-CPF0201D100RE1CT-ND', 
  'Active', 
  'TE Connectivity Passive Product', 
  '2023-05-16T19:24:28.813', 
  '1', 
  '77425', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=1773200&DocType=DS&DocLang=English', 
  'RES 0201_0603', 
  'Datasheet', 
  '±0.5%', 
  'DigiKey', 
  '0.023" L x 0.011" W (0.58mm x 0.29mm)', 
  '100 Ohms', 
  '0.03W, 1/32W', 
  'CPF, Neohm', 
  '0.09', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '100 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

