--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 15 OHM 1% 1/10W 0603', 
  'SFR03EZPF15R0', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SFR03EZPF15R0/16009203', 
  '0.022" (0.55mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '511-SFR03EZPF15R0CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Anti-Sulfur, Automotive AEC-Q200', 
  '2023-05-16T19:38:26.403', 
  '1', 
  '77433', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/sfr-e.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  '15 Ohms', 
  '0.1W, 1/10W', 
  'SFR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '15 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 150 OHM 1% 1/10W 0603', 
  'KTR03EZPF1500', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/KTR03EZPF1500/4051573', 
  '0.022" (0.55mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '511-KTR03EZPF1500CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, High Voltage', 
  '2023-05-16T19:38:26.420', 
  '1', 
  '77435', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/ktr-e.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  '150 Ohms', 
  '0.1W, 1/10W', 
  'KTR', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '150 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 100 OHM 5% 1/10W 0603', 
  'KTR03EZPJ101', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/KTR03EZPJ101/2288559', 
  '0.022" (0.55mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '511-KTR03EZPJ101CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, High Voltage', 
  '2023-05-16T19:38:26.440', 
  '1', 
  '77436', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/ktr-e.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  '100 Ohms', 
  '0.1W, 1/10W', 
  'KTR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '100 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 1.8K OHM 1% 1/10W 0603', 
  'CRCW06031K80FHEAP', 
  'https://www.digikey.com/en/products/detail/vishay-dale/CRCW06031K80FHEAP/5071289', 
  '0.020" (0.50mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±50ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-CRCW06031K80FHEAPCT-ND', 
  'Active', 
  'Vishay Dale', 
  'Automotive AEC-Q200', 
  '2023-05-16T19:38:26.473', 
  '1', 
  '77437', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://media.digikey.com/pdf/Data%20Sheets/Vishay%20Dale%20PDFs/D_CRCW-P_e3_Series.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.033" W (1.60mm x 0.85mm)', 
  '1.8 kOhms', 
  '0.1W, 1/10W', 
  'CRCW-P', 
  '0.03', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1.8 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 12K OHM 0.1% 1/10W 0603', 
  'AT0603BRD0712KL', 
  'https://www.digikey.com/en/products/detail/yageo/AT0603BRD0712KL/16988354', 
  '0.022" (0.55mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±25ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '13-AT0603BRD0712KLCT-ND', 
  'Active', 
  'Yageo', 
  'Anti-Sulfur, Automotive AEC-Q200, Moisture Resistant', 
  '2023-05-16T19:38:26.483', 
  '1', 
  '77438', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.yageo.com/upload/media/product/productsearch/datasheet/rchip/PYu-AT_51_RoHS_L_6.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±0.1%', 
  'DigiKey', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  '12 kOhms', 
  '0.1W, 1/10W', 
  'AT', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '12 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

