--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 102 OHM 1% 1/20W 0201', 
  'RK73H1HTTC1020F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RK73H1HTTC1020F/9850438', 
  '0.010" (0.26mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0201', 
  'AEC-Q200', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '2019-RK73H1HTTC1020FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant', 
  '2023-05-06T19:21:11.507', 
  '1000', 
  '77002', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/RK73H.pdf', 
  'RES 0201_0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  '102 Ohms', 
  '0.05W, 1/20W', 
  'RK73H', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '102 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 97.6K OHM 1% 1/20W 0201', 
  'RK73H1HTTC9762F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RK73H1HTTC9762F/9850455', 
  '0.010" (0.26mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0201', 
  'AEC-Q200', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '2019-RK73H1HTTC9762FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant', 
  '2023-05-06T19:21:11.513', 
  '1000', 
  '77003', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/RK73H.pdf', 
  'RES 0201_0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  '97.6 kOhms', 
  '0.05W, 1/20W', 
  'RK73H', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '97.6 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 71.5 OHM 1% 1/20W 0201', 
  'RK73H1HTTC71R5F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RK73H1HTTC71R5F/9850323', 
  '0.010" (0.26mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0201', 
  'AEC-Q200', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '2019-RK73H1HTTC71R5FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant', 
  '2023-05-06T19:21:11.520', 
  '1000', 
  '77004', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/RK73H.pdf', 
  'RES 0201_0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  '71.5 Ohms', 
  '0.05W, 1/20W', 
  'RK73H', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '71.5 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 24 OHM 5% 1/20W 0201', 
  'RK73B1HTTC240J', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RK73B1HTTC240J/9850014', 
  '0.010" (0.26mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0201', 
  'AEC-Q200', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '2019-RK73B1HTTC240JCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200', 
  '2023-05-06T19:21:11.557', 
  '1000', 
  '77005', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/RK73B.pdf', 
  'RES 0201_0603', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  '24 Ohms', 
  '0.05W, 1/20W', 
  'RK73B', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '24 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 54.9 OHM 1% 1/20W 0201', 
  'RK73H1HTTC54R9F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RK73H1HTTC54R9F/9850305', 
  '0.010" (0.26mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0201', 
  'AEC-Q200', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '2019-RK73H1HTTC54R9FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant', 
  '2023-05-06T19:21:11.563', 
  '1', 
  '77006', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/RK73H.pdf', 
  'RES 0201_0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  '54.9 Ohms', 
  '0.05W, 1/20W', 
  'RK73H', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '54.9 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 412K OHM 1% 1/20W 0201', 
  'RK73H1HTTC4123F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RK73H1HTTC4123F/9850379', 
  '0.010" (0.26mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0201', 
  'AEC-Q200', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '2019-RK73H1HTTC4123FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant', 
  '2023-05-06T19:21:11.563', 
  '1000', 
  '77007', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/RK73H.pdf', 
  'RES 0201_0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  '412 kOhms', 
  '0.05W, 1/20W', 
  'RK73H', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '412 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 16.2K OHM 1% 1/20W 0201', 
  'RK73H1HTTC1622F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RK73H1HTTC1622F/9850316', 
  '0.010" (0.26mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0201', 
  'AEC-Q200', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '2019-RK73H1HTTC1622FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant', 
  '2023-05-06T19:21:11.580', 
  '1000', 
  '77008', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/RK73H.pdf', 
  'RES 0201_0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  '16.2 kOhms', 
  '0.05W, 1/20W', 
  'RK73H', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '16.2 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

