--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 75 OHM 1% 1/4W 0805', 
  'SG73P2ATTD75R0F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/SG73P2ATTD75R0F/10191829', 
  '0.024" (0.60mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '2019-SG73P2ATTD75R0FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-06T19:55:15.870', 
  '1', 
  '77165', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/SG73P.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '75 Ohms', 
  '0.25W, 1/4W', 
  'SG73P', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '75 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 390 OHM 5% 1/4W 0805', 
  'SG73P2ATTD391J', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/SG73P2ATTD391J/10191433', 
  '0.024" (0.60mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '2019-SG73P2ATTD391JCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-06T19:55:15.880', 
  '1', 
  '77166', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/SG73P.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '390 Ohms', 
  '0.25W, 1/4W', 
  'SG73P', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '390 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 620 OHM 1% 1/4W 0805', 
  'SG73P2ATTD6200F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/SG73P2ATTD6200F/10192066', 
  '0.024" (0.60mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '2019-SG73P2ATTD6200FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-06T19:55:15.890', 
  '1', 
  '77167', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/SG73P.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '620 Ohms', 
  '0.25W, 1/4W', 
  'SG73P', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '620 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 15 OHM 1% 1/4W 0805', 
  'SG73P2ATTD15R0F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/SG73P2ATTD15R0F/10191647', 
  '0.024" (0.60mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '2019-SG73P2ATTD15R0FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-06T19:55:15.897', 
  '1', 
  '77168', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/SG73P.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '15 Ohms', 
  '0.25W, 1/4W', 
  'SG73P', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '15 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 100 OHM 5% 1/8W 0805', 
  'SFR10EZPJ101', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SFR10EZPJ101/9805644', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SFR10EZPJ101CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Anti-Sulfur', 
  '2023-05-06T19:55:15.903', 
  '1', 
  '77169', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/sfr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '100 Ohms', 
  '0.125W, 1/8W', 
  'SFR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '100 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPF2R00', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPF2R00/18674830', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPF2R00CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-06T19:55:15.910', 
  '1', 
  '77170', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '2 Ohms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0 OHM JUMPER 1/8W 0805', 
  'SFR10EZPJ000', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SFR10EZPJ000/9805642', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '0805', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SFR10EZPJ000CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Anti-Sulfur', 
  '2023-05-06T19:55:15.923', 
  '1', 
  '77171', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/sfr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  'Jumper', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '0 Ohms', 
  'SFR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '0 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPF4302', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPF4302/18674808', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPF4302CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-06T19:55:15.930', 
  '1', 
  '77172', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '43 kOhms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '43 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 22 KOHM 5% 1/8W 0805', 
  'SFR10EZPJ223', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SFR10EZPJ223/9805649', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SFR10EZPJ223CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Anti-Sulfur', 
  '2023-05-06T19:55:15.937', 
  '1', 
  '77173', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/sfr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '22 kOhms', 
  '0.125W, 1/8W', 
  'SFR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '22 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 330 OHM 5% 1/8W 0805', 
  'SFR10EZPJ331', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SFR10EZPJ331/9805652', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SFR10EZPJ331CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Anti-Sulfur', 
  '2023-05-06T19:55:15.940', 
  '1', 
  '77174', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/sfr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '330 Ohms', 
  '0.125W, 1/8W', 
  'SFR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '330 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 330 OHM 1% 1/8W 0805', 
  'SFR10EZPF3300', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SFR10EZPF3300/9805632', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SFR10EZPF3300CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Anti-Sulfur', 
  '2023-05-06T19:55:15.943', 
  '1', 
  '77175', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/sfr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '330 Ohms', 
  '0.125W, 1/8W', 
  'SFR', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '330 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPF5602', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPF5602/18674860', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPF5602CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-06T19:55:15.950', 
  '1', 
  '77176', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '56 kOhms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '56 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RLW73P A2 1% R039 200PPM 5K RL', 
  'RLW73PA2FR039TD', 
  'https://www.digikey.com/en/products/detail/te-connectivity-passive-product/RLW73PA2FR039TD/17763006', 
  '0.028" (0.70mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0508', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '1712-RLW73PA2FR039TDCT-ND', 
  'Active', 
  'TE Connectivity Passive Product', 
  'Current Sense', 
  '2023-05-06T19:55:15.953', 
  '1', 
  '77177', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.049" L x 0.079" W (1.25mm x 2.00mm)', 
  '39 mOhms', 
  '1W', 
  'RLW73', 
  '0.09', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '39 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 1.78M OHM 1% 1/4W 0805', 
  'RK73H2ATTD1784F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RK73H2ATTD1784F/10228834', 
  '0.024" (0.60mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±400ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '2019-RK73H2ATTD1784FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant', 
  '2023-05-06T19:55:15.960', 
  '1000', 
  '77178', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/RK73H.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '1.78 MOhms', 
  '0.25W, 1/4W', 
  'RK73H', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1.78 MOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RLW73P A2 1% R022 600PPM 5K RL', 
  'RLW73PA2FR022TD', 
  'https://www.digikey.com/en/products/detail/te-connectivity-passive-product/RLW73PA2FR022TD/17764208', 
  '0.028" (0.70mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±600ppm/°C', 
  '0508', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '1712-RLW73PA2FR022TDCT-ND', 
  'Active', 
  'TE Connectivity Passive Product', 
  'Current Sense', 
  '2023-05-06T19:55:15.967', 
  '1', 
  '77179', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.049" L x 0.079" W (1.25mm x 2.00mm)', 
  '22 mOhms', 
  '1W', 
  'RLW73', 
  '0.09', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '22 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 5.9 OHM 1% 1/4W 0805', 
  'RK73H2ATTD5R90F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RK73H2ATTD5R90F/10228754', 
  '0.024" (0.60mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '2019-RK73H2ATTD5R90FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant', 
  '2023-05-06T19:55:15.970', 
  '1000', 
  '77180', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/RK73H.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '5.9 Ohms', 
  '0.25W, 1/4W', 
  'RK73H', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '5.9 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 866K OHM 1% 1/4W 0805', 
  'RK73H2ATTD8663F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RK73H2ATTD8663F/10228455', 
  '0.024" (0.60mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '2019-RK73H2ATTD8663FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant', 
  '2023-05-06T19:55:15.973', 
  '1000', 
  '77181', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/RK73H.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '866 kOhms', 
  '0.25W, 1/4W', 
  'RK73H', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '866 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RLW73P A2 1% R033 200PPM 5K RL', 
  'RLW73PA2FR033TD', 
  'https://www.digikey.com/en/products/detail/te-connectivity-passive-product/RLW73PA2FR033TD/17763728', 
  '0.028" (0.70mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0508', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '1712-RLW73PA2FR033TDCT-ND', 
  'Active', 
  'TE Connectivity Passive Product', 
  'Current Sense', 
  '2023-05-06T19:55:15.997', 
  '1', 
  '77182', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.049" L x 0.079" W (1.25mm x 2.00mm)', 
  '33 mOhms', 
  '1W', 
  'RLW73', 
  '0.09', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '33 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RLW73P A2 1% R027 600PPM 5K RL', 
  'RLW73PA2FR027TD', 
  'https://www.digikey.com/en/products/detail/te-connectivity-passive-product/RLW73PA2FR027TD/17763138', 
  '0.028" (0.70mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±600ppm/°C', 
  '0508', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '1712-RLW73PA2FR027TDCT-ND', 
  'Active', 
  'TE Connectivity Passive Product', 
  'Current Sense', 
  '2023-05-06T19:55:16.003', 
  '1', 
  '77183', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.049" L x 0.079" W (1.25mm x 2.00mm)', 
  '27 mOhms', 
  '1W', 
  'RLW73', 
  '0.09', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '27 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 3.01KOHM 0.1% 1/10W 0805', 
  'RN73A2A3K01BTDF', 
  'https://www.digikey.com/en/products/detail/te-connectivity-passive-product/RN73A2A3K01BTDF/2378347', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±5ppm/°C', 
  '0805', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '1712-RN73A2A3K01BTDFCT-ND', 
  'Active', 
  'TE Connectivity Passive Product', 
  '2023-05-06T19:55:16.007', 
  '1', 
  '77184', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=1773270&DocType=DS&DocLang=English', 
  'RES 0805_2012', 
  'Datasheet', 
  '±0.1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '3.01 kOhms', 
  '0.1W, 1/10W', 
  'RN73, Holsworthy', 
  '0.63', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '3.01 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 10 KOHM 5% 1/8W 0805', 
  'SFR10EZPJ103', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SFR10EZPJ103/9805646', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SFR10EZPJ103CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Anti-Sulfur', 
  '2023-05-06T19:55:16.013', 
  '1', 
  '77185', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/sfr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '10 kOhms', 
  '0.125W, 1/8W', 
  'SFR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '10 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RLW73P A2 1% R018 600PPM 5K RL', 
  'RLW73PA2FR018TD', 
  'https://www.digikey.com/en/products/detail/te-connectivity-passive-product/RLW73PA2FR018TD/17764245', 
  '0.028" (0.70mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±600ppm/°C', 
  '0508', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '1712-RLW73PA2FR018TDCT-ND', 
  'Active', 
  'TE Connectivity Passive Product', 
  'Current Sense', 
  '2023-05-06T19:55:16.017', 
  '1', 
  '77186', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.049" L x 0.079" W (1.25mm x 2.00mm)', 
  '18 mOhms', 
  '1W', 
  'RLW73', 
  '0.09', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '18 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPJ333', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPJ333/18674926', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPJ333CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-06T19:55:16.020', 
  '1', 
  '77187', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '33 kOhms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '33 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 3.16M OHM 1% 1/4W 0805', 
  'RK73H2ATTD3164F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RK73H2ATTD3164F/10228532', 
  '0.024" (0.60mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±400ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '2019-RK73H2ATTD3164FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant', 
  '2023-05-06T19:55:16.027', 
  '1000', 
  '77188', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/RK73H.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '3.16 MOhms', 
  '0.25W, 1/4W', 
  'RK73H', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '3.16 MOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 1.6 OHM 1% 1/4W 0805', 
  'RK73H2ATTD1R60F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RK73H2ATTD1R60F/10228659', 
  '0.024" (0.60mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '2019-RK73H2ATTD1R60FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant', 
  '2023-05-06T19:55:16.030', 
  '1000', 
  '77189', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/RK73H.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '1.6 Ohms', 
  '0.25W, 1/4W', 
  'RK73H', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1.6 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 5.76 OHM 1% 1/4W 0805', 
  'RK73H2ATTD5R76F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RK73H2ATTD5R76F/10228487', 
  '0.024" (0.60mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '2019-RK73H2ATTD5R76FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant', 
  '2023-05-06T19:55:16.033', 
  '1000', 
  '77190', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/RK73H.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '5.76 Ohms', 
  '0.25W, 1/4W', 
  'RK73H', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '5.76 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 2.43 OHM 1% 1/4W 0805', 
  'RK73H2ATTD2R43F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RK73H2ATTD2R43F/10228913', 
  '0.024" (0.60mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '2019-RK73H2ATTD2R43FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant', 
  '2023-05-06T19:55:16.033', 
  '1000', 
  '77191', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/RK73H.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '2.43 Ohms', 
  '0.25W, 1/4W', 
  'RK73H', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2.43 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPF4R70', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPF4R70/18674909', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPF4R70CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-06T19:55:16.037', 
  '1', 
  '77192', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '4.7 Ohms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '4.7 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 11.5 OHM 1% 1/4W 0805', 
  'RK73H2ATTD11R5F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RK73H2ATTD11R5F/10229046', 
  '0.024" (0.60mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '2019-RK73H2ATTD11R5FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant', 
  '2023-05-06T19:55:16.040', 
  '1000', 
  '77193', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/RK73H.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '11.5 Ohms', 
  '0.25W, 1/4W', 
  'RK73H', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '11.5 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH POWER LOW OHMIC CHIP RESIST', 
  'LTR10LEZPFLR390', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/LTR10LEZPFLR390/18674901', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '0/ +100ppm/°C', 
  '0508', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-LTR10LEZPFLR390CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Current Sense', 
  '2023-05-06T19:55:16.047', 
  '1', 
  '77194', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.049" L x 0.079" W (1.25mm x 2.00mm)', 
  '390 mOhms', 
  '1W', 
  'LTR', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '390 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH POWER LOW OHMIC CHIP RESIST', 
  'LTR10LEZPJLR10', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/LTR10LEZPJLR10/18674839', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '0/ +150ppm/°C', 
  '0508', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-LTR10LEZPJLR10CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Current Sense', 
  '2023-05-06T19:55:16.057', 
  '1', 
  '77195', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±5%', 
  'DigiKey', 
  '0.049" L x 0.079" W (1.25mm x 2.00mm)', 
  '100 mOhms', 
  '1W', 
  'LTR', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '100 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 2K OHM 5% 1/8W 0805', 
  'KTR10EZPJ202', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/KTR10EZPJ202/4008656', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-KTR10EZPJ202CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, High Voltage', 
  '2023-05-06T19:55:16.063', 
  '1', 
  '77196', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/ktr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '2 kOhms', 
  '0.125W, 1/8W', 
  'KTR', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH POWER LOW OHMIC CHIP RESIST', 
  'LTR10LEZPFLR300', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/LTR10LEZPFLR300/18674907', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '0/ +100ppm/°C', 
  '0508', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-LTR10LEZPFLR300CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Current Sense', 
  '2023-05-06T19:55:16.067', 
  '1', 
  '77197', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.049" L x 0.079" W (1.25mm x 2.00mm)', 
  '300 mOhms', 
  '1W', 
  'LTR', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '300 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 20K OHM 1% 0.4W 0805', 
  'ESR10EZPF2002', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/ESR10EZPF2002/4007443', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-ESR10EZPF2002CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-06T19:55:16.070', 
  '1', 
  '77198', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/esr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '20 kOhms', 
  '0.4W, 2/5W', 
  'ESR', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '20 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 750 OHM 1% 0.4W 0805', 
  'ESR10EZPF7500', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/ESR10EZPF7500/3900256', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-ESR10EZPF7500CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-06T19:55:16.077', 
  '1', 
  '77199', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/esr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '750 Ohms', 
  '0.4W, 2/5W', 
  'ESR', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '750 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 120 OHM 5% 1/8W 0805', 
  'KTR10EZPJ121', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/KTR10EZPJ121/4008622', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-KTR10EZPJ121CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, High Voltage', 
  '2023-05-06T19:55:16.080', 
  '1', 
  '77200', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/ktr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '120 Ohms', 
  '0.125W, 1/8W', 
  'KTR', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '120 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 2.2K OHM 5% 1/8W 0805', 
  'KTR10EZPJ222', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/KTR10EZPJ222/4008658', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-KTR10EZPJ222CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, High Voltage', 
  '2023-05-06T19:55:16.087', 
  '1', 
  '77201', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/ktr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '2.2 kOhms', 
  '0.125W, 1/8W', 
  'KTR', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2.2 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 2.7K OHM 5% 1/8W 0805', 
  'KTR10EZPJ272', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/KTR10EZPJ272/4008666', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-KTR10EZPJ272CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, High Voltage', 
  '2023-05-06T19:55:16.100', 
  '1', 
  '77202', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/ktr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '2.7 kOhms', 
  '0.125W, 1/8W', 
  'KTR', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2.7 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 3.3K OHM 5% 1/8W 0805', 
  'KTR10EZPJ332', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/KTR10EZPJ332/4008676', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-KTR10EZPJ332CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, High Voltage', 
  '2023-05-06T19:55:16.103', 
  '1', 
  '77203', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/ktr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '3.3 kOhms', 
  '0.125W, 1/8W', 
  'KTR', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '3.3 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 2.2K OHM 1% 0.4W 0805', 
  'ESR10EZPF2201', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/ESR10EZPF2201/4007461', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-ESR10EZPF2201CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-06T19:55:16.107', 
  '1', 
  '77204', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/esr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '2.2 kOhms', 
  '0.4W, 2/5W', 
  'ESR', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2.2 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH POWER LOW OHMIC CHIP RESIST', 
  'LTR10LEZPFLR100', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/LTR10LEZPFLR100/18674863', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '0/ +150ppm/°C', 
  '0508', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-LTR10LEZPFLR100CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Current Sense', 
  '2023-05-06T19:55:16.113', 
  '1', 
  '77205', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.049" L x 0.079" W (1.25mm x 2.00mm)', 
  '100 mOhms', 
  '1W', 
  'LTR', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '100 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 4.99K OHM 1% 0.4W 0805', 
  'ESR10EZPF4991', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/ESR10EZPF4991/4007659', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-ESR10EZPF4991CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-06T19:55:16.120', 
  '1', 
  '77206', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/esr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '4.99 kOhms', 
  '0.4W, 2/5W', 
  'ESR', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '4.99 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 499 OHM 1% 0.4W 0805', 
  'ESR10EZPF4990', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/ESR10EZPF4990/4007658', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-ESR10EZPF4990CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-06T19:55:16.127', 
  '1', 
  '77207', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/esr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '499 Ohms', 
  '0.4W, 2/5W', 
  'ESR', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '499 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 8.06K OHM 1% 0.4W 0805', 
  'ESR10EZPF8061', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/ESR10EZPF8061/4007760', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-ESR10EZPF8061CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-06T19:55:16.133', 
  '1', 
  '77208', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/esr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '8.06 kOhms', 
  '0.4W, 2/5W', 
  'ESR', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '8.06 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 2.4 OHM 1% 0.4W 0805', 
  'ESR10EZPF2R40', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/ESR10EZPF2R40/1983518', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-ESR10EZPF2R40CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-06T19:55:16.140', 
  '1', 
  '77209', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/esr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '2.4 Ohms', 
  '0.4W, 2/5W', 
  'ESR', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2.4 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 3.9 OHM 1% 0.4W 0805', 
  'ESR10EZPF3R90', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/ESR10EZPF3R90/1983528', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-ESR10EZPF3R90CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-06T19:55:16.143', 
  '1', 
  '77210', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/esr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '3.9 Ohms', 
  '0.4W, 2/5W', 
  'ESR', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '3.9 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 1 OHM 1% 0.4W 0805', 
  'ESR10EZPF1R00', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/ESR10EZPF1R00/4007439', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-ESR10EZPF1R00CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-06T19:55:16.147', 
  '1', 
  '77211', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/esr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '1 Ohms', 
  '0.4W, 2/5W', 
  'ESR', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

