--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '1.0 UH SHIELDED MOLDED INDUCTOR', 
  'TMIM 201610A-1R0MG', 
  'https://www.digikey.com/en/products/detail/tai-tech-advanced-electronics-co-ltd/TMIM-201610A-1R0MG/17835735', 
  '0.039" (1.00mm)', 
  '3.2 A', 
  '0806 (2016 Metric)', 
  '59mOhm Max', 
  '0806', 
  '1 µH', 
  '0806 (2016 Metric)', 
  'INDUCTOR', 
  '4816-TMIM201610A-1R0MGCT-ND', 
  'Active', 
  'TAI-TECH Advanced Electronics Co., Ltd.', 
  '2023-05-06T20:31:31.933', 
  '1', 
  '6394', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100 kHz', 
  'https://media.digikey.com/pdf/Data%20Sheets/Tai%20Tech%20PDFs/TMIM%20Series.pdf', 
  'IND 0806_2016', 
  'Datasheet', 
  '±20%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.063" W (2.00mm x 1.60mm)', 
  'TMIM201610A', 
  'Molded', 
  '0.09', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1 µH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0806_2016.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '2.2 UH SHIELDED MOLDED INDUCTOR', 
  'TMIM 201610A-2R2MG', 
  'https://www.digikey.com/en/products/detail/tai-tech-advanced-electronics-co-ltd/TMIM-201610A-2R2MG/17835791', 
  '0.039" (1.00mm)', 
  '2 A', 
  '0806 (2016 Metric)', 
  '150mOhm Max', 
  '0806', 
  '2.2 µH', 
  '0806 (2016 Metric)', 
  'INDUCTOR', 
  '4816-TMIM201610A-2R2MGCT-ND', 
  'Active', 
  'TAI-TECH Advanced Electronics Co., Ltd.', 
  '2023-05-06T20:31:31.953', 
  '1', 
  '6395', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100 kHz', 
  'https://media.digikey.com/pdf/Data%20Sheets/Tai%20Tech%20PDFs/TMIM%20Series.pdf', 
  'IND 0806_2016', 
  'Datasheet', 
  '±20%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.063" W (2.00mm x 1.60mm)', 
  'TMIM201610A', 
  'Molded', 
  '0.09', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2.2 µH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0806_2016.PCBLIB'
);

