--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."RF-Switches" (
  "Frequency Range",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Voltage - Supply",
  "Test Frequency",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Rf Type",
  "Comment",
  "Iip3",
  "Insertion Loss",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Circuit",
  "Supplier 1",
  "Topology",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Isolation",
  "P1db",
  "Impedance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '100MHz ~ 3GHz', 
  'IC RF SWITCH SP4T 3GHZ 14QFN', 
  'SKY13414-485LF', 
  'https://www.digikey.com/en/products/detail/skyworks-solutions-inc/SKY13414-485LF/5214211', 
  '14-QFN (2x2)', 
  '14-UFQFN Exposed Pad', 
  'SKYWORKS SKY13414-485LF', 
  '863-1582-1-ND', 
  'Active', 
  '2.5V ~ 4.8V', 
  '1GHz', 
  'Skyworks Solutions Inc.', 
  '2025-07-31T20:34:03.927', 
  '1', 
  'General Purpose', 
  '=Part Number', 
  '70dBm', 
  '0.4dB', 
  '-40°C ~ 85°C', 
  'http://www.skyworksinc.com/uploads/documents/SKY13414_485LF_201689J.pdf', 
  'SKYWORKS SKY13414-485LF', 
  'Datasheet', 
  'SP4T', 
  'DigiKey', 
  'Reflective', 
  '-', 
  '0.55', 
  'symbols/RF - Switch/SCH - RF - SWITCH - SKYWORKS SKY13414-485LF.SchLib', 
  'TapeAndReel', 
  'Active', 
  '42dB', 
  '37dBm', 
  '50Ohm', 
  'DigiKey Link', 
  'footprints/Leadless - PQFN/PCB - LEADLESS - PQFN - SKYWORKS SKY13414-485LF.PcbLib'
);

