--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 1.2PF 200V C0G/NP0 0402', 
  '600L1R2BT200T4K', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/600L1R2BT200T4K/3905152', 
  '0402 (1005 Metric)', 
  '200V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-600L1R2BT200T4KCT-ND', 
  'Active', 
  'American Technical Ceramics', 
  'High Q, Low Loss, Ultra Low ESR', 
  '2023-07-03T20:01:13.397', 
  '1', 
  '4638', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency, Bypass, Decoupling', 
  'https://datasheets.kyocera-avx.com/600L.pdf', 
  'CAP 0402_1005 RF', 
  'Datasheet', 
  '±0.1pF', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.040" L x 0.020" W (1.02mm x 0.51mm)', 
  'ATC 600L', 
  '0.024" (0.60mm)', 
  '0.37', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1.2 pF', 
  '1.2 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 5.6PF 200V C0G/NP0 0402', 
  'VJ0402D5R6CXCAJ', 
  'https://www.digikey.com/en/products/detail/vishay-vitramon/VJ0402D5R6CXCAJ/3280870', 
  '0402 (1005 Metric)', 
  '200V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '720-VJ0402D5R6CXCAJCT-ND', 
  'Active', 
  'Vishay Vitramon', 
  'High Q, Low Loss', 
  '2023-07-03T20:01:13.413', 
  '1', 
  '4639', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://www.vishay.com/docs/45258/vjhifreqseries.pdf', 
  'CAP 0402_1005 RF', 
  'Datasheet', 
  '±0.25pF', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.040" L x 0.020" W (1.02mm x 0.51mm)', 
  'VJ HIFREQ', 
  '0.024" (0.61mm)', 
  '0.09', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '5.6 pF', 
  '5.6 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 4.8PF 50V NP0 0402', 
  'GJM1555C1H4R8WB01D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GJM1555C1H4R8WB01D/2593012', 
  '0402 (1005 Metric)', 
  '50V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '490-GJM1555C1H4R8WB01DCT-ND', 
  'Active', 
  'Murata Electronics', 
  'High Q, Low Loss', 
  '2023-07-03T20:01:13.427', 
  '1', 
  '4640', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GJM1555C1H4R8WB01-01.pdf', 
  'CAP 0402_1005 RF', 
  'Datasheet', 
  '±0.05pF', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  'GJM', 
  '0.022" (0.55mm)', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '4.8 pF', 
  '4.8 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 9PF 200V NP0 0402', 
  'GQM1555C2D9R0BB01D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GQM1555C2D9R0BB01D/5882210', 
  '0402 (1005 Metric)', 
  '200V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '490-GQM1555C2D9R0BB01DCT-ND', 
  'Active', 
  'Murata Electronics', 
  'High Q, Low Loss', 
  '2023-07-03T20:01:13.437', 
  '1', 
  '4641', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GQM1555C2D9R0BB01-01A.pdf', 
  'CAP 0402_1005 RF', 
  'Datasheet', 
  '±0.1pF', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  'GQM', 
  '0.022" (0.55mm)', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '9 pF', 
  '9 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 0.5PF 200V C0G/NP0 0402', 
  '600L0R5BT200T4K', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/600L0R5BT200T4K/3905139', 
  '0402 (1005 Metric)', 
  '200V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-600L0R5BT200T4KCT-ND', 
  'Active', 
  'American Technical Ceramics', 
  'High Q, Low Loss, Ultra Low ESR', 
  '2023-07-03T20:01:13.507', 
  '1', 
  '4642', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency, Bypass, Decoupling', 
  'https://datasheets.kyocera-avx.com/600L.pdf', 
  'CAP 0402_1005 RF', 
  'Datasheet', 
  '±0.1pF', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.040" L x 0.020" W (1.02mm x 0.51mm)', 
  'ATC 600L', 
  '0.024" (0.60mm)', 
  '0.32', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '0.5 pF', 
  '0.5 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 1.1PF 200V C0G/NP0 0402', 
  '600L1R1AT200T4K', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/600L1R1AT200T4K/3905151', 
  '0402 (1005 Metric)', 
  '200V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-600L1R1AT200T4KCT-ND', 
  'Active', 
  'American Technical Ceramics', 
  'High Q, Low Loss, Ultra Low ESR', 
  '2023-07-03T20:01:13.513', 
  '1', 
  '4643', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency, Bypass, Decoupling', 
  'https://datasheets.kyocera-avx.com/600L.pdf', 
  'CAP 0402_1005 RF', 
  'Datasheet', 
  '±0.05pF', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.040" L x 0.020" W (1.02mm x 0.51mm)', 
  'ATC 600L', 
  '0.024" (0.60mm)', 
  '0.61', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1.1 pF', 
  '1.1 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 3.3PF 200V C0G/NP0 0402', 
  '600L3R3BT200T4K', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/600L3R3BT200T4K/3905166', 
  '0402 (1005 Metric)', 
  '200V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-600L3R3BT200T4KCT-ND', 
  'Active', 
  'American Technical Ceramics', 
  'High Q, Low Loss, Ultra Low ESR', 
  '2023-07-03T20:01:13.567', 
  '1', 
  '4644', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency, Bypass, Decoupling', 
  'https://datasheets.kyocera-avx.com/600L.pdf', 
  'CAP 0402_1005 RF', 
  'Datasheet', 
  '±0.1pF', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.040" L x 0.020" W (1.02mm x 0.51mm)', 
  'ATC 600L', 
  '0.024" (0.60mm)', 
  '0.49', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '3.3 pF', 
  '3.3 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 22PF 200V C0G/NP0 0402', 
  '600L220JT200T4K', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/600L220JT200T4K/3905158', 
  '0402 (1005 Metric)', 
  '200V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-600L220JT200T4KCT-ND', 
  'Active', 
  'American Technical Ceramics', 
  'High Q, Low Loss, Ultra Low ESR', 
  '2023-07-03T20:01:13.613', 
  '1', 
  '4645', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency, Bypass, Decoupling', 
  'https://datasheets.kyocera-avx.com/600L.pdf', 
  'CAP 0402_1005 RF', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.040" L x 0.020" W (1.02mm x 0.51mm)', 
  'ATC 600L', 
  '0.024" (0.60mm)', 
  '0.34', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '22 pF', 
  '22 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 8.2PF 200V NP0 0402', 
  '600L8R2CT200T4K', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/600L8R2CT200T4K/3908971', 
  '0402 (1005 Metric)', 
  '200V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-600L8R2CT200T4KCT-ND', 
  'Active', 
  'American Technical Ceramics', 
  'High Q, Low Loss, Ultra Low ESR', 
  '2023-07-03T20:01:13.630', 
  '1', 
  '4646', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency, Bypass, Decoupling', 
  'https://datasheets.kyocera-avx.com/600L.pdf', 
  'CAP 0402_1005 RF', 
  'Datasheet', 
  '±0.25pF', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.040" L x 0.020" W (1.02mm x 0.51mm)', 
  'ATC 600L', 
  '0.024" (0.60mm)', 
  '0.64', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '8.2 pF', 
  '8.2 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 10PF 200V C0G/NP0 0402', 
  '600L100FT200T4K', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/600L100FT200T4K/3905053', 
  '0402 (1005 Metric)', 
  '200V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-600L100FT200T4KCT-ND', 
  'Active', 
  'American Technical Ceramics', 
  'High Q, Low Loss, Ultra Low ESR', 
  '2023-07-03T20:01:13.677', 
  '1', 
  '4647', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency, Bypass, Decoupling', 
  'https://datasheets.kyocera-avx.com/600L.pdf', 
  'CAP 0402_1005 RF', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.040" L x 0.020" W (1.02mm x 0.51mm)', 
  'ATC 600L', 
  '0.024" (0.60mm)', 
  '0.81', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '10 pF', 
  '10 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 0.3PF 200V C0G/NP0 0402', 
  '600L0R3AT200T4K', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/600L0R3AT200T4K/3905004', 
  '0402 (1005 Metric)', 
  '200V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-600L0R3AT200T4KCT-ND', 
  'Active', 
  'American Technical Ceramics', 
  'High Q, Low Loss, Ultra Low ESR', 
  '2023-07-03T20:01:13.727', 
  '1', 
  '4648', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency, Bypass, Decoupling', 
  'https://datasheets.kyocera-avx.com/600L.pdf', 
  'CAP 0402_1005 RF', 
  'Datasheet', 
  '±0.05pF', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.040" L x 0.020" W (1.02mm x 0.51mm)', 
  'ATC 600L', 
  '0.024" (0.60mm)', 
  '0.53', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '0.3 pF', 
  '0.3 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 10PF 200V NP0 0402', 
  '600L100FW200T4K', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/600L100FW200T4K/3908910', 
  '0402 (1005 Metric)', 
  '200V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-600L100FW200T4KCT-ND', 
  'Active', 
  'American Technical Ceramics', 
  'High Q, Low Loss, Ultra Low ESR', 
  '2023-07-03T20:01:13.760', 
  '1', 
  '4649', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency, Bypass, Decoupling', 
  'https://datasheets.kyocera-avx.com/600L.pdf', 
  'CAP 0402_1005 RF', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.040" L x 0.020" W (1.02mm x 0.51mm)', 
  'ATC 600L', 
  '0.024" (0.60mm)', 
  '0.81', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '10 pF', 
  '10 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 1.2PF 200V C0G/NP0 0402', 
  '600L1R2AT200T4K', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/600L1R2AT200T4K/3905006', 
  '0402 (1005 Metric)', 
  '200V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-600L1R2AT200T4KCT-ND', 
  'Active', 
  'American Technical Ceramics', 
  'High Q, Low Loss, Ultra Low ESR', 
  '2023-07-03T20:01:13.777', 
  '1', 
  '4650', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency, Bypass, Decoupling', 
  'https://datasheets.kyocera-avx.com/600L.pdf', 
  'CAP 0402_1005 RF', 
  'Datasheet', 
  '±0.05pF', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.040" L x 0.020" W (1.02mm x 0.51mm)', 
  'ATC 600L', 
  '0.024" (0.60mm)', 
  '0.61', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1.2 pF', 
  '1.2 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 1.6PF 200V C0G/NP0 0402', 
  '600L1R6AT200T4K', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/600L1R6AT200T4K/3905155', 
  '0402 (1005 Metric)', 
  '200V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-600L1R6AT200T4KCT-ND', 
  'Active', 
  'American Technical Ceramics', 
  'High Q, Low Loss, Ultra Low ESR', 
  '2023-07-03T20:01:13.783', 
  '1', 
  '4651', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency, Bypass, Decoupling', 
  'https://datasheets.kyocera-avx.com/600L.pdf', 
  'CAP 0402_1005 RF', 
  'Datasheet', 
  '±0.05pF', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.040" L x 0.020" W (1.02mm x 0.51mm)', 
  'ATC 600L', 
  '0.024" (0.60mm)', 
  '0.69', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1.6 pF', 
  '1.6 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER MLCC', 
  'GQM1875C2E750FB12D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GQM1875C2E750FB12D/10704733', 
  '0603 (1608 Metric)', 
  '250V', 
  'C0G, NP0', 
  '0603 (1608 Metric)', 
  'CAPACITOR', 
  '490-GQM1875C2E750FB12DCT-ND', 
  'Active', 
  'Murata Electronics', 
  'High Q, Low Loss', 
  '2023-07-03T20:04:23.657', 
  '1', 
  '4652', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GQM1875C2E750FB12-01A.pdf', 
  'CAP 0603_1608 RF', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  'GQM', 
  '0.031" (0.80mm)', 
  '0.11', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '75 pF', 
  '75 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0603_1608 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 13PF 200V NP0 0603', 
  'KGQ15ACG2D130FT', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGQ15ACG2D130FT/1598989', 
  '0603 (1608 Metric)', 
  '200V', 
  'C0G, NP0', 
  '0603 (1608 Metric)', 
  'CAPACITOR', 
  '478-KGQ15ACG2D130FTCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  'Ultra Low ESR', 
  '2023-07-03T20:04:23.767', 
  '1', 
  '4653', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://datasheets.kyocera-avx.com/U-Series.pdf', 
  'CAP 0603_1608 RF', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  'U', 
  '0.036" (0.91mm)', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '13 pF', 
  '13 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0603_1608 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH-Q MLCC (CF): 0603, 22 PF (1', 
  'C06CF220F-9ZN-X0T', 
  'https://www.digikey.com/en/products/detail/knowles-dielectric-labs/C06CF220F-9ZN-X0T/19203937', 
  '0603 (1608 Metric)', 
  '250V', 
  'C0G, NP0', 
  '0603 (1608 Metric)', 
  'CAPACITOR', 
  '1761-C06CF220F-9ZN-X0TCT-ND', 
  'Active', 
  'Knowles Dielectric Labs', 
  'High Q, Low Loss', 
  '2023-07-03T20:04:23.853', 
  '1', 
  '4654', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://media.digikey.com/pdf/Data%20Sheets/Knowles%20Dielectric%20Labs%20PDFs/MLC_SLC_Cap_Cat.pdf', 
  'CAP 0603_1608 RF', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  'CF', 
  '0.031" (0.80mm)', 
  '2.56', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '22 pF', 
  '22 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0603_1608 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH-Q MLCC (CF): 0603, 39 PF (1', 
  'C06CF390F-9ZN-X0T', 
  'https://www.digikey.com/en/products/detail/knowles-dielectric-labs/C06CF390F-9ZN-X0T/19204452', 
  '0603 (1608 Metric)', 
  '250V', 
  'C0G, NP0', 
  '0603 (1608 Metric)', 
  'CAPACITOR', 
  '1761-C06CF390F-9ZN-X0TCT-ND', 
  'Active', 
  'Knowles Dielectric Labs', 
  'High Q, Low Loss', 
  '2023-07-03T20:04:23.863', 
  '1', 
  '4655', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://media.digikey.com/pdf/Data%20Sheets/Knowles%20Dielectric%20Labs%20PDFs/MLC_SLC_Cap_Cat.pdf', 
  'CAP 0603_1608 RF', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  'CF', 
  '0.031" (0.80mm)', 
  '2.59', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '39 pF', 
  '39 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0603_1608 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH-Q MLCC (CF): 0603, 15 PF (1', 
  'C06CF150F-9ZN-X0T', 
  'https://www.digikey.com/en/products/detail/knowles-dielectric-labs/C06CF150F-9ZN-X0T/19204050', 
  '0603 (1608 Metric)', 
  '250V', 
  'C0G, NP0', 
  '0603 (1608 Metric)', 
  'CAPACITOR', 
  '1761-C06CF150F-9ZN-X0TCT-ND', 
  'Active', 
  'Knowles Dielectric Labs', 
  'High Q, Low Loss', 
  '2023-07-03T20:04:23.890', 
  '1', 
  '4656', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://media.digikey.com/pdf/Data%20Sheets/Knowles%20Dielectric%20Labs%20PDFs/MLC_SLC_Cap_Cat.pdf', 
  'CAP 0603_1608 RF', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.060" L x 0.030" W (1.52mm x 0.76mm)', 
  'CF', 
  '0.031" (0.80mm)', 
  '2.54', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '15 pF', 
  '15 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0603_1608 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 0.3PF 250V NP0 0805', 
  'GQM2195C2ER30BB12D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GQM2195C2ER30BB12D/2042699', 
  '0805 (2012 Metric)', 
  '250V', 
  'C0G, NP0', 
  '0805 (2012 Metric)', 
  'CAPACITOR', 
  '490-GQM2195C2ER30BB12DCT-ND', 
  'Active', 
  'Murata Electronics', 
  'High Q, Low Loss', 
  '2023-07-03T20:07:07.943', 
  '1', 
  '4657', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GQM2195C2ER30BB12-01.pdf', 
  'CAP 0805_2012 RF', 
  'Datasheet', 
  '±0.1pF', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  'GQM', 
  '0.039" (1.00mm)', 
  '0.20', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '0.3 pF', 
  '0.3 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0805_2012 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 82PF 250V NP0 0805', 
  'GQM2195C2E820GB12D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GQM2195C2E820GB12D/2042742', 
  '0805 (2012 Metric)', 
  '250V', 
  'C0G, NP0', 
  '0805 (2012 Metric)', 
  'CAPACITOR', 
  '490-GQM2195C2E820GB12DCT-ND', 
  'Active', 
  'Murata Electronics', 
  'High Q, Low Loss', 
  '2023-07-03T20:07:07.973', 
  '1', 
  '4658', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GQM2195C2E820GB12-01.pdf', 
  'CAP 0805_2012 RF', 
  'Datasheet', 
  '±2%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  'GQM', 
  '0.039" (1.00mm)', 
  '0.33', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '82 pF', 
  '82 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0805_2012 RF.PCBLIB'
);

