--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "LED-Indication" (
  "Description",
  "Configuration",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Millicandela Rating",
  "Lens Style",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Color",
  "ComponentLink1Description",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'REVERSE MOUNT / PLCC 4 / 3.5 X 2', 
  'Common Anode', 
  'IN-P32TRRRGB', 
  'https://www.digikey.com/en/products/detail/inolux/IN-P32TRRRGB/14555717', 
  'Clear', 
  '120°', 
  '600mcd Red, 2000mcd Green, 450mcd Blue', 
  'Round with Flat Top', 
  'LED RGB COMMON ANODE', 
  '1830-IN-P32TRRRGBCT-ND', 
  'Active', 
  'Inolux', 
  '2V Red, 3.2V Green, 3.2V Blue', 
  '2023-07-02T14:10:27.453', 
  '1', 
  '632nm Red, 520nm Green, 468nm Blue', 
  '1353', 
  '2.40mm Dia', 
  '=Part Number', 
  'https://www.inolux-corp.com/datasheet/SMDLED/Mono%20Color%20Reverse%20Mount/IN-P32TRRRGB_V1.2.pdf', 
  'INOLUX IN-P32TRRRGB', 
  'Red, Green, Blue (RGB)', 
  'Datasheet', 
  '20mA Red, 20mA Green, 20mA Blue', 
  'DigiKey', 
  'Surface Mount, Bottom Entry', 
  '3.25mm L x 2.80mm W', 
  '-', 
  '0.09', 
  'symbols/Diodes/SCH - DIODES - LED RGB COMMON ANODE.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - INOLUX IN-P32TRRRGB.PCBLIB'
);

INSERT INTO "LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Configuration",
  "Part Number",
  "ComponentLink2URL",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "Footprint Ref",
  "Color",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '473nm', 
  'CHIP,TOP MT,INGAN, BLUE', 
  'Standard', 
  'HSMR-C320', 
  'https://www.digikey.com/en/products/detail/broadcom-limited/HSMR-C320/10257474', 
  '50°', 
  '0603 (1608 Metric)', 
  '653mcd', 
  '0603', 
  'Round with Domed Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '516-HSMR-C320CT-ND', 
  'Active', 
  'Broadcom Limited', 
  '3V', 
  '2023-07-03T20:17:21.640', 
  '1', 
  '469nm', 
  '1354', 
  '0.70mm Dia', 
  '=Value', 
  'LED 0603_1608 BLUE', 
  'Blue', 
  '20mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '1.08mm', 
  '-', 
  '0.34', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  'Blue', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 BLUE.PCBLIB'
);

INSERT INTO "LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Configuration",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Color",
  "ComponentLink1Description",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Lens Color",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '631nm', 
  'LED RED CLEAR 0402 SMD', 
  'Standard', 
  'XZMDR68W-3', 
  'https://www.digikey.com/en/products/detail/sunled/XZMDR68W-3/6615526', 
  'Clear', 
  '120°', 
  '0402 (1005 Metric)', 
  '64mcd', 
  '0402', 
  'Rectangle with Flat Top', 
  '0402 (1005 Metric)', 
  'LED', 
  '1497-XZMDR68W-3CT-ND', 
  'Active', 
  'SunLED', 
  '2V', 
  '2023-07-03T20:18:41.010', 
  '1', 
  '639nm', 
  '1355', 
  '0.60mm x 0.50mm', 
  '=Value', 
  'https://www.sunledusa.com/products/spec/XZMDR68W-3.pdf', 
  'LED 0402_1005 RED', 
  'Red', 
  'Datasheet', 
  '20mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.00mm L x 0.50mm W', 
  '0.25mm', 
  '-', 
  '0.10', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  'Red', 
  'Colorless', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0402_1005 RED.PCBLIB'
);

