--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "DC Resistance (DCR) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD 220 OHM 0402 1LN', 
  '220 Ohms @ 100 MHz', 
  'BLM15PX221BH1D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/BLM15PX221BH1D/18742628', 
  '0402 (1005 Metric)', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'FERRITE CHIP', 
  '490-BLM15PX221BH1DCT-ND', 
  '1.4A', 
  'Active', 
  'Murata Electronics', 
  'Automotive', 
  '2023-07-03T20:10:44.540', 
  '1', 
  '3417', 
  '=Value', 
  '-55°C ~ 150°C', 
  'https://www.murata.com/products/productdata/8817911136286/QNFA9176.pdf', 
  'FER 0402_1005', 
  'Datasheet', 
  '100mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '0.022" (0.55mm)', 
  'BLM15PX', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '220 Ohms @ 100 MHz', 
  'Power, Signal Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0402_1005.PCBLIB', 
  '1'
);

INSERT INTO "Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "DC Resistance (DCR) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD 180 OHM 0402 1LN', 
  '180 Ohms @ 100 MHz', 
  'BLM15PX181BH1D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/BLM15PX181BH1D/18742635', 
  '0402 (1005 Metric)', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'FERRITE CHIP', 
  '490-BLM15PX181BH1DCT-ND', 
  '1.5A', 
  'Active', 
  'Murata Electronics', 
  'Automotive', 
  '2023-07-03T20:10:44.560', 
  '1', 
  '3418', 
  '=Value', 
  '-55°C ~ 150°C', 
  'https://www.murata.com/products/productdata/8817911136286/QNFA9176.pdf', 
  'FER 0402_1005', 
  'Datasheet', 
  '90mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '0.022" (0.55mm)', 
  'BLM15PX', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '180 Ohms @ 100 MHz', 
  'Power, Signal Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0402_1005.PCBLIB', 
  '1'
);

INSERT INTO "Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "DC Resistance (DCR) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD 220 OHM 0402 1LN', 
  '220 Ohms @ 100 MHz', 
  'BLM15PX221SH1D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/BLM15PX221SH1D/18742630', 
  '0402 (1005 Metric)', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'FERRITE CHIP', 
  '490-BLM15PX221SH1DCT-ND', 
  '1.4A', 
  'Active', 
  'Murata Electronics', 
  'Automotive', 
  '2023-07-03T20:10:44.600', 
  '1', 
  '3419', 
  '=Value', 
  '-55°C ~ 125°C', 
  'https://www.murata.com/products/productdata/8796743696414/QNFA9103.pdf', 
  'FER 0402_1005', 
  'Datasheet', 
  '100mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '0.022" (0.55mm)', 
  'BLM15PX', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '220 Ohms @ 100 MHz', 
  'Power, Signal Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0402_1005.PCBLIB', 
  '1'
);

INSERT INTO "Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Footprint Ref",
  "DC Resistance (DCR) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD', 
  '600 Ohms @ 100 MHz', 
  'BLM18HG601SZ1D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/BLM18HG601SZ1D/10698347', 
  '0603 (1608 Metric)', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'FERRITE CHIP', 
  '490-BLM18HG601SZ1DCT-ND', 
  '200mA', 
  'Active', 
  'Murata Electronics', 
  'Automotive', 
  '2023-07-03T20:11:16.263', 
  '1', 
  '3420', 
  '=Value', 
  '-55°C ~ 125°C', 
  'FER 0603_1608', 
  '1Ohm', 
  'DigiKey', 
  'Surface Mount', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  '0.037" (0.95mm)', 
  'BLM', 
  '0.04', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '600 Ohms @ 100 MHz', 
  'Signal Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0603_1608.PCBLIB', 
  '1'
);

INSERT INTO "Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "DC Resistance (DCR) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD 8.5 OHM 0603 1LN', 
  '8.5 Ohms @ 100 MHz', 
  'BLE18PS080BH1D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/BLE18PS080BH1D/13904871', 
  '0603 (1608 Metric)', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'FERRITE CHIP', 
  '490-BLE18PS080BH1DCT-ND', 
  '5A', 
  'Active', 
  'Murata Electronics', 
  '2023-07-03T20:11:16.283', 
  '1', 
  '3421', 
  '=Value', 
  '-55°C ~ 150°C', 
  'https://www.murata.com/products/productdata/8801029750814/QNFA9147.pdf', 
  'FER 0603_1608', 
  'Datasheet', 
  '4mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  '0.030" (0.75mm)', 
  'EMIFIL®, BLE18', 
  '0.09', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '8.5 Ohms @ 100 MHz', 
  'Power Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0603_1608.PCBLIB', 
  '1'
);

INSERT INTO "Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "DC Resistance (DCR) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD', 
  '120 Ohms @ 100 MHz', 
  'BLM21PG121BH1D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/BLM21PG121BH1D/10702696', 
  '0805 (2012 Metric)', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'FERRITE CHIP', 
  '490-BLM21PG121BH1DCT-ND', 
  '1.55A', 
  'Active', 
  'Murata Electronics', 
  'Automotive', 
  '2023-07-03T20:11:41.930', 
  '1', 
  '3422', 
  '=Value', 
  '-55°C ~ 150°C', 
  'https://www.murata.com/en-us/products/en-us/products/productdata/8798463819806/QNFA9131.pdf', 
  'FER 0805_2012', 
  'Datasheet', 
  '30mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '0.041" (1.05mm)', 
  'BLM', 
  '0.04', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '120 Ohms @ 100 MHz', 
  'Power Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0805_2012.PCBLIB', 
  '1'
);

INSERT INTO "Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "DC Resistance (DCR) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD', 
  '220 Ohms @ 100 MHz', 
  'BLM21AG221BH1D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/BLM21AG221BH1D/10691298', 
  '0805 (2012 Metric)', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'FERRITE CHIP', 
  '490-BLM21AG221BH1DCT-ND', 
  '900mA', 
  'Active', 
  'Murata Electronics', 
  'Automotive', 
  '2023-07-03T20:11:41.947', 
  '1', 
  '3423', 
  '=Value', 
  '-55°C ~ 150°C', 
  'https://www.murata.com/en-us/products/en-us/products/productdata/8798463819806/QNFA9131.pdf', 
  'FER 0805_2012', 
  'Datasheet', 
  '120mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '0.041" (1.05mm)', 
  'BLM', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '220 Ohms @ 100 MHz', 
  'Signal Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0805_2012.PCBLIB', 
  '1'
);

INSERT INTO "Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "DC Resistance (DCR) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD', 
  '22 Ohms @ 100 MHz', 
  'BLM21PG220BH1D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/BLM21PG220BH1D/10695174', 
  '0805 (2012 Metric)', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'FERRITE CHIP', 
  '490-BLM21PG220BH1DCT-ND', 
  '3.3A', 
  'Active', 
  'Murata Electronics', 
  'Automotive', 
  '2023-07-03T20:11:41.997', 
  '1', 
  '3424', 
  '=Value', 
  '-55°C ~ 150°C', 
  'https://www.murata.com/en-us/products/en-us/products/productdata/8798463819806/QNFA9131.pdf', 
  'FER 0805_2012', 
  'Datasheet', 
  '9mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '0.041" (1.05mm)', 
  'BLM', 
  '0.04', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '22 Ohms @ 100 MHz', 
  'Power Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0805_2012.PCBLIB', 
  '1'
);

