--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Capacitors-Tantalum" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Manufacturer Size Code",
  "Height - Seated (Max)",
  "Device Package",
  "Voltage - Rated",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP TANT 10UF 10% 20V 1411', 
  'T494B106K020AG', 
  'https://www.digikey.com/en/products/detail/kemet/T494B106K020AG/12546414', 
  'B', 
  '0.083" (2.10mm)', 
  '1411 (3528 Metric)', 
  '20 V', 
  '1411 (3528 Metric)', 
  'POLARISED CAPACITOR', 
  '399-T494B106K020AG-ND', 
  'Active', 
  'KEMET', 
  'General Purpose', 
  '2023-07-03T19:55:21.810', 
  '1', 
  '5359', 
  '=Value', 
  '-55°C ~ 125°C', 
  'https://connect.kemet.com:7667/gateway/IntelliData-ComponentDocumentation/1.0/download/datasheet/T494B106K020AG', 
  'CAP POL 1411_3528', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  '1Ohm @ 100kHz', 
  'Surface Mount', 
  '0.138" L x 0.110" W (3.50mm x 2.80mm)', 
  '2000 Hrs @ 125°C', 
  'T494', 
  'Molded', 
  '0.77', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'Bulk', 
  'Active', 
  '10 µF', 
  '10 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Tantalum/PCB - CAPACITOR - TANTALUM - CAP POL 1411_3528.PCBLIB'
);

INSERT INTO "Capacitors-Tantalum" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Manufacturer Size Code",
  "Height - Seated (Max)",
  "Device Package",
  "Voltage - Rated",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP TANT 150UF 20% 6.3V 1206', 
  'TLJA157M006R0900', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/TLJA157M006R0900/3068501', 
  'A', 
  '0.071" (1.80mm)', 
  '1206 (3216 Metric)', 
  '6.3 V', 
  '1206 (3216 Metric)', 
  'POLARISED CAPACITOR', 
  '478-TLJA157M006R0900CT-ND', 
  'Active', 
  'KYOCERA AVX', 
  'General Purpose', 
  '2023-07-03T19:55:53.933', 
  '1', 
  '5360', 
  '=Value', 
  '-55°C ~ 125°C', 
  'https://datasheets.kyocera-avx.com/TLJ.pdf', 
  'CAP POL 1206_3216', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '900mOhm', 
  'Surface Mount', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'TLJ', 
  'Molded', 
  '0.84', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '150 µF', 
  '150 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Tantalum/PCB - CAPACITOR - TANTALUM - CAP POL 1206_3216.PCBLIB'
);

INSERT INTO "Capacitors-Tantalum" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Manufacturer Size Code",
  "Height - Seated (Max)",
  "Device Package",
  "Voltage - Rated",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP TANT 47UF 10% 20V 2917', 
  'T496X476K020ATE300', 
  'https://www.digikey.com/en/products/detail/kemet/T496X476K020ATE300/3759763', 
  'X', 
  '0.169" (4.30mm)', 
  '2917 (7343 Metric)', 
  '20 V', 
  '2917 (7343 Metric)', 
  'POLARISED CAPACITOR', 
  '399-T496X476K020ATE300CT-ND', 
  'Active', 
  'KEMET', 
  'Fail Safe with Built-in Fuse', 
  '2023-07-03T19:56:34.883', 
  '1', 
  '5361', 
  '=Value', 
  '-55°C ~ 125°C', 
  'https://connect.kemet.com:7667/gateway/IntelliData-ComponentDocumentation/1.0/download/specsheet/T496X476K020ATE300', 
  'CAP POL 2917_7343', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  '300mOhm', 
  'Surface Mount', 
  '0.287" L x 0.169" W (7.30mm x 4.30mm)', 
  '2000 Hrs @ 85°C', 
  'T496', 
  'Molded', 
  '2.88', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '47 µF', 
  '47 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Tantalum/PCB - CAPACITOR - TANTALUM - CAP POL 2917_7343.PCBLIB'
);

INSERT INTO "Capacitors-Tantalum" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Manufacturer Size Code",
  "Height - Seated (Max)",
  "Device Package",
  "Voltage - Rated",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP TANT 100UF 10% 16V 2917', 
  'TPSD107K016R0125V', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/TPSD107K016R0125V/11203048', 
  'D', 
  '0.122" (3.10mm)', 
  '2917 (7343 Metric)', 
  '16 V', 
  '2917 (7343 Metric)', 
  'POLARISED CAPACITOR', 
  '478-TPSD107K016R0125VCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  'General Purpose', 
  '2023-07-03T19:56:34.907', 
  '1', 
  '5362', 
  '=Value', 
  '-55°C ~ 125°C', 
  'https://datasheets.kyocera-avx.com/TPS.pdf', 
  'CAP POL 2917_7343', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  '125mOhm @ 100kHz', 
  'Surface Mount', 
  '0.287" L x 0.169" W (7.30mm x 4.30mm)', 
  '2000 Hrs @ 125°C', 
  'TPS', 
  'Molded', 
  '1.21', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '100 µF', 
  '100 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Tantalum/PCB - CAPACITOR - TANTALUM - CAP POL 2917_7343.PCBLIB'
);

INSERT INTO "Capacitors-Tantalum" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Manufacturer Size Code",
  "Height - Seated (Max)",
  "Device Package",
  "Voltage - Rated",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP TANT 4.7UF 10% 50V 2917', 
  'T496D475K050ATE400', 
  'https://www.digikey.com/en/products/detail/kemet/T496D475K050ATE400/12546470', 
  'D', 
  '0.122" (3.10mm)', 
  '2917 (7343 Metric)', 
  '50 V', 
  '2917 (7343 Metric)', 
  'POLARISED CAPACITOR', 
  '399-T496D475K050ATE400CT-ND', 
  'Active', 
  'KEMET', 
  'General Purpose', 
  '2023-07-03T19:56:34.920', 
  '1', 
  '5363', 
  '=Value', 
  '-55°C ~ 125°C', 
  'https://connect.kemet.com:7667/gateway/IntelliData-ComponentDocumentation/1.0/download/datasheet/T496D475K050ATE400', 
  'CAP POL 2917_7343', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  '400mOhm @ 100kHz', 
  'Surface Mount', 
  '0.287" L x 0.169" W (7.30mm x 4.30mm)', 
  '2000 Hrs @ 125°C', 
  'T496', 
  'Molded', 
  '1.19', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '4.7 µF', 
  '4.7 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Tantalum/PCB - CAPACITOR - TANTALUM - CAP POL 2917_7343.PCBLIB'
);

