--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 50 OHM 0.5% 1/20W 0201', 
  'RFD0603P-50R0-D-T10', 
  'https://www.digikey.com/en/products/detail/susumu/RFD0603P-50R0-D-T10/18103247', 
  '0.012" (0.30mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '±25ppm/°C', 
  '0201', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '408-RFD0603P-50R0-D-T10CT-ND', 
  'Active', 
  'Susumu', 
  '2023-07-03T19:18:40.800', 
  '1', 
  '78454', 
  '=Value', 
  '-40°C ~ 125°C', 
  'Thin Film', 
  'https://www.susumu.co.jp/common/pdf/n_catalog_partition42_en.pdf', 
  'RES 0201_0603', 
  'Datasheet', 
  '±0.5%', 
  'DigiKey', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  '50 Ohms', 
  '0.05W, 1/20W', 
  'RFD', 
  '0.95', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '50 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

