--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Capacitors-Ceramic-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER .47UF      0402', 
  'KGM05HR51C474KH', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGM05HR51C474KH/13557250', 
  '0402 (1005 Metric)', 
  '16V', 
  'X5R', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-KGM05HR51C474KHCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2023-05-23T19:05:02.300', 
  '1', 
  '51836', 
  '=Value', 
  '-55°C ~ 85°C', 
  'General Purpose', 
  'https://datasheets.kyocera-avx.com/C0GNP0-Dielectric.pdf', 
  'CAP 0402_1005', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '-', 
  '0.022" (0.56mm)', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '0.47 µF', 
  '0.47 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 680PF 25V X7R 0402', 
  'KGM05AR71E681JH', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGM05AR71E681JH/1597333', 
  '0402 (1005 Metric)', 
  '25V', 
  'X7R', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-KGM05AR71E681JHCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2023-05-23T19:05:02.327', 
  '1', 
  '51837', 
  '=Value', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://datasheets.kyocera-avx.com/X7RDielectric.pdf', 
  'CAP 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '-', 
  '0.022" (0.56mm)', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '680 pF', 
  '680 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 0.012UF 16V X7R 0402', 
  'KGM05AR71C123JH', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGM05AR71C123JH/1597810', 
  '0402 (1005 Metric)', 
  '16V', 
  'X7R', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-KGM05AR71C123JHCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2023-05-23T19:05:02.333', 
  '1', 
  '51838', 
  '=Value', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://datasheets.kyocera-avx.com/X7RDielectric.pdf', 
  'CAP 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '-', 
  '0.022" (0.56mm)', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '0.012 µF', 
  '0.012 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 820PF 50V C0G/NP0 0402', 
  'KGM05ACG1H821JH', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGM05ACG1H821JH/9948352', 
  '0402 (1005 Metric)', 
  '50V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-KGM05ACG1H821JHCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2023-05-23T19:05:02.340', 
  '1', 
  '51839', 
  '=Value', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://datasheets.kyocera-avx.com/C0GNP0-Dielectric.pdf', 
  'CAP 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '-', 
  '0.022" (0.56mm)', 
  '0.09', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '820 pF', 
  '820 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 15PF 25V NP0 0402', 
  'KGM05ACG1E150JH', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGM05ACG1E150JH/1597116', 
  '0402 (1005 Metric)', 
  '25V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-KGM05ACG1E150JHCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2023-05-23T19:05:02.350', 
  '1', 
  '51840', 
  '=Value', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://datasheets.kyocera-avx.com/C0GNP0-Dielectric.pdf', 
  'CAP 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '-', 
  '0.022" (0.56mm)', 
  '0.04', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '15 pF', 
  '15 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 2.2UF 16V X5R 0402', 
  'KGM05AR51C225KH', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGM05AR51C225KH/10815005', 
  '0402 (1005 Metric)', 
  '16V', 
  'X5R', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-KGM05AR51C225KHCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2023-05-23T19:05:02.357', 
  '1', 
  '51841', 
  '=Value', 
  '-55°C ~ 85°C', 
  'General Purpose', 
  'https://ele.kyocera.com/assets/products/capacitor/CM_Series_e.pdf', 
  'CAP 0402_1005', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  'CM', 
  '0.022" (0.55mm)', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2.2 µF', 
  '2.2 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER SMD', 
  'KAM05AR71H681KH', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KAM05AR71H681KH/11267749', 
  '0402 (1005 Metric)', 
  '50V', 
  'X7R', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-KAM05AR71H681KHCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2023-05-23T19:05:02.363', 
  '1', 
  '51842', 
  '=Value', 
  '-55°C ~ 125°C', 
  'Automotive', 
  'CAP 0402_1005', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.040" L x 0.020" W (1.00mm x 0.50mm)', 
  '-', 
  '0.022" (0.56mm)', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '680 pF', 
  '680 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 3.1PF 50V NP0 0402', 
  'GJM1555C1H3R1BB01D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GJM1555C1H3R1BB01D/2592949', 
  '0402 (1005 Metric)', 
  '50V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '490-GJM1555C1H3R1BB01DCT-ND', 
  'Active', 
  'Murata Electronics', 
  'High Q, Low Loss', 
  '2023-05-23T19:05:02.370', 
  '1', 
  '51843', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GJM1555C1H3R1BB01-01.pdf', 
  'CAP 0402_1005', 
  'Datasheet', 
  '±0.1pF', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  'GJM', 
  '0.022" (0.55mm)', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '3.1 pF', 
  '3.1 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '0402 25V X5R 2.2UF 10%', 
  'KGM05HR51E225KH', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGM05HR51E225KH/17868578', 
  '0402 (1005 Metric)', 
  '25V', 
  'X5R', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-KGM05HR51E225KHCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2023-05-23T19:05:02.377', 
  '1', 
  '51844', 
  '=Value', 
  '-55°C ~ 85°C', 
  'General Purpose', 
  'https://datasheets.kyocera-avx.com/cx5r.pdf', 
  'CAP 0402_1005', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '-', 
  '0.022" (0.56mm)', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2.2 µF', 
  '2.2 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 5600PF 50V X7R 0402', 
  'KGM05AR71H562JH', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGM05AR71H562JH/3079920', 
  '0402 (1005 Metric)', 
  '50V', 
  'X7R', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-KGM05AR71H562JHCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2023-05-23T19:05:02.383', 
  '1', 
  '51845', 
  '=Value', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://datasheets.kyocera-avx.com/X7RDielectric.pdf', 
  'CAP 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '-', 
  '0.022" (0.55mm)', 
  '0.06', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '5600 pF', 
  '5600 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 270PF 50V C0G/NP0 0402', 
  'KGM05ACG1H271JH', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGM05ACG1H271JH/3079879', 
  '0402 (1005 Metric)', 
  '50V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-KGM05ACG1H271JHCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2023-05-23T19:05:02.390', 
  '1', 
  '51846', 
  '=Value', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://datasheets.kyocera-avx.com/C0GNP0-Dielectric.pdf', 
  'CAP 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '-', 
  '0.022" (0.55mm)', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '270 pF', 
  '270 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER SMD', 
  'KAF05AR71E103KH', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KAF05AR71E103KH/11266103', 
  '0402 (1005 Metric)', 
  '25V', 
  'X7R', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-KAF05AR71E103KHCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  'Soft Termination', 
  '2023-05-23T19:05:02.393', 
  '1', 
  '51847', 
  '=Value', 
  '-55°C ~ 125°C', 
  'Automotive, Boardflex Sensitive', 
  'CAP 0402_1005', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.040" L x 0.020" W (1.00mm x 0.50mm)', 
  'FLEXITERM®', 
  '0.022" (0.56mm)', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '10000 pF', 
  '10000 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 30PF 50V NP0 0402', 
  'KGQ05FCG1H300GH', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGQ05FCG1H300GH/3080002', 
  '0402 (1005 Metric)', 
  '50V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-KGQ05FCG1H300GHCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  'Ultra Low ESR', 
  '2023-05-23T19:05:02.403', 
  '1', 
  '51848', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://datasheets.kyocera-avx.com/U-Series.pdf', 
  'CAP 0402_1005', 
  'Datasheet', 
  '±2%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  'U', 
  '0.022" (0.55mm)', 
  '0.03', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '30 pF', 
  '30 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 0.033UF 10V X7R 0402', 
  'KGM05AR71A333KH', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGM05AR71A333KH/563230', 
  '0402 (1005 Metric)', 
  '10V', 
  'X7R', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-KGM05AR71A333KHCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2023-05-23T19:05:02.433', 
  '1', 
  '51849', 
  '=Value', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://datasheets.kyocera-avx.com/X7RDielectric.pdf', 
  'CAP 0402_1005', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '-', 
  '0.022" (0.56mm)', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '0.033 µF', 
  '0.033 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 33PF 50V C0G/NP0 0402', 
  'KGM05ACG1H330KH', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGM05ACG1H330KH/1597458', 
  '0402 (1005 Metric)', 
  '50V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-KGM05ACG1H330KHCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2023-05-23T19:05:02.443', 
  '1', 
  '51850', 
  '=Value', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://datasheets.kyocera-avx.com/C0GNP0-Dielectric.pdf', 
  'CAP 0402_1005', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '-', 
  '0.022" (0.56mm)', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '33 pF', 
  '33 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 2200PF 50V X7R 0402', 
  'KAM05AR71H222JH', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KAM05AR71H222JH/9948353', 
  '0402 (1005 Metric)', 
  '50V', 
  'X7R', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '478-KAM05AR71H222JHCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2023-05-23T19:05:02.450', 
  '1', 
  '51851', 
  '=Value', 
  '-55°C ~ 125°C', 
  'Automotive', 
  'https://datasheets.kyocera-avx.com/AutoMLCC.pdf', 
  'CAP 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '-', 
  '0.022" (0.56mm)', 
  '0.06', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2200 pF', 
  '2200 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005.PCBLIB'
);

