--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."VoltageRegulators-SpecialPurpose" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Voltage - Output",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage - Input",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG CONV DDR 1OUT 10TDFN', 
  'MAX1510ETB+T', 
  'https://www.digikey.com/en/products/detail/analog-devices-inc-maxim-integrated/MAX1510ETB-T/1475792', 
  '10-TDFN (3x3)', 
  'AD MAX1510', 
  'MAX1510ETB+TCT-ND', 
  'Active', 
  '0.5V ~ 1.5V', 
  'Analog Devices Inc./Maxim Integrated', 
  '2024-08-28T10:55:11.353', 
  '1', 
  '1.1V ~ 3.6V', 
  '=Part Number', 
  '1', 
  '-40°C ~ 85°C', 
  'Converter, DDR', 
  'https://datasheets.maximintegrated.com/en/ds/MAX1510-MAX17510.pdf', 
  'MAXIM TDFN-10 3X3MM T1033-1', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '-', 
  '4.89', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - AD MAX1510.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - DFN/PCB - LEADLESS - DFN - MAXIM TDFN-10 3X3MM T1033-1.PCBLIB'
);

