--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Resistors-CurrentSense-SMT" (
  "Comment",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Composition",
  "Description",
  "Device Package",
  "Features",
  "Footprint Path",
  "Footprint Ref",
  "Height - Seated (Max)",
  "LastUpdated",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Minimum Order",
  "Number of Terminations",
  "Operating Temperature",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Power (Watts)",
  "Price",
  "Resistance",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Supplier Device Package",
  "Library Path",
  "Library Ref",
  "Temperature Coefficient",
  "Tolerance",
  "Value"
)
VALUES (
  '=Value', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/te-connectivity-passive-product/TLRP3A30WR020FTE/10230086', 
  'Metal Foil', 
  'RES 0.02 OHM 1% 3W 2512', 
  '2512 (6332 Metric)', 
  'Current Sense', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - TE TLRP 2512.PCBLIB', 
  'TE TLRP 2512', 
  '0.035" (0.90mm)', 
  '2023-01-24T22:34:20.443', 
  'Active', 
  'TE Connectivity Passive Product', 
  'TLRP3A30WR020FTE', 
  '4000', 
  '2', 
  '-55°C ~ 170°C', 
  '2512 (6332 Metric)', 
  'TapeAndReel', 
  '3337', 
  'Active', 
  '3W', 
  '0.16', 
  '20 mOhms', 
  'TLRP', 
  '0.252" L x 0.126" W (6.40mm x 3.20mm)', 
  'DigiKey', 
  'TLRP3A30WR020FTE-ND', 
  '2512', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'RESISTOR', 
  '±75ppm/°C', 
  '±1%', 
  '20 mOhms'
);

