--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Capacitors-Tantalum-Polymer" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Manufacturer Size Code",
  "Height - Seated (Max)",
  "Device Package",
  "Voltage - Rated",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '330UF (MICRO FARAD)15MOHM @ 100K', 
  'TCJY337M006R0015E', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/TCJY337M006R0015E/17868558', 
  'Y', 
  '0.079" (2.00mm)', 
  '2917 (7343 Metric)', 
  '6.3 V', 
  '2917 (7343 Metric)', 
  'POLARISED CAPACITOR', 
  '478-TCJY337M006R0015ECT-ND', 
  'Active', 
  'KYOCERA AVX', 
  'General Purpose', 
  '2023-05-22T20:32:57.047', 
  '1', 
  '6575', 
  '=Value', 
  '-55°C ~ 85°C', 
  'https://datasheets.kyocera-avx.com/TCJ.pdf', 
  'CAP POL 2917_7343', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '15mOhm @ 100kHz', 
  'Surface Mount', 
  '0.287" L x 0.169" W (7.30mm x 4.30mm)', 
  '2000 Hrs @ 85°C', 
  'TCJ', 
  'Molded', 
  '0.70', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '330 µF', 
  '330 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Tantalum/PCB - CAPACITOR - TANTALUM - CAP POL 2917_7343.PCBLIB'
);

INSERT INTO "Capacitors-Tantalum-Polymer" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Manufacturer Size Code",
  "Height - Seated (Max)",
  "Device Package",
  "Voltage - Rated",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '220UF (MICRO FARAD)18MOHM @ 100K', 
  'TCJD227M010R0015E', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/TCJD227M010R0015E/17868573', 
  'D', 
  '0.122" (3.10mm)', 
  '2917 (7343 Metric)', 
  '10 V', 
  '2917 (7343 Metric)', 
  'POLARISED CAPACITOR', 
  '478-TCJD227M010R0015ECT-ND', 
  'Active', 
  'KYOCERA AVX', 
  'General Purpose', 
  '2023-05-22T20:32:57.153', 
  '1', 
  '6576', 
  '=Value', 
  '-55°C ~ 105°C', 
  'https://datasheets.kyocera-avx.com/TCJ.pdf', 
  'CAP POL 2917_7343', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '15mOhm @ 100kHz', 
  'Surface Mount', 
  '0.287" L x 0.169" W (7.30mm x 4.30mm)', 
  '2000 Hrs @ 105°C', 
  'TCJ', 
  'Molded', 
  '0.72', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '220 µF', 
  '220 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Tantalum/PCB - CAPACITOR - TANTALUM - CAP POL 2917_7343.PCBLIB'
);

