--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RLW73 A2 1% R015 600PPM 5K RL', 
  'RLW73A2FR015TD', 
  'https://www.digikey.com/en/products/detail/te-connectivity-passive-product/RLW73A2FR015TD/17764212', 
  '0.028" (0.70mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±600ppm/°C', 
  '0508', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '1712-RLW73A2FR015TDCT-ND', 
  'Active', 
  'TE Connectivity Passive Product', 
  'Current Sense', 
  '2023-05-22T20:38:47.490', 
  '1', 
  '4630', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'STACKPOLE CSR0805', 
  '±1%', 
  'DigiKey', 
  '0.049" L x 0.079" W (1.25mm x 2.00mm)', 
  '15 mOhms', 
  '0.5W, 1/2W', 
  'RLW73', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '15 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - STACKPOLE CSR0805.PCBLIB'
);

INSERT INTO "Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RLW73 B2 1% R018 600PPM 5K RL', 
  'RLW73B2FR018TD', 
  'https://www.digikey.com/en/products/detail/te-connectivity-passive-product/RLW73B2FR018TD/17764069', 
  '0.028" (0.70mm)', 
  '1206 (3216 Metric)', 
  '2', 
  '±600ppm/°C', 
  '0612', 
  '1206 (3216 Metric)', 
  'RESISTOR', 
  '1712-RLW73B2FR018TDCT-ND', 
  'Active', 
  'TE Connectivity Passive Product', 
  'Current Sense', 
  '2023-05-22T20:39:19.900', 
  '1', 
  '4631', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'STACKPOLE CSR1206', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.126" W (1.60mm x 3.20mm)', 
  '18 mOhms', 
  '0.75W, 3/4W', 
  'RLW73', 
  '0.10', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '18 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - STACKPOLE CSR1206.PCBLIB'
);

INSERT INTO "Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RLW73 B2 1% R015 600PPM 5K RL', 
  'RLW73B2FR015TD', 
  'https://www.digikey.com/en/products/detail/te-connectivity-passive-product/RLW73B2FR015TD/17763965', 
  '0.028" (0.70mm)', 
  '1206 (3216 Metric)', 
  '2', 
  '±600ppm/°C', 
  '0612', 
  '1206 (3216 Metric)', 
  'RESISTOR', 
  '1712-RLW73B2FR015TDCT-ND', 
  'Active', 
  'TE Connectivity Passive Product', 
  'Current Sense', 
  '2023-05-22T20:39:19.910', 
  '1', 
  '4632', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'STACKPOLE CSR1206', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.126" W (1.60mm x 3.20mm)', 
  '15 mOhms', 
  '0.75W, 3/4W', 
  'RLW73', 
  '0.10', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '15 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - STACKPOLE CSR1206.PCBLIB'
);

INSERT INTO "Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RLW73P B2 1% R027 600PPM 5K RL', 
  'RLW73PB2FR027TD', 
  'https://www.digikey.com/en/products/detail/te-connectivity-passive-product/RLW73PB2FR027TD/17763633', 
  '0.028" (0.70mm)', 
  '1206 (3216 Metric)', 
  '2', 
  '±600ppm/°C', 
  '0612', 
  '1206 (3216 Metric)', 
  'RESISTOR', 
  '1712-RLW73PB2FR027TDCT-ND', 
  'Active', 
  'TE Connectivity Passive Product', 
  'Current Sense', 
  '2023-05-22T20:39:19.913', 
  '1', 
  '4633', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'STACKPOLE CSR1206', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.126" W (1.60mm x 3.20mm)', 
  '27 mOhms', 
  '1.5W', 
  'RLW73', 
  '0.13', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '27 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - STACKPOLE CSR1206.PCBLIB'
);

INSERT INTO "Resistors-CurrentSense-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RLW73 B2 1% R010 600PPM 5K RL', 
  'RLW73B2FR010TD', 
  'https://www.digikey.com/en/products/detail/te-connectivity-passive-product/RLW73B2FR010TD/17763476', 
  '0.028" (0.70mm)', 
  '1206 (3216 Metric)', 
  '2', 
  '±600ppm/°C', 
  '0612', 
  '1206 (3216 Metric)', 
  'RESISTOR', 
  '1712-RLW73B2FR010TDCT-ND', 
  'Active', 
  'TE Connectivity Passive Product', 
  'Current Sense', 
  '2023-05-22T20:39:19.923', 
  '1', 
  '4634', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'STACKPOLE CSR1206', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.126" W (1.60mm x 3.20mm)', 
  '10 mOhms', 
  '0.75W, 3/4W', 
  'RLW73', 
  '0.10', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '10 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - STACKPOLE CSR1206.PCBLIB'
);

