--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LINEAR 0.4V 500MA 6WDFN', 
  'NCV8135BMT040TBG', 
  'https://www.digikey.com/en/products/detail/onsemi/NCV8135BMT040TBG/9764792', 
  'Fixed', 
  '5.5V', 
  '500mA', 
  'Positive', 
  '6-WDFN (2x2)', 
  '1', 
  'ONSEMI NCV8135', 
  'NCV8135BMT040TBGOSCT-ND', 
  'Active', 
  'onsemi', 
  '0.4V', 
  '2024-08-14T14:30:50.170', 
  '1', 
  '0.1V @ 500mA', 
  '=Part Number', 
  '-40°C ~ 125°C (TJ)', 
  'https://www.onsemi.com/pdf/datasheet/ncv8135-d.pdf', 
  '55 µA', 
  'ONSEMI WDFN6 2X2 511BR', 
  '73dB ~ 90dB (1kHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  'Enable', 
  '-', 
  '0.30', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - ONSEMI NCV8135.SchLib', 
  'Over Current, Over Temperature', 
  'TapeAndReel', 
  'DigiKey Link', 
  'footprints/Leadless - DFN/PCB - LEADLESS - DFN - ONSEMI WDFN6 2X2 511BR.PCBLIB'
);

INSERT INTO "altium"."VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LINEAR 0.4V 500MA 6WDFN', 
  'NCV8135AMT040TBG', 
  'https://www.digikey.com/en/products/detail/onsemi/NCV8135AMT040TBG/9764790', 
  'Fixed', 
  '5.5V', 
  '500mA', 
  'Positive', 
  '6-WDFN (2x2)', 
  '1', 
  'ONSEMI NCV8135', 
  'NCV8135AMT040TBGOSCT-ND', 
  'Active', 
  'onsemi', 
  '0.4V', 
  '2024-08-14T14:31:58.043', 
  '1', 
  '0.1V @ 500mA', 
  '=Part Number', 
  '-40°C ~ 125°C (TJ)', 
  'https://www.onsemi.com/pdf/datasheet/ncv8135-d.pdf', 
  '55 µA', 
  'ONSEMI WDFN6 2X2 511BR', 
  '73dB ~ 90dB (1kHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  'Enable', 
  '-', 
  '0.30', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - ONSEMI NCV8135.SchLib', 
  'Over Current, Over Temperature', 
  'TapeAndReel', 
  'DigiKey Link', 
  'footprints/Leadless - DFN/PCB - LEADLESS - DFN - ONSEMI WDFN6 2X2 511BR.PCBLIB'
);

