--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."PowerSupplies-BoardMount-DC-DC-Converters" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Voltage - Input (Max)",
  "Current - Output (Max)",
  "Voltage - Input (Min)",
  "Library Ref",
  "Efficiency",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "Voltage - Isolation",
  "ComponentLink1Description",
  "Supplier 1",
  "Voltage - Output 1",
  "Mounting Type",
  "Size / Dimension",
  "Power (Watts)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'ISOLATED MODULE DC DC CONVERTERS', 
  '1S4E_0315S1U', 
  'https://www.digikey.com/en/products/detail/gaptec-electronic/1S4E-0315S1U/13691888', 
  '3.63V', 
  '66.6mA', 
  '2.97V', 
  'GAPTEC 1S4E_S1U', 
  '79%', 
  '3182-1S4E_0315S1U-ND', 
  'Active', 
  'GAPTEC Electronic', 
  '2024-10-12T06:32:24.500', 
  '1', 
  '98', 
  '=Part Number', 
  '1', 
  '-40°C ~ 85°C', 
  'ITE (Commercial)', 
  'https://gaptec-electronic.com/datenblaetter/1S4E_1U.pdf', 
  'GAPTEC 1S4E_S1U', 
  '1 kV', 
  'Datasheet', 
  'DigiKey', 
  '15V', 
  'Through Hole', 
  '0.46" L x 0.24" W x 0.40" H (11.7mm x 6.0mm x 10.2mm)', 
  '1 W', 
  '1S4E_S1U (1W)', 
  'Isolated Module', 
  '2.10', 
  'symbols/Power - Module/SCH - POWER - MODULE - GAPTEC 1S4E_S1U.SCHLIB', 
  'Tube', 
  'Active', 
  'DigiKey Link', 
  'footprints/Power Module/PCB - POWER MODULE - GAPTEC 1S4E_S1U.PCBLIB'
);

