--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 1UH 3.2A 32.4 MOHM SMD', 
  'LSXND4040TKL1R0NDG', 
  'https://www.digikey.com/en/products/detail/taiyo-yuden/LSXND4040TKL1R0NDG/16667126', 
  '0.071" (1.80mm)', 
  '3.2 A', 
  '1616', 
  '1 µH', 
  'INDUCTOR', 
  '587-LSXND4040TKL1R0NDGCT-ND', 
  'Active', 
  '90MHz', 
  'Taiyo Yuden', 
  '2024-10-12T07:27:56.033', 
  '1', 
  'Ferrite', 
  '8230', 
  '=Value', 
  '-25°C ~ 125°C', 
  '100 kHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/6025/LSXND4040TKL1R0NDG_SS.pdf', 
  'TAIYO YUDEN LSXND4040 1.8H', 
  'Datasheet', 
  '±30%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.157" L x 0.157" W (4.00mm x 4.00mm)', 
  '32.4mOhm Max', 
  'LSXN', 
  'Wirewound', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '1 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - TAIYO YUDEN LSXND4040 1.8H.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 100UH 280MA 1.74OHM SM', 
  'LSXND4040TKL101MDG', 
  'https://www.digikey.com/en/products/detail/taiyo-yuden/LSXND4040TKL101MDG/16665031', 
  '0.071" (1.80mm)', 
  '280 mA', 
  '1616', 
  '100 µH', 
  'INDUCTOR', 
  '587-LSXND4040TKL101MDGCT-ND', 
  'Active', 
  '6.5MHz', 
  'Taiyo Yuden', 
  '2024-10-12T07:27:56.047', 
  '1', 
  'Ferrite', 
  '8231', 
  '=Value', 
  '-25°C ~ 125°C', 
  '100 kHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/6025/LSXND4040TKL101MDG_SS.pdf', 
  'TAIYO YUDEN LSXND4040 1.8H', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.157" L x 0.157" W (4.00mm x 4.00mm)', 
  '1.74Ohm Max', 
  'LSXN', 
  'Wirewound', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '100 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - TAIYO YUDEN LSXND4040 1.8H.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "Footprint Ref",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 150UH 220MA 2.76OHM SM', 
  'LSXND4040TKL151MDG', 
  'https://www.digikey.com/en/products/detail/taiyo-yuden/LSXND4040TKL151MDG/16661696', 
  '0.071" (1.80mm)', 
  '220 mA', 
  '1616', 
  '150 µH', 
  'INDUCTOR', 
  '587-LSXND4040TKL151MDGCT-ND', 
  'Active', 
  '5.5MHz', 
  'Taiyo Yuden', 
  '2024-10-12T07:27:56.057', 
  '1', 
  'Ferrite', 
  '8232', 
  '=Value', 
  '-25°C ~ 125°C', 
  '100 kHz', 
  'TAIYO YUDEN LSXND4040 1.8H', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.157" L x 0.157" W (4.00mm x 4.00mm)', 
  '2.76Ohm Max', 
  'LSXN', 
  'Wirewound', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '150 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - TAIYO YUDEN LSXND4040 1.8H.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 33UH 550MA 552MOHM SMD', 
  'LSXND4040TKL330MDG', 
  'https://www.digikey.com/en/products/detail/taiyo-yuden/LSXND4040TKL330MDG/16661763', 
  '0.071" (1.80mm)', 
  '550 mA', 
  '1616', 
  '33 µH', 
  'INDUCTOR', 
  '587-LSXND4040TKL330MDGCT-ND', 
  'Active', 
  '12MHz', 
  'Taiyo Yuden', 
  '2024-10-12T07:27:56.070', 
  '1', 
  'Ferrite', 
  '8233', 
  '=Value', 
  '-25°C ~ 125°C', 
  '100 kHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/6025/LSXND4040TKL330MDG_SS.pdf', 
  'TAIYO YUDEN LSXND4040 1.8H', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.157" L x 0.157" W (4.00mm x 4.00mm)', 
  '552mOhm Max', 
  'LSXN', 
  'Wirewound', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '33 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - TAIYO YUDEN LSXND4040 1.8H.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 6.8UH 1.45A 117.6 MOHM', 
  'LSXND4040TKL6R8MDG', 
  'https://www.digikey.com/en/products/detail/taiyo-yuden/LSXND4040TKL6R8MDG/16661507', 
  '0.071" (1.80mm)', 
  '1.45 A', 
  '1616', 
  '6.8 µH', 
  'INDUCTOR', 
  '587-LSXND4040TKL6R8MDGCT-ND', 
  'Active', 
  '30MHz', 
  'Taiyo Yuden', 
  '2024-10-12T07:27:56.080', 
  '1', 
  'Ferrite', 
  '8234', 
  '=Value', 
  '-25°C ~ 125°C', 
  '100 kHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/6025/LSXND4040TKL6R8MDG_SS.pdf', 
  'TAIYO YUDEN LSXND4040 1.8H', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.157" L x 0.157" W (4.00mm x 4.00mm)', 
  '117.6mOhm Max', 
  'LSXN', 
  'Wirewound', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '6.8 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - TAIYO YUDEN LSXND4040 1.8H.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "Footprint Ref",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 1.5UH 2.4A 44.4MOHM SM', 
  'LSXND4040TKL1R5NDG', 
  'https://www.digikey.com/en/products/detail/taiyo-yuden/LSXND4040TKL1R5NDG/16665915', 
  '0.071" (1.80mm)', 
  '2.4 A', 
  '1616', 
  '1.5 µH', 
  'INDUCTOR', 
  '587-LSXND4040TKL1R5NDGCT-ND', 
  'Active', 
  '75MHz', 
  'Taiyo Yuden', 
  '2024-10-12T07:27:56.090', 
  '1', 
  'Ferrite', 
  '8235', 
  '=Value', 
  '-25°C ~ 125°C', 
  '100 kHz', 
  'TAIYO YUDEN LSXND4040 1.8H', 
  '±30%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.157" L x 0.157" W (4.00mm x 4.00mm)', 
  '44.4mOhm Max', 
  'LSXN', 
  'Wirewound', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '1.5 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - TAIYO YUDEN LSXND4040 1.8H.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 220UH 170MA 4.56OHM SM', 
  'LSXND4040TKL221MDG', 
  'https://www.digikey.com/en/products/detail/taiyo-yuden/LSXND4040TKL221MDG/16666913', 
  '0.071" (1.80mm)', 
  '170 mA', 
  '1616', 
  '220 µH', 
  'INDUCTOR', 
  '587-LSXND4040TKL221MDGCT-ND', 
  'Active', 
  '4MHz', 
  'Taiyo Yuden', 
  '2024-10-12T07:27:56.100', 
  '1', 
  'Ferrite', 
  '8236', 
  '=Value', 
  '-25°C ~ 125°C', 
  '100 kHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/6025/LSXND4040TKL221MDG_SS.pdf', 
  'TAIYO YUDEN LSXND4040 1.8H', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.157" L x 0.157" W (4.00mm x 4.00mm)', 
  '4.56Ohm Max', 
  'LSXN', 
  'Wirewound', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '220 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - TAIYO YUDEN LSXND4040 1.8H.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 68UH 320MA 1.2 OHM SMD', 
  'LSXND4040TKL680MDG', 
  'https://www.digikey.com/en/products/detail/taiyo-yuden/LSXND4040TKL680MDG/16660602', 
  '0.071" (1.80mm)', 
  '320 mA', 
  '1616', 
  '68 µH', 
  'INDUCTOR', 
  '587-LSXND4040TKL680MDGCT-ND', 
  'Active', 
  '8.3MHz', 
  'Taiyo Yuden', 
  '2024-10-12T07:27:56.110', 
  '1', 
  'Ferrite', 
  '8237', 
  '=Value', 
  '-25°C ~ 125°C', 
  '100 kHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/6025/LSXND4040TKL680MDG_SS.pdf', 
  'TAIYO YUDEN LSXND4040 1.8H', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.157" L x 0.157" W (4.00mm x 4.00mm)', 
  '1.2Ohm Max', 
  'LSXN', 
  'Wirewound', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '68 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - TAIYO YUDEN LSXND4040 1.8H.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 15UH 850MA 252MOHM SMD', 
  'LSXND4040TKL150MDG', 
  'https://www.digikey.com/en/products/detail/taiyo-yuden/LSXND4040TKL150MDG/16665584', 
  '0.071" (1.80mm)', 
  '850 mA', 
  '1616', 
  '15 µH', 
  'INDUCTOR', 
  '587-LSXND4040TKL150MDGCT-ND', 
  'Active', 
  '18MHz', 
  'Taiyo Yuden', 
  '2024-10-12T07:27:56.123', 
  '1', 
  'Ferrite', 
  '8238', 
  '=Value', 
  '-25°C ~ 125°C', 
  '100 kHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/6025/LSXND4040TKL150MDG_SS.pdf', 
  'TAIYO YUDEN LSXND4040 1.8H', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.157" L x 0.157" W (4.00mm x 4.00mm)', 
  '252mOhm Max', 
  'LSXN', 
  'Wirewound', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '15 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - TAIYO YUDEN LSXND4040 1.8H.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "Footprint Ref",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 22UH 720MA 348MOHM SMD', 
  'LSXND4040TKL220MDG', 
  'https://www.digikey.com/en/products/detail/taiyo-yuden/LSXND4040TKL220MDG/16661908', 
  '0.071" (1.80mm)', 
  '720 mA', 
  '1616', 
  '22 µH', 
  'INDUCTOR', 
  '587-LSXND4040TKL220MDGCT-ND', 
  'Active', 
  '15MHz', 
  'Taiyo Yuden', 
  '2024-10-12T07:27:56.133', 
  '1', 
  'Ferrite', 
  '8239', 
  '=Value', 
  '-25°C ~ 125°C', 
  '100 kHz', 
  'TAIYO YUDEN LSXND4040 1.8H', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.157" L x 0.157" W (4.00mm x 4.00mm)', 
  '348mOhm Max', 
  'LSXN', 
  'Wirewound', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '22 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - TAIYO YUDEN LSXND4040 1.8H.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "Footprint Ref",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 47UH 440MA 780MOHM SMD', 
  'LSXND4040TKL470MDG', 
  'https://www.digikey.com/en/products/detail/taiyo-yuden/LSXND4040TKL470MDG/16661435', 
  '0.071" (1.80mm)', 
  '440 mA', 
  '1616', 
  '47 µH', 
  'INDUCTOR', 
  '587-LSXND4040TKL470MDGCT-ND', 
  'Active', 
  '10MHz', 
  'Taiyo Yuden', 
  '2024-10-12T07:27:56.147', 
  '1', 
  'Ferrite', 
  '8240', 
  '=Value', 
  '-25°C ~ 125°C', 
  '100 kHz', 
  'TAIYO YUDEN LSXND4040 1.8H', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.157" L x 0.157" W (4.00mm x 4.00mm)', 
  '780mOhm Max', 
  'LSXN', 
  'Wirewound', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '47 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - TAIYO YUDEN LSXND4040 1.8H.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "Footprint Ref",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 4.7UH 1.7A 84 MOHM SMD', 
  'LSXND4040TKL4R7MDG', 
  'https://www.digikey.com/en/products/detail/taiyo-yuden/LSXND4040TKL4R7MDG/16665567', 
  '0.071" (1.80mm)', 
  '1.7 A', 
  '1616', 
  '4.7 µH', 
  'INDUCTOR', 
  '587-LSXND4040TKL4R7MDGCT-ND', 
  'Active', 
  '35MHz', 
  'Taiyo Yuden', 
  '2024-10-12T07:27:56.153', 
  '1', 
  'Ferrite', 
  '8241', 
  '=Value', 
  '-25°C ~ 125°C', 
  '100 kHz', 
  'TAIYO YUDEN LSXND4040 1.8H', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.157" L x 0.157" W (4.00mm x 4.00mm)', 
  '84mOhm Max', 
  'LSXN', 
  'Wirewound', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '4.7 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - TAIYO YUDEN LSXND4040 1.8H.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "Footprint Ref",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 3.3UH 2A 66 MOHM SMD', 
  'LSXND4040TKL3R3MDG', 
  'https://www.digikey.com/en/products/detail/taiyo-yuden/LSXND4040TKL3R3MDG/16661919', 
  '0.071" (1.80mm)', 
  '2 A', 
  '1616', 
  '3.3 µH', 
  'INDUCTOR', 
  '587-LSXND4040TKL3R3MDGCT-ND', 
  'Active', 
  '45MHz', 
  'Taiyo Yuden', 
  '2024-10-12T07:27:56.173', 
  '1', 
  'Ferrite', 
  '8242', 
  '=Value', 
  '-25°C ~ 125°C', 
  '100 kHz', 
  'TAIYO YUDEN LSXND4040 1.8H', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.157" L x 0.157" W (4.00mm x 4.00mm)', 
  '66mOhm Max', 
  'LSXN', 
  'Wirewound', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '3.3 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - TAIYO YUDEN LSXND4040 1.8H.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "Footprint Ref",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 2.2UH 2.2A 50.4MOHM SM', 
  'LSXND4040TKL2R2MDG', 
  'https://www.digikey.com/en/products/detail/taiyo-yuden/LSXND4040TKL2R2MDG/16661591', 
  '0.071" (1.80mm)', 
  '2.2 A', 
  '1616', 
  '2.2 µH', 
  'INDUCTOR', 
  '587-LSXND4040TKL2R2MDGCT-ND', 
  'Active', 
  '60MHz', 
  'Taiyo Yuden', 
  '2024-10-12T07:27:56.190', 
  '1', 
  'Ferrite', 
  '8243', 
  '=Value', 
  '-25°C ~ 125°C', 
  '100 kHz', 
  'TAIYO YUDEN LSXND4040 1.8H', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.157" L x 0.157" W (4.00mm x 4.00mm)', 
  '50.4mOhm Max', 
  'LSXN', 
  'Wirewound', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2.2 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - TAIYO YUDEN LSXND4040 1.8H.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "Footprint Ref",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 10UH 1.2A 180 MOHM SMD', 
  'LSXND4040TKL100MDG', 
  'https://www.digikey.com/en/products/detail/taiyo-yuden/LSXND4040TKL100MDG/16665770', 
  '0.071" (1.80mm)', 
  '1.2 A', 
  '1616', 
  '10 µH', 
  'INDUCTOR', 
  '587-LSXND4040TKL100MDGCT-ND', 
  'Active', 
  '25MHz', 
  'Taiyo Yuden', 
  '2024-10-12T07:27:56.210', 
  '1', 
  'Ferrite', 
  '8244', 
  '=Value', 
  '-25°C ~ 125°C', 
  '100 kHz', 
  'TAIYO YUDEN LSXND4040 1.8H', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.157" L x 0.157" W (4.00mm x 4.00mm)', 
  '180mOhm Max', 
  'LSXN', 
  'Wirewound', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '10 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - TAIYO YUDEN LSXND4040 1.8H.PcbLib'
);

