--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Memory" (
  "Clock Frequency",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Memory Type",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Technology",
  "Lifecycle Status",
  "Voltage - Supply",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Memory Format",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Memory Interface",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Series",
  "Memory Size",
  "Price",
  "Library Path",
  "Packaging",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '200 MHz', 
  'IC FLASH 512MBIT SPI 24FBGA', 
  'S26HS512TGABHI010', 
  'https://www.digikey.com/en/products/detail/infineon-technologies/S26HS512TGABHI010/10493037', 
  'Non-Volatile', 
  '24-FBGA (6x8)', 
  'Infineon S26HS512TGABHI010', 
  '448-S26HS512TGABHI010-ND', 
  'FLASH - NOR', 
  'Active', 
  '1.7V ~ 2V', 
  'Infineon Technologies', 
  '2026-04-14T05:51:47.723', 
  '1', 
  'FLASH', 
  '1471', 
  '=Part Number', 
  '-40°C ~ 85°C (TA)', 
  'HyperBus', 
  'https://www.infineon.com/dgdl/Infineon-AN200810_S25FL-P_(32_Mb_64_Mb)_Package_Routing_Guide-ApplicationNotes-v03_00-EN.pdf?fileId=8ac78c8c7cdc391c017d07432ba2664a&utm_source=cypress&utm_medium=referral&utm_campaign=202110_globe_en_all_integration-files', 
  'INFINEON PG-BGA-24 8X6', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  'HS-T', 
  '512Mbit', 
  '6.70', 
  'symbols/Memory/SCH - MEMORY - Infineon S26HS512TGABHI010.SchLib', 
  'Tray', 
  'DigiKey Link', 
  'footprints/Leadless - BGA/PCB - LEADLESS - BGA - INFINEON PG-BGA-24 8X6.PcbLib'
);

