--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Color",
  "ComponentLink1Description",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '570nm', 
  'LED GREEN 0603 SMD', 
  'TLMG1100-GS15', 
  'https://www.digikey.com/en/products/detail/vishay-semiconductor-opto-division/TLMG1100-GS15/16652837', 
  '160°', 
  '0603 (1608 Metric)', 
  '35mcd', 
  '0603', 
  'Rectangle with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '751-TLMG1100-GS15CT-ND', 
  'Active', 
  'Vishay Semiconductor Opto Division', 
  '2.1V', 
  '2023-09-02T20:14:37.323', 
  '1', 
  '572nm', 
  '1369', 
  '1.60mm x 0.80mm', 
  '=Value', 
  'https://www.vishay.com/docs/83173/tlmx1100.pdf', 
  'LED 0603_1608 GREEN', 
  'Green', 
  'Datasheet', 
  '20mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '0.65mm', 
  'Automotive, AEC-Q101', 
  '0.09', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 GREEN.PCBLIB'
);

INSERT INTO "LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Color",
  "ComponentLink1Description",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '561nm', 
  'LED GREEN 0603 SMD', 
  'TLMP1100-GS15', 
  'https://www.digikey.com/en/products/detail/vishay-semiconductor-opto-division/TLMP1100-GS15/16652841', 
  '160°', 
  '0603 (1608 Metric)', 
  '15mcd', 
  '0603', 
  'Rectangle with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '751-TLMP1100-GS15CT-ND', 
  'Active', 
  'Vishay Semiconductor Opto Division', 
  '2.1V', 
  '2023-09-02T20:14:37.337', 
  '1', 
  '572nm', 
  '1370', 
  '1.60mm x 0.80mm', 
  '=Value', 
  'https://www.vishay.com/docs/83173/tlmx1100.pdf', 
  'LED 0603_1608 GREEN', 
  'Green', 
  'Datasheet', 
  '20mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '0.65mm', 
  'Automotive, AEC-Q101', 
  '0.11', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 GREEN.PCBLIB'
);

INSERT INTO "LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Color",
  "ComponentLink1Description",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '628nm', 
  'LED RED 0603 SMD', 
  'TLMS1000-GS15', 
  'https://www.digikey.com/en/products/detail/vishay-semiconductor-opto-division/TLMS1000-GS15/16652847', 
  '160°', 
  '0603 (1608 Metric)', 
  '4mcd', 
  '0603', 
  'Rectangle with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '751-TLMS1000-GS15CT-ND', 
  'Active', 
  'Vishay Semiconductor Opto Division', 
  '1.8V', 
  '2023-09-02T20:16:35.030', 
  '1', 
  '640nm', 
  '1371', 
  '1.60mm x 0.80mm', 
  '=Value', 
  'https://www.vishay.com/docs/83172/tlmo1000.pdf', 
  'LED 0603_1608 RED', 
  'Red', 
  'Datasheet', 
  '2mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '0.65mm', 
  'Automotive, AEC-Q101', 
  '0.09', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Red', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 RED.PCBLIB'
);

INSERT INTO "LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Color",
  "ComponentLink1Description",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '588nm', 
  'LED YELLOW 0603 SMD', 
  'TLMY1000-GS15', 
  'https://www.digikey.com/en/products/detail/vishay-semiconductor-opto-division/TLMY1000-GS15/16652838', 
  '160°', 
  '0603 (1608 Metric)', 
  '7.5mcd', 
  '0603', 
  'Rectangle with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '751-TLMY1000-GS15CT-ND', 
  'Active', 
  'Vishay Semiconductor Opto Division', 
  '1.8V', 
  '2023-09-02T20:19:53.580', 
  '1', 
  '591nm', 
  '1372', 
  '1.60mm x 0.80mm', 
  '=Value', 
  'https://www.vishay.com/docs/83172/tlmo1000.pdf', 
  'LED 0603_1608 YELLOW', 
  'Yellow', 
  'Datasheet', 
  '2mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '0.65mm', 
  'Automotive, AEC-Q101', 
  '0.09', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Yellow', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 YELLOW.PCBLIB'
);

