--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Resistors-SurfaceMount-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.025 OHM 1% 1/2W 1210', 
  'RL1210FR-070R025L', 
  'https://www.digikey.com/en/products/detail/yageo/RL1210FR-070R025L/5925192', 
  '0.026" (0.65mm)', 
  '1210 (3225 Metric)', 
  '2', 
  '±1000ppm/°C', 
  '1210', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'RESISTOR', 
  '13-RL1210FR-070R025LCT-ND', 
  'Active', 
  'Yageo', 
  'Automotive AEC-Q200, Current Sense, Moisture Resistant', 
  '2023-09-02T20:55:08.827', 
  '1', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.yageo.com/upload/media/product/productsearch/datasheet/rchip/PYu-RL_Group_521_RoHS_L_2.pdf', 
  'RES 1210_3225', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.122" L x 0.102" W (3.10mm x 2.60mm)', 
  '25 mOhms', 
  '0.5W, 1/2W', 
  'RL', 
  '0.11', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '25 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1210_3225.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 392 OHM 1% 1/2W 1210', 
  'CRCW1210392RFKEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/CRCW1210392RFKEA/1198028', 
  '0.024" (0.60mm)', 
  '1210 (3225 Metric)', 
  '2', 
  '±100ppm/°C', 
  '1210', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'RESISTOR', 
  '541-CRCW1210392RFKEACT-ND', 
  'Active', 
  'Vishay Dale', 
  'Automotive AEC-Q200', 
  '2023-09-02T20:55:08.930', 
  '1', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.vishay.com/docs/20035/dcrcwe3.pdf', 
  'RES 1210_3225', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.126" L x 0.098" W (3.20mm x 2.50mm)', 
  '392 Ohms', 
  '0.5W, 1/2W', 
  'CRCW', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '392 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1210_3225.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 267 OHM 1% 1/2W 1210', 
  'CRCW1210267RFKEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/CRCW1210267RFKEA/1198015', 
  '0.024" (0.60mm)', 
  '1210 (3225 Metric)', 
  '2', 
  '±100ppm/°C', 
  '1210', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'RESISTOR', 
  '541-CRCW1210267RFKEACT-ND', 
  'Active', 
  'Vishay Dale', 
  'Automotive AEC-Q200', 
  '2023-09-02T20:55:08.963', 
  '1', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.vishay.com/docs/20035/dcrcwe3.pdf', 
  'RES 1210_3225', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.126" L x 0.098" W (3.20mm x 2.50mm)', 
  '267 Ohms', 
  '0.5W, 1/2W', 
  'CRCW', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '267 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1210_3225.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 20 OHM 1% 3/4W 1210', 
  'CRCW121020R0FKEAHP', 
  'https://www.digikey.com/en/products/detail/vishay-dale/CRCW121020R0FKEAHP/2577665', 
  '0.028" (0.70mm)', 
  '1210 (3225 Metric)', 
  '2', 
  '±100ppm/°C', 
  '1210', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'RESISTOR', 
  '541-CRCW121020R0FKEAHPCT-ND', 
  'Active', 
  'Vishay Dale', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-09-02T20:55:08.993', 
  '1', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.vishay.com/docs/20043/crcwhpe3.pdf', 
  'RES 1210_3225', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.126" L x 0.098" W (3.20mm x 2.50mm)', 
  '20 Ohms', 
  '0.75W, 3/4W', 
  'CRCW-HP', 
  '0.12', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '20 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1210_3225.PCBLIB'
);

