--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Diodes-Rectifiers-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Current - Average Rectified (Io)",
  "Operating Temperature - Junction",
  "PartId",
  "Comment",
  "Speed",
  "Capacitance @ Vr, F",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Reverse Recovery Time (Trr)",
  "Price",
  "Library Path",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Voltage - Dc Reverse (Vr) (Max)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE GEN PURP 600V 1.6A DO220AA', 
  'SE20PAJHM3/I', 
  'https://www.digikey.com/en/products/detail/vishay-general-semiconductor-diodes-division/SE20PAJHM3-I/5426918', 
  'DO-220AA (SMP)', 
  'DIODE IPC', 
  '112-SE20PAJHM3/ICT-ND', 
  'Active', 
  'Vishay General Semiconductor - Diodes Division', 
  '2023-09-02T21:17:02.597', 
  '1', 
  '1.6A', 
  '-55°C ~ 175°C', 
  '3611', 
  '=Part Number', 
  'Standard Recovery >500ns, > 200mA (Io)', 
  '13pF @ 4V, 1MHz', 
  'https://www.vishay.com/docs/87905/se20pbdgj.pdf', 
  'VISHAY SMP DO-220AA', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '5 µA @ 600 V', 
  'Automotive, AEC-Q101, eSMP®', 
  '1.2 µs', 
  '0.09', 
  'symbols/Diodes/SCH - DIODES - DIODE IPC.SCHLIB', 
  '1.05 V @ 2 A', 
  'TapeAndReel', 
  '600 V', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - VISHAY SMP DO-220AA.PcbLib'
);

INSERT INTO "Diodes-Rectifiers-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Current - Average Rectified (Io)",
  "Operating Temperature - Junction",
  "PartId",
  "Comment",
  "Speed",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Reverse Recovery Time (Trr)",
  "Price",
  "Library Path",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Voltage - Dc Reverse (Vr) (Max)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE GEN PURP 200V 1A DO220AA', 
  'SE10PDHM3/84A', 
  'https://www.digikey.com/en/products/detail/vishay-general-semiconductor-diodes-division/SE10PDHM3-84A/2150415', 
  'DO-220AA (SMP)', 
  'DIODE IPC', 
  '112-SE10PDHM3/84ACT-ND', 
  'Active', 
  'Vishay General Semiconductor - Diodes Division', 
  '2023-09-02T21:17:02.603', 
  '1', 
  '1A', 
  '-55°C ~ 175°C', 
  '3612', 
  '=Part Number', 
  'Standard Recovery >500ns, > 200mA (Io)', 
  'https://www.vishay.com/docs/89024/se10pb.pdf', 
  'VISHAY SMP DO-220AA', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '5 µA @ 200 V', 
  'Automotive, AEC-Q101, eSMP®', 
  '780 ns', 
  '0.08', 
  'symbols/Diodes/SCH - DIODES - DIODE IPC.SCHLIB', 
  '1.05 V @ 1 A', 
  'TapeAndReel', 
  '200 V', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - VISHAY SMP DO-220AA.PcbLib'
);

INSERT INTO "Diodes-Rectifiers-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Current - Average Rectified (Io)",
  "Operating Temperature - Junction",
  "PartId",
  "Comment",
  "Speed",
  "Capacitance @ Vr, F",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Reverse Recovery Time (Trr)",
  "Price",
  "Library Path",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Voltage - Dc Reverse (Vr) (Max)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE GEN PURP 200V 1A DO220AA', 
  'ESH1PDHM3/84A', 
  'https://www.digikey.com/en/products/detail/vishay-general-semiconductor-diodes-division/ESH1PDHM3-84A/4494779', 
  'DO-220AA (SMP)', 
  'DIODE IPC', 
  '112-ESH1PDHM3/84ACT-ND', 
  'Active', 
  'Vishay General Semiconductor - Diodes Division', 
  '2023-09-02T21:17:02.610', 
  '1', 
  '1A', 
  '-55°C ~ 175°C', 
  '3613', 
  '=Part Number', 
  'Fast Recovery =< 500ns, > 200mA (Io)', 
  '25pF @ 4V, 1MHz', 
  'https://www.vishay.com/docs/88895/esh1pb.pdf', 
  'VISHAY SMP DO-220AA', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '1 µA @ 200 V', 
  'Automotive, AEC-Q101, eSMP®', 
  '25 ns', 
  '0.13', 
  'symbols/Diodes/SCH - DIODES - DIODE IPC.SCHLIB', 
  '900 mV @ 1 A', 
  'TapeAndReel', 
  '200 V', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - VISHAY SMP DO-220AA.PcbLib'
);

INSERT INTO "Diodes-Rectifiers-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Current - Average Rectified (Io)",
  "Operating Temperature - Junction",
  "PartId",
  "Comment",
  "Speed",
  "Capacitance @ Vr, F",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Reverse Recovery Time (Trr)",
  "Price",
  "Library Path",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Voltage - Dc Reverse (Vr) (Max)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE AVALANCHE 200V 1A DO220AA', 
  'AU1PDHM3/84A', 
  'https://www.digikey.com/en/products/detail/vishay-general-semiconductor-diodes-division/AU1PDHM3-84A/2642427', 
  'DO-220AA (SMP)', 
  'DIODE IPC', 
  '112-AU1PDHM3/84ACT-ND', 
  'Active', 
  'Vishay General Semiconductor - Diodes Division', 
  '2023-09-02T21:17:02.617', 
  '1', 
  '1A', 
  '-55°C ~ 175°C', 
  '3614', 
  '=Part Number', 
  'Fast Recovery =< 500ns, > 200mA (Io)', 
  '11pF @ 4V, 1MHz', 
  'https://www.vishay.com/docs/89291/au1pm.pdf', 
  'VISHAY SMP DO-220AA', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '1 µA @ 200 V', 
  'Automotive, AEC-Q101, eSMP®', 
  '75 ns', 
  '0.15', 
  'symbols/Diodes/SCH - DIODES - DIODE IPC.SCHLIB', 
  '1.5 V @ 1 A', 
  'TapeAndReel', 
  '200 V', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - VISHAY SMP DO-220AA.PcbLib'
);

INSERT INTO "Diodes-Rectifiers-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Current - Average Rectified (Io)",
  "Operating Temperature - Junction",
  "PartId",
  "Comment",
  "Speed",
  "Capacitance @ Vr, F",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Reverse Recovery Time (Trr)",
  "Price",
  "Library Path",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Voltage - Dc Reverse (Vr) (Max)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE AVALANCHE 800V 1A DO220AA', 
  'AU1PKHM3/85A', 
  'https://www.digikey.com/en/products/detail/vishay-general-semiconductor-diodes-division/AU1PKHM3-85A/2642440', 
  'DO-220AA (SMP)', 
  'DIODE IPC', 
  '112-AU1PKHM3/85ACT-ND', 
  'Active', 
  'Vishay General Semiconductor - Diodes Division', 
  '2023-09-02T21:17:02.623', 
  '1', 
  '1A', 
  '-55°C ~ 175°C', 
  '3615', 
  '=Part Number', 
  'Fast Recovery =< 500ns, > 200mA (Io)', 
  '7.5pF @ 4V, 1MHz', 
  'https://www.vishay.com/docs/89291/au1pm.pdf', 
  'VISHAY SMP DO-220AA', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '1 µA @ 800 V', 
  'Automotive, AEC-Q101, eSMP®', 
  '75 ns', 
  '0.15', 
  'symbols/Diodes/SCH - DIODES - DIODE IPC.SCHLIB', 
  '1.85 V @ 1 A', 
  'TapeAndReel', 
  '800 V', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - VISHAY SMP DO-220AA.PcbLib'
);

INSERT INTO "Diodes-Rectifiers-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Current - Average Rectified (Io)",
  "Operating Temperature - Junction",
  "PartId",
  "Comment",
  "Speed",
  "Capacitance @ Vr, F",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Reverse Recovery Time (Trr)",
  "Price",
  "Library Path",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Voltage - Dc Reverse (Vr) (Max)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE AVALANCHE 400V 1A DO220AA', 
  'AR1PGHM3/84A', 
  'https://www.digikey.com/en/products/detail/vishay-general-semiconductor-diodes-division/AR1PGHM3-84A/2642307', 
  'DO-220AA (SMP)', 
  'DIODE IPC', 
  '112-AR1PGHM3/84ACT-ND', 
  'Active', 
  'Vishay General Semiconductor - Diodes Division', 
  '2023-09-02T21:17:02.630', 
  '1', 
  '1A', 
  '-55°C ~ 175°C', 
  '3616', 
  '=Part Number', 
  'Fast Recovery =< 500ns, > 200mA (Io)', 
  '12.5pF @ 4V, 1MHz', 
  'https://www.vishay.com/docs/89289/ar1pm.pdf', 
  'VISHAY SMP DO-220AA', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '1 µA @ 400 V', 
  'Automotive, AEC-Q101, eSMP®', 
  '140 ns', 
  '0.15', 
  'symbols/Diodes/SCH - DIODES - DIODE IPC.SCHLIB', 
  '1.25 V @ 1 A', 
  'TapeAndReel', 
  '400 V', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - VISHAY SMP DO-220AA.PcbLib'
);

