--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Capacitors-Tantalum-Polymer" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Manufacturer Size Code",
  "Height - Seated (Max)",
  "Device Package",
  "Voltage - Rated",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '22UF (MICRO FARAD)75MOHM @ 100KH', 
  'TCME226M050R0075E', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/TCME226M050R0075E/17868569', 
  'E', 
  '0.169" (4.30mm)', 
  '2917 (7343 Metric)', 
  '50 V', 
  '2917 (7343 Metric)', 
  'POLARISED CAPACITOR', 
  '478-TCME226M050R0075ECT-ND', 
  'Active', 
  'KYOCERA AVX', 
  'General Purpose', 
  '2023-09-01T20:03:03.123', 
  '1', 
  '6643', 
  '=Value', 
  '-55°C ~ 125°C', 
  'https://datasheets.kyocera-avx.com/TCM.pdf', 
  'CAP POL 2917_7343', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '75mOhm @ 100kHz', 
  'Surface Mount', 
  '0.287" L x 0.169" W (7.30mm x 4.30mm)', 
  '2000 Hrs @ 125°C', 
  'TCM', 
  'Molded', 
  '2.31', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '22 µF', 
  '22 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Tantalum/PCB - CAPACITOR - TANTALUM - CAP POL 2917_7343.PCBLIB'
);

