--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Capacitors-Aluminum-Polymer-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Surface Mount Land Size",
  "Voltage - Rated",
  "Ripple Current @ Low Frequency",
  "Ratings",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Ripple Current @ High Frequency",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP ALUM HYB 68UF 20% 50V SMD', 
  'A780KN686M1HLAS035', 
  'https://www.digikey.com/en/products/detail/kemet/A780KN686M1HLAS035/17737717', 
  '0.394" (10.00mm)', 
  '0.327" L x 0.327" W (8.30mm x 8.30mm)', 
  '50 V', 
  '308 mA @ 100 Hz', 
  'AEC-Q200', 
  'POLARISED CAPACITOR', 
  '399-A780KN686M1HLAS035CT-ND', 
  'Active', 
  'KEMET', 
  '2023-09-02T20:52:59.570', 
  '1', 
  '5728', 
  '=Value', 
  '-55°C ~ 125°C', 
  'Automotive', 
  'https://connect.kemet.com:7667/gateway/IntelliData-ComponentDocumentation/1.0/download/datasheet/A780KN686M1HLAS035', 
  'CAP ALSMD POLY 8.3MM H10.0MM', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '35mOhm', 
  'Surface Mount', 
  '0.315" Dia (8.00mm)', 
  '4000 Hrs @ 125°C', 
  'A780', 
  'Hybrid', 
  '0.26', 
  '1.4 A @ 100 kHz', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '68 µF', 
  '68 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP ALSMD POLY 8.3MM H10.0MM.PCBLIB'
);

INSERT INTO "Capacitors-Aluminum-Polymer-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Surface Mount Land Size",
  "Voltage - Rated",
  "Ripple Current @ Low Frequency",
  "Ratings",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Ripple Current @ High Frequency",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP ALUM HYB 39UF 20% 63V SMD', 
  'A780KN396M1JLAS040', 
  'https://www.digikey.com/en/products/detail/kemet/A780KN396M1JLAS040/17737720', 
  '0.394" (10.00mm)', 
  '0.327" L x 0.327" W (8.30mm x 8.30mm)', 
  '63 V', 
  '290.4 mA @ 100 Hz', 
  'AEC-Q200', 
  'POLARISED CAPACITOR', 
  '399-A780KN396M1JLAS040CT-ND', 
  'Active', 
  'KEMET', 
  '2023-09-02T20:52:59.590', 
  '1', 
  '5729', 
  '=Value', 
  '-55°C ~ 125°C', 
  'Automotive', 
  'https://connect.kemet.com:7667/gateway/IntelliData-ComponentDocumentation/1.0/download/datasheet/A780KN396M1JLAS040', 
  'CAP ALSMD POLY 8.3MM H10.0MM', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '40mOhm', 
  'Surface Mount', 
  '0.315" Dia (8.00mm)', 
  '4000 Hrs @ 125°C', 
  'A780', 
  'Hybrid', 
  '0.26', 
  '1.32 A @ 100 kHz', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '39 µF', 
  '39 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP ALSMD POLY 8.3MM H10.0MM.PCBLIB'
);

INSERT INTO "Capacitors-Aluminum-Polymer-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Surface Mount Land Size",
  "Voltage - Rated",
  "Ripple Current @ Low Frequency",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Ripple Current @ High Frequency",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP ALUM HYB 33UF 20% 63V SMD', 
  'HZA336M063F24VT-F', 
  'https://www.digikey.com/en/products/detail/cornell-dubilier-electronics-cde/HZA336M063F24VT-F/5774261', 
  '0.413" (10.50mm)', 
  'Radial, Can - SMD', 
  '0.327" L x 0.327" W (8.30mm x 8.30mm)', 
  '63 V', 
  '170 mA @ 120 Hz', 
  'AEC-Q200', 
  'Radial, Can - SMD', 
  'POLARISED CAPACITOR', 
  '338-4240-1-ND', 
  'Active', 
  'Cornell Dubilier Electronics (CDE)', 
  '2023-09-02T20:53:09.780', 
  '1', 
  '5731', 
  '=Value', 
  '-55°C ~ 105°C', 
  'Automotive, Bypass, Decoupling', 
  'http://www.cde.com/resources/catalogs/HZA-V.pdf', 
  'CAP ALSMD POLY 8.3MM H10.5MM', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '40mOhm', 
  'Surface Mount', 
  '0.315" Dia (8.00mm)', 
  '10000 Hrs @ 105°C', 
  'HZA_V', 
  'Hybrid', 
  '1.70', 
  '1.7 A @ 100 kHz', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '33 µF', 
  '33 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP ALSMD POLY 8.3MM H10.5MM.PCBLIB'
);

INSERT INTO "Capacitors-Aluminum-Polymer-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Surface Mount Land Size",
  "Voltage - Rated",
  "Ripple Current @ Low Frequency",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Ripple Current @ High Frequency",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP ALUM POLY 680UF 20% 4V SMD', 
  'APXT4R0ARA681MF80G', 
  'https://www.digikey.com/en/products/detail/chemi-con/APXT4R0ARA681MF80G/17728401', 
  '0.315" (8.00mm)', 
  '0.260" L x 0.260" W (6.60mm x 6.60mm)', 
  '4 V', 
  '142.5 mA @ 120 Hz', 
  'POLARISED CAPACITOR', 
  '565-APXT4R0ARA681MF80GCT-ND', 
  'Active', 
  'Chemi-Con', 
  '2023-09-02T20:52:22.517', 
  '1', 
  '5733', 
  '=Value', 
  '-55°C ~ 105°C', 
  'General Purpose', 
  'CAP ALSMD 6.6MM H8.0MM', 
  '±20%', 
  'DigiKey', 
  '22mOhm', 
  'Surface Mount', 
  '0.248" Dia (6.30mm)', 
  '15000 Hrs @ 105°C', 
  'NPCAP™-PXT', 
  'Polymer', 
  '0.17', 
  '2.85 A @ 100 kHz', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '680 µF', 
  '680 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP ALSMD 6.6MM H8.0MM.PCBLIB'
);

