--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Capacitors-Tantalum-Polymer" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Voltage - Rated",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP TANT POLY AUTO 22F 10V', 
  'T597S226M010APE200', 
  'https://www.digikey.com/en/products/detail/kemet/T597S226M010APE200/20115176', 
  '0.047" (1.20mm)', 
  '1206 (3216 Metric)', 
  '10 V', 
  'AEC-Q200', 
  '1206 (3216 Metric)', 
  'POLARISED CAPACITOR', 
  '399-T597S226M010APE200CT-ND', 
  'Active', 
  'KEMET', 
  'Automotive', 
  '2023-10-29T19:59:52.443', 
  '1', 
  '6662', 
  '=Value', 
  '-55°C ~ 125°C', 
  'https://connect.kemet.com:7667/gateway/IntelliData-ComponentDocumentation/1.0/download/datasheet/T597S226M010APE200', 
  'CAP POL 1206_3216', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '200mOhm @ 100kHz', 
  'Surface Mount', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  '2000 Hrs @ 125°C', 
  'T597', 
  'Molded', 
  '0.34', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '22 µF', 
  '22 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Tantalum/PCB - CAPACITOR - TANTALUM - CAP POL 1206_3216.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Tantalum-Polymer" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Manufacturer Size Code",
  "Height - Seated (Max)",
  "Device Package",
  "Voltage - Rated",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'BL- CASE / 227- CAP CODE / POLY', 
  'TCTOBL0E227M8R-ZN1', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/TCTOBL0E227M8R-ZN1/21298101', 
  'BL', 
  '0.047" (1.20mm)', 
  '1411 (3528 Metric)', 
  '2.5 V', 
  '1411 (3528 Metric)', 
  'POLARISED CAPACITOR', 
  '478-TCTOBL0E227M8R-ZN1CT-ND', 
  'Active', 
  'KYOCERA AVX', 
  'General Purpose', 
  '2023-10-29T20:00:38.973', 
  '1', 
  '6663', 
  '=Value', 
  '-55°C ~ 105°C', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5010/TCTO_Series_DS.pdf', 
  'CAP POL 1411_3528', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '35mOhm @ 100kHz', 
  'Surface Mount', 
  '0.138" L x 0.110" W (3.50mm x 2.80mm)', 
  'TCTO', 
  'Molded', 
  '0.32', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '220 µF', 
  '220 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Tantalum/PCB - CAPACITOR - TANTALUM - CAP POL 1411_3528.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Tantalum-Polymer" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Manufacturer Size Code",
  "Height - Seated (Max)",
  "Device Package",
  "Voltage - Rated",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'BL- CASE / 336- CAP CODE / POLY', 
  'TCTOBL1C336M8R-ZW1', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/TCTOBL1C336M8R-ZW1/21298100', 
  'BL', 
  '0.047" (1.20mm)', 
  '1411 (3528 Metric)', 
  '16 V', 
  '1411 (3528 Metric)', 
  'POLARISED CAPACITOR', 
  '478-TCTOBL1C336M8R-ZW1CT-ND', 
  'Active', 
  'KYOCERA AVX', 
  'General Purpose', 
  '2023-10-29T20:00:39.183', 
  '1', 
  '6664', 
  '=Value', 
  '-55°C ~ 105°C', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5010/TCTO_Series_DS.pdf', 
  'CAP POL 1411_3528', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '70mOhm @ 100kHz', 
  'Surface Mount', 
  '0.138" L x 0.110" W (3.50mm x 2.80mm)', 
  'TCTO', 
  'Molded', 
  '0.32', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '33 µF', 
  '33 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Tantalum/PCB - CAPACITOR - TANTALUM - CAP POL 1411_3528.PCBLIB'
);

