--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 0.7NH 800MA 0.08O', 
  'MCI0603TM0N7BHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TM0N7BHBPDG/20486582', 
  '14 @ 500MHz', 
  '0.013" (0.33mm)', 
  '800 mA', 
  '0201 (0603 Metric)', 
  '80mOhm Max', 
  '0201', 
  '0.7 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TM0N7BHBPDGCT-ND', 
  'Active', 
  '20GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:48.987', 
  '1', 
  'Ceramic', 
  '6777', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TM Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±0.1nH', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TM', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '0.7 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 6.2NH 300MA 0.6OH', 
  'MCI0603TM6N2HHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TM6N2HHBPDG/20486693', 
  '14 @ 500MHz', 
  '0.013" (0.33mm)', 
  '300 mA', 
  '0201 (0603 Metric)', 
  '600mOhm Max', 
  '0201', 
  '6.2 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TM6N2HHBPDGCT-ND', 
  'Active', 
  '4GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.017', 
  '1', 
  'Ceramic', 
  '6778', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TM Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±3%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TM', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '6.2 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 1.5NH 600MA 0.15O', 
  'MCI0603TM1N5BHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TM1N5BHBPDG/20486668', 
  '14 @ 500MHz', 
  '0.013" (0.33mm)', 
  '600 mA', 
  '0201 (0603 Metric)', 
  '150mOhm Max', 
  '0201', 
  '1.5 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TM1N5BHBPDGCT-ND', 
  'Active', 
  '15GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.043', 
  '1', 
  'Ceramic', 
  '6779', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TM Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±0.1nH', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TM', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '1.5 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 2.0NH 450MA 0.2OH', 
  'MCI0603TG2N0BHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TG2N0BHBPDG/20486654', 
  '12 @ 500MHz', 
  '0.013" (0.33mm)', 
  '450 mA', 
  '0201 (0603 Metric)', 
  '200mOhm Max', 
  '0201', 
  '2 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TG2N0BHBPDGCT-ND', 
  'Active', 
  '12.5GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.070', 
  '1', 
  'Ceramic', 
  '6780', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TG Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±0.1nH', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TG', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '2 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 9.1NH 250MA 0.7OH', 
  'MCI0603TM9N1HHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TM9N1HHBPDG/20486671', 
  '14 @ 500MHz', 
  '0.013" (0.33mm)', 
  '250 mA', 
  '0201 (0603 Metric)', 
  '700mOhm Max', 
  '0201', 
  '9.1 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TM9N1HHBPDGCT-ND', 
  'Active', 
  '3.3GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.093', 
  '1', 
  'Ceramic', 
  '6781', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TM Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±3%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TM', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '9.1 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 8.2NH 250MA 0.7OH', 
  'MCI0603TM8N2HHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TM8N2HHBPDG/20486717', 
  '14 @ 500MHz', 
  '0.013" (0.33mm)', 
  '250 mA', 
  '0201 (0603 Metric)', 
  '700mOhm Max', 
  '0201', 
  '8.2 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TM8N2HHBPDGCT-ND', 
  'Active', 
  '3.6GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.117', 
  '1', 
  'Ceramic', 
  '6782', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TM Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±3%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TM', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '8.2 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 10NH 250MA 0.7OHM', 
  'MCI0603TM10NHHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TM10NHHBPDG/20486566', 
  '14 @ 500MHz', 
  '0.013" (0.33mm)', 
  '250 mA', 
  '0201 (0603 Metric)', 
  '700mOhm Max', 
  '0201', 
  '10 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TM10NHHBPDGCT-ND', 
  'Active', 
  '3.2GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.143', 
  '1', 
  'Ceramic', 
  '6783', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TM Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±3%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TM', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '10 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 3.3NH 450MA 0.25O', 
  'MCI0603TM3N3BHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TM3N3BHBPDG/20486644', 
  '14 @ 500MHz', 
  '0.013" (0.33mm)', 
  '450 mA', 
  '0201 (0603 Metric)', 
  '250mOhm Max', 
  '0201', 
  '3.3 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TM3N3BHBPDGCT-ND', 
  'Active', 
  '8GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.173', 
  '1', 
  'Ceramic', 
  '6784', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TM Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±0.1nH', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TM', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '3.3 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 2.2NH 600MA 0.15O', 
  'MCI0603TM2N2BHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TM2N2BHBPDG/20486657', 
  '14 @ 500MHz', 
  '0.013" (0.33mm)', 
  '600 mA', 
  '0201 (0603 Metric)', 
  '150mOhm Max', 
  '0201', 
  '2.2 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TM2N2BHBPDGCT-ND', 
  'Active', 
  '11GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.193', 
  '1', 
  'Ceramic', 
  '6785', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TM Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±0.1nH', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TM', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '2.2 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 7.5NH 300MA 0.6OH', 
  'MCI0603TM7N5HHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TM7N5HHBPDG/20486611', 
  '14 @ 500MHz', 
  '0.013" (0.33mm)', 
  '300 mA', 
  '0201 (0603 Metric)', 
  '600mOhm Max', 
  '0201', 
  '7.5 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TM7N5HHBPDGCT-ND', 
  'Active', 
  '3.7GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.200', 
  '1', 
  'Ceramic', 
  '6786', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TM Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±3%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TM', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '7.5 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 2.7NH 500MA 0.2OH', 
  'MCI0603TM2N7BHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TM2N7BHBPDG/20486655', 
  '14 @ 500MHz', 
  '0.013" (0.33mm)', 
  '500 mA', 
  '0201 (0603 Metric)', 
  '200mOhm Max', 
  '0201', 
  '2.7 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TM2N7BHBPDGCT-ND', 
  'Active', 
  '10GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.210', 
  '1', 
  'Ceramic', 
  '6787', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TM Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±0.1nH', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TM', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '2.7 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 0.6NH 850MA 0.07O', 
  'MCI0603TM0N6BHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TM0N6BHBPDG/20486602', 
  '14 @ 500MHz', 
  '0.013" (0.33mm)', 
  '850 mA', 
  '0201 (0603 Metric)', 
  '70mOhm Max', 
  '0201', 
  '0.6 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TM0N6BHBPDGCT-ND', 
  'Active', 
  '20GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.217', 
  '1', 
  'Ceramic', 
  '6788', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TM Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±0.1nH', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TM', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '0.6 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 3.9NH 400MA 0.3OH', 
  'MCI0603TM3N9BHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TM3N9BHBPDG/20486567', 
  '14 @ 500MHz', 
  '0.013" (0.33mm)', 
  '400 mA', 
  '0201 (0603 Metric)', 
  '300mOhm Max', 
  '0201', 
  '3.9 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TM3N9BHBPDGCT-ND', 
  'Active', 
  '5.7GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.223', 
  '1', 
  'Ceramic', 
  '6789', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TM Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±0.1nH', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TM', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '3.9 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 4.3NH 350MA 0.4OH', 
  'MCI0603TM4N3HHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TM4N3HHBPDG/20486673', 
  '14 @ 500MHz', 
  '0.013" (0.33mm)', 
  '350 mA', 
  '0201 (0603 Metric)', 
  '400mOhm Max', 
  '0201', 
  '4.3 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TM4N3HHBPDGCT-ND', 
  'Active', 
  '5.3GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.257', 
  '1', 
  'Ceramic', 
  '6790', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TM Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±3%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TM', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '4.3 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 3.0NH 450MA 0.25O', 
  'MCI0603TG3N0BHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TG3N0BHBPDG/20486721', 
  '12 @ 500MHz', 
  '0.013" (0.33mm)', 
  '450 mA', 
  '0201 (0603 Metric)', 
  '250mOhm Max', 
  '0201', 
  '3 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TG3N0BHBPDGCT-ND', 
  'Active', 
  '9.5GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.263', 
  '1', 
  'Ceramic', 
  '6791', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TG Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±0.1nH', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TG', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '3 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 1.0NH 750MA 0.1OH', 
  'MCI0603TM1N0BHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TM1N0BHBPDG/20486705', 
  '14 @ 500MHz', 
  '0.013" (0.33mm)', 
  '750 mA', 
  '0201 (0603 Metric)', 
  '100mOhm Max', 
  '0201', 
  '1 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TM1N0BHBPDGCT-ND', 
  'Active', 
  '17GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.293', 
  '1', 
  'Ceramic', 
  '6792', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TM Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±0.1nH', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TM', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '1 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 1.0NH 600MA 0.14O', 
  'MCI0603TG1N0BHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TG1N0BHBPDG/20486623', 
  '12 @ 500MHz', 
  '0.013" (0.33mm)', 
  '600 mA', 
  '0201 (0603 Metric)', 
  '140mOhm Max', 
  '0201', 
  '1 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TG1N0BHBPDGCT-ND', 
  'Active', 
  '17GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.313', 
  '1', 
  'Ceramic', 
  '6793', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TG Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±0.1nH', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TG', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '1 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 18NH 200MA 0.8OHM', 
  'MCI0603TM18NHHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TM18NHHBPDG/20486747', 
  '12 @ 500MHz', 
  '0.013" (0.33mm)', 
  '200 mA', 
  '0201 (0603 Metric)', 
  '800mOhm Max', 
  '0201', 
  '18 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TM18NHHBPDGCT-ND', 
  'Active', 
  '2.2GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.320', 
  '1', 
  'Ceramic', 
  '6794', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TM Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±3%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TM', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '18 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 1.2NH 750MA 0.1OH', 
  'MCI0603TM1N2BHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TM1N2BHBPDG/20486642', 
  '14 @ 500MHz', 
  '0.013" (0.33mm)', 
  '750 mA', 
  '0201 (0603 Metric)', 
  '100mOhm Max', 
  '0201', 
  '1.2 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TM1N2BHBPDGCT-ND', 
  'Active', 
  '17GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.327', 
  '1', 
  'Ceramic', 
  '6795', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TM Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±0.1nH', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TM', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '1.2 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 15NH 250MA 0.7OHM', 
  'MCI0603TM15NHHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TM15NHHBPDG/20486575', 
  '12 @ 500MHz', 
  '0.013" (0.33mm)', 
  '250 mA', 
  '0201 (0603 Metric)', 
  '700mOhm Max', 
  '0201', 
  '15 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TM15NHHBPDGCT-ND', 
  'Active', 
  '2.6GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.337', 
  '1', 
  'Ceramic', 
  '6796', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TM Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±3%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TM', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '15 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 2.2NH 450MA 0.22O', 
  'MCI0603TG2N2BHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TG2N2BHBPDG/20486669', 
  '12 @ 500MHz', 
  '0.013" (0.33mm)', 
  '450 mA', 
  '0201 (0603 Metric)', 
  '220mOhm Max', 
  '0201', 
  '2.2 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TG2N2BHBPDGCT-ND', 
  'Active', 
  '12GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.343', 
  '1', 
  'Ceramic', 
  '6797', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TG Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±0.1nH', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TG', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '2.2 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 1.5NH 600MA 0.15O', 
  'MCI0603TG1N5BHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TG1N5BHBPDG/20486743', 
  '12 @ 500MHz', 
  '0.013" (0.33mm)', 
  '600 mA', 
  '0201 (0603 Metric)', 
  '150mOhm Max', 
  '0201', 
  '1.5 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TG1N5BHBPDGCT-ND', 
  'Active', 
  '13.5GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.350', 
  '1', 
  'Ceramic', 
  '6798', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TG Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±0.1nH', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TG', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '1.5 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 4.7NH 350MA 0.4OH', 
  'MCI0603TM4N7HHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TM4N7HHBPDG/20486581', 
  '14 @ 500MHz', 
  '0.013" (0.33mm)', 
  '350 mA', 
  '0201 (0603 Metric)', 
  '400mOhm Max', 
  '0201', 
  '4.7 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TM4N7HHBPDGCT-ND', 
  'Active', 
  '4.4GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:34:49.377', 
  '1', 
  'Ceramic', 
  '6799', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MCI0603-TM Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±3%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TM', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'CutTape', 
  '4.7 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CHIP IND 1005,19.0NH,G,24Q,0.48A', 
  'WCI1005CP19NGDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/WCI1005CP19NGDG/20486725', 
  '60 @ 900MHz', 
  '0.026" (0.66mm)', 
  '480 mA', 
  '0402 (1005 Metric)', 
  '200mOhm Max', 
  '0402', 
  '19 nH', 
  '0402 (1005 Metric)', 
  'INDUCTOR', 
  '3526-WCI1005CP19NGDGCT-ND', 
  'Active', 
  '3.04GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:38:23.203', 
  '1', 
  'Ceramic', 
  '6800', 
  '=Value', 
  '-25°C ~ 125°C', 
  '250 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/WCI1005CP Series.pdf', 
  'IND 0402_1005', 
  'Datasheet', 
  '±2%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.047" L x 0.025" W (1.19mm x 0.64mm)', 
  'WCI1005CP', 
  'Wirewound', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '19 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0402_1005.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CHIP IND 1005,20.0NH,G,25Q,0.42A', 
  'WCI1005CP20NGDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/WCI1005CP20NGDG/20486730', 
  '52 @ 900MHz', 
  '0.026" (0.66mm)', 
  '420 mA', 
  '0402 (1005 Metric)', 
  '250mOhm Max', 
  '0402', 
  '20 nH', 
  '0402 (1005 Metric)', 
  'INDUCTOR', 
  '3526-WCI1005CP20NGDGCT-ND', 
  'Active', 
  '3GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:38:23.230', 
  '1', 
  'Ceramic', 
  '6801', 
  '=Value', 
  '-25°C ~ 125°C', 
  '250 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/WCI1005CP Series.pdf', 
  'IND 0402_1005', 
  'Datasheet', 
  '±2%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.047" L x 0.025" W (1.19mm x 0.64mm)', 
  'WCI1005CP', 
  'Wirewound', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '20 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0402_1005.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CHIP IND 1005,18.0NH,G,25Q,0.42A', 
  'WCI1005CP18NGDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/WCI1005CP18NGDG/20486735', 
  '52 @ 900MHz', 
  '0.026" (0.66mm)', 
  '420 mA', 
  '0402 (1005 Metric)', 
  '230mOhm Max', 
  '0402', 
  '18 nH', 
  '0402 (1005 Metric)', 
  'INDUCTOR', 
  '3526-WCI1005CP18NGDGCT-ND', 
  'Active', 
  '3.1GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:38:23.260', 
  '1', 
  'Ceramic', 
  '6802', 
  '=Value', 
  '-25°C ~ 125°C', 
  '250 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/WCI1005CP Series.pdf', 
  'IND 0402_1005', 
  'Datasheet', 
  '±2%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.047" L x 0.025" W (1.19mm x 0.64mm)', 
  'WCI1005CP', 
  'Wirewound', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '18 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0402_1005.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CHIP IND 1005,12NH,G,24Q,0.64A,4', 
  'WCI1005CP12NGDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/WCI1005CP12NGDG/20486698', 
  '62 @ 900MHz', 
  '0.026" (0.66mm)', 
  '640 mA', 
  '0402 (1005 Metric)', 
  '120mOhm Max', 
  '0402', 
  '12 nH', 
  '0402 (1005 Metric)', 
  'INDUCTOR', 
  '3526-WCI1005CP12NGDGCT-ND', 
  'Active', 
  '3.6GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:38:23.287', 
  '1', 
  'Ceramic', 
  '6803', 
  '=Value', 
  '-25°C ~ 125°C', 
  '250 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/WCI1005CP Series.pdf', 
  'IND 0402_1005', 
  'Datasheet', 
  '±2%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.047" L x 0.025" W (1.19mm x 0.64mm)', 
  'WCI1005CP', 
  'Wirewound', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '12 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0402_1005.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CHIP IND 1005,9.1NH,G,22Q,0.68A,', 
  'WCI1005CP9N1GDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/WCI1005CP9N1GDG/20486583', 
  '63 @ 900MHz', 
  '0.026" (0.66mm)', 
  '680 mA', 
  '0402 (1005 Metric)', 
  '100mOhm Max', 
  '0402', 
  '9.1 nH', 
  '0402 (1005 Metric)', 
  'INDUCTOR', 
  '3526-WCI1005CP9N1GDGCT-ND', 
  'Active', 
  '4.16GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:38:23.293', 
  '1', 
  'Ceramic', 
  '6804', 
  '=Value', 
  '-25°C ~ 125°C', 
  '250 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/WCI1005CP Series.pdf', 
  'IND 0402_1005', 
  'Datasheet', 
  '±2%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.047" L x 0.025" W (1.19mm x 0.64mm)', 
  'WCI1005CP', 
  'Wirewound', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '9.1 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0402_1005.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CHIP IND 1005,5.6NH,G,20Q,0.76A,', 
  'WCI1005CP5N6GDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/WCI1005CP5N6GDG/20486592', 
  '48 @ 900MHz', 
  '0.026" (0.66mm)', 
  '760 mA', 
  '0402 (1005 Metric)', 
  '83mOhm Max', 
  '0402', 
  '5.6 nH', 
  '0402 (1005 Metric)', 
  'INDUCTOR', 
  '3526-WCI1005CP5N6GDGCT-ND', 
  'Active', 
  '4.8GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:38:23.317', 
  '1', 
  'Ceramic', 
  '6805', 
  '=Value', 
  '-25°C ~ 125°C', 
  '250 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/WCI1005CP Series.pdf', 
  'IND 0402_1005', 
  'Datasheet', 
  '±2%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.047" L x 0.025" W (1.19mm x 0.64mm)', 
  'WCI1005CP', 
  'Wirewound', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '5.6 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0402_1005.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 7.5NH 600MA 160MOHM SM', 
  'MHQ1005P7N5JT000', 
  'https://www.digikey.com/en/products/detail/tdk-corporation/MHQ1005P7N5JT000/3910213', 
  '23 @ 250MHz', 
  '0.024" (0.60mm)', 
  '600 mA', 
  '0402 (1005 Metric)', 
  '160mOhm Max', 
  '0402 (1005 Metric)', 
  '7.5 nH', 
  '0402 (1005 Metric)', 
  'INDUCTOR', 
  '445-MHQ1005P7N5JT000CT-ND', 
  'Active', 
  '4GHz', 
  'TDK Corporation', 
  '2023-10-29T20:39:11.413', 
  '1', 
  'Ceramic, Non-Magnetic', 
  '6806', 
  '=Part Number', 
  '-55°C ~ 125°C', 
  '100 MHz', 
  'https://product.tdk.com/info/en/catalog/datasheets/inductor_commercial_high-frequency_mhq1005p_en.pdf?ref_disty=digikey', 
  'IND 0402_1005', 
  'Datasheet', 
  '±5%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  'MHQ-P', 
  'Multilayer', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0402_1005.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 1.0UH 3.7A 52MOHM SMD', 
  'AOTA-B201608S1R0MT', 
  'https://www.digikey.com/en/products/detail/abracon-llc/AOTA-B201608S1R0MT/20838366', 
  '0.031" (0.80mm)', 
  '3.7 A', 
  '0806 (2016 Metric)', 
  '52mOhm Max', 
  '0806', 
  '1 µH', 
  '0806 (2016 Metric)', 
  'INDUCTOR', 
  '535-AOTA-B201608S1R0MTCT-ND', 
  'Active', 
  '57MHz', 
  'Abracon LLC', 
  '2023-10-29T20:40:15.493', 
  '1', 
  '6807', 
  '=Value', 
  '-40°C ~ 125°C', 
  '1 MHz', 
  'https://abracon.com/datasheets/AOTA-B201608S.pdf', 
  'IND 0806_2016', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.063" W (2.00mm x 1.60mm)', 
  'AOTA-B201608S', 
  'Molded', 
  '0.10', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '1 µH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0806_2016.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'POWER INDUCTOR 2016 0.22UH 20% D', 
  'WIP201610S-R22MLDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/WIP201610S-R22MLDG/20486687', 
  '0.039" (1.00mm)', 
  '6 A', 
  '0806 (2016 Metric)', 
  '19mOhm Max', 
  '0806', 
  '220 nH', 
  '0806 (2016 Metric)', 
  'INDUCTOR', 
  '3526-WIP201610S-R22MLDGCT-ND', 
  'Active', 
  '120MHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-10-29T20:40:15.523', 
  '1', 
  'Iron Powder', 
  '6808', 
  '=Value', 
  '-40°C ~ 125°C', 
  '1 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/WIP201610S L Series.pdf', 
  'IND 0806_2016', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.063" W (2.00mm x 1.60mm)', 
  'WIP201610S L', 
  'Wirewound', 
  '0.04', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '220 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0806_2016.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 22UH 130MA 7.15OHM SMD', 
  'LQH2MCN220M52L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/LQH2MCN220M52L/2594272', 
  '0.037" (0.95mm)', 
  '130 mA', 
  '0806 (2016 Metric)', 
  '7.15Ohm Max', 
  '0806 (2016 Metric)', 
  '22 µH', 
  '0806 (2016 Metric)', 
  'INDUCTOR', 
  '490-LQH2MCN220M52LCT-ND', 
  'Active', 
  '30MHz', 
  'Murata Electronics', 
  '2023-10-29T20:40:15.553', 
  '1', 
  'Ferrite', 
  '6809', 
  '=Value', 
  '-40°C ~ 85°C', 
  '1 MHz', 
  'https://search.murata.co.jp/Ceramy/image/img/P02/JELF243A-0060.pdf', 
  'IND 0806_2016', 
  'Datasheet', 
  '±20%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.063" W (2.00mm x 1.60mm)', 
  'LQH2', 
  'Drum Core, Wirewound', 
  '0.13', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '22 µH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0806_2016.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0.24UH 5.5A 22MOHM SMD', 
  'AOTA-B201608SR24MT', 
  'https://www.digikey.com/en/products/detail/abracon-llc/AOTA-B201608SR24MT/20838529', 
  '0.031" (0.80mm)', 
  '5.5 A', 
  '0806 (2016 Metric)', 
  '22mOhm Max', 
  '0806', 
  '240 nH', 
  '0806 (2016 Metric)', 
  'INDUCTOR', 
  '535-AOTA-B201608SR24MTCT-ND', 
  'Active', 
  '120MHz', 
  'Abracon LLC', 
  '2023-10-29T20:40:15.597', 
  '1', 
  '6810', 
  '=Value', 
  '-40°C ~ 125°C', 
  '1 MHz', 
  'https://abracon.com/datasheets/AOTA-B201608S.pdf', 
  'IND 0806_2016', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.063" W (2.00mm x 1.60mm)', 
  'AOTA-B201608S', 
  'Molded', 
  '0.10', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '240 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0806_2016.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 2.2UH 1.8A 148MOHM SMD', 
  'AOTA-B201608S2R2MT', 
  'https://www.digikey.com/en/products/detail/abracon-llc/AOTA-B201608S2R2MT/20838418', 
  '0.031" (0.80mm)', 
  '1.8 A', 
  '0806 (2016 Metric)', 
  '148mOhm Max', 
  '0806', 
  '2.2 µH', 
  '0806 (2016 Metric)', 
  'INDUCTOR', 
  '535-AOTA-B201608S2R2MTCT-ND', 
  'Active', 
  '40MHz', 
  'Abracon LLC', 
  '2023-10-29T20:40:15.627', 
  '1', 
  '6811', 
  '=Value', 
  '-40°C ~ 125°C', 
  '1 MHz', 
  'https://abracon.com/datasheets/AOTA-B201608S.pdf', 
  'IND 0806_2016', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.063" W (2.00mm x 1.60mm)', 
  'AOTA-B201608S', 
  'Molded', 
  '0.10', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '2.2 µH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0806_2016.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0.47UH 3.6A 24MOHM SMD', 
  'AOTA-B201608SR47MT', 
  'https://www.digikey.com/en/products/detail/abracon-llc/AOTA-B201608SR47MT/20838412', 
  '0.031" (0.80mm)', 
  '3.6 A', 
  '0806 (2016 Metric)', 
  '24mOhm Max', 
  '0806', 
  '470 nH', 
  '0806 (2016 Metric)', 
  'INDUCTOR', 
  '535-AOTA-B201608SR47MTCT-ND', 
  'Active', 
  '104MHz', 
  'Abracon LLC', 
  '2023-10-29T20:40:15.653', 
  '1', 
  '6812', 
  '=Value', 
  '-40°C ~ 125°C', 
  '1 MHz', 
  'https://abracon.com/datasheets/AOTA-B201608S.pdf', 
  'IND 0806_2016', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.063" W (2.00mm x 1.60mm)', 
  'AOTA-B201608S', 
  'Molded', 
  '0.10', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '470 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0806_2016.PCBLIB'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Dc Resistance (Dcr)",
  "Ratings",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IND METAL POWDER 0.22UH 7A', 
  'SRP2012TMA-R22M', 
  'https://www.digikey.com/en/products/detail/bourns-inc/SRP2012TMA-R22M/16546447', 
  '5 @ 1MHz', 
  '0.047" (1.20mm)', 
  '7 A', 
  '0806 (2016 Metric)', 
  '13mOhm Max', 
  'AEC-Q200', 
  '220 nH', 
  '0806 (2016 Metric)', 
  'INDUCTOR', 
  '118-SRP2012TMA-R22MCT-ND', 
  'Active', 
  '170MHz', 
  'Bourns Inc.', 
  'Flat Wire', 
  '2023-10-29T20:40:23.107', 
  '1', 
  'Metal', 
  '6813', 
  '=Value', 
  '-55°C ~ 150°C', 
  '1 MHz', 
  'https://www.bourns.com/docs/product-datasheets/srp2012tma.pdf', 
  'IND 0806_2016', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.063" W (2.00mm x 1.60mm)', 
  'SRP2012TMA', 
  '0.09', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '220 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0806_2016.PCBLIB'
);

