--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Capacitors-Aluminum-Polymer-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Surface Mount Land Size",
  "Voltage - Rated",
  "Ripple Current @ Low Frequency",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Ripple Current @ High Frequency",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP ALUM POLY 560UF 20% 16V SMD', 
  '16SVPT560MX', 
  'https://www.digikey.com/en/products/detail/panasonic-electronic-components/16SVPT560MX/19244244', 
  '0.413" (10.50mm)', 
  '0.327" L x 0.327" W (8.30mm x 8.30mm)', 
  '16 V', 
  '195 mA @ 120 Hz', 
  'POLARISED CAPACITOR', 
  '10-16SVPT560MXCT-ND', 
  'Active', 
  'Panasonic Electronic Components', 
  '2023-10-29T20:43:00.623', 
  '1', 
  '5748', 
  '=Value', 
  '-55°C ~ 105°C', 
  'General Purpose', 
  'https://api.pim.na.industrial.panasonic.com/file_stream/main/fileversion/8462', 
  'CAP ALSMD POLY 8.3MM H10.5MM', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '18mOhm', 
  'Surface Mount', 
  '0.315" Dia (8.00mm)', 
  '20000 Hrs @ 105°C', 
  'OS-CON™, SVPT', 
  'Polymer', 
  '0.66', 
  '3.9 A @ 100 kHz', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '560 µF', 
  '560 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP ALSMD POLY 8.3MM H10.5MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Aluminum-Polymer-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Surface Mount Land Size",
  "Voltage - Rated",
  "Ripple Current @ Low Frequency",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Ripple Current @ High Frequency",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP ALUM POLY 560UF 20% 16V SMD', 
  '16SVT560MX', 
  'https://www.digikey.com/en/products/detail/panasonic-electronic-components/16SVT560MX/19247692', 
  '0.413" (10.50mm)', 
  '0.327" L x 0.327" W (8.30mm x 8.30mm)', 
  '16 V', 
  '195 mA @ 120 Hz', 
  'POLARISED CAPACITOR', 
  '10-16SVT560MXCT-ND', 
  'Active', 
  'Panasonic Electronic Components', 
  '2023-10-29T20:43:00.643', 
  '1', 
  '5749', 
  '=Value', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://industrial.panasonic.com/cdbs/www-data/pdf/AAB8000/ast-ind-134270.pdf', 
  'CAP ALSMD POLY 8.3MM H10.5MM', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '18mOhm', 
  'Surface Mount', 
  '0.315" Dia (8.00mm)', 
  '2000 Hrs @ 125°C', 
  'OS-CON™, SVT', 
  'Polymer', 
  '0.68', 
  '3.9 A @ 100 kHz', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '560 µF', 
  '560 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP ALSMD POLY 8.3MM H10.5MM.PCBLIB'
);

INSERT INTO "altium"."Capacitors-Aluminum-Polymer-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Surface Mount Land Size",
  "Voltage - Rated",
  "Ripple Current @ Low Frequency",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Ripple Current @ High Frequency",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP ALUM HYB 220UF 20% 25V SMD', 
  'HZA227M025F24VT-F', 
  'https://www.digikey.com/en/products/detail/cornell-dubilier-electronics-cde/HZA227M025F24VT-F/5774256', 
  '0.413" (10.50mm)', 
  'Radial, Can - SMD', 
  '0.327" L x 0.327" W (8.30mm x 8.30mm)', 
  '25 V', 
  '230 mA @ 120 Hz', 
  'AEC-Q200', 
  'Radial, Can - SMD', 
  'POLARISED CAPACITOR', 
  '338-4235-1-ND', 
  'Active', 
  'Cornell Dubilier Electronics (CDE)', 
  '2023-10-29T20:43:03.050', 
  '1', 
  '5750', 
  '=Value', 
  '-55°C ~ 105°C', 
  'Automotive, Bypass, Decoupling', 
  'http://www.cde.com/resources/catalogs/HZA-V.pdf', 
  'CAP ALSMD POLY 8.3MM H10.5MM', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '27mOhm', 
  'Surface Mount', 
  '0.315" Dia (8.00mm)', 
  '10000 Hrs @ 105°C', 
  'HZA_V', 
  'Hybrid', 
  '1.70', 
  '2.3 A @ 100 kHz', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '220 µF', 
  '220 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP ALSMD POLY 8.3MM H10.5MM.PCBLIB'
);

