--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Interface-DriversReceiversTransceivers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Data Rate",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Voltage - Supply",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Protocol",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Drivers/Receivers"
)
VALUES (
  'IC TRANSCEIVER 1/1 24SQFN', 
  'LAN8742A-CZ-TR', 
  'http://digikey.com/product-detail/en/microchip-technology/LAN8742A-CZ-TR/LAN8742A-CZ-CT-ND/8256089', 
  '24-SQFN (4x4)', 
  '100Mbps', 
  '24-VFQFN Exposed Pad', 
  'MICROCHIP LAN8742A-CZ', 
  'LAN8742A-CZ-CT-ND', 
  'Active', 
  '1.6V ~ 3.6V', 
  'Microchip Technology', 
  '2025-11-12T22:44:26.777', 
  '1', 
  'Ethernet', 
  '=Part Number', 
  'http://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en576112', 
  'SMSC QFN-24 4X4MM', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  'flexPWR™', 
  'Transceiver', 
  '0.91', 
  'symbols/Interface/SCH - INTERFACE - MICROCHIP LAN8742A-CZ.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - QFN/PCB - LEADLESS - QFN - SMSC QFN-24 4X4MM.PCBLIB', 
  '1/1'
);

