--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Composition",
  "Description",
  "Device Package",
  "Features",
  "Footprint Path",
  "Footprint Ref",
  "Height - Seated (Max)",
  "LastUpdated",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Minimum Order",
  "Number of Terminations",
  "Operating Temperature",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Power (Watts)",
  "Price",
  "Resistance",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Supplier Device Package",
  "Library Path",
  "Library Ref",
  "Temperature Coefficient",
  "Tolerance",
  "Value"
)
VALUES (
  '=Value', 
  'Datasheet', 
  'https://industrial.panasonic.com/cdbs/www-data/pdf/RDP0000/AOA0000C334.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/panasonic-electronic-components/ERJ-U01F5902C/11631235', 
  'Thick Film', 
  'RES 59K OHM 1% 1/20W 0201 SMD', 
  '0201 (0603 Metric)', 
  'Anti-Sulfur', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB', 
  'RES 0201_0603', 
  '0.010" (0.26mm)', 
  '2023-01-25T20:16:19.727', 
  'Active', 
  'Panasonic Electronic Components', 
  'ERJ-U01F5902C', 
  '15000', 
  '2', 
  '-55°C ~ 125°C', 
  '0201 (0603 Metric)', 
  'TapeAndReel', 
  '69411', 
  'Active', 
  '0.05W, 1/20W', 
  '0.04', 
  '59 kOhms', 
  'ERJ-U01', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'DigiKey', 
  '10-ERJ-U01F5902CTR-ND', 
  '0201', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'RESISTOR', 
  '±200ppm/°C', 
  '±1%', 
  '59 kOhms'
);

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Composition",
  "Description",
  "Device Package",
  "Features",
  "Footprint Path",
  "Footprint Ref",
  "Height - Seated (Max)",
  "LastUpdated",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Minimum Order",
  "Number of Terminations",
  "Operating Temperature",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Power (Watts)",
  "Price",
  "Resistance",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Supplier Device Package",
  "Library Path",
  "Library Ref",
  "Temperature Coefficient",
  "Tolerance"
)
VALUES (
  '=Part Number', 
  'Datasheet', 
  'http://www.samsungsem.com/kr/support/product-search/chip-resistor/__icsFiles/afieldfile/2019/01/21/RC_Spec_Sheet(1901).pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/samsung-electro-mechanics/RC0603J103CS/3964124', 
  'Thick Film', 
  'RES SMD 10K OHM 5% 1/20W 0201', 
  '0201 (0603 Metric)', 
  'Moisture Resistant', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB', 
  'RES 0201_0603', 
  '0.010" (0.26mm)', 
  '2023-01-25T20:16:29.553', 
  'Active', 
  'Samsung Electro-Mechanics', 
  'RC0603J103CS', 
  '1', 
  '2', 
  '-55°C ~ 125°C', 
  '0201 (0603 Metric)', 
  'CutTape', 
  '69412', 
  'Active', 
  '0.05W, 1/20W', 
  '0.01', 
  '10 kOhms', 
  'RC', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'DigiKey', 
  '1276-3817-1-ND', 
  '0201', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'RESISTOR', 
  '±250ppm/°C', 
  '±5%'
);

