--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Capacitors-Aluminum-Polymer-TH" (
  "Applications",
  "Capacitance",
  "comment",
  "componentlink1description",
  "componentlink1url",
  "componentlink2description",
  "componentlink2url",
  "description",
  "Device Package",
  "ESR (Equivalent Series Resistance)",
  "Footprint Path",
  "Footprint Ref",
  "Height - Seated (Max)",
  "lastupdated",
  "Lead Spacing",
  "Lifecycle Status",
  "Lifetime @ Temp.",
  "manufacturer",
  "Part Number",
  "Minimum Order",
  "Mounting Type",
  "Operating Temperature",
  "Package / Case",
  "packaging",
  "partid",
  "Part Status",
  "price",
  "Ripple Current @ High Frequency",
  "series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Library Path",
  "Library Ref",
  "Tolerance",
  "Type",
  "value",
  "Voltage - Rated"
)
VALUES (
  'General Purpose', 
  '150 µF', 
  '=Value', 
  'Datasheet', 
  'http://nichicon-us.com/english/products/pdfs/e-pls.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/nichicon/PLS1A151MDL4TD/4991339', 
  'CAP ALUM POLY 150UF 20% 10V T/H', 
  'Radial, Can', 
  '20mOhm', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP TH ALPOLY D6.30mm S2.50mm H10.50mm.PCBLIB', 
  'CAP TH ALPOLY D6.30mm S2.50mm H10.50mm', 
  '0.413" (10.50mm)', 
  '2023-01-25T21:06:18.760', 
  '0.098" (2.50mm)', 
  'Active', 
  '5000 Hrs @ 105°C', 
  'Nichicon', 
  'PLS1A151MDL4TD', 
  '1', 
  'Through Hole', 
  '-55°C ~ 105°C', 
  'Radial, Can', 
  'TapeAndBox', 
  '5458', 
  'Active', 
  '0.47', 
  '3 A @ 100 kHz', 
  'PLS', 
  '0.248" Dia (6.30mm)', 
  'DigiKey', 
  '493-14164-1-ND', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'POLARISED CAPACITOR', 
  '±20%', 
  'Polymer', 
  '150 µF', 
  '10 V'
);

INSERT INTO "Capacitors-Aluminum-Polymer-TH" (
  "Applications",
  "Capacitance",
  "comment",
  "componentlink1description",
  "componentlink1url",
  "componentlink2description",
  "componentlink2url",
  "description",
  "Device Package",
  "ESR (Equivalent Series Resistance)",
  "Footprint Path",
  "Footprint Ref",
  "Height - Seated (Max)",
  "lastupdated",
  "Lead Spacing",
  "Lifecycle Status",
  "Lifetime @ Temp.",
  "manufacturer",
  "Part Number",
  "Minimum Order",
  "Mounting Type",
  "Operating Temperature",
  "Package / Case",
  "packaging",
  "partid",
  "Part Status",
  "price",
  "Ripple Current @ High Frequency",
  "Ripple Current @ Low Frequency",
  "series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Library Path",
  "Library Ref",
  "Tolerance",
  "Type",
  "value",
  "Voltage - Rated"
)
VALUES (
  'General Purpose', 
  '2200 µF', 
  '=Value', 
  'Datasheet', 
  'http://nichicon-us.com/english/products/pdfs/e-rnl.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/nichicon/RNL1C222MDS1/7427972', 
  'CAP ALUM POLY 2200UF 20% 16V T/H', 
  'Radial, Can', 
  '8mOhm', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP TH ALPOLY D10.00mm S5.00mm H21.50mm.PCBLIB', 
  'CAP TH ALPOLY D10.00mm S5.00mm H21.50mm', 
  '0.846" (21.50mm)', 
  '2023-01-25T21:06:31.790', 
  '0.197" (5.00mm)', 
  'Active', 
  '2000 Hrs @ 105°C', 
  'Nichicon', 
  'RNL1C222MDS1', 
  '1', 
  'Through Hole', 
  '-55°C ~ 105°C', 
  'Radial, Can', 
  'Bulk', 
  '5459', 
  'Active', 
  '1.30', 
  '8.1 A @ 100 kHz', 
  '810 mA @ 120 Hz', 
  'FPCAP, RNL', 
  '0.394" Dia (10.00mm)', 
  'DigiKey', 
  '493-16394-ND', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'POLARISED CAPACITOR', 
  '±20%', 
  'Polymer', 
  '2200 µF', 
  '16 V'
);

INSERT INTO "Capacitors-Aluminum-Polymer-TH" (
  "Applications",
  "Capacitance",
  "comment",
  "componentlink1description",
  "componentlink1url",
  "componentlink2description",
  "componentlink2url",
  "description",
  "ESR (Equivalent Series Resistance)",
  "Footprint Path",
  "Footprint Ref",
  "Height - Seated (Max)",
  "lastupdated",
  "Lead Spacing",
  "Lifecycle Status",
  "Lifetime @ Temp.",
  "manufacturer",
  "Part Number",
  "Minimum Order",
  "Mounting Type",
  "Operating Temperature",
  "packaging",
  "partid",
  "Part Status",
  "price",
  "Ripple Current @ High Frequency",
  "Ripple Current @ Low Frequency",
  "series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Library Path",
  "Library Ref",
  "Tolerance",
  "Type",
  "value",
  "Voltage - Rated"
)
VALUES (
  'General Purpose', 
  '82 µF', 
  '=Value', 
  'Datasheet', 
  'https://api.pim.na.industrial.panasonic.com/file_stream/main/fileversion/4365', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/panasonic-electronic-components/72SXE82M/16902170', 
  'CAP ALUM POLY 82UF 20% 72V RADIA', 
  '28mOhm', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP TH ALPOLY D10.00mm S5.00mm H13.00mm.PCBLIB', 
  'CAP TH ALPOLY D10.00mm S5.00mm H13.00mm', 
  '0.512" (13.00mm)', 
  '2023-01-25T21:06:42.827', 
  '0.197" (5.00mm)', 
  'Active', 
  '1000 Hrs @ 125°C', 
  'Panasonic Electronic Components', 
  '72SXE82M', 
  '1', 
  'Through Hole', 
  '-55°C ~ 125°C', 
  'Bulk', 
  '5460', 
  'Active', 
  '2.06', 
  '980 mA @ 100 kHz', 
  '49 mA @ 120 Hz', 
  'OS-CON™, SXE', 
  '0.394" Dia (10.00mm)', 
  'DigiKey', 
  '10-72SXE82M-ND', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'POLARISED CAPACITOR', 
  '±20%', 
  'Polymer', 
  '82 µF', 
  '72 V'
);

