--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Connectors-Barrel-Audio" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Gender",
  "Signal Lines",
  "Industry Recognized Mating Diameter",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Connector Type",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Number Of Positions/Contacts",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Termination",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Internal Switch(S)",
  "Actual Diameter",
  "Series",
  "Price",
  "Library Path",
  "Insulation Color",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CONN RCA JACK MONO 3.2MM R/A', 
  'RCJ-044', 
  'http://digikey.com/product-detail/en/cui-devices/RCJ-044/CP-1421-ND/408508', 
  'Female', 
  'Mono', 
  '3.20mm ID, 9.00mm OD (RCA)', 
  'RCA CONNECTOR', 
  'CP-1421-ND', 
  'Active', 
  'Phono (RCA) Jack', 
  'CUI Devices', 
  'Board Lock', 
  '2024-09-18T14:53:30.270', 
  '1', 
  '2 Conductors, 2 Contacts', 
  '=Part Number', 
  '-20°C ~ 85°C', 
  'https://www.cuidevices.com/product/resource/digikeypdf/rcj-04x.pdf', 
  'CUI RCJ-04', 
  'Datasheet', 
  'Solder', 
  'Unshielded', 
  'DigiKey', 
  'Through Hole, Right Angle', 
  'Does Not Contain Switch', 
  '0.130" (3.30mm ID), 0.327" (8.30mm OD)', 
  'RCJ', 
  '1.36', 
  'symbols/Connectors/SCH - CONNECTORS - RCA CONNECTOR.SCHLIB', 
  'Yellow', 
  'Bulk', 
  'Active', 
  'DigiKey Link', 
  'footprints/Connector - CUI/PCB - CONNECTOR - CUI - CUI RCJ-04.PCBLIB'
);

