--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Capacitors-Tantalum" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Manufacturer Size Code",
  "Height - Seated (Max)",
  "Device Package",
  "Voltage - Rated",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP TANT 100UF 10% 10V 1411', 
  'T491B107K010AT', 
  'https://www.digikey.com/en/products/detail/kemet/T491B107K010AT/2039666', 
  'B', 
  '0.083" (2.10mm)', 
  '1411 (3528 Metric)', 
  '10 V', 
  '1411 (3528 Metric)', 
  'POLARISED CAPACITOR', 
  '399-5598-1-ND', 
  'Active', 
  'KEMET', 
  'General Purpose', 
  '2023-05-08T19:45:08.050', 
  '1', 
  '5354', 
  '=Value', 
  '-55°C ~ 125°C', 
  'https://media.digikey.com/pdf/Data%20Sheets/Kemet%20PDFs/T491_Series_Rev_Oct_2016.pdf', 
  'CAP POL 1411_3528', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  '1.2Ohm', 
  'Surface Mount', 
  '0.138" L x 0.110" W (3.50mm x 2.80mm)', 
  '2000 Hrs @ 125°C', 
  'T491', 
  'Molded', 
  '0.39', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '100 µF', 
  '100 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Tantalum/PCB - CAPACITOR - TANTALUM - CAP POL 1411_3528.PCBLIB'
);

