--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR03EZPD9092', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR03EZPD9092/16180254', 
  '0.022" (0.55mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '511-SDR03EZPD9092CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:26:31.930', 
  '1', 
  '76947', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/sdr-e.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±0.5%', 
  'DigiKey', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  '90.9 kOhms', 
  '0.3W', 
  'SDR', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '90.9 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR03EZPJ431', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR03EZPJ431/16180024', 
  '0.022" (0.55mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '511-SDR03EZPJ431CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:26:31.940', 
  '1', 
  '76948', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/sdr-e.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  '430 Ohms', 
  '0.3W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '430 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 470K OHM 0.1% 1/5W 0603', 
  'RS73F1JTTD4703B', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RS73F1JTTD4703B/11571716', 
  '0.022" (0.55mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±25ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '2019-RS73F1JTTD4703BCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant', 
  '2023-05-01T19:26:31.947', 
  '1', 
  '76949', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/RS73.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±0.1%', 
  'DigiKey', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  '470 kOhms', 
  '0.2W, 1/5W', 
  'RS73', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '470 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 44.2K OHM 1% 1/4W 0603', 
  'RCS060344K2FKEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/RCS060344K2FKEA/5868662', 
  '0.020" (0.50mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-RCS060344K2FKEACT-ND', 
  'Active', 
  'Vishay Dale', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:26:31.963', 
  '1', 
  '76951', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.vishay.com/docs/20065/rcse3.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.061" L x 0.033" W (1.55mm x 0.85mm)', 
  '44.2 kOhms', 
  '0.25W, 1/4W', 
  'RCS e3', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '44.2 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 22.6 OHM 1% 1/10W 0603', 
  'MCT06030C2269FP500', 
  'https://www.digikey.com/en/products/detail/vishay-beyschlag-draloric-bc-components/MCT06030C2269FP500/2800775', 
  '0.022" (0.55mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±50ppm/°C', 
  '0603', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '749-MCT06030C2269FP500CT-ND', 
  'Active', 
  'Vishay Beyschlag/Draloric/BC Components', 
  'Anti-Sulfur', 
  '2023-05-01T19:26:31.977', 
  '1', 
  '76953', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.vishay.com/docs/28705/mcx0x0xpro.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.061" L x 0.033" W (1.55mm x 0.85mm)', 
  '22.6 Ohms', 
  '0.1W, 1/10W', 
  'MCT - Professional', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '22.6 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 47K OHM 1% 1/4W 0603', 
  'ESR03EZPF4702', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/ESR03EZPF4702/4007243', 
  '0.022" (0.55mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '511-ESR03EZPF4702CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:26:31.980', 
  '1', 
  '76954', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/esr-e.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  '47 kOhms', 
  '0.25W, 1/4W', 
  'ESR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '47 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 2.7 OHM 1% 1/4W 0603', 
  'ESR03EZPF2R70', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/ESR03EZPF2R70/4007210', 
  '0.022" (0.55mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '511-ESR03EZPF2R70CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:26:31.983', 
  '1', 
  '76955', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/esr-e.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  '2.7 Ohms', 
  '0.25W, 1/4W', 
  'ESR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2.7 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 30K OHM 1% 1/4W 0603', 
  'ESR03EZPF3002', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/ESR03EZPF3002/4007213', 
  '0.022" (0.55mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '511-ESR03EZPF3002CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:26:31.987', 
  '1', 
  '76956', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/esr-e.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  '30 kOhms', 
  '0.25W, 1/4W', 
  'ESR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '30 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 3.3M OHM 1% 1/4W 0603', 
  'ESR03EZPF3304', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/ESR03EZPF3304/4007220', 
  '0.022" (0.55mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '511-ESR03EZPF3304CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:26:31.993', 
  '1', 
  '76957', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/esr-e.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  '3.3 MOhms', 
  '0.25W, 1/4W', 
  'ESR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '3.3 MOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 4.7K OHM 1% 1/4W 0603', 
  'ESR03EZPF4701', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/ESR03EZPF4701/4007242', 
  '0.022" (0.55mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '511-ESR03EZPF4701CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:26:32', 
  '1', 
  '76958', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/esr-e.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  '4.7 kOhms', 
  '0.25W, 1/4W', 
  'ESR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '4.7 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 33K OHM 1% 1/4W 0603', 
  'ESR03EZPF3302', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/ESR03EZPF3302/4007219', 
  '0.022" (0.55mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '511-ESR03EZPF3302CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:26:32.003', 
  '1', 
  '76959', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/esr-e.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  '33 kOhms', 
  '0.25W, 1/4W', 
  'ESR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '33 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 8.2 OHM 1% 1/3W 0603', 
  'CRCW06038R20FKEAHP', 
  'https://www.digikey.com/en/products/detail/vishay-dale/CRCW06038R20FKEAHP/2225949', 
  '0.022" (0.55mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-CRCW06038R20FKEAHPCT-ND', 
  'Active', 
  'Vishay Dale', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:26:32.010', 
  '1', 
  '76960', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.vishay.com/docs/20043/crcwhpe3.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.033" W (1.60mm x 0.85mm)', 
  '8.2 Ohms', 
  '0.333W, 1/3W', 
  'CRCW-HP', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '8.2 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

