--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Resistors-SurfaceMount-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 2.43K OHM 1% 1/2W 1210', 
  'RK73H2ETTD2431F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RK73H2ETTD2431F/10322796', 
  '0.028" (0.70mm)', 
  '1210 (3225 Metric)', 
  '2', 
  '±100ppm/°C', 
  '1210', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'RESISTOR', 
  '2019-RK73H2ETTD2431FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant', 
  '2023-05-01T20:10:33.790', 
  '1000', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/RK73H.pdf', 
  'RES 1210_3225', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.126" L x 0.102" W (3.20mm x 2.60mm)', 
  '2.43 kOhms', 
  '0.5W, 1/2W', 
  'RK73H', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2.43 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1210_3225.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 1.87K OHM 1% 1/2W 1210', 
  'CRCW12101K87FKEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/CRCW12101K87FKEA/1177360', 
  '0.024" (0.60mm)', 
  '1210 (3225 Metric)', 
  '2', 
  '±100ppm/°C', 
  '1210', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'RESISTOR', 
  '541-1.87KAACT-ND', 
  'Active', 
  'Vishay Dale', 
  'Automotive AEC-Q200', 
  '2023-05-01T20:10:37.503', 
  '1', 
  '=Part Number', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'http://www.vishay.com/docs/20035/dcrcwe3.pdf', 
  'RES 1210_3225', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.126" L x 0.098" W (3.20mm x 2.50mm)', 
  '1.87 kOhms', 
  '0.5W, 1/2W', 
  'CRCW', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1210_3225.PCBLIB'
);

