--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 75K OHM 1% 1/8W 0805', 
  'SFR10EZPF7502', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SFR10EZPF7502/16009165', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SFR10EZPF7502CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Anti-Sulfur, Automotive AEC-Q200', 
  '2023-05-01T19:39:47.313', 
  '1', 
  '76972', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/sfr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '75 kOhms', 
  '0.125W, 1/8W', 
  'SFR', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '75 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPJ563', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPJ563/18674893', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPJ563CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.337', 
  '1', 
  '76973', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '56 kOhms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '56 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPJ433', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPJ433/18674879', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPJ433CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.350', 
  '1', 
  '76974', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '43 kOhms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '43 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPJ200', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPJ200/18674825', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPJ200CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.357', 
  '1', 
  '76975', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '20 Ohms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '20 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPJ1R8', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPJ1R8/18674831', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPJ1R8CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.370', 
  '1', 
  '76976', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '1.8 Ohms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1.8 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPF4701', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPF4701/18674811', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPF4701CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.377', 
  '1', 
  '76977', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '4.7 kOhms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '4.7 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 0.03 OHM 0.5% 1/2W 0805', 
  'WSLP0805R0300DEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/WSLP0805R0300DEA/9755273', 
  '0.023" (0.58mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±75ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '541-WSLP0805R0300DEACT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200, Current Sense, Moisture Resistant, Pulse Withstanding', 
  '2023-05-01T19:39:47.393', 
  '1', 
  '76978', 
  '=Value', 
  '-65°C ~ 170°C', 
  'Metal Element', 
  'https://www.vishay.com/docs/30122/wslp.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±0.5%', 
  'DigiKey', 
  '0.080" L x 0.050" W (2.03mm x 1.27mm)', 
  '30 mOhms', 
  '0.5W, 1/2W', 
  'WSLP', 
  '0.75', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  'Active', 
  '30 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPF2402', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPF2402/18674832', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPF2402CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.403', 
  '1', 
  '76979', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '24 kOhms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '24 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPJ472', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPJ472/18674877', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPJ472CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.413', 
  '1', 
  '76980', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '4.7 kOhms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '4.7 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPJ184', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPJ184/18674870', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPJ184CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.427', 
  '1', 
  '76981', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '180 kOhms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '180 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPJ1R5', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPJ1R5/18674813', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPJ1R5CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.433', 
  '1', 
  '76982', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '1.5 Ohms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1.5 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPJ243', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPJ243/18674799', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPJ243CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.443', 
  '1', 
  '76983', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '24 kOhms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '24 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 75 OHM 1% 1/8W 0805', 
  'SFR10EZPF75R0', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SFR10EZPF75R0/16009328', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SFR10EZPF75R0CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Anti-Sulfur, Automotive AEC-Q200', 
  '2023-05-01T19:39:47.450', 
  '1', 
  '76984', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/sfr-e.pdf', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '75 Ohms', 
  '0.125W, 1/8W', 
  'SFR', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '75 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPJ2R0', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPJ2R0/18674921', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPJ2R0CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.463', 
  '1', 
  '76985', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '2 Ohms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPF1R80', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPF1R80/18674826', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPF1R80CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.477', 
  '1', 
  '76986', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '1.8 Ohms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1.8 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPF1302', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPF1302/18674927', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPF1302CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.483', 
  '1', 
  '76987', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '13 kOhms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '13 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPJ431', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPJ431/18674689', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPJ431CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.490', 
  '1', 
  '76988', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '430 Ohms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '430 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPF20R0', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPF20R0/18674849', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPF20R0CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.500', 
  '1', 
  '76989', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '20 Ohms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '20 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPJ4R7', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPJ4R7/18674698', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPJ4R7CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.513', 
  '1', 
  '76990', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '4.7 Ohms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '4.7 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPJ390', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPJ390/18675341', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPJ390CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.520', 
  '1', 
  '76991', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '39 Ohms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '39 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPF4300', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPF4300/18674696', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPF4300CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.527', 
  '1', 
  '76992', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '430 Ohms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '430 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPJ244', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPJ244/18674796', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPJ244CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.537', 
  '1', 
  '76993', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '240 kOhms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '240 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPF2403', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPF2403/18674888', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPF2403CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.543', 
  '1', 
  '76994', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '240 kOhms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '240 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPJ4R3', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPJ4R3/18674687', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPJ4R3CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.550', 
  '1', 
  '76995', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±5%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '4.3 Ohms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '4.3 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH ANTI-SURGE THICK FILM CHIP', 
  'SDR10EZPF39R0', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SDR10EZPF39R0/18674828', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-SDR10EZPF39R0CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-01T19:39:47.557', 
  '1', 
  '76996', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '39 Ohms', 
  '0.5W, 1/2W', 
  'SDR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '39 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH VOLTAGE RESISTANCE CHIP RES', 
  'KTR10EZPF2R70', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/KTR10EZPF2R70/18674864', 
  '0.026" (0.65mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '511-KTR10EZPF2R70CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, High Voltage', 
  '2023-05-01T19:39:47.563', 
  '1', 
  '76997', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0805_2012', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '2.7 Ohms', 
  '0.125W, 1/8W', 
  'KTR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2.7 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 287 OHM 1% 1/8W 0805', 
  'CR0805-FX-2870ELF', 
  'https://www.digikey.com/en/products/detail/bourns-inc/CR0805-FX-2870ELF/3784823', 
  '0.024" (0.60mm)', 
  '0805 (2012 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0805', 
  '0805 (2012 Metric)', 
  'RESISTOR', 
  '118-CR0805-FX-2870ELFCT-ND', 
  'Active', 
  'Bourns Inc.', 
  'Moisture Resistant', 
  '2023-05-01T19:39:47.577', 
  '1', 
  '76998', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.bourns.com/docs/product-datasheets/cr.pdf?sfvrsn=574d41f6_14', 
  'RES 0805_2012', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '287 Ohms', 
  '0.125W, 1/8W', 
  'CR0805', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '287 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0805_2012.PCBLIB'
);

