--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "Footprint Ref",
  "Color",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Lens Color",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '470nm', 
  'NEXT GENERATION OF CHIP LED 0603', 
  'LB Q99G.01-P1R1-35-1', 
  'https://www.digikey.com/en/products/detail/ams-osram-usa-inc/LB-Q99G-01-P1R1-35-1/21556500', 
  'Clear', 
  '140°', 
  '0603 (1608 Metric)', 
  '92.5mcd', 
  '0603', 
  'Rectangle with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '475-LBQ99G.01-P1R1-35-1CT-ND', 
  'Active', 
  'ams-OSRAM USA Inc.', 
  '2.85V', 
  '2023-11-05T21:28:51.017', 
  '1', 
  '466nm', 
  '1417', 
  '1.10mm x 0.80mm', 
  '=Value', 
  'LED 0603_1608 BLUE', 
  'Blue', 
  '5mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '0.75mm', 
  'Chip LED 0603', 
  '0.03', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Blue', 
  'Colorless', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 BLUE.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Lens Size",
  "Comment",
  "Footprint Ref",
  "Color",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Lens Color",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'NEXT GENERATION OF CHIP LED 0603', 
  'LW Q98G.01-R2T1-3K6L-1', 
  'https://www.digikey.com/en/products/detail/ams-osram-usa-inc/LW-Q98G-01-R2T1-3K6L-1/21556497', 
  'Diffused', 
  '130°', 
  '0603 (1608 Metric)', 
  '247.5mcd', 
  '0603', 
  'Rectangle with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '475-LWQ98G.01-R2T1-3K6L-1CT-ND', 
  'Active', 
  'ams-OSRAM USA Inc.', 
  '2.75V', 
  '2023-11-05T21:35:07.743', 
  '1', 
  '1418', 
  '1.10mm x 0.80mm', 
  '=Value', 
  'LED 0603_1608', 
  'White', 
  '5mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '0.75mm', 
  'Chip LED 0603', 
  '0.03', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'White', 
  'Yellow', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608.PCBLIB'
);

