--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "DC Resistance (DCR) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'NOISE FILTER, 800, 0.27A', 
  '800 Ohms @ 100 MHz', 
  'MAF1005FRQ801AT000', 
  'https://www.digikey.com/en/products/detail/tdk-corporation/MAF1005FRQ801AT000/21292080', 
  '0402 (1005 Metric)', 
  '0402 (1005 Metric)', 
  'FERRITE CHIP', 
  '445-MAF1005FRQ801AT000CT-ND', 
  '270mA', 
  'Active', 
  'TDK Corporation', 
  '2023-11-05T21:21:20.793', 
  '1', 
  '3511', 
  '=Value', 
  '-55°C ~ 125°C', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5488/MAF1005FR_Type_DS.pdf', 
  'FER 0402_1005', 
  'Datasheet', 
  '1.35Ohm', 
  'DigiKey', 
  'Surface Mount', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '0.022" (0.55mm)', 
  'MAF', 
  '0.06', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  '800 Ohms @ 100 MHz', 
  'Audio Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0402_1005.PCBLIB', 
  '1'
);

INSERT INTO "altium"."Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "DC Resistance (DCR) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'NOISE FILTER, 1000, 0.24A', 
  '1 kOhms @ 100 MHz', 
  'MAF1005FRQ102AT000', 
  'https://www.digikey.com/en/products/detail/tdk-corporation/MAF1005FRQ102AT000/21292078', 
  '0402 (1005 Metric)', 
  '0402 (1005 Metric)', 
  'FERRITE CHIP', 
  '445-MAF1005FRQ102AT000CT-ND', 
  '240mA', 
  'Active', 
  'TDK Corporation', 
  '2023-11-05T21:21:20.820', 
  '1', 
  '3512', 
  '=Value', 
  '-55°C ~ 125°C', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5488/MAF1005FR_Type_DS.pdf', 
  'FER 0402_1005', 
  'Datasheet', 
  '1.65Ohm', 
  'DigiKey', 
  'Surface Mount', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '0.022" (0.55mm)', 
  'MAF', 
  '0.06', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  '1 kOhms @ 100 MHz', 
  'Audio Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0402_1005.PCBLIB', 
  '1'
);

INSERT INTO "altium"."Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "DC Resistance (DCR) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD', 
  '600 Ohms @ 100 MHz', 
  'CZB1JGTTD601P', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/CZB1JGTTD601P/21681781', 
  '0603 (1608 Metric)', 
  '0603 (1608 Metric)', 
  'FERRITE CHIP', 
  '2019-CZB1JGTTD601PCT-ND', 
  '300mA', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  '2023-11-05T21:22:07.073', 
  '1', 
  '3513', 
  '=Value', 
  '-55°C ~ 125°C', 
  'https://www.koaspeer.com/pdfs/CZB.pdf', 
  'FER 0603_1608', 
  'Datasheet', 
  '450mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  '0.037" (0.95mm)', 
  '-', 
  '0.03', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  '600 Ohms @ 100 MHz', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0603_1608.PCBLIB', 
  '1'
);

INSERT INTO "altium"."Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "DC Resistance (DCR) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD', 
  '60 Ohms @ 100 MHz', 
  'CZP1JFTTD600P', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/CZP1JFTTD600P/21679612', 
  '0603 (1608 Metric)', 
  '0603 (1608 Metric)', 
  'FERRITE CHIP', 
  '2019-CZP1JFTTD600PCT-ND', 
  '3A', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  '2023-11-05T21:22:07.087', 
  '1', 
  '3514', 
  '=Value', 
  '-55°C ~ 125°C', 
  'https://www.koaspeer.com/pdfs/CZP.pdf', 
  'FER 0603_1608', 
  'Datasheet', 
  '40mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  '0.037" (0.95mm)', 
  'CZP', 
  '0.04', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  '60 Ohms @ 100 MHz', 
  'Power Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0603_1608.PCBLIB', 
  '1'
);

INSERT INTO "altium"."Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "DC Resistance (DCR) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD 300 OHM 0805 1LN', 
  '300 Ohms @ 100 MHz', 
  'ABPY00201209301Y00', 
  'https://www.digikey.com/en/products/detail/pulse-electronics/ABPY00201209301Y00/16503333', 
  '0805 (2012 Metric)', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'FERRITE CHIP', 
  '553-ABPY00201209301Y00CT-ND', 
  '2A', 
  'Active', 
  'Chilisin Electronics', 
  'Automotive', 
  '2023-11-05T21:22:43.543', 
  '1', 
  '3515', 
  '=Value', 
  '-55°C ~ 125°C', 
  'https://productfinder.pulseelectronics.com/api/open/part-attachments/datasheet/ABPY00201209301Y00', 
  'FER 0805_2012', 
  'Datasheet', 
  '80mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '0.043" (1.10mm)', 
  'ABPY', 
  '0.03', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  '300 Ohms @ 100 MHz', 
  'Power Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0805_2012.PCBLIB', 
  '1'
);

INSERT INTO "altium"."Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "DC Resistance (DCR) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD', 
  '600 Ohms @ 100 MHz', 
  'CZP2BPTTE601P', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/CZP2BPTTE601P/21680564', 
  '1206 (3216 Metric)', 
  '1206 (3216 Metric)', 
  'FERRITE CHIP', 
  '2019-CZP2BPTTE601PCT-ND', 
  '1.5A', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  '2023-11-05T21:23:04.043', 
  '1', 
  '3516', 
  '=Value', 
  '-55°C ~ 125°C', 
  'https://www.koaspeer.com/pdfs/CZP.pdf', 
  'FER 1206_3216', 
  'Datasheet', 
  '100mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  '0.051" (1.30mm)', 
  'CZP', 
  '0.04', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  '600 Ohms @ 100 MHz', 
  'Power Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 1206_3216.PCBLIB', 
  '1'
);

