--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Resistors-SurfaceMount-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 1M OHM 1% 3/4W 1210', 
  'SG73P2ETTD1004F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/SG73P2ETTD1004F/10195922', 
  '0.028" (0.70mm)', 
  '1210 (3225 Metric)', 
  '2', 
  '±100ppm/°C', 
  '1210', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'RESISTOR', 
  '2019-SG73P2ETTD1004FTR-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-08-15T20:38:13.947', 
  '5000', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/SG73P.pdf', 
  'RES 1210_3225', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.126" L x 0.102" W (3.20mm x 2.60mm)', 
  '1 MOhms', 
  '0.75W, 3/4W', 
  'SG73P', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '1 MOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1210_3225.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 6.2 OHM 2% 1/2W 1210', 
  'SG73S2ETTD6R2G', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/SG73S2ETTD6R2G/10287166', 
  '0.028" (0.70mm)', 
  '1210 (3225 Metric)', 
  '2', 
  '±200ppm/°C', 
  '1210', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'RESISTOR', 
  '2019-SG73S2ETTD6R2GTR-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant, Pulse Withstanding', 
  '2023-08-15T20:38:13.970', 
  '5000', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/SG73S.pdf', 
  'RES 1210_3225', 
  'Datasheet', 
  '±2%', 
  'DigiKey', 
  '0.126" L x 0.102" W (3.20mm x 2.60mm)', 
  '6.2 Ohms', 
  '0.5W, 1/2W', 
  'SG73S', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '6.2 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1210_3225.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 10 OHM 1% 1/2W 1210', 
  'SG73S2ETTD10R0F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/SG73S2ETTD10R0F/10297556', 
  '0.028" (0.70mm)', 
  '1210 (3225 Metric)', 
  '2', 
  '±200ppm/°C', 
  '1210', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'RESISTOR', 
  '2019-SG73S2ETTD10R0FTR-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant, Pulse Withstanding', 
  '2023-08-15T20:38:13.983', 
  '5000', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/SG73S.pdf', 
  'RES 1210_3225', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.126" L x 0.102" W (3.20mm x 2.60mm)', 
  '10 Ohms', 
  '0.5W, 1/2W', 
  'SG73S', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '10 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1210_3225.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 49.9 OHM 1% 3/4W 1210', 
  'SG73P2ETTD49R9F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/SG73P2ETTD49R9F/10194764', 
  '0.028" (0.70mm)', 
  '1210 (3225 Metric)', 
  '2', 
  '±200ppm/°C', 
  '1210', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'RESISTOR', 
  '2019-SG73P2ETTD49R9FTR-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-08-15T20:38:14', 
  '5000', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/SG73P.pdf', 
  'RES 1210_3225', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.126" L x 0.102" W (3.20mm x 2.60mm)', 
  '49.9 Ohms', 
  '0.75W, 3/4W', 
  'SG73P', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '49.9 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1210_3225.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 33.2 OHM 1% 3/4W 1210', 
  'SG73P2ETTD33R2F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/SG73P2ETTD33R2F/10194716', 
  '0.028" (0.70mm)', 
  '1210 (3225 Metric)', 
  '2', 
  '±200ppm/°C', 
  '1210', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'RESISTOR', 
  '2019-SG73P2ETTD33R2FTR-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-08-15T20:38:14.010', 
  '5000', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/SG73P.pdf', 
  'RES 1210_3225', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.126" L x 0.102" W (3.20mm x 2.60mm)', 
  '33.2 Ohms', 
  '0.75W, 3/4W', 
  'SG73P', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '33.2 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1210_3225.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 1 OHM 5% 1/2W 1210', 
  'SG73S2ETTD1R0J', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/SG73S2ETTD1R0J/10297749', 
  '0.028" (0.70mm)', 
  '1210 (3225 Metric)', 
  '2', 
  '±200ppm/°C', 
  '1210', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'RESISTOR', 
  '2019-SG73S2ETTD1R0JTR-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant, Pulse Withstanding', 
  '2023-08-15T20:38:14.017', 
  '5000', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/SG73S.pdf', 
  'RES 1210_3225', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.126" L x 0.102" W (3.20mm x 2.60mm)', 
  '1 Ohms', 
  '0.5W, 1/2W', 
  'SG73S', 
  '0.03', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '1 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1210_3225.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 330 OHM 10% 1/2W 1210', 
  'SG732ETTD331K', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/SG732ETTD331K/10196444', 
  '0.028" (0.70mm)', 
  '1210 (3225 Metric)', 
  '2', 
  '±200ppm/°C', 
  '1210', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'RESISTOR', 
  '2019-SG732ETTD331KTR-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant, Pulse Withstanding', 
  '2023-08-15T20:38:14.040', 
  '5000', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/SG73.pdf', 
  'RES 1210_3225', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  '0.126" L x 0.102" W (3.20mm x 2.60mm)', 
  '330 Ohms', 
  '0.5W, 1/2W', 
  'SG73', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '330 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1210_3225.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 4.7 OHM 1% 3/4W 1210', 
  'SG73P2ETTD4R70F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/SG73P2ETTD4R70F/10188325', 
  '0.028" (0.70mm)', 
  '1210 (3225 Metric)', 
  '2', 
  '±200ppm/°C', 
  '1210', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'RESISTOR', 
  '2019-SG73P2ETTD4R70FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-08-15T20:38:14.057', 
  '1', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/SG73P.pdf', 
  'RES 1210_3225', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.126" L x 0.102" W (3.20mm x 2.60mm)', 
  '4.7 Ohms', 
  '0.75W, 3/4W', 
  'SG73P', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '4.7 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1210_3225.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 390 OHM 1% 3/4W 1210', 
  'SG73P2ETTD3900F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/SG73P2ETTD3900F/10194998', 
  '0.028" (0.70mm)', 
  '1210 (3225 Metric)', 
  '2', 
  '±100ppm/°C', 
  '1210', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'RESISTOR', 
  '2019-SG73P2ETTD3900FTR-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-08-15T20:38:14.063', 
  '5000', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/SG73P.pdf', 
  'RES 1210_3225', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.126" L x 0.102" W (3.20mm x 2.60mm)', 
  '390 Ohms', 
  '0.75W, 3/4W', 
  'SG73P', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '390 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1210_3225.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 3.3K OHM 10% 1/2W 1210', 
  'SG732ETTD332K', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/SG732ETTD332K/10196468', 
  '0.028" (0.70mm)', 
  '1210 (3225 Metric)', 
  '2', 
  '±200ppm/°C', 
  '1210', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'RESISTOR', 
  '2019-SG732ETTD332KTR-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant, Pulse Withstanding', 
  '2023-08-15T20:38:14.073', 
  '5000', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/SG73.pdf', 
  'RES 1210_3225', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  '0.126" L x 0.102" W (3.20mm x 2.60mm)', 
  '3.3 kOhms', 
  '0.5W, 1/2W', 
  'SG73', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '3.3 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1210_3225.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 4.99K OHM 1% 3/4W 1210', 
  'SG73P2ETTD4991F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/SG73P2ETTD4991F/10195296', 
  '0.028" (0.70mm)', 
  '1210 (3225 Metric)', 
  '2', 
  '±100ppm/°C', 
  '1210', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'RESISTOR', 
  '2019-SG73P2ETTD4991FTR-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-08-15T20:38:14.180', 
  '5000', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/SG73P.pdf', 
  'RES 1210_3225', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.126" L x 0.102" W (3.20mm x 2.60mm)', 
  '4.99 kOhms', 
  '0.75W, 3/4W', 
  'SG73P', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '4.99 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1210_3225.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 12 OHM 1% 3/4W 1210', 
  'SG73P2ETTD12R0F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/SG73P2ETTD12R0F/10188268', 
  '0.028" (0.70mm)', 
  '1210 (3225 Metric)', 
  '2', 
  '±200ppm/°C', 
  '1210', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'RESISTOR', 
  '2019-SG73P2ETTD12R0FTR-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-08-15T20:38:14.193', 
  '5000', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/SG73P.pdf', 
  'RES 1210_3225', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.126" L x 0.102" W (3.20mm x 2.60mm)', 
  '12 Ohms', 
  '0.75W, 3/4W', 
  'SG73P', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '12 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1210_3225.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 22 OHM 1% 3/4W 1210', 
  'SG73P2ETTD22R0F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/SG73P2ETTD22R0F/10188326', 
  '0.028" (0.70mm)', 
  '1210 (3225 Metric)', 
  '2', 
  '±200ppm/°C', 
  '1210', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'RESISTOR', 
  '2019-SG73P2ETTD22R0FTR-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-08-15T20:38:14.200', 
  '5000', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/SG73P.pdf', 
  'RES 1210_3225', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.126" L x 0.102" W (3.20mm x 2.60mm)', 
  '22 Ohms', 
  '0.75W, 3/4W', 
  'SG73P', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '22 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1210_3225.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 51K OHM 1% 1/2W 1210', 
  'RC1210FR-0751KL', 
  'https://www.digikey.com/en/products/detail/yageo/RC1210FR-0751KL/5919651', 
  '0.024" (0.60mm)', 
  '1210 (3225 Metric)', 
  '2', 
  '±100ppm/°C', 
  '1210', 
  '1210 (3225 Metric)', 
  'RESISTOR', 
  '13-RC1210FR-0751KLCT-ND', 
  'Active', 
  'Yageo', 
  'Moisture Resistant', 
  '2023-08-15T20:38:13.570', 
  '1', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.yageo.com/upload/media/product/productsearch/datasheet/rchip/PYu-RC_Group_51_RoHS_L_12.pdf', 
  'RES 1210_3225', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.122" L x 0.102" W (3.10mm x 2.60mm)', 
  '51 kOhms', 
  '0.5W, 1/2W', 
  'RC_L', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '51 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1210_3225.PCBLIB'
);

