--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Capacitors-Ceramic-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 4.7UF 16V X7R 1210', 
  'KGM32LR71C475MU', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGM32LR71C475MU/3082094', 
  '1210 (3225 Metric)', 
  '16V', 
  'X7R', 
  '1210 (3225 Metric)', 
  'CAPACITOR', 
  '478-KGM32LR71C475MUCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2023-08-15T19:35:14.120', 
  '1', 
  '56020', 
  '=Value', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://datasheets.kyocera-avx.com/KGM_X7R.pdf', 
  'CAP 1210_3225 - 1MM', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.098" W (3.20mm x 2.50mm)', 
  '-', 
  '0.110" (2.79mm)', 
  '0.45', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '4.7 µF', 
  '4.7 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1210_3225 - 1MM.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER SMD', 
  'KGM32LCG3D471JU', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGM32LCG3D471JU/11252681', 
  '1210 (3225 Metric)', 
  '2000V (2kV)', 
  'C0G, NP0', 
  '1210 (3225 Metric)', 
  'CAPACITOR', 
  '478-KGM32LCG3D471JUCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  'High Voltage', 
  '2023-08-15T19:35:14.133', 
  '1', 
  '56021', 
  '=Value', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://datasheets.kyocera-avx.com/HVKGM.pdf', 
  'CAP 1210_3225 - 1MM', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.130" L x 0.098" W (3.30mm x 2.50mm)', 
  '-', 
  '0.071" (1.80mm)', 
  '0.30', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '470 pF', 
  '470 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1210_3225 - 1MM.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 3300PF 500V X7R 1210', 
  'CC1210KKX7RBBB332', 
  'https://www.digikey.com/en/products/detail/yageo/CC1210KKX7RBBB332/5884747', 
  '1210 (3225 Metric)', 
  '500V', 
  'X7R', 
  '1210 (3225 Metric)', 
  'CAPACITOR', 
  '13-CC1210KKX7RBBB332CT-ND', 
  'Active', 
  'Yageo', 
  '2023-08-15T19:35:14.143', 
  '1', 
  '56022', 
  '=Value', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://www.yageo.com/upload/media/product/productsearch/datasheet/mlcc/UPY-NP0X7R_MV_100-to-630V_25.pdf', 
  'CAP 1210_3225 - 1MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.098" W (3.20mm x 2.50mm)', 
  'CC', 
  '0.057" (1.45mm)', 
  '0.15', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '3300 pF', 
  '3300 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1210_3225 - 1MM.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 0.022UF 200V X7R 1210', 
  'CC1210KKX7RABB223', 
  'https://www.digikey.com/en/products/detail/yageo/CC1210KKX7RABB223/5884742', 
  '1210 (3225 Metric)', 
  '200V', 
  'X7R', 
  '1210 (3225 Metric)', 
  'CAPACITOR', 
  '13-CC1210KKX7RABB223CT-ND', 
  'Active', 
  'Yageo', 
  '2023-08-15T19:35:14.153', 
  '1', 
  '56023', 
  '=Value', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'https://www.yageo.com/upload/media/product/productsearch/datasheet/mlcc/UPY-NP0X7R_MV_100-to-630V_25.pdf', 
  'CAP 1210_3225 - 1MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.098" W (3.20mm x 2.50mm)', 
  'CC', 
  '0.057" (1.45mm)', 
  '0.11', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '0.022 µF', 
  '0.022 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1210_3225 - 1MM.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 1210 5.1NF 100V ULTRA ST', 
  'C1210X512F1HACAUTO', 
  'https://www.digikey.com/en/products/detail/kemet/C1210X512F1HACAUTO/8331401', 
  '1210 (3225 Metric)', 
  '100V', 
  'X8R', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'CAPACITOR', 
  '399-C1210X512F1HACAUTOCT-ND', 
  'Active', 
  'KEMET', 
  'Low ESL, Soft Termination, High Temperature', 
  '2023-08-15T19:35:14.167', 
  '1', 
  '56024', 
  '=Value', 
  '-55°C ~ 150°C', 
  'Automotive, Boardflex Sensitive', 
  'https://connect.kemet.com:7667/gateway/IntelliData-ComponentDocumentation/1.0/download/datasheet/C1210X512F1HACAUTO', 
  'CAP 1210_3225 - 1MM', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.130" L x 0.102" W (3.30mm x 2.60mm)', 
  'SMD Auto X8R HT150C Flex', 
  '0.057" (1.45mm)', 
  '0.25', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '5100 pF', 
  '5100 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1210_3225 - 1MM.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 6200PF 1KV C0G/NP0 1210', 
  'C1210C622JDGACAUTO', 
  'https://www.digikey.com/en/products/detail/kemet/C1210C622JDGACAUTO/16889543', 
  '1210 (3225 Metric)', 
  '1000V (1kV)', 
  'C0G, NP0', 
  'AEC-Q200', 
  '1210 (3225 Metric)', 
  'CAPACITOR', 
  '399-C1210C622JDGACAUTOCT-ND', 
  'Active', 
  'KEMET', 
  'Low ESL, High Voltage', 
  '2023-08-15T19:35:14.183', 
  '1', 
  '56025', 
  '=Value', 
  '-55°C ~ 125°C', 
  'Automotive', 
  'https://content.kemet.com/datasheets/KEM_C1080_C0G_HV_AUTO_SMD.pdf', 
  'CAP 1210_3225 - 1MM', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.098" W (3.20mm x 2.50mm)', 
  'SMD Auto C0G HV', 
  '0.087" (2.20mm)', 
  '0.63', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '6200 pF', 
  '6200 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1210_3225 - 1MM.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '-EM , NON FLIGHT ENGINEERING MOD', 
  '12101C394KAR1-EM', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/12101C394KAR1-EM/19115334', 
  '1210 (3225 Metric)', 
  '100V', 
  'X7R', 
  '1210 (3225 Metric)', 
  'CAPACITOR', 
  '478-12101C394KAR1-EMCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  'Soft Termination', 
  '2023-08-15T19:35:14.200', 
  '1', 
  '56026', 
  '=Value', 
  '-55°C ~ 125°C', 
  'Boardflex Sensitive', 
  'https://datasheets.kyocera-avx.com/em-series.pdf', 
  'CAP 1210_3225 - 1MM', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.126" L x 0.098" W (3.20mm x 2.50mm)', 
  'Prototype, MIL-PRF-32535', 
  '0.110" (2.80mm)', 
  '14.49', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '0.39 µF', 
  '0.39 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1210_3225 - 1MM.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-1210" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 0.22UF 250V X7R 1210', 
  '1210VC224KAT2A', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/1210VC224KAT2A/6149356', 
  '1210 (3225 Metric)', 
  '250V', 
  'X7R', 
  '1210 (3225 Metric)', 
  'CAPACITOR', 
  '478-1210VC224KAT2ACT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2023-08-15T19:35:14.223', 
  '1', 
  '56027', 
  '=Value', 
  '-55°C ~ 125°C', 
  'General Purpose', 
  'CAP 1210_3225 - 1MM', 
  '±10%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.130" L x 0.098" W (3.30mm x 2.50mm)', 
  '-', 
  '0.110" (2.80mm)', 
  '0.16', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '0.22 µF', 
  '0.22 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 1210_3225 - 1MM.PCBLIB'
);

