--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Capacitors-Aluminum-Polymer-SMT" (
  "Applications",
  "Capacitance",
  "comment",
  "componentlink1description",
  "componentlink1url",
  "componentlink2description",
  "componentlink2url",
  "description",
  "Device Package",
  "ESR (Equivalent Series Resistance)",
  "Footprint Path",
  "Footprint Ref",
  "Height - Seated (Max)",
  "lastupdated",
  "Lifecycle Status",
  "Lifetime @ Temp.",
  "manufacturer",
  "Part Number",
  "Minimum Order",
  "Mounting Type",
  "Operating Temperature",
  "Package / Case",
  "packaging",
  "partid",
  "Part Status",
  "price",
  "Ratings",
  "Ripple Current @ High Frequency",
  "Ripple Current @ Low Frequency",
  "series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Surface Mount Land Size",
  "Library Path",
  "Library Ref",
  "Tolerance",
  "Type",
  "value",
  "Voltage - Rated"
)
VALUES (
  'Automotive', 
  '220 µF', 
  '=Value', 
  'Datasheet', 
  'https://industrial.panasonic.com/cdbs/www-data/pdf/RDD0000/ABA0000C1234.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/panasonic-electronic-components/EEH-ZC1E221V/6188461', 
  'CAP ALUM POLY 220UF 20% 25V SMD', 
  'Radial, Can - SMD', 
  '27mOhm', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP ALSMD POLY 8.3MM H10.5MM.PCBLIB', 
  'CAP ALSMD POLY 8.3MM H10.5MM', 
  '0.413" (10.50mm)', 
  '2023-01-27T21:00:00.507', 
  'Active', 
  '4000 Hrs @ 125°C', 
  'Panasonic Electronic Components', 
  'EEH-ZC1E221V', 
  '0', 
  'Surface Mount', 
  '-55°C ~ 125°C', 
  'Radial, Can - SMD', 
  '', 
  '5461', 
  'Active', 
  '0', 
  'AEC-Q200', 
  '1.6 A @ 100 kHz', 
  '240 mA @ 100 Hz', 
  'ZC, Anti-Vibration', 
  '0.315" Dia (8.00mm)', 
  'DigiKey', 
  'P19832TR-ND', 
  '0.327" L x 0.327" W (8.30mm x 8.30mm)', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'POLARISED CAPACITOR', 
  '±20%', 
  'Hybrid', 
  '220 µF', 
  '25 V'
);

INSERT INTO "Capacitors-Aluminum-Polymer-SMT" (
  "Applications",
  "Capacitance",
  "comment",
  "componentlink1description",
  "componentlink1url",
  "componentlink2description",
  "componentlink2url",
  "description",
  "Device Package",
  "ESR (Equivalent Series Resistance)",
  "Footprint Path",
  "Footprint Ref",
  "Height - Seated (Max)",
  "lastupdated",
  "Lifecycle Status",
  "Lifetime @ Temp.",
  "manufacturer",
  "Part Number",
  "Minimum Order",
  "Mounting Type",
  "Operating Temperature",
  "Package / Case",
  "packaging",
  "partid",
  "Part Status",
  "price",
  "Ratings",
  "Ripple Current @ High Frequency",
  "Ripple Current @ Low Frequency",
  "series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Surface Mount Land Size",
  "Library Path",
  "Library Ref",
  "Tolerance",
  "Type",
  "value",
  "Voltage - Rated"
)
VALUES (
  'Automotive', 
  '150 µF', 
  '=Value', 
  'Datasheet', 
  'https://industrial.panasonic.com/cdbs/www-data/pdf/RDD0000/ABA0000C1234.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/panasonic-electronic-components/EEH-ZC1V151V/6188463', 
  'CAP ALUM POLY 150UF 20% 35V SMD', 
  'Radial, Can - SMD', 
  '27mOhm', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP ALSMD POLY 8.3MM H10.5MM.PCBLIB', 
  'CAP ALSMD POLY 8.3MM H10.5MM', 
  '0.413" (10.50mm)', 
  '2023-01-27T21:00:00.893', 
  'Active', 
  '4000 Hrs @ 125°C', 
  'Panasonic Electronic Components', 
  'EEH-ZC1V151V', 
  '0', 
  'Surface Mount', 
  '-55°C ~ 125°C', 
  'Radial, Can - SMD', 
  '', 
  '5462', 
  'Active', 
  '0', 
  'AEC-Q200', 
  '1.6 A @ 100 kHz', 
  '240 mA @ 100 Hz', 
  'ZC, Anti-Vibration', 
  '0.315" Dia (8.00mm)', 
  'DigiKey', 
  'P19834TR-ND', 
  '0.327" L x 0.327" W (8.30mm x 8.30mm)', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'POLARISED CAPACITOR', 
  '±20%', 
  'Hybrid', 
  '150 µF', 
  '35 V'
);

