--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Diodes-TVS" (
  "Applications",
  "Capacitance @ Frequency",
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Current - Peak Pulse (10/1000µs)",
  "Description",
  "Device Package",
  "Footprint Path",
  "Footprint Ref",
  "LastUpdated",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Minimum Order",
  "Mounting Type",
  "Operating Temperature",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Power Line Protection",
  "Power - Peak Pulse",
  "Price",
  "Series",
  "Supplier 1",
  "Supplier Part Number 1",
  "Library Path",
  "Library Ref",
  "Type",
  "Unidirectional Channels",
  "Voltage - Breakdown (Min)",
  "Voltage - Clamping (Max) @ Ipp",
  "Voltage - Reverse Standoff (Typ)"
)
VALUES (
  'Automotive', 
  '110pF @ 1MHz', 
  '=Part Number', 
  'Datasheet', 
  'https://www.diodes.com/assets/Datasheets/D12V0HA1U2LPQ.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/diodes-incorporated/D12V0HA1U2LPQ-7B/17511713', 
  '25A (8/20µs)', 
  'SURGE PROTECTION PP X1-DFN1006-2', 
  '0402 (1005 Metric)', 
  'footprints/Diodes/PCB - DIODES - 0402.PCBLIB', 
  '0402', 
  '2023-01-27T21:03:05.253', 
  'Active', 
  'Diodes Incorporated', 
  'D12V0HA1U2LPQ-7B', 
  '1', 
  'Surface Mount', 
  '-55°C ~ 150°C (TJ)', 
  '0402 (1005 Metric)', 
  'TapeAndReel', 
  '11672', 
  'Active', 
  'No', 
  '500W', 
  '0.05', 
  'Automotive, AEC-Q101', 
  'DigiKey', 
  '31-D12V0HA1U2LPQ-7BCT-ND', 
  'symbols/Diodes/SCH - DIODES - DIODE TVS UNI.SCHLIB', 
  'DIODE TVS UNI', 
  'Zener', 
  '1', 
  '13.5V', 
  '20V (Typ)', 
  '12V (Max)'
);

