--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Diodes-TVS" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Voltage - Clamping (Max) @ Ipp",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Voltage - Reverse Standoff (Typ)",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Power Line Protection",
  "Bidirectional Channels",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Capacitance @ Frequency",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'BIDIRECTIONAL SINGLE LINE ESD PR', 
  'VETH100A1DD1HG3-08', 
  'https://www.digikey.com/en/products/detail/vishay-general-semiconductor-diodes-division/VETH100A1DD1HG3-08/21293001', 
  '0402 (1005 Metric)', 
  'DFN1006-2B', 
  '0402 (1005 Metric)', 
  'DIODE TVS', 
  '34V (Typ)', 
  '112-VETH100A1DD1HG3-08CT-ND', 
  'Active', 
  '24V (Max)', 
  'Vishay General Semiconductor - Diodes Division', 
  '2023-09-06T20:44:04', 
  '1', 
  '11800', 
  'No', 
  '1', 
  '=Part Number', 
  '-55°C ~ 150°C (TJ)', 
  'Automotive, Ethernet', 
  'https://www.vishay.com/docs/86195/veth100a1dd1.pdf', 
  '1.7pF @ 1MHz', 
  '0402', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  'Automotive, AEC-Q101', 
  'Zener', 
  '0.06', 
  'symbols/Diodes/SCH - DIODES - DIODE TVS.SCHLIB', 
  'TapeAndReel', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - 0402.PCBLIB'
);

INSERT INTO "Diodes-TVS" (
  "Current - Peak Pulse (10/1000µs)",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Power - Peak Pulse",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Voltage - Clamping (Max) @ Ipp",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Voltage - Reverse Standoff (Typ)",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Power Line Protection",
  "Bidirectional Channels",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Capacitance @ Frequency",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '5A (8/20µs)', 
  'TVS DIODE 2.5VWM 8VC SLP1006P2T', 
  'UCLAMP2511T.TNT', 
  'https://www.digikey.com/en/products/detail/semtech-corporation/UCLAMP2511T-TNT/7392894', 
  '0402 (1005 Metric)', 
  '40W', 
  'SLP1006P2T', 
  '0402 (1005 Metric)', 
  'DIODE TVS', 
  '8V', 
  'UCLAMP2511T.TNT-ND', 
  'Active', 
  '2.5V (Max)', 
  'Semtech Corporation', 
  '2023-09-06T20:44:04.013', 
  '10000', 
  '11801', 
  'No', 
  '1', 
  '=Part Number', 
  '-40°C ~ 85°C (TJ)', 
  'General Purpose', 
  'https://semtech.my.salesforce.com/sfc/p/E0000000JelG/a/2R000000HTDE/n930U3uU4_nmWI2QtzZaZK5Ilc9LRBfvIYsvxXWV2Ao', 
  '6pF @ 1MHz', 
  '0402', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  'uClamp®', 
  'Zener', 
  '0.25', 
  'symbols/Diodes/SCH - DIODES - DIODE TVS.SCHLIB', 
  'TapeAndReel', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - 0402.PCBLIB'
);

