--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Connectors-ModularJacksWithMagnetics" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Contact Finish",
  "Number Of Rows",
  "Height Above Board",
  "Number Of Cores Per Jack",
  "Number Of Ports",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Connector Type",
  "Contact Material",
  "Led Color",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Termination",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Orientation",
  "Tab Direction",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '1X1, 1G', 
  'RJMG201K21120FR', 
  'https://www.digikey.com/en/products/detail/amphenol-icc-commercial-products/RJMG201K21120FR/13683222', 
  'Gold', 
  '1', 
  '0.670" (17.02mm)', 
  '8', 
  '1', 
  'AMPHENOL RJMG201K2', 
  '664-RJMG201K21120FR-ND', 
  'Active', 
  'RJ45', 
  'Phosphor Bronze', 
  'Green - Green', 
  'Amphenol ICC (Commercial Products)', 
  'Board Lock', 
  '2025-11-13T02:07:09.587', 
  '1', 
  '=Part Number', 
  '0°C ~ 70°C', 
  '10/100/1000 Base-T, AutoMDIX', 
  'https://cdn.amphenol-icc.com/media/wysiwyg/files/drawing/rjmg201k1xx30xr.pdf', 
  'AMPHENOL RJMG201K2', 
  'Datasheet', 
  'Solder', 
  'Unshielded', 
  'DigiKey', 
  'Through Hole', 
  'Vertical', 
  'User Selectable', 
  'RJMG', 
  '2.44', 
  'symbols/Connector - RJ45/SCH - CONNECTOR - RJ45 - AMPHENOL RJMG201K2.SCHLIB', 
  'Tray', 
  'Active', 
  'DigiKey Link', 
  'footprints/Connector - Modular/PCB - CONNECTOR - MODULAR - AMPHENOL RJMG201K2.PCBLIB'
);

