--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LINEAR 3V 300MA SOT23-3', 
  'AP2210N-3.0TRG1', 
  'https://www.digikey.com/en/products/detail/diodes-incorporated/AP2210N-3-0TRG1/4570642', 
  'Fixed', 
  '13.2V', 
  '300mA', 
  '15 mA', 
  'Positive', 
  'SOT-23-3', 
  '1', 
  'TO-236-3, SC-59, SOT-23-3', 
  'DIODES INC AP2210-FIXED', 
  'AP2210N-3.0TRG1DICT-ND', 
  'Active', 
  'Diodes Incorporated', 
  '3V', 
  '2025-08-09T08:00:40.997', 
  '1', 
  '0.5V @ 300mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://www.diodes.com/assets/Datasheets/AP2210.pdf', 
  '180 µA', 
  'DIODES SOT-23-3 N', 
  '75dB (100Hz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '-', 
  '0.07', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - DIODES INC AP2210-FIXED.SchLib', 
  'Over Current, Over Temperature, Reverse Polarity', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - DIODES SOT-23-3 N.PCBLIB'
);

INSERT INTO "altium"."VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LINEAR 5V 300MA SOT23-3', 
  'AP2210N-5.0TRG1', 
  'https://www.digikey.com/en/products/detail/diodes-incorporated/AP2210N-5-0TRG1/5305728', 
  'Fixed', 
  '13.2V', 
  '300mA', 
  '15 mA', 
  'Positive', 
  'SOT-23-3', 
  '1', 
  'TO-236-3, SC-59, SOT-23-3', 
  'DIODES INC AP2210-FIXED', 
  'AP2210N-5.0TRG1DICT-ND', 
  'Active', 
  'Diodes Incorporated', 
  '5V', 
  '2025-08-09T08:00:41.023', 
  '1', 
  '0.5V @ 300mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://www.diodes.com/assets/Datasheets/AP2210.pdf', 
  '180 µA', 
  'DIODES SOT-23-3 N', 
  '75dB (100Hz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '-', 
  '0.07', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - DIODES INC AP2210-FIXED.SchLib', 
  'Over Current, Over Temperature, Reverse Polarity', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - DIODES SOT-23-3 N.PCBLIB'
);

INSERT INTO "altium"."VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LINEAR 4V 300MA SOT23-3', 
  'AP2210N-4.0TRG1', 
  'https://www.digikey.com/en/products/detail/diodes-incorporated/AP2210N-4-0TRG1/5305727', 
  'Fixed', 
  '13.2V', 
  '300mA', 
  '15 mA', 
  'Positive', 
  'SOT-23-3', 
  '1', 
  'TO-236-3, SC-59, SOT-23-3', 
  'DIODES INC AP2210-FIXED', 
  'AP2210N-4.0TRG1DICT-ND', 
  'Active', 
  'Diodes Incorporated', 
  '4V', 
  '2025-08-09T08:00:41.033', 
  '1', 
  '0.5V @ 300mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://www.diodes.com/assets/Datasheets/AP2210.pdf', 
  '180 µA', 
  'DIODES SOT-23-3 N', 
  '75dB (100Hz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '-', 
  '0.07', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - DIODES INC AP2210-FIXED.SchLib', 
  'Over Current, Over Temperature, Reverse Polarity', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - DIODES SOT-23-3 N.PCBLIB'
);

INSERT INTO "altium"."VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LINEAR 3.3V 300MA SOT23-3', 
  'AP2210N-3.3TRG1', 
  'https://www.digikey.com/en/products/detail/diodes-incorporated/AP2210N-3-3TRG1/4470822', 
  'Fixed', 
  '13.2V', 
  '300mA', 
  '15 mA', 
  'Positive', 
  'SOT-23-3', 
  '1', 
  'TO-236-3, SC-59, SOT-23-3', 
  'DIODES INC AP2210-FIXED', 
  'AP2210N-3.3TRG1DICT-ND', 
  'Active', 
  'Diodes Incorporated', 
  '3.3V', 
  '2025-08-09T08:00:41.043', 
  '1', 
  '0.5V @ 300mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://www.diodes.com/assets/Datasheets/AP2210.pdf', 
  '180 µA', 
  'DIODES SOT-23-3 N', 
  '75dB (100Hz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '-', 
  '0.07', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - DIODES INC AP2210-FIXED.SchLib', 
  'Over Current, Over Temperature, Reverse Polarity', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - DIODES SOT-23-3 N.PCBLIB'
);

INSERT INTO "altium"."VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LINEAR 2.5V 300MA SOT23-5', 
  'AP2210K-2.5TRG1', 
  'https://www.digikey.com/en/products/detail/diodes-incorporated/AP2210K-2-5TRG1/5305720', 
  'Fixed', 
  '13.2V', 
  '300mA', 
  '15 mA', 
  'Positive', 
  'SOT-23-5', 
  '1', 
  'DIODES INC AP2210-ADJ', 
  '31-AP2210K-2.5TRG1CT-ND', 
  'Active', 
  'Diodes Incorporated', 
  '2.5V', 
  '2025-08-09T08:00:13.383', 
  '1', 
  '0.5V @ 300mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://www.diodes.com/assets/Datasheets/AP2210.pdf', 
  '180 µA', 
  'DIODES SOT-23-5 K', 
  '75dB (100Hz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  'Enable', 
  '-', 
  '0.07', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - DIODES INC AP2210-ADJ.SchLib', 
  'Over Current, Over Temperature, Reverse Polarity', 
  'TapeAndReel', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - DIODES SOT-23-5 K.PCBLIB'
);

INSERT INTO "altium"."VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LINEAR 2.8V 300MA SOT23-5', 
  'AP2210K-2.8TRG1', 
  'https://www.digikey.com/en/products/detail/diodes-incorporated/AP2210K-2-8TRG1/5305722', 
  'Fixed', 
  '13.2V', 
  '300mA', 
  '15 mA', 
  'Positive', 
  'SOT-23-5', 
  '1', 
  'DIODES INC AP2210-ADJ', 
  '31-AP2210K-2.8TRG1TR-ND', 
  'Active', 
  'Diodes Incorporated', 
  '2.8V', 
  '2025-08-09T08:00:13.400', 
  '3000', 
  '0.5V @ 300mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://www.diodes.com/assets/Datasheets/AP2210.pdf', 
  '180 µA', 
  'DIODES SOT-23-5 K', 
  '75dB (100Hz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  'Enable', 
  '-', 
  '0.07', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - DIODES INC AP2210-ADJ.SchLib', 
  'Over Current, Over Temperature, Reverse Polarity', 
  'TapeAndReel', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - DIODES SOT-23-5 K.PCBLIB'
);

INSERT INTO "altium"."VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LINEAR 3.3V 300MA SOT23-5', 
  'AP2210K-3.3TRE1', 
  'https://www.digikey.com/en/products/detail/diodes-incorporated/AP2210K-3-3TRE1/4470818', 
  'Fixed', 
  '13.2V', 
  '300mA', 
  '15 mA', 
  'Positive', 
  'SOT-23-5', 
  '1', 
  'DIODES INC AP2210-ADJ', 
  '31-AP2210K-3.3TRE1CT-ND', 
  'Active', 
  'Diodes Incorporated', 
  '3.3V', 
  '2025-08-09T08:00:13.410', 
  '1', 
  '0.5V @ 300mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://www.diodes.com/assets/Datasheets/AP2210.pdf', 
  '180 µA', 
  'DIODES SOT-23-5 K', 
  '75dB (100Hz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  'Enable', 
  '-', 
  '0.22', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - DIODES INC AP2210-ADJ.SchLib', 
  'Over Current, Over Temperature, Reverse Polarity', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - DIODES SOT-23-5 K.PCBLIB'
);

INSERT INTO "altium"."VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LINEAR 2.5V 300MA SOT23-5', 
  'AP2210K-2.5TRE1', 
  'https://www.digikey.com/en/products/detail/diodes-incorporated/AP2210K-2-5TRE1/5305719', 
  'Fixed', 
  '13.2V', 
  '300mA', 
  '15 mA', 
  'Positive', 
  'SOT-23-5', 
  '1', 
  'SC-74A, SOT-753', 
  'DIODES INC AP2210-ADJ', 
  'AP2210K-2.5TRE1DICT-ND', 
  'Active', 
  'Diodes Incorporated', 
  '2.5V', 
  '2025-08-09T08:00:13.427', 
  '1', 
  '0.5V @ 300mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://www.diodes.com/assets/Datasheets/AP2210.pdf', 
  '180 µA', 
  'DIODES SOT-23-5 K', 
  '75dB (100Hz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  'Enable', 
  '-', 
  '0.07', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - DIODES INC AP2210-ADJ.SchLib', 
  'Over Current, Over Temperature, Reverse Polarity', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - DIODES SOT-23-5 K.PCBLIB'
);

INSERT INTO "altium"."VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LINEAR 5V 300MA SOT23-5', 
  'AP2210K-5.0TRG1', 
  'https://www.digikey.com/en/products/detail/diodes-incorporated/AP2210K-5-0TRG1/4470820', 
  'Fixed', 
  '13.2V', 
  '300mA', 
  '15 mA', 
  'Positive', 
  'SOT-23-5', 
  '1', 
  'SC-74A, SOT-753', 
  'DIODES INC AP2210-ADJ', 
  'AP2210K-5.0TRG1DICT-ND', 
  'Active', 
  'Diodes Incorporated', 
  '5V', 
  '2025-08-09T08:00:13.443', 
  '1', 
  '0.5V @ 300mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://www.diodes.com/assets/Datasheets/AP2210.pdf', 
  '180 µA', 
  'DIODES SOT-23-5 K', 
  '75dB (100Hz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  'Enable', 
  '-', 
  '0.10', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - DIODES INC AP2210-ADJ.SchLib', 
  'Over Current, Over Temperature, Reverse Polarity', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - DIODES SOT-23-5 K.PCBLIB'
);

INSERT INTO "altium"."VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LINEAR 3.3V 300MA SOT23-5', 
  'AP2210K-3.3TRG1', 
  'https://www.digikey.com/en/products/detail/diodes-incorporated/AP2210K-3-3TRG1/4470819', 
  'Fixed', 
  '13.2V', 
  '300mA', 
  '15 mA', 
  'Positive', 
  'SOT-23-5', 
  '1', 
  'SC-74A, SOT-753', 
  'DIODES INC AP2210-ADJ', 
  'AP2210K-3.3TRG1DICT-ND', 
  'Active', 
  'Diodes Incorporated', 
  '3.3V', 
  '2025-08-09T08:00:13.457', 
  '1', 
  '0.5V @ 300mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://www.diodes.com/assets/Datasheets/AP2210.pdf', 
  '180 µA', 
  'DIODES SOT-23-5 K', 
  '75dB (100Hz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  'Enable', 
  '-', 
  '0.07', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - DIODES INC AP2210-ADJ.SchLib', 
  'Over Current, Over Temperature, Reverse Polarity', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - DIODES SOT-23-5 K.PCBLIB'
);

INSERT INTO "altium"."VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LINEAR 3V 300MA SOT23-5', 
  'AP2210K-3.0TRG1', 
  'https://www.digikey.com/en/products/detail/diodes-incorporated/AP2210K-3-0TRG1/4470817', 
  'Fixed', 
  '13.2V', 
  '300mA', 
  '15 mA', 
  'Positive', 
  'SOT-23-5', 
  '1', 
  'SC-74A, SOT-753', 
  'DIODES INC AP2210-ADJ', 
  'AP2210K-3.0TRG1DICT-ND', 
  'Active', 
  'Diodes Incorporated', 
  '3V', 
  '2025-08-09T08:00:13.463', 
  '1', 
  '0.5V @ 300mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://www.diodes.com/assets/Datasheets/AP2210.pdf', 
  '180 µA', 
  'DIODES SOT-23-5 K', 
  '75dB (100Hz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  'Enable', 
  '-', 
  '0.07', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - DIODES INC AP2210-ADJ.SchLib', 
  'Over Current, Over Temperature, Reverse Polarity', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - DIODES SOT-23-5 K.PCBLIB'
);

INSERT INTO "altium"."VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LINEAR 3.3V 300MA SOT23-3', 
  'AP2210N-3.3TRE1', 
  'https://www.digikey.com/en/products/detail/diodes-incorporated/AP2210N-3-3TRE1/4570643', 
  'Fixed', 
  '13.2V', 
  '300mA', 
  '15 mA', 
  'Positive', 
  'SOT-23-3', 
  '1', 
  'TO-236-3, SC-59, SOT-23-3', 
  'DIODES INC AP2210-FIXED', 
  'AP2210N-3.3TRE1DICT-ND', 
  'Active', 
  'Diodes Incorporated', 
  '3.3V', 
  '2025-08-09T08:00:40.987', 
  '1', 
  '0.5V @ 300mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://www.diodes.com/assets/Datasheets/AP2210.pdf', 
  '180 µA', 
  'DIODES SOT-23-3 N', 
  '75dB (100Hz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '-', 
  '0.22', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - DIODES INC AP2210-FIXED.SchLib', 
  'Over Current, Over Temperature, Reverse Polarity', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - DIODES SOT-23-3 N.PCBLIB'
);

INSERT INTO "altium"."VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LIN POS ADJ 300MA SOT23-5', 
  'AP2210K-ADJTRG1', 
  'https://www.digikey.com/en/products/detail/diodes-incorporated/AP2210K-ADJTRG1/4470821', 
  'Adjustable', 
  '13.2V', 
  '300mA', 
  '15 mA', 
  'Positive', 
  'SOT-23-5', 
  '1', 
  'SC-74A, SOT-753', 
  'DIODES INC AP2210-ADJ', 
  'AP2210K-ADJTRG1DICT-ND', 
  'Active', 
  'Diodes Incorporated', 
  '1.25V', 
  '2025-08-09T08:01:34.173', 
  '1', 
  '0.5V @ 300mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://www.diodes.com/assets/Datasheets/AP2210.pdf', 
  '180 µA', 
  'DIODES SOT-23-5 K', 
  '75dB (100Hz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '12.7V', 
  'Enable', 
  '-', 
  '0.11', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - DIODES INC AP2210-ADJ.SchLib', 
  'Over Current, Over Temperature, Reverse Polarity', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - DIODES SOT-23-5 K.PCBLIB'
);

