--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Gain Bandwidth Product",
  "Current - Input Bias",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "ComponentLink2Description",
  "Current - Output / Channel",
  "Footprint Path"
)
VALUES (
  'IC OPAMP 1 CIRCUIT SOT-23-5', 
  'LMV321B-TR', 
  'https://www.digikey.com/en/products/detail/3peak/LMV321B-TR/22228606', 
  'Single Ended, Rail-to-Rail', 
  '1 MHz', 
  '1 pA', 
  'SOT-23-5', 
  '3PEAK LMV321B', 
  '5503-LMV321B-TRCT-ND', 
  'Active', 
  '3PEAK', 
  '2025-08-09T06:49:16.863', 
  '1', 
  'Standard', 
  '93', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://file.3peakic.com.cn:8080/product/Datasheet_LMV321B-LMV358B-LMV324B.pdf', 
  '3PEAK SOT23-5 S5T SOT23-5-A', 
  'Datasheet', 
  '0.7V/µs', 
  'DigiKey', 
  '80µA', 
  'Surface Mount', 
  '1', 
  '2 mV', 
  'LMV321B', 
  '0.04', 
  'symbols/Opamp/SCH - OPAMP - 3PEAK LMV321B.SCHLIB', 
  'TapeAndReel', 
  'DigiKey Link', 
  '100 mA', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - 3PEAK SOT23-5 S5T SOT23-5-A.PcbLib'
);

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Gain Bandwidth Product",
  "Current - Input Bias",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "ComponentLink2Description",
  "Current - Output / Channel",
  "Footprint Path"
)
VALUES (
  'IC OPAMP 1 CIRCUIT SOT-353', 
  'LMV321B-CR', 
  'https://www.digikey.com/en/products/detail/3peak/LMV321B-CR/22229648', 
  'Single Ended, Rail-to-Rail', 
  '1 MHz', 
  '1 pA', 
  'SOT-353 (SC-70-5)', 
  '3PEAK LMV321B', 
  '5503-LMV321B-CRCT-ND', 
  'Active', 
  '3PEAK', 
  '2025-08-09T06:50:28.713', 
  '1', 
  'Standard', 
  '94', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://file.3peakic.com.cn:8080/product/Datasheet_LMV321B-LMV358B-LMV324B.pdf', 
  '3PEAK SC5 SOT353-5-A', 
  'Datasheet', 
  '0.7V/µs', 
  'DigiKey', 
  '80µA', 
  'Surface Mount', 
  '1', 
  '2 mV', 
  'LMV321B', 
  '0.04', 
  'symbols/Opamp/SCH - OPAMP - 3PEAK LMV321B.SCHLIB', 
  'TapeAndReel', 
  'DigiKey Link', 
  '100 mA', 
  'footprints/Leaded - SC-70/PCB - LEADED - SC-70 - 3PEAK SC5 SOT353-5-A.PcbLib'
);

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Gain Bandwidth Product",
  "Current - Input Bias",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "ComponentLink2Description",
  "Current - Output / Channel",
  "Footprint Path"
)
VALUES (
  'IC OPAMP 2 CIRCUIT 8-MSOP', 
  'LMV358B-VR', 
  'https://www.digikey.com/en/products/detail/3peak/LMV358B-VR/22229595', 
  'Single Ended, Rail-to-Rail', 
  '1 MHz', 
  '1 pA', 
  '8-MSOP', 
  '3PEAK LMV358B', 
  '5503-LMV358B-VRCT-ND', 
  'Active', 
  '3PEAK', 
  '2025-08-09T06:51:47.410', 
  '1', 
  'Standard (General Purpose)', 
  '95', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://file.3peakic.com.cn:8080/product/Datasheet_LMV321B-LMV358B-LMV324B.pdf', 
  '3PEAK MSOP8 VS1 MSOP-8-A', 
  'Datasheet', 
  '0.7V/µs', 
  'DigiKey', 
  '80µA (x2 Channels)', 
  'Surface Mount', 
  '2', 
  '2 mV', 
  'LMV358B', 
  '0.04', 
  'symbols/Opamp/SCH - OPAMP - 3PEAK LMV358B.SCHLIB', 
  'TapeAndReel', 
  'DigiKey Link', 
  '100 mA', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - 3PEAK MSOP8 VS1 MSOP-8-A.PcbLib'
);

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Gain Bandwidth Product",
  "Current - Input Bias",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "ComponentLink2Description",
  "Current - Output / Channel",
  "Footprint Path"
)
VALUES (
  'IC OPAMP 2 CIRCUIT 8-TSSOP', 
  'LMV358B-TSR', 
  'https://www.digikey.com/en/products/detail/3peak/LMV358B-TSR/22229370', 
  'Single Ended, Rail-to-Rail', 
  '1 MHz', 
  '1 pA', 
  '8-TSSOP', 
  '3PEAK LMV358B', 
  '5503-LMV358B-TSRCT-ND', 
  'Active', 
  '3PEAK', 
  '2025-08-09T06:51:59.837', 
  '1', 
  'Standard', 
  '96', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://file.3peakic.com.cn:8080/product/Datasheet_LMV321B-LMV358B-LMV324B.pdf', 
  '3PEAK TSSOP8 TS1 TSSOP-8-A', 
  'Datasheet', 
  '0.7V/µs', 
  'DigiKey', 
  '80µA (x2 Channels)', 
  'Surface Mount', 
  '2', 
  '2 mV', 
  'LMV358B', 
  '0.04', 
  'symbols/Opamp/SCH - OPAMP - 3PEAK LMV358B.SCHLIB', 
  'TapeAndReel', 
  'DigiKey Link', 
  '100 mA', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - 3PEAK TSSOP8 TS1 TSSOP-8-A.PcbLib'
);

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Gain Bandwidth Product",
  "Current - Input Bias",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "ComponentLink2Description",
  "Current - Output / Channel",
  "Footprint Path"
)
VALUES (
  'IC OPAMP 2 CIRCUIT 8-SOP', 
  'LMV358B-SR', 
  'https://www.digikey.com/en/products/detail/3peak/LMV358B-SR/22228681', 
  'Single Ended, Rail-to-Rail', 
  '1 MHz', 
  '1 pA', 
  '8-SOP', 
  '3PEAK LMV358B', 
  '5503-LMV358B-SRCT-ND', 
  'Active', 
  '3PEAK', 
  '2025-08-09T06:52:18.893', 
  '1', 
  'Standard', 
  '97', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://file.3peakic.com.cn:8080/product/Datasheet_LMV321B-LMV358B-LMV324B.pdf', 
  '3PEAK SOP8 SO1 SOP-8-A', 
  'Datasheet', 
  '0.7V/µs', 
  'DigiKey', 
  '80µA (x2 Channels)', 
  'Surface Mount', 
  '2', 
  '2 mV', 
  'LMV358B', 
  '0.04', 
  'symbols/Opamp/SCH - OPAMP - 3PEAK LMV358B.SCHLIB', 
  'TapeAndReel', 
  'DigiKey Link', 
  '100 mA', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - 3PEAK SOP8 SO1 SOP-8-A.PcbLib'
);

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Gain Bandwidth Product",
  "Current - Input Bias",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "ComponentLink2Description",
  "Current - Output / Channel",
  "Footprint Path"
)
VALUES (
  'IC OPAMP 4 CIRCUIT 14-TSSOP', 
  'LMV324B-TR', 
  'https://www.digikey.com/en/products/detail/3peak/LMV324B-TR/22169040', 
  'Single Ended, Rail-to-Rail', 
  '1 MHz', 
  '1 pA', 
  '14-TSSOP', 
  '3PEAK LMV324B', 
  '5503-LMV324B-TRCT-ND', 
  'Active', 
  '3PEAK', 
  '2025-08-09T06:53:23.287', 
  '1', 
  'Standard', 
  '98', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://file.3peakic.com.cn:8080/product/Datasheet_LM321A-LM358A-LM324A.pdf', 
  '3PEAK TSSOP14 TS2 TSSOP-14-A', 
  'Datasheet', 
  '0.7V/µs', 
  'DigiKey', 
  '80µA (x4 Channels)', 
  'Surface Mount', 
  '4', 
  '2 mV', 
  '-', 
  '0.05', 
  'symbols/Opamp/SCH - OPAMP - 3PEAK LMV324B.SCHLIB', 
  'TapeAndReel', 
  'DigiKey Link', 
  '100 mA', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - 3PEAK TSSOP14 TS2 TSSOP-14-A.PcbLib'
);

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Gain Bandwidth Product",
  "Current - Input Bias",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "ComponentLink2Description",
  "Current - Output / Channel",
  "Footprint Path"
)
VALUES (
  'IC OPAMP 4 CIRCUIT 14-SOP', 
  'LMV324B-SR', 
  'https://www.digikey.com/en/products/detail/3peak/LMV324B-SR/22228395', 
  'Single Ended, Rail-to-Rail', 
  '1 MHz', 
  '1 pA', 
  '14-SOP', 
  '3PEAK LMV324B', 
  '5503-LMV324B-SRCT-ND', 
  'Active', 
  '3PEAK', 
  '2025-08-09T06:53:44.887', 
  '1', 
  'Standard', 
  '99', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://file.3peakic.com.cn:8080/product/Datasheet_LMV321B-LMV358B-LMV324B.pdf', 
  '3PEAK SOP14 SO2 SOP-14-A', 
  'Datasheet', 
  '0.7V/µs', 
  'DigiKey', 
  '80µA (x4 Channels)', 
  'Surface Mount', 
  '4', 
  '2 mV', 
  'LMV324B', 
  '0.05', 
  'symbols/Opamp/SCH - OPAMP - 3PEAK LMV324B.SCHLIB', 
  'TapeAndReel', 
  'DigiKey Link', 
  '100 mA', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - 3PEAK SOP14 SO2 SOP-14-A.PcbLib'
);

