--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMT0402220', 
  'NRC04J221TRF', 
  'https://www.digikey.com/en/products/detail/nic-components-corp/NRC04J221TRF/18896002', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '4988-NRC04J221TRFCT-ND', 
  'Active', 
  'NIC Components Corp', 
  'Automotive AEC-Q200', 
  '2023-08-24T19:22:03.250', 
  '1', 
  '80744', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.niccomp.com/quickbuilder/qbpn.php?pNumber=NRC04J221TRF', 
  'RES 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '220 Ohms', 
  '0.063W, 1/16W', 
  'NRC', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  '220 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 1K OHM 1% 1/16W 0402', 
  'NRC04F1001TRF', 
  'https://www.digikey.com/en/products/detail/nic-components-corp/NRC04F1001TRF/18724523', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '4988-NRC04F1001TRFCT-ND', 
  'Active', 
  'NIC Components Corp', 
  'Automotive AEC-Q200', 
  '2023-08-24T19:22:03.287', 
  '1', 
  '80745', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://media.digikey.com/pdf/Data%20Sheets/Nic%20Components%20PDFs/NRC%20Series.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '1 kOhms', 
  '0.063W, 1/16W', 
  'NRC', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  '1 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'SULFUR TOLERANT CHIP RESISTORS:', 
  'SFR01MZPJ9R1', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SFR01MZPJ9R1/19530903', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '-250/ +500ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '511-SFR01MZPJ9R1CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Anti-Sulfur, Automotive AEC-Q200', 
  '2023-08-24T19:22:03.313', 
  '1', 
  '80746', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/sfr-e.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '9.1 Ohms', 
  '0.063W, 1/16W', 
  'SFR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '9.1 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'SULFUR TOLERANT CHIP RESISTORS:', 
  'SFR01MZPJ825', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SFR01MZPJ825/19531010', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '511-SFR01MZPJ825CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Anti-Sulfur, Automotive AEC-Q200', 
  '2023-08-24T19:22:03.337', 
  '1', 
  '80747', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/sfr-e.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '8.2 MOhms', 
  '0.063W, 1/16W', 
  'SFR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '8.2 MOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'SULFUR TOLERANT CHIP RESISTORS:', 
  'SFR01MZPJ7R5', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SFR01MZPJ7R5/19530921', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '-250/ +500ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '511-SFR01MZPJ7R5CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Anti-Sulfur, Automotive AEC-Q200', 
  '2023-08-24T19:22:03.363', 
  '1', 
  '80748', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/sfr-e.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '7.5 Ohms', 
  '0.063W, 1/16W', 
  'SFR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '7.5 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'SULFUR TOLERANT CHIP RESISTORS:', 
  'SFR01MZPJ6R2', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SFR01MZPJ6R2/19530882', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '-250/ +500ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '511-SFR01MZPJ6R2CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Anti-Sulfur, Automotive AEC-Q200', 
  '2023-08-24T19:22:03.383', 
  '1', 
  '80749', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/sfr-e.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '6.2 Ohms', 
  '0.063W, 1/16W', 
  'SFR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '6.2 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 180K OHM 1% 1/16W 0402', 
  'RT0402FRE07180KL', 
  'https://www.digikey.com/en/products/detail/yageo/RT0402FRE07180KL/1071806', 
  '0.014" (0.35mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±50ppm/°C', 
  '0402', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '13-RT0402FRE07180KLCT-ND', 
  'Active', 
  'Yageo', 
  '2023-08-24T19:22:03.400', 
  '1', 
  '80750', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/968/RT.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '180 kOhms', 
  '0.063W, 1/16W', 
  'RT', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '180 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 147K OHM 1% 1/16W 0402', 
  'RT0402FRE07147KL', 
  'https://www.digikey.com/en/products/detail/yageo/RT0402FRE07147KL/1071762', 
  '0.014" (0.35mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±50ppm/°C', 
  '0402', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '13-RT0402FRE07147KLCT-ND', 
  'Active', 
  'Yageo', 
  '2023-08-24T19:22:03.417', 
  '1', 
  '80751', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/968/RT.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '147 kOhms', 
  '0.063W, 1/16W', 
  'RT', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '147 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 8.45K OHM 0.1% 1/16W 0402', 
  'RP0402BRD078K45L', 
  'https://www.digikey.com/en/products/detail/yageo/RP0402BRD078K45L/16916511', 
  '0.014" (0.35mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±25ppm/°C', 
  '0402', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '13-RP0402BRD078K45LCT-ND', 
  'Active', 
  'Yageo', 
  'Anti-Sulfur, Automotive AEC-Q200, Moisture Resistant', 
  '2023-08-24T19:22:03.423', 
  '1', 
  '80752', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.yageo.com/upload/media/product/products/datasheet/rchip/PYu-RP_51_RoHS_L_0.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±0.1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '8.45 kOhms', 
  '0.063W, 1/16W', 
  'RP', 
  '0.06', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '8.45 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 30.9K OHM 1% 1/16W 0402', 
  'RT0402FRE0730K9L', 
  'https://www.digikey.com/en/products/detail/yageo/RT0402FRE0730K9L/1071947', 
  '0.014" (0.35mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±50ppm/°C', 
  '0402', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '13-RT0402FRE0730K9LCT-ND', 
  'Active', 
  'Yageo', 
  '2023-08-24T19:22:03.440', 
  '1', 
  '80753', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.yageo.com/upload/media/product/productsearch/datasheet/rchip/PYu-RT_1-to-0.01_RoHS_L_13.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '30.9 kOhms', 
  '0.063W, 1/16W', 
  'RT', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '30.9 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 18.2K OHM 1% 1/16W 0402', 
  'RT0402FRE0718K2L', 
  'https://www.digikey.com/en/products/detail/yageo/RT0402FRE0718K2L/1071812', 
  '0.014" (0.35mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±50ppm/°C', 
  '0402', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '13-RT0402FRE0718K2LCT-ND', 
  'Active', 
  'Yageo', 
  '2023-08-24T19:22:03.453', 
  '1', 
  '80754', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.yageo.com/upload/media/product/productsearch/datasheet/rchip/PYu-RT_1-to-0.01_RoHS_L_13.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '18.2 kOhms', 
  '0.063W, 1/16W', 
  'RT', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '18.2 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 160K OHM 1% 1/16W 0402', 
  'RT0402FRE07160KL', 
  'https://www.digikey.com/en/products/detail/yageo/RT0402FRE07160KL/1071782', 
  '0.014" (0.35mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±50ppm/°C', 
  '0402', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '13-RT0402FRE07160KLCT-ND', 
  'Active', 
  'Yageo', 
  '2023-08-24T19:22:03.463', 
  '1', 
  '80755', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/968/RT.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '160 kOhms', 
  '0.063W, 1/16W', 
  'RT', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '160 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'SULFUR TOLERANT CHIP RESISTORS:', 
  'SFR01MZPJ8R2', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SFR01MZPJ8R2/19531134', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '-250/ +500ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '511-SFR01MZPJ8R2CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Anti-Sulfur, Automotive AEC-Q200', 
  '2023-08-24T19:22:03.470', 
  '1', 
  '80756', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/sfr-e.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '8.2 Ohms', 
  '0.063W, 1/16W', 
  'SFR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '8.2 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'SULFUR TOLERANT CHIP RESISTORS:', 
  'SFR01MZPJ2R4', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SFR01MZPJ2R4/19531053', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '-250/ +500ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '511-SFR01MZPJ2R4CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Anti-Sulfur, Automotive AEC-Q200', 
  '2023-08-24T19:22:03.480', 
  '1', 
  '80757', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/sfr-e.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '2.4 Ohms', 
  '0.063W, 1/16W', 
  'SFR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '2.4 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMT040233', 
  'NRC04J330TRF', 
  'https://www.digikey.com/en/products/detail/nic-components-corp/NRC04J330TRF/18895928', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '4988-NRC04J330TRFCT-ND', 
  'Active', 
  'NIC Components Corp', 
  'Automotive AEC-Q200', 
  '2023-08-24T19:22:03.487', 
  '1', 
  '80758', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.niccomp.com/quickbuilder/qbpn.php?pNumber=NRC04J330TRF', 
  'RES 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '33 Ohms', 
  '0.063W, 1/16W', 
  'NRC', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  '33 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMT04022.2K', 
  'NRC04J222TRF', 
  'https://www.digikey.com/en/products/detail/nic-components-corp/NRC04J222TRF/18895951', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '4988-NRC04J222TRFCT-ND', 
  'Active', 
  'NIC Components Corp', 
  'Automotive AEC-Q200', 
  '2023-08-24T19:22:03.527', 
  '1', 
  '80760', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.niccomp.com/quickbuilder/qbpn.php?pNumber=NRC04J222TRF', 
  'RES 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '2.2 kOhms', 
  '0.063W, 1/16W', 
  'NRC', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  '2.2 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMT0402100', 
  'NRC04F1000TRF', 
  'https://www.digikey.com/en/products/detail/nic-components-corp/NRC04F1000TRF/18895917', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '4988-NRC04F1000TRFCT-ND', 
  'Active', 
  'NIC Components Corp', 
  'Automotive AEC-Q200', 
  '2023-08-24T19:22:03.543', 
  '1', 
  '80761', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.niccomp.com/quickbuilder/qbpn.php?pNumber=NRC04F1000TRF', 
  'RES 0402_1005', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '100 Ohms', 
  '0.063W, 1/16W', 
  'NRC', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  '100 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMT04024.99K', 
  'NRC04F4991TRF', 
  'https://www.digikey.com/en/products/detail/nic-components-corp/NRC04F4991TRF/18895958', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '4988-NRC04F4991TRFCT-ND', 
  'Active', 
  'NIC Components Corp', 
  'Automotive AEC-Q200', 
  '2023-08-24T19:22:03.560', 
  '1', 
  '80762', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.niccomp.com/quickbuilder/qbpn.php?pNumber=NRC04F4991TRF', 
  'RES 0402_1005', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '4.99 kOhms', 
  '0.063W, 1/16W', 
  'NRC', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  '4.99 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMT040249.9', 
  'NRC04F49R9TRF', 
  'https://www.digikey.com/en/products/detail/nic-components-corp/NRC04F49R9TRF/18896019', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '4988-NRC04F49R9TRFCT-ND', 
  'Active', 
  'NIC Components Corp', 
  'Automotive AEC-Q200', 
  '2023-08-24T19:22:03.577', 
  '1', 
  '80763', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.niccomp.com/quickbuilder/qbpn.php?pNumber=NRC04F49R9TRF', 
  'RES 0402_1005', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '49.9 Ohms', 
  '0.063W, 1/16W', 
  'NRC', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  '49.9 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMT0402100K', 
  'NRC04J104TRF', 
  'https://www.digikey.com/en/products/detail/nic-components-corp/NRC04J104TRF/18895911', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '4988-NRC04J104TRFCT-ND', 
  'Active', 
  'NIC Components Corp', 
  'Automotive AEC-Q200', 
  '2023-08-24T19:22:03.593', 
  '1', 
  '80764', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.niccomp.com/quickbuilder/qbpn.php?pNumber=NRC04J104TRF', 
  'RES 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '100 kOhms', 
  '0.063W, 1/16W', 
  'NRC', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  '100 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMT0402240', 
  'NRC04F2400TRF', 
  'https://www.digikey.com/en/products/detail/nic-components-corp/NRC04F2400TRF/18896086', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '4988-NRC04F2400TRFCT-ND', 
  'Active', 
  'NIC Components Corp', 
  'Automotive AEC-Q200', 
  '2023-08-24T19:22:03.600', 
  '1', 
  '80765', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.niccomp.com/quickbuilder/qbpn.php?pNumber=NRC04F2400TRF', 
  'RES 0402_1005', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '240 Ohms', 
  '0.063W, 1/16W', 
  'NRC', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  '240 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RCA0402 100R 5% 200 ET7 E3', 
  'RCA0402100RJNED', 
  'https://www.digikey.com/en/products/detail/vishay-dale/RCA0402100RJNED/19522971', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '541-RCA0402100RJNEDCT-ND', 
  'Active', 
  'Vishay Dale', 
  'Anti-Sulfur, Automotive AEC-Q200', 
  '2023-08-24T19:22:03.613', 
  '1', 
  '80766', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.vishay.com/docs/20037/rcae3.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '100 Ohms', 
  '0.063W, 1/16W', 
  'RCA', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '100 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 100K OHM 1% 1/16W 0402', 
  'NRC04F1003TRF', 
  'https://www.digikey.com/en/products/detail/nic-components-corp/NRC04F1003TRF/18724524', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '4988-NRC04F1003TRFCT-ND', 
  'Active', 
  'NIC Components Corp', 
  'Automotive AEC-Q200', 
  '2023-08-24T19:22:03.627', 
  '1', 
  '80767', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://media.digikey.com/pdf/Data%20Sheets/Nic%20Components%20PDFs/NRC%20Series.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '100 kOhms', 
  '0.063W, 1/16W', 
  'NRC', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  '100 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 1.96M OHM 1% 1/16W 0402', 
  'RC0402FR-071M96L', 
  'https://www.digikey.com/en/products/detail/yageo/RC0402FR-071M96L/5917584', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0402', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '13-RC0402FR-071M96LCT-ND', 
  'Active', 
  'Yageo', 
  'Moisture Resistant', 
  '2023-08-24T19:22:03.643', 
  '1', 
  '80768', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.yageo.com/upload/media/product/productsearch/datasheet/rchip/PYu-RC_Group_51_RoHS_L_12.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '1.96 MOhms', 
  '0.063W, 1/16W', 
  'RC_L', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  '1.96 MOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'THIN FILM RES SMD 49.9K OHM 0.1%', 
  'PTN0402E4992BST1', 
  'https://www.digikey.com/en/products/detail/vishay-dale-thin-film/PTN0402E4992BST1/14564702', 
  '0.033" (0.84mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±25ppm/°C', 
  '0402', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '764-PTN0402E4992BST1CT-ND', 
  'Active', 
  'Vishay Dale Thin Film', 
  'Anti-Sulfur, Moisture Resistant, Non-Inductive', 
  '2023-08-24T19:22:03.663', 
  '1', 
  '80769', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.vishay.com/docs/60026/ptn.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±0.1%', 
  'DigiKey', 
  '0.042" L x 0.022" W (1.07mm x 0.56mm)', 
  '49.9 kOhms', 
  '0.05W, 1/20W', 
  'PTN', 
  '0.20', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '49.9 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMT04024.02K', 
  'NRC04F4021TRF', 
  'https://www.digikey.com/en/products/detail/nic-components-corp/NRC04F4021TRF/18895879', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '4988-NRC04F4021TRFCT-ND', 
  'Active', 
  'NIC Components Corp', 
  'Automotive AEC-Q200', 
  '2023-08-24T19:22:03.680', 
  '1', 
  '80770', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.niccomp.com/quickbuilder/qbpn.php?pNumber=NRC04F4021TRF', 
  'RES 0402_1005', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '4.02 kOhms', 
  '0.063W, 1/16W', 
  'NRC', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  '4.02 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMT04024.75K', 
  'NRC04F4751TRF', 
  'https://www.digikey.com/en/products/detail/nic-components-corp/NRC04F4751TRF/18896063', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '4988-NRC04F4751TRFCT-ND', 
  'Active', 
  'NIC Components Corp', 
  'Automotive AEC-Q200', 
  '2023-08-24T19:22:03.687', 
  '1', 
  '80771', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.niccomp.com/quickbuilder/qbpn.php?pNumber=NRC04F4751TRF', 
  'RES 0402_1005', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '4.75 kOhms', 
  '0.063W, 1/16W', 
  'NRC', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  '4.75 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'ANTI-SURGE CHIP RESISTORS: ROHM''', 
  'ESR01MZPJ8R2', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/ESR01MZPJ8R2/19531034', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '-250/ +500ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '511-ESR01MZPJ8R2CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-08-24T19:22:03.697', 
  '1', 
  '80772', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/esr-e.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '8.2 Ohms', 
  '0.2W, 1/5W', 
  'ESR', 
  '0.03', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '8.2 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'ANTI-SURGE CHIP RESISTORS: ROHM''', 
  'ESR01MZPJ7R5', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/ESR01MZPJ7R5/19530862', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '-250/ +500ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '511-ESR01MZPJ7R5CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-08-24T19:22:03.713', 
  '1', 
  '80773', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/esr-e.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '7.5 Ohms', 
  '0.2W, 1/5W', 
  'ESR', 
  '0.03', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '7.5 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'ANTI-SURGE CHIP RESISTORS: ROHM''', 
  'ESR01MZPJ685', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/ESR01MZPJ685/19530857', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '511-ESR01MZPJ685CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-08-24T19:22:03.720', 
  '1', 
  '80774', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/esr-e.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '6.8 MOhms', 
  '0.2W, 1/5W', 
  'ESR', 
  '0.03', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '6.8 MOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 7.15M OHM 1% 1/16W 0402', 
  'CRCW04027M15FKED', 
  'https://www.digikey.com/en/products/detail/vishay-dale/CRCW04027M15FKED/2555951', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '541-CRCW04027M15FKEDCT-ND', 
  'Active', 
  'Vishay Dale', 
  'Automotive AEC-Q200', 
  '2023-08-24T19:22:03.737', 
  '1', 
  '80775', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.vishay.com/docs/20035/dcrcwe3.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '7.15 MOhms', 
  '0.063W, 1/16W', 
  'CRCW', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  '7.15 MOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 18K OHM 0.1% 1/16W 0402', 
  'AT0402BRD0718KL', 
  'https://www.digikey.com/en/products/detail/yageo/AT0402BRD0718KL/16991265', 
  '0.014" (0.35mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±25ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '13-AT0402BRD0718KLCT-ND', 
  'Active', 
  'Yageo', 
  'Anti-Sulfur, Automotive AEC-Q200, Moisture Resistant', 
  '2023-08-24T19:22:03.757', 
  '1', 
  '80776', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.yageo.com/upload/media/product/productsearch/datasheet/rchip/PYu-AT_51_RoHS_L_6.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±0.1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '18 kOhms', 
  '0.063W, 1/16W', 
  'AT', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '18 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 2.2K OHM 1% 1/16W 0402', 
  'AT0402FRE072K2L', 
  'https://www.digikey.com/en/products/detail/yageo/AT0402FRE072K2L/16990327', 
  '0.014" (0.35mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±50ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '13-AT0402FRE072K2LCT-ND', 
  'Active', 
  'Yageo', 
  'Anti-Sulfur, Automotive AEC-Q200, Moisture Resistant', 
  '2023-08-24T19:22:03.773', 
  '1', 
  '80777', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.yageo.com/upload/media/product/productsearch/datasheet/rchip/PYu-AT_51_RoHS_L_6.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '2.2 kOhms', 
  '0.063W, 1/16W', 
  'AT', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '2.2 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 249 OHM 1% 1/16W 0402', 
  'AF0402FR-07249RL', 
  'https://www.digikey.com/en/products/detail/yageo/AF0402FR-07249RL/17009110', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '13-AF0402FR-07249RLCT-ND', 
  'Active', 
  'Yageo', 
  'Anti-Sulfur, Automotive AEC-Q200, Moisture Resistant', 
  '2023-08-24T19:22:03.790', 
  '1', 
  '80778', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.yageo.com/upload/media/product/productsearch/datasheet/rchip/PYu-AF_51_RoHS_L_9.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '249 Ohms', 
  '0.063W, 1/16W', 
  'AF', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '249 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 100 OHM 5% 1/16W 0402', 
  'AF0402JR-07100RL', 
  'https://www.digikey.com/en/products/detail/yageo/AF0402JR-07100RL/5900708', 
  '0.015" (0.37mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '13-AF0402JR-07100RLCT-ND', 
  'Active', 
  'Yageo', 
  'Anti-Sulfur, Automotive AEC-Q200', 
  '2023-08-24T19:22:03.803', 
  '1', 
  '80779', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.yageo.com/upload/media/product/productsearch/datasheet/rchip/PYu-AF_51_RoHS_L_9.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '100 Ohms', 
  '0.063W, 1/16W', 
  'AF', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  '100 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 11K OHM 0.1% 1/16W 0402', 
  'AT0402BRD0711KL', 
  'https://www.digikey.com/en/products/detail/yageo/AT0402BRD0711KL/5905749', 
  '0.014" (0.35mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±25ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '13-AT0402BRD0711KLCT-ND', 
  'Active', 
  'Yageo', 
  'Anti-Sulfur, Automotive AEC-Q200, Moisture Resistant', 
  '2023-08-24T19:22:03.820', 
  '1', 
  '80780', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.yageo.com/upload/media/product/productsearch/datasheet/rchip/PYu-AT_51_RoHS_L_6.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±0.1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '11 kOhms', 
  '0.063W, 1/16W', 
  'AT', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  '11 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

