--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 7.5NH 250MA 0.55O', 
  'MCI0603TG7N5HHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TG7N5HHBPDG/20486590', 
  '12 @ 500MHz', 
  '0.013" (0.33mm)', 
  '250 mA', 
  '0201 (0603 Metric)', 
  '550mOhm Max', 
  '0201', 
  '7.5 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TG7N5HHBPDGCT-ND', 
  'Active', 
  '4.8GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:30:07.497', 
  '1', 
  'Ceramic', 
  '6688', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/derivates/3/002/756/976/MFG_CT0603CTF-39NJ_tmb.jpg', 
  'IND 0201_0603', 
  'Datasheet', 
  '±3%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TG', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '7.5 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 22NH 150MA 1.2OHM', 
  'MCI0603TG22NHHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TG22NHHBPDG/20486674', 
  '9 @ 500MHz', 
  '0.013" (0.33mm)', 
  '150 mA', 
  '0201 (0603 Metric)', 
  '1.2Ohm Max', 
  '0201', 
  '22 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TG22NHHBPDGCT-ND', 
  'Active', 
  '2.5GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:30:07.507', 
  '1', 
  'Ceramic', 
  '6689', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5382/MCI0603-TG%20Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±3%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TG', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '22 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 4.3NH 350MA 0.4OH', 
  'MCI0603TG4N3HHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TG4N3HHBPDG/20486601', 
  '12 @ 500MHz', 
  '0.013" (0.33mm)', 
  '350 mA', 
  '0201 (0603 Metric)', 
  '400mOhm Max', 
  '0201', 
  '4.3 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TG4N3HHBPDGCT-ND', 
  'Active', 
  '6.5GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:30:07.517', 
  '1', 
  'Ceramic', 
  '6690', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5382/MCI0603-TG%20Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±3%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TG', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '4.3 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 3.9NH 350MA 0.35O', 
  'MCI0603TG3N9BHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TG3N9BHBPDG/20486741', 
  '12 @ 500MHz', 
  '0.013" (0.33mm)', 
  '350 mA', 
  '0201 (0603 Metric)', 
  '350mOhm Max', 
  '0201', 
  '3.9 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TG3N9BHBPDGCT-ND', 
  'Active', 
  '6.5GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:30:07.523', 
  '1', 
  'Ceramic', 
  '6691', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5382/MCI0603-TG%20Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±0.1nH', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TG', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '3.9 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 18NH 200MA 1.0OHM', 
  'MCI0603TG18NJHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TG18NJHBPDG/20486608', 
  '11 @ 500MHz', 
  '0.013" (0.33mm)', 
  '200 mA', 
  '0201 (0603 Metric)', 
  '1Ohm Max', 
  '0201', 
  '18 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TG18NJHBPDGCT-ND', 
  'Active', 
  '2.8GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:30:07.533', 
  '1', 
  'Ceramic', 
  '6692', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5382/MCI0603-TG%20Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±5%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TG', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '18 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 12NH 250MA 0.75OH', 
  'MCI0603TG12NHHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TG12NHHBPDG/20486678', 
  '11 @ 500MHz', 
  '0.013" (0.33mm)', 
  '250 mA', 
  '0201 (0603 Metric)', 
  '750mOhm Max', 
  '0201', 
  '12 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TG12NHHBPDGCT-ND', 
  'Active', 
  '3.7GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:30:07.550', 
  '1', 
  'Ceramic', 
  '6693', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5382/MCI0603-TG%20Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±3%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TG', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '12 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 2.7NH 450MA 0.25O', 
  'MCI0603TG2N7BHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TG2N7BHBPDG/20486740', 
  '12 @ 500MHz', 
  '0.013" (0.33mm)', 
  '450 mA', 
  '0201 (0603 Metric)', 
  '250mOhm Max', 
  '0201', 
  '2.7 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TG2N7BHBPDGCT-ND', 
  'Active', 
  '11GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:30:07.563', 
  '1', 
  'Ceramic', 
  '6694', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5382/MCI0603-TG%20Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±0.1nH', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TG', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '2.7 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 10NH 250MA 0.7OHM', 
  'MCI0603TG10NHHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TG10NHHBPDG/20486724', 
  '11 @ 500MHz', 
  '0.013" (0.33mm)', 
  '250 mA', 
  '0201 (0603 Metric)', 
  '700mOhm Max', 
  '0201', 
  '10 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TG10NHHBPDGCT-ND', 
  'Active', 
  '4GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:30:07.580', 
  '1', 
  'Ceramic', 
  '6695', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5382/MCI0603-TG%20Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±3%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TG', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '10 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 8.2NH 250MA 0.62O', 
  'MCI0603TG8N2HHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TG8N2HHBPDG/20486675', 
  '12 @ 500MHz', 
  '0.013" (0.33mm)', 
  '250 mA', 
  '0201 (0603 Metric)', 
  '620mOhm Max', 
  '0201', 
  '8.2 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TG8N2HHBPDGCT-ND', 
  'Active', 
  '4.8GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:30:07.597', 
  '1', 
  'Ceramic', 
  '6696', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5382/MCI0603-TG%20Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±3%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TG', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '8.2 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 5.1NH 350MA 0.4OH', 
  'MCI0603TM5N1HHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TM5N1HHBPDG/20486645', 
  '14 @ 500MHz', 
  '0.013" (0.33mm)', 
  '350 mA', 
  '0201 (0603 Metric)', 
  '400mOhm Max', 
  '0201', 
  '5.1 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TM5N1HHBPDGCT-ND', 
  'Active', 
  '4.2GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:30:07.603', 
  '1', 
  'Ceramic', 
  '6697', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5382/MCI0603-TM%20Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±3%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TM', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '5.1 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 5.1NH 350MA 0.4OH', 
  'MCI0603TG5N1HHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TG5N1HHBPDG/20486634', 
  '12 @ 500MHz', 
  '0.013" (0.33mm)', 
  '350 mA', 
  '0201 (0603 Metric)', 
  '400mOhm Max', 
  '0201', 
  '5.1 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TG5N1HHBPDGCT-ND', 
  'Active', 
  '6.5GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:30:07.610', 
  '1', 
  'Ceramic', 
  '6698', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5382/MCI0603-TG%20Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±3%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TG', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '5.1 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 6.2NH 300MA 0.5OH', 
  'MCI0603TG6N2HHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TG6N2HHBPDG/20486624', 
  '12 @ 500MHz', 
  '0.013" (0.33mm)', 
  '300 mA', 
  '0201 (0603 Metric)', 
  '500mOhm Max', 
  '0201', 
  '6.2 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TG6N2HHBPDGCT-ND', 
  'Active', 
  '6GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:30:07.617', 
  '1', 
  'Ceramic', 
  '6699', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5382/MCI0603-TG%20Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±3%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TG', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '6.2 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 3.6NH 400MA 0.3OH', 
  'MCI0603TG3N6BHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TG3N6BHBPDG/20486609', 
  '12 @ 500MHz', 
  '0.013" (0.33mm)', 
  '400 mA', 
  '0201 (0603 Metric)', 
  '300mOhm Max', 
  '0201', 
  '3.6 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TG3N6BHBPDGCT-ND', 
  'Active', 
  '8GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:30:07.633', 
  '1', 
  'Ceramic', 
  '6700', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5382/MCI0603-TG%20Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±0.1nH', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TG', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '3.6 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0603 3.3NH 400MA 0.3OH', 
  'MCI0603TG3N3BHBPDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/MCI0603TG3N3BHBPDG/20486652', 
  '12 @ 500MHz', 
  '0.013" (0.33mm)', 
  '400 mA', 
  '0201 (0603 Metric)', 
  '300mOhm Max', 
  '0201', 
  '3.3 nH', 
  '0201 (0603 Metric)', 
  'INDUCTOR', 
  '3526-MCI0603TG3N3BHBPDGCT-ND', 
  'Active', 
  '9.5GHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:30:07.647', 
  '1', 
  'Ceramic', 
  '6701', 
  '=Value', 
  '-55°C ~ 125°C', 
  '500 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5382/MCI0603-TG%20Series.pdf', 
  'IND 0201_0603', 
  'Datasheet', 
  '±0.1nH', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'MCI-TG', 
  'Multilayer', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '3.3 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0201_0603.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 4.4NH 750MA 0.07OHM SM', 
  'LQW15AN4N4B00D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/LQW15AN4N4B00D/10693880', 
  '25 @ 250MHz', 
  '0.024" (0.60mm)', 
  '750 mA', 
  '0402 (1005 Metric)', 
  '70mOhm Max', 
  '4.4 nH', 
  '0402 (1005 Metric)', 
  'INDUCTOR', 
  '490-LQW15AN4N4B00DCT-ND', 
  'Active', 
  '8GHz', 
  'Murata Electronics', 
  '2023-08-24T20:33:23.173', 
  '1', 
  'Non-Magnetic', 
  '6702', 
  '=Value', 
  '-55°C ~ 125°C', 
  '100 MHz', 
  'https://search.murata.co.jp/Ceramy/image/img/P02/JELF243A-0050.pdf', 
  'IND 0402_1005', 
  'Datasheet', 
  '±0.1nH', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.039" L x 0.024" W (1.00mm x 0.60mm)', 
  'LQW15', 
  'Drum Core, Wirewound', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '4.4 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0402_1005.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Ratings",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 0.7NH 1.2A 30 MOHM SMD', 
  'LQG15WZ0N7B02D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/LQG15WZ0N7B02D/11690033', 
  '0.022" (0.55mm)', 
  '1.2 A', 
  '0402 (1005 Metric)', 
  '30mOhm Max', 
  '0402', 
  'AEC-Q200', 
  '0.7 nH', 
  '0402 (1005 Metric)', 
  'INDUCTOR', 
  '490-LQG15WZ0N7B02DCT-ND', 
  'Active', 
  '15GHz', 
  'Murata Electronics', 
  '2023-08-24T20:33:23.180', 
  '1', 
  '6703', 
  '=Value', 
  '-55°C ~ 125°C', 
  '100 MHz', 
  'https://search.murata.co.jp/Ceramy/image/img/P02/JELF243B-9117.pdf', 
  'IND 0402_1005', 
  'Datasheet', 
  '±0.1nH', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  'LQG15', 
  'Multilayer', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '0.7 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0402_1005.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Q @ Freq",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Ratings",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 18NH 400MA 0402', 
  'LQG15HH18NG02D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/LQG15HH18NG02D/16033377', 
  '8 @ 100MHz', 
  '0.022" (0.55mm)', 
  '400 mA', 
  '0402 (1005 Metric)', 
  '360mOhm Max', 
  '0402', 
  'AEC-Q200', 
  '18 nH', 
  '0402 (1005 Metric)', 
  'INDUCTOR', 
  '490-LQG15HH18NG02DCT-ND', 
  'Active', 
  '2.2GHz', 
  'Murata Electronics', 
  '2023-08-24T20:33:23.190', 
  '1', 
  'Air', 
  '6704', 
  '=Value', 
  '-55°C ~ 125°C', 
  '100 MHz', 
  'https://search.murata.co.jp/Ceramy/image/img/P02/JELF243B-9101.pdf', 
  'IND 0402_1005', 
  'Datasheet', 
  '±2%', 
  'Unshielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  'LQG15', 
  'Multilayer', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '18 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0402_1005.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'POWER INDUCTOR 2016 4.7UH 20% DC', 
  'WIP201610S-4R7MLDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/WIP201610S-4R7MLDG/20486680', 
  '0.039" (1.00mm)', 
  '1.1 A', 
  '0806 (2016 Metric)', 
  '288mOhm Max', 
  '0806', 
  '4.7 µH', 
  '0806 (2016 Metric)', 
  'INDUCTOR', 
  '3526-WIP201610S-4R7MLDGCT-ND', 
  'Active', 
  '40MHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:35:06.280', 
  '1', 
  'Iron Powder', 
  '6705', 
  '=Value', 
  '-40°C ~ 125°C', 
  '1 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5383/WIP201610S%20L%20Series.pdf', 
  'IND 0806_2016', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.063" W (2.00mm x 1.60mm)', 
  'WIP201610S L', 
  'Wirewound', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '4.7 µH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0806_2016.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'POWER INDUCTOR 2016 0.68UH 20% D', 
  'WIP201610S-R68MLDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/WIP201610S-R68MLDG/20486633', 
  '0.039" (1.00mm)', 
  '3.5 A', 
  '0806 (2016 Metric)', 
  '47mOhm Max', 
  '0806', 
  '680 nH', 
  '0806 (2016 Metric)', 
  'INDUCTOR', 
  '3526-WIP201610S-R68MLDGCT-ND', 
  'Active', 
  '120MHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:35:06.290', 
  '1', 
  'Iron Powder', 
  '6706', 
  '=Value', 
  '-40°C ~ 125°C', 
  '1 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5383/WIP201610S%20L%20Series.pdf', 
  'IND 0806_2016', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.063" W (2.00mm x 1.60mm)', 
  'WIP201610S L', 
  'Wirewound', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '680 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0806_2016.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'POWER INDUCTOR 2016 0.1UH 20% DC', 
  'WIP201610S-R10MLDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/WIP201610S-R10MLDG/20486742', 
  '0.039" (1.00mm)', 
  '9 A', 
  '0806 (2016 Metric)', 
  '11mOhm Max', 
  '0806', 
  '100 nH', 
  '0806 (2016 Metric)', 
  'INDUCTOR', 
  '3526-WIP201610S-R10MLDGCT-ND', 
  'Active', 
  '120MHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:35:06.307', 
  '1', 
  'Iron Powder', 
  '6707', 
  '=Value', 
  '-40°C ~ 125°C', 
  '1 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5383/WIP201610S%20L%20Series.pdf', 
  'IND 0806_2016', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.063" W (2.00mm x 1.60mm)', 
  'WIP201610S L', 
  'Wirewound', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '100 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0806_2016.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'POWER INDUCTOR 2016 0.47UH 20% D', 
  'WIP201610Y-R47MLDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/WIP201610Y-R47MLDG/20486734', 
  '0.039" (1.00mm)', 
  '4.7 A', 
  '0806 (2016 Metric)', 
  '23mOhm Max', 
  '0806', 
  '470 nH', 
  '0806 (2016 Metric)', 
  'INDUCTOR', 
  '3526-WIP201610Y-R47MLDGCT-ND', 
  'Active', 
  '120MHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:35:06.323', 
  '1', 
  'Metal', 
  '6708', 
  '=Value', 
  '-40°C ~ 125°C', 
  '1 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5383/WIP201610Y%20Series.pdf', 
  'IND 0806_2016', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.063" W (2.00mm x 1.60mm)', 
  'WIP201610Y', 
  'Wirewound', 
  '0.10', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '470 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0806_2016.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'POWER INDUCTOR 2016 2.2UH 20% DC', 
  'WIP201610S-2R2MLDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/WIP201610S-2R2MLDG/20486614', 
  '0.039" (1.00mm)', 
  '2 A', 
  '0806 (2016 Metric)', 
  '140mOhm Max', 
  '0806', 
  '2.2 µH', 
  '0806 (2016 Metric)', 
  'INDUCTOR', 
  '3526-WIP201610S-2R2MLDGCT-ND', 
  'Active', 
  '60MHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:35:06.340', 
  '1', 
  'Iron Powder', 
  '6709', 
  '=Value', 
  '-40°C ~ 125°C', 
  '1 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5383/WIP201610S%20L%20Series.pdf', 
  'IND 0806_2016', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.063" W (2.00mm x 1.60mm)', 
  'WIP201610S L', 
  'Wirewound', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '2.2 µH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0806_2016.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'POWER INDUCTOR 2016 1.0UH 20% DC', 
  'WIP201610Y-1R0MLDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/WIP201610Y-1R0MLDG/20486571', 
  '0.039" (1.00mm)', 
  '3.1 A', 
  '0806 (2016 Metric)', 
  '44mOhm Max', 
  '0806', 
  '1 µH', 
  '0806 (2016 Metric)', 
  'INDUCTOR', 
  '3526-WIP201610Y-1R0MLDGCT-ND', 
  'Active', 
  '90MHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:35:06.353', 
  '1', 
  'Metal', 
  '6710', 
  '=Value', 
  '-40°C ~ 125°C', 
  '1 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5383/WIP201610Y%20Series.pdf', 
  'IND 0806_2016', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.063" W (2.00mm x 1.60mm)', 
  'WIP201610Y', 
  'Wirewound', 
  '0.10', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '1 µH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0806_2016.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'POWER INDUCTOR 2016 0.47UH 20% D', 
  'WIP201610S-R47MLDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/WIP201610S-R47MLDG/20486729', 
  '0.039" (1.00mm)', 
  '4.1 A', 
  '0806 (2016 Metric)', 
  '30mOhm Max', 
  '0806', 
  '470 nH', 
  '0806 (2016 Metric)', 
  'INDUCTOR', 
  '3526-WIP201610S-R47MLDGCT-ND', 
  'Active', 
  '120MHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:35:06.367', 
  '1', 
  'Iron Powder', 
  '6711', 
  '=Value', 
  '-40°C ~ 125°C', 
  '1 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5383/WIP201610S%20L%20Series.pdf', 
  'IND 0806_2016', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.063" W (2.00mm x 1.60mm)', 
  'WIP201610S L', 
  'Wirewound', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '470 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0806_2016.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'POWER INDUCTOR 2016 1.0UH 20% DC', 
  'WIP201610S-1R0MLDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/WIP201610S-1R0MLDG/20486697', 
  '0.039" (1.00mm)', 
  '3 A', 
  '0806 (2016 Metric)', 
  '60mOhm Max', 
  '0806', 
  '1 µH', 
  '0806 (2016 Metric)', 
  'INDUCTOR', 
  '3526-WIP201610S-1R0MLDGCT-ND', 
  'Active', 
  '90MHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:35:06.373', 
  '1', 
  'Iron Powder', 
  '6712', 
  '=Value', 
  '-40°C ~ 125°C', 
  '1 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5383/WIP201610S%20L%20Series.pdf', 
  'IND 0806_2016', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.063" W (2.00mm x 1.60mm)', 
  'WIP201610S L', 
  'Wirewound', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '1 µH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0806_2016.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'POWER INDUCTOR 2016 0.33UH 20% D', 
  'WIP201610S-R33MLDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/WIP201610S-R33MLDG/20486677', 
  '0.039" (1.00mm)', 
  '4.2 A', 
  '0806 (2016 Metric)', 
  '26mOhm Max', 
  '0806', 
  '330 nH', 
  '0806 (2016 Metric)', 
  'INDUCTOR', 
  '3526-WIP201610S-R33MLDGCT-ND', 
  'Active', 
  '120MHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:35:06.387', 
  '1', 
  'Iron Powder', 
  '6713', 
  '=Value', 
  '-40°C ~ 125°C', 
  '1 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5383/WIP201610S%20L%20Series.pdf', 
  'IND 0806_2016', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.063" W (2.00mm x 1.60mm)', 
  'WIP201610S L', 
  'Wirewound', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '330 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0806_2016.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'POWER INDUCTOR 2016 0.24UH 20% D', 
  'WIP201610S-R24MLDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/WIP201610S-R24MLDG/20486695', 
  '0.039" (1.00mm)', 
  '5.3 A', 
  '0806 (2016 Metric)', 
  '20mOhm Max', 
  '0806', 
  '240 nH', 
  '0806 (2016 Metric)', 
  'INDUCTOR', 
  '3526-WIP201610S-R24MLDGCT-ND', 
  'Active', 
  '120MHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:35:06.393', 
  '1', 
  'Iron Powder', 
  '6714', 
  '=Value', 
  '-40°C ~ 125°C', 
  '1 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5383/WIP201610S%20L%20Series.pdf', 
  'IND 0806_2016', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.063" W (2.00mm x 1.60mm)', 
  'WIP201610S L', 
  'Wirewound', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '240 nH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0806_2016.PCBLIB'
);

INSERT INTO "Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "DC Resistance (DCR)",
  "Supplier Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Frequency - Self Resonant",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'POWER INDUCTOR 2016 1.5UH 20% DC', 
  'WIP201610S-1R5MLDG', 
  'https://www.digikey.com/en/products/detail/inpaq-technology-co-ltd/WIP201610S-1R5MLDG/20486744', 
  '0.039" (1.00mm)', 
  '2.2 A', 
  '0806 (2016 Metric)', 
  '99mOhm Max', 
  '0806', 
  '1.5 µH', 
  '0806 (2016 Metric)', 
  'INDUCTOR', 
  '3526-WIP201610S-1R5MLDGCT-ND', 
  'Active', 
  '80MHz', 
  'INPAQ Technology Co., Ltd', 
  '2023-08-24T20:35:06.403', 
  '1', 
  'Iron Powder', 
  '6715', 
  '=Value', 
  '-40°C ~ 125°C', 
  '1 MHz', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5383/WIP201610S%20L%20Series.pdf', 
  'IND 0806_2016', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.063" W (2.00mm x 1.60mm)', 
  'WIP201610S L', 
  'Wirewound', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '1.5 µH', 
  'DigiKey Link', 
  'footprints/Passives/PCB - PASSIVES - IND 0806_2016.PCBLIB'
);

