--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Diodes-Rectifiers-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Diode Type",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Current - Average Rectified (Io)",
  "Operating Temperature - Junction",
  "PartId",
  "Comment",
  "Speed",
  "Capacitance @ Vr, F",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Dc Reverse (Vr) (Max)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE SCHOTTKY 30V 1A SOD323', 
  'PMEG3010BEA,135', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/PMEG3010BEA-135/4020502', 
  'Schottky', 
  'SOD-323', 
  'SC-76, SOD-323', 
  'DIODE', 
  '1727-PMEG3010BEA,135CT-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-02-06T21:03:07.157', 
  '1', 
  '1A', 
  '150°C (Max)', 
  '3440', 
  '=Part Number', 
  'Fast Recovery =< 500ns, > 200mA (Io)', 
  '70pF @ 1V, 1MHz', 
  'https://assets.nexperia.com/documents/data-sheet/PMEGXX10BEA_PMEGXX10BEV.pdf', 
  'SOD323', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '150 µA @ 30 V', 
  '-', 
  '0.08', 
  'symbols/Diodes/SCH - DIODES - DIODE.SCHLIB', 
  '560 mV @ 1 A', 
  'TapeAndReel', 
  'Active', 
  '30 V', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD323.PCBLIB'
);

