--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

UPDATE "Controller-Power-OR-andIdealDiodes"
SET
  "Applications" = 'Battery Backup, Industrial/Automotive, High Current Switch',
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.linear.com/docs/9037',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/linear-technology-analog-devices/LTC4414EMS8-PBF/LTC4414EMS8-PBF-ND/1620230',
  "Current - Supply" = '33µA',
  "Delay Time - OFF" = '20µs',
  "Delay Time - ON" = '600µs',
  "Description" = 'IC OR CTRLR SRC SELECT 8MSOP',
  "Device Package" = '8-TSSOP, 8-MSOP (0.118", 3.00mm Width)',
  "FET Type" = 'P-Channel',
  "Footprint Path" = 'footprints/Leaded - SOP/PCB - LEADED - SOP - ANALOG MSOP-8 RM-8.PCBLIB',
  "Footprint Ref" = 'ANALOG MSOP-8 RM-8',
  "Internal Switch(s)" = 'No',
  "LastUpdated" = '2020-02-02T11:30:25.917',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Linear Technology/Analog Devices',
  "Part Number" = 'LTC4414EMS8#PBF',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Operating Temperature" = '-40°C ~ 85°C',
  "Package / Case" = '8-TSSOP, 8-MSOP (0.118", 3.00mm Width)',
  "Packaging" = 'Tube',
  "Part Status" = 'Active',
  "Price" = '4.49',
  "Ratio - Input:Output" = '2:1',
  "Series" = 'PowerPath™',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'LTC4414EMS8#PBF-ND',
  "Supplier Device Package" = '8-MSOP',
  "Library Path" = 'symbols/Power - Controller/SCH - POWER - CONTROLLER - ANALOG LTC4414.SCHLIB',
  "Library Ref" = 'ANALOG LTC4414',
  "Type" = 'Source Selector Switch',
  "Voltage - Supply" = '3V ~ 36V'
WHERE ("Part Number" = 'LTC4414EMS8#PBF');

UPDATE "Controller-Power-OR-andIdealDiodes"
SET
  "Applications" = 'Battery Backup, Industrial/Automotive, High Current Switch',
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.linear.com/docs/9037',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/linear-technology-analog-devices/LTC4414IMS8-PBF/LTC4414IMS8-PBF-ND/1620227',
  "Current - Supply" = '31µA',
  "Delay Time - OFF" = '20µs',
  "Delay Time - ON" = '600µs',
  "Description" = 'IC OR CTRLR SRC SELECT 8MSOP',
  "Device Package" = '8-TSSOP, 8-MSOP (0.118", 3.00mm Width)',
  "FET Type" = 'P-Channel',
  "Footprint Path" = 'footprints/Leaded - SOP/PCB - LEADED - SOP - ANALOG MSOP-8 RM-8.PCBLIB',
  "Footprint Ref" = 'ANALOG MSOP-8 RM-8',
  "Internal Switch(s)" = 'No',
  "LastUpdated" = '2020-02-02T11:30:38.270',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Linear Technology/Analog Devices',
  "Part Number" = 'LTC4414IMS8#PBF',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Operating Temperature" = '-40°C ~ 125°C',
  "Package / Case" = '8-TSSOP, 8-MSOP (0.118", 3.00mm Width)',
  "Packaging" = 'Tube',
  "Part Status" = 'Active',
  "Price" = '4.97',
  "Ratio - Input:Output" = '2:1',
  "Series" = 'PowerPath™',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'LTC4414IMS8#PBF-ND',
  "Supplier Device Package" = '8-MSOP',
  "Library Path" = 'symbols/Power - Controller/SCH - POWER - CONTROLLER - ANALOG LTC4414.SCHLIB',
  "Library Ref" = 'ANALOG LTC4414',
  "Type" = 'Source Selector Switch',
  "Voltage - Supply" = '3V ~ 36V'
WHERE ("Part Number" = 'LTC4414IMS8#PBF');

