--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

UPDATE "Connectors-Coaxial-RF"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.molex.com/pdm_docs/sd/731000114_sd.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'https://www.digikey.com/en/products/detail/molex/0731000114/1465147',
  "Connector Style" = 'SMA',
  "Connector Type" = 'Receptacle, Female Socket',
  "Contact Termination" = 'Solder',
  "Description" = 'CONN SMA RCPT R/A 50 OHM PCB',
  "Fastening Type" = 'Threaded',
  "Footprint Path" = 'footprints/Connector - RF/PCB - CONNECTOR - RF - MOLEX SD-73100-0114.PCBLIB',
  "Footprint Ref" = 'MOLEX SD-73100-0114',
  "Frequency - Max" = '18 GHz',
  "Housing Color" = 'Gold',
  "Impedance" = '50Ohm',
  "LastUpdated" = '2022-06-29T18:00:23.737',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Molex',
  "Part Number" = '0731000114',
  "Minimum Order" = '1',
  "Mounting Type" = 'Through Hole, Right Angle',
  "Number of Ports" = '1',
  "Packaging" = 'Tray',
  "Part Status" = 'Active',
  "Price" = '3.19',
  "Series" = '73100',
  "Shield Termination" = 'Solder',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'WM5525-ND',
  "Library Path" = 'symbols/RF - Antenna/SCH - RF - ANTENNA - BASIC ANTENNA.SCHLIB',
  "Library Ref" = 'BASIC ANTENNA'
WHERE ("Part Number" = '0731000114');

UPDATE "Connectors-Coaxial-RF"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=1307191_BNC_Connectors&DocType=CS&DocLang=English',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'https://www.digikey.com/en/products/detail/te-connectivity-amp-connectors/5413631-1/811168',
  "Connector Style" = 'BNC',
  "Connector Type" = 'Jack, Female Socket',
  "Contact Termination" = 'Solder',
  "Description" = 'CONN BNC JACK R/A 50 OHM PCB',
  "Fastening Type" = 'Bayonet Lock',
  "Footprint Path" = 'footprints/Connector - TE/PCB - CONNECTOR - TE - TE 5413631-1.PCBLIB',
  "Footprint Ref" = 'TE 5413631-1',
  "Frequency - Max" = '4 GHz',
  "Housing Color" = 'Silver',
  "Impedance" = '50Ohm',
  "LastUpdated" = '2022-06-29T18:00:52.303',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'TE Connectivity AMP Connectors',
  "Part Number" = '5413631-1',
  "Minimum Order" = '1',
  "Mounting Type" = 'Through Hole, Right Angle',
  "Number of Ports" = '1',
  "Packaging" = 'Bulk',
  "Part Status" = 'Active',
  "Price" = '5.77',
  "Series" = '-',
  "Shield Termination" = 'Solder',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'A32270-ND',
  "Library Path" = 'symbols/RF - Antenna/SCH - RF - ANTENNA - BASIC ANTENNA.SCHLIB',
  "Library Ref" = 'BASIC ANTENNA'
WHERE ("Part Number" = '5413631-1');

UPDATE "Connectors-Coaxial-RF"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = '//media.digikey.com/pdf/Data%20Sheets/Linx%20Technologies%20PDFs/RFConnector_Overview_Guide_2-19-15.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'https://www.digikey.com/en/products/detail/linx-technologies-inc/CONREVSMA003-062/340147',
  "Connector Style" = 'RP-SMA',
  "Connector Type" = 'Receptacle, Male Pin',
  "Contact Termination" = 'Solder',
  "Description" = 'CONN RPSMA RCPT STR 50OHM EDGEMT',
  "Fastening Type" = 'Threaded',
  "Footprint Path" = 'footprints/Connector - RF/PCB - CONNECTOR - RF - LINX CONREVSMA003.062.PCBLIB',
  "Footprint Ref" = 'LINX CONREVSMA003.062',
  "Frequency - Max" = '18 GHz',
  "Housing Color" = 'Silver',
  "Impedance" = '50Ohm',
  "LastUpdated" = '2022-06-29T18:01:54.403',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Linx Technologies Inc.',
  "Part Number" = 'CONREVSMA003.062',
  "Minimum Order" = '1',
  "Mounting Type" = 'Board Edge, End Launch',
  "Number of Ports" = '1',
  "Packaging" = 'Bulk',
  "Part Status" = 'Active',
  "Price" = '4.12',
  "Series" = '-',
  "Shield Termination" = 'Solder',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'CONREVSMA003.062-ND',
  "Library Path" = 'symbols/RF - Antenna/SCH - RF - ANTENNA - BASIC ANTENNA.SCHLIB',
  "Library Ref" = 'BASIC ANTENNA'
WHERE ("Part Number" = 'CONREVSMA003.062');

UPDATE "Connectors-Coaxial-RF"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.molex.com/pdm_docs/sd/731000115_sd.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'https://www.digikey.com/en/products/detail/molex/0731000115/3044674',
  "Connector Style" = 'SMA',
  "Connector Type" = 'Receptacle, Female Socket',
  "Contact Termination" = 'Solder',
  "Description" = 'CONN SMA RCPT R/A 50 OHM PCB',
  "Fastening Type" = 'Threaded',
  "Footprint Path" = 'footprints/Connector - RF/PCB - CONNECTOR - RF - MOLEX SD-73100-0115.PCBLIB',
  "Footprint Ref" = 'MOLEX SD-73100-0115',
  "Frequency - Max" = '18 GHz',
  "Housing Color" = 'Silver',
  "Impedance" = '50Ohm',
  "LastUpdated" = '2022-06-29T18:03:04.613',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Molex',
  "Part Number" = '0731000115',
  "Minimum Order" = '1',
  "Mounting Type" = 'Through Hole, Right Angle',
  "Number of Ports" = '1',
  "Packaging" = 'Tray',
  "Part Status" = 'Active',
  "Price" = '2.95',
  "Series" = '73100',
  "Shield Termination" = 'Solder',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'WM8552-ND',
  "Library Path" = 'symbols/RF - Antenna/SCH - RF - ANTENNA - BASIC ANTENNA.SCHLIB',
  "Library Ref" = 'BASIC ANTENNA'
WHERE ("Part Number" = '0731000115');

UPDATE "Connectors-Coaxial-RF"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.molex.com/pdm_docs/ps/PS-89675-346.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'https://www.digikey.com/en/products/detail/molex/0732511150/1465156',
  "Connector Style" = 'SMA',
  "Connector Type" = 'Receptacle, Female Socket',
  "Contact Termination" = 'Solder',
  "Description" = 'CONN SMA RCPT STR 50OHM EDGE MNT',
  "Fastening Type" = 'Threaded',
  "Footprint Path" = 'footprints/Connector - RF/PCB - CONNECTOR - RF - MOLEX SD-73251-115.PCBLIB',
  "Footprint Ref" = 'MOLEX SD-73251-115',
  "Frequency - Max" = '18 GHz',
  "Housing Color" = 'Gold',
  "Impedance" = '50Ohm',
  "LastUpdated" = '2022-06-29T18:06:18.150',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Molex',
  "Part Number" = '0732511150',
  "Minimum Order" = '1',
  "Mounting Type" = 'Board Edge, End Launch',
  "Number of Ports" = '1',
  "Packaging" = 'Tray',
  "Part Status" = 'Active',
  "Price" = '2.16',
  "Series" = '73251',
  "Shield Termination" = 'Solder',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'WM5534-ND',
  "Library Path" = 'symbols/RF - Antenna/SCH - RF - ANTENNA - BASIC ANTENNA.SCHLIB',
  "Library Ref" = 'BASIC ANTENNA'
WHERE ("Part Number" = '0732511150');

UPDATE "Connectors-Coaxial-RF"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.molex.com/pdm_docs/ps/PS-89675-346.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'https://www.digikey.com/en/products/detail/molex/0732511290/3878247',
  "Connector Style" = 'SMA',
  "Connector Type" = 'Jack, Female Socket',
  "Contact Termination" = 'Solder',
  "Description" = 'CONN SMA JACK STR 50OHM EDGE MNT',
  "Fastening Type" = 'Threaded',
  "Footprint Path" = 'footprints/Connector - RF/PCB - CONNECTOR - RF - MOLEX SD-73251-129.PCBLIB',
  "Footprint Ref" = 'MOLEX SD-73251-129',
  "Frequency - Max" = '18 GHz',
  "Housing Color" = 'Gold',
  "Impedance" = '50Ohm',
  "LastUpdated" = '2022-06-29T18:07:55.463',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Molex',
  "Part Number" = '0732511290',
  "Minimum Order" = '1',
  "Mounting Feature" = 'Bulkhead - Front Side Nut',
  "Mounting Type" = 'Board Edge, End Launch; Panel Mount',
  "Number of Ports" = '1',
  "Packaging" = 'Tray',
  "Part Status" = 'Active',
  "Price" = '4.46',
  "Series" = '73251',
  "Shield Termination" = 'Solder',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'WM9461-ND',
  "Library Path" = 'symbols/RF - Antenna/SCH - RF - ANTENNA - BASIC ANTENNA.SCHLIB',
  "Library Ref" = 'BASIC ANTENNA'
WHERE ("Part Number" = '0732511290');

UPDATE "Connectors-Coaxial-RF"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.molex.com/pdm_docs/sd/732512120_sd.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/molex/0732512120/WM5536-ND/1465158',
  "Connector Style" = 'SMA',
  "Connector Type" = 'Jack, Female Socket',
  "Contact Termination" = 'Solder',
  "Description" = 'CONN SMA JACK STR 50OHM EDGE MNT',
  "Fastening Type" = 'Threaded',
  "Footprint Path" = 'footprints/Connector - RF/PCB - CONNECTOR - RF - MOLEX SD-73251-212.PCBLIB',
  "Footprint Ref" = 'MOLEX SD-73251-212',
  "Frequency - Max" = '18GHz',
  "Housing Color" = 'Gold',
  "Impedance" = '50Ohm',
  "LastUpdated" = '2022-06-29T18:09:18.907',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Molex',
  "Part Number" = '0732512120',
  "Minimum Order" = '1',
  "Mounting Feature" = 'Bulkhead - Front Side Nut',
  "Mounting Type" = 'Board Edge, End Launch; Panel Mount',
  "Number of Ports" = '1',
  "Packaging" = 'Bag',
  "Part Status" = 'Active',
  "Price" = '3.64',
  "Series" = '73251',
  "Shield Termination" = 'Solder',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'WM5536-ND',
  "Library Path" = 'symbols/RF - Antenna/SCH - RF - ANTENNA - BASIC ANTENNA.SCHLIB',
  "Library Ref" = 'BASIC ANTENNA'
WHERE ("Part Number" = '0732512120');

UPDATE "Connectors-Coaxial-RF"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.molex.com/pdm_docs/ps/PS-89675-346.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/molex/0732512200/WM9352-ND/3468838',
  "Connector Style" = 'SMA',
  "Connector Type" = 'Jack, Female Socket',
  "Contact Termination" = 'Solder',
  "Description" = 'CONN SMA JACK R/A 50 OHM PCB',
  "Fastening Type" = 'Threaded',
  "Footprint Path" = 'footprints/Connector - RF/PCB - CONNECTOR - RF - MOLEX SD-73251-220 (NICKEL, 2.79MM FEET).PCBLIB',
  "Footprint Ref" = 'MOLEX SD-73251-220 (NICKEL, 2.79MM FEET)',
  "Frequency - Max" = '18GHz',
  "Housing Color" = 'Silver',
  "Impedance" = '50Ohm',
  "LastUpdated" = '2022-06-29T18:13:16.770',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Molex',
  "Part Number" = '0732512200',
  "Minimum Order" = '1',
  "Mounting Feature" = 'Bulkhead - Front Side Nut',
  "Mounting Type" = 'Panel Mount, Through Hole, Right Angle',
  "Number of Ports" = '1',
  "Packaging" = 'Bulk',
  "Part Status" = 'Active',
  "Price" = '5.75',
  "Series" = '73251',
  "Shield Termination" = 'Solder',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'WM9352-ND',
  "Library Path" = 'symbols/RF - Antenna/SCH - RF - ANTENNA - BASIC ANTENNA.SCHLIB',
  "Library Ref" = 'BASIC ANTENNA'
WHERE ("Part Number" = '0732512200');

UPDATE "Connectors-Coaxial-RF"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.molex.com/pdm_docs/ps/PS-89675-346.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'https://www.digikey.com/en/products/detail/molex/0732512300/3468839',
  "Connector Style" = 'RP-SMA',
  "Connector Type" = 'Jack, Male Pin',
  "Contact Termination" = 'Solder',
  "Description" = 'CONN RP-SMA JACK STR 50 OHM PCB',
  "Fastening Type" = 'Threaded',
  "Footprint Path" = 'footprints/Connector - RF/PCB - CONNECTOR - RF - MOLEX SD-73251-230.PCBLIB',
  "Footprint Ref" = 'MOLEX SD-73251-230',
  "Frequency - Max" = '18 GHz',
  "Housing Color" = 'Silver',
  "Impedance" = '50Ohm',
  "LastUpdated" = '2022-06-29T18:14:24.333',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Molex',
  "Part Number" = '0732512300',
  "Minimum Order" = '1',
  "Mounting Type" = 'Through Hole',
  "Number of Ports" = '1',
  "Packaging" = 'Bulk',
  "Part Status" = 'Active',
  "Price" = '2.31',
  "Series" = '73251',
  "Shield Termination" = 'Solder',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'WM14067-ND',
  "Library Path" = 'symbols/RF - Antenna/SCH - RF - ANTENNA - BASIC ANTENNA.SCHLIB',
  "Library Ref" = 'BASIC ANTENNA'
WHERE ("Part Number" = '0732512300');

UPDATE "Connectors-Coaxial-RF"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.molex.com/pdm_docs/ps/PS-89675-346.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'https://www.digikey.com/en/products/detail/molex/0733910060/1465165',
  "Connector Style" = 'SMA',
  "Connector Type" = 'Receptacle, Female Socket',
  "Contact Termination" = 'Solder',
  "Description" = 'CONN SMA RCPT STR 50 OHM PCB',
  "Fastening Type" = 'Threaded',
  "Footprint Path" = 'footprints/Connector - RF/PCB - CONNECTOR - RF - MOLEX SD-73391-0060.PCBLIB',
  "Footprint Ref" = 'MOLEX SD-73391-0060',
  "Frequency - Max" = '18 GHz',
  "Housing Color" = 'Gold',
  "Impedance" = '50Ohm',
  "LastUpdated" = '2022-06-29T18:15:25.380',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Molex',
  "Part Number" = '0733910060',
  "Minimum Order" = '1',
  "Mounting Type" = 'Through Hole',
  "Number of Ports" = '1',
  "Packaging" = 'Tray',
  "Part Status" = 'Active',
  "Price" = '1.94',
  "Series" = '73391',
  "Shield Termination" = 'Solder',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'WM5543-ND',
  "Library Path" = 'symbols/RF - Antenna/SCH - RF - ANTENNA - BASIC ANTENNA.SCHLIB',
  "Library Ref" = 'BASIC ANTENNA'
WHERE ("Part Number" = '0733910060');

UPDATE "Connectors-Coaxial-RF"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.molex.com/pdm_docs/ps/PS-73598-021-001.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/molex/0734120110/WM5587CT-ND/1894612',
  "Connector Type" = 'Receptacle, Male Pin',
  "Contact Termination" = 'Solder',
  "Description" = 'CONN UMC RCPT STR 50 OHM SMD',
  "Fastening Type" = 'Snap-On',
  "Footprint Path" = 'footprints/Connector - RF/PCB - CONNECTOR - RF - MOLEX SD-734120110.PCBLIB',
  "Footprint Ref" = 'MOLEX SD-734120110',
  "Frequency - Max" = '6GHz',
  "Housing Color" = 'Silver',
  "Impedance" = '50Ohm',
  "LastUpdated" = '2022-06-29T18:16:05.840',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Molex',
  "Part Number" = '0734120110',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Ports" = '1',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '0.32',
  "Series" = '73412',
  "Shield Termination" = 'Solder',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'WM5587CT-ND',
  "Library Path" = 'symbols/RF - Antenna/SCH - RF - ANTENNA - BASIC ANTENNA.SCHLIB',
  "Library Ref" = 'BASIC ANTENNA'
WHERE ("Part Number" = '0734120110');

UPDATE "Connectors-Coaxial-RF"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=1909763&DocType=Customer+Drawing&DocLang=English',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'https://www.digikey.com/en/products/detail/te-connectivity-amp-connectors/1909763-1/4731728',
  "Connector Style" = 'U.FL (UMCC)',
  "Connector Type" = 'Jack, Male Pin',
  "Contact Termination" = 'Solder',
  "Description" = 'CONN UMCC JACK STR 50OHM SMD',
  "Fastening Type" = 'Snap-On',
  "Footprint Path" = 'footprints/Connector - RF/PCB - CONNECTOR - RF - TE C-1909763.PCBLIB',
  "Footprint Ref" = 'TE C-1909763',
  "Frequency - Max" = '6 GHz',
  "Housing Color" = 'Ivory',
  "Impedance" = '50Ohm',
  "LastUpdated" = '2022-06-29T18:17:07.053',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'TE Connectivity AMP Connectors',
  "Part Number" = '1909763-1',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Ports" = '1',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '0.23',
  "Series" = '-',
  "Shield Termination" = 'Solder',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'A118077CT-ND',
  "Library Path" = 'symbols/RF - Antenna/SCH - RF - ANTENNA - BASIC ANTENNA.SCHLIB',
  "Library Ref" = 'BASIC ANTENNA'
WHERE ("Part Number" = '1909763-1');

UPDATE "Connectors-Coaxial-RF"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.molex.com/pdm_docs/sd/734130040_sd.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'https://www.digikey.com/en/products/detail/molex/0734130040/3599790',
  "Connector Style" = 'SSMCX',
  "Connector Type" = 'Jack, Female Socket',
  "Contact Termination" = 'Solder',
  "Description" = 'CONN SSMCX JACK STR 50 OHM SMD',
  "Fastening Type" = 'Snap-On',
  "Footprint Path" = 'footprints/Connector - Molex/PCB - CONNECTOR - MOLEX - MOLEX 0734130040.PcbLib',
  "Footprint Ref" = 'MOLEX 0734130040',
  "Frequency - Max" = '6 GHz',
  "Housing Color" = 'Gold',
  "Impedance" = '50Ohm',
  "LastUpdated" = '2022-07-03T19:04:51.260',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Molex',
  "Part Number" = '0734130040',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Ports" = '1',
  "Packaging" = 'Bulk',
  "Part Status" = 'Active',
  "Price" = '1.13',
  "Series" = '73413',
  "Shield Termination" = 'Solder',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'WM9358-ND',
  "Library Path" = 'symbols/RF - Antenna/SCH - RF - ANTENNA - BASIC ANTENNA.SCHLIB',
  "Library Ref" = 'BASIC ANTENNA'
WHERE ("Part Number" = '0734130040');

UPDATE "Connectors-Coaxial-RF"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.molex.com/pdm_docs/sd/734152063_sd.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'https://www.digikey.com/en/products/detail/molex/0734152063/2421475',
  "Connector Style" = 'MMCX',
  "Connector Type" = 'Jack, Female Socket',
  "Contact Termination" = 'Solder',
  "Description" = 'CONN MMCX JACK STR 50 OHM SMD',
  "Fastening Type" = 'Snap-On',
  "Footprint Path" = 'footprints/Connector - Molex/PCB - CONNECTOR - MOLEX - MOLEX 0734152063.PcbLib',
  "Footprint Ref" = 'MOLEX 0734152063',
  "Frequency - Max" = '6 GHz',
  "Housing Color" = 'Gold',
  "Impedance" = '50Ohm',
  "LastUpdated" = '2022-07-03T19:04:17.953',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Molex',
  "Part Number" = '0734152063',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Ports" = '1',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '1.28',
  "Series" = '73415',
  "Shield Termination" = 'Solder',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'WM3914CT-ND',
  "Library Path" = 'symbols/RF - Connector/SCH - RF - CONNECTOR - RF CONNECTOR - COAX AS TEST POINT.SCHLIB',
  "Library Ref" = 'RF CONNECTOR - COAX AS TEST POINT'
WHERE ("Part Number" = '0734152063');

