--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

UPDATE "Audio-Speakers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.cuidevices.com/product/resource/digikeypdf/cms-16093-078x.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/cui-devices/CMS-16093-078SP/102-4622-ND/8581456',
  "Description" = 'SPEAKER, 16 X 9 MM, 3 MM DEEP, M',
  "Efficiency - dBA" = '91.00',
  "Efficiency - Testing" = '700mW/100mm',
  "Efficiency - Type" = 'Sound Pressure Level (SPL)',
  "Footprint Path" = 'footprints/Audio/PCB - AUDIO - CUI CMS-16093-078SP.PcbLib',
  "Footprint Ref" = 'CUI CMS-16093-078SP',
  "Frequency Range" = '100Hz ~ 20kHz',
  "Frequency - Self Resonant" = '550Hz',
  "Height - Seated (Max)" = '0.118" (3.00mm)',
  "Impedance" = '8 Ohms',
  "LastUpdated" = '2020-09-06T11:49:34.980',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'CUI Devices',
  "Part Number" = 'CMS-16093-078SP',
  "Material - Cone" = 'Polyester, Polyethylene Terephthalate (PET)',
  "Material - Magnet" = 'Nd-Fe-B',
  "Minimum Order" = '1',
  "Packaging" = 'Tray',
  "Part Status" = 'Active',
  "Port Location" = 'Top',
  "Power - Max" = '1W',
  "Power - Rated" = '700mW',
  "Price" = '2.04',
  "Series" = 'CMS',
  "Shape" = 'Rectangular',
  "Size / Dimension" = '0.630" L x 0.354" W (16.00mm x 9.00mm)',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '102-4622-ND',
  "Library Path" = 'symbols/Audio/SCH - AUDIO - SPEAKER 2 PIN.SCHLIB',
  "Library Ref" = 'SPEAKER 2 PIN',
  "Technology" = 'Magnetic',
  "Termination" = 'Solder Pads',
  "Type" = 'General Purpose'
WHERE ("Part Number" = 'CMS-16093-078SP');

UPDATE "Audio-Speakers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.cuidevices.com/product/resource/digikeypdf/cms-15113-076x.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/cui-devices/CMS-15113-076SP/102-4627-ND/8581461',
  "Description" = 'SPEAKER, 15 X 11 MM, 3 MM DEEP,',
  "Efficiency - dBA" = '92.00',
  "Efficiency - Testing" = '700mW/100mm',
  "Efficiency - Type" = 'Sound Pressure Level (SPL)',
  "Footprint Path" = 'footprints/Audio/PCB - AUDIO - CUI CMS-15113-078SP.PcbLib',
  "Footprint Ref" = 'CUI CMS-15113-078SP',
  "Frequency Range" = '100Hz ~ 20kHz',
  "Frequency - Self Resonant" = '600Hz',
  "Height - Seated (Max)" = '0.118" (3.00mm)',
  "Impedance" = '6 Ohms',
  "LastUpdated" = '2020-09-06T11:51:04.873',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'CUI Devices',
  "Part Number" = 'CMS-15113-076SP',
  "Material - Cone" = 'Polyester, Polyethylene Terephthalate (PET)',
  "Material - Magnet" = 'Nd-Fe-B',
  "Minimum Order" = '1',
  "Packaging" = 'Tray',
  "Part Status" = 'Active',
  "Port Location" = 'Top',
  "Power - Max" = '1W',
  "Power - Rated" = '700mW',
  "Price" = '2.04',
  "Series" = 'CMS',
  "Shape" = 'Rectangular',
  "Size / Dimension" = '0.591" L x 0.433" W (15.00mm x 11.00mm)',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '102-4627-ND',
  "Library Path" = 'symbols/Audio/SCH - AUDIO - SPEAKER 2 PIN.SCHLIB',
  "Library Ref" = 'SPEAKER 2 PIN',
  "Technology" = 'Magnetic',
  "Termination" = 'Solder Pads',
  "Type" = 'General Purpose'
WHERE ("Part Number" = 'CMS-15113-076SP');

UPDATE "Audio-Speakers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.cuidevices.com/product/resource/digikeypdf/cms-15113-076x-67.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/cui-devices/CMS-15113-076SP-67/102-4997-ND/9561099',
  "Description" = 'SPEAKER, 15 X 11 MM, 3 MM DEEP,',
  "Efficiency - dBA" = '92.00',
  "Efficiency - Testing" = '700mW/100mm',
  "Efficiency - Type" = 'Sound Pressure Level (SPL)',
  "Footprint Path" = 'footprints/Audio/PCB - AUDIO - CUI CMS-15113-078SP.PcbLib',
  "Footprint Ref" = 'CUI CMS-15113-078SP',
  "Frequency Range" = '100Hz ~ 20kHz',
  "Frequency - Self Resonant" = '600Hz',
  "Height - Seated (Max)" = '0.118" (3.00mm)',
  "Impedance" = '6 Ohms',
  "Ingress Protection" = 'IP67 - Dust Tight, Waterproof',
  "LastUpdated" = '2020-09-06T11:51:20.007',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'CUI Devices',
  "Part Number" = 'CMS-15113-076SP-67',
  "Material - Cone" = 'Polyester, Polyethylene Terephthalate (PET)',
  "Material - Magnet" = 'Nd-Fe-B',
  "Minimum Order" = '1',
  "Packaging" = 'Tray',
  "Part Status" = 'Active',
  "Port Location" = 'Top',
  "Power - Max" = '1W',
  "Power - Rated" = '700mW',
  "Price" = '2.17',
  "Series" = 'CMS',
  "Shape" = 'Rectangular',
  "Size / Dimension" = '0.591" L x 0.433" W (15.00mm x 11.00mm)',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '102-4997-ND',
  "Library Path" = 'symbols/Audio/SCH - AUDIO - SPEAKER 2 PIN.SCHLIB',
  "Library Ref" = 'SPEAKER 2 PIN',
  "Technology" = 'Magnetic',
  "Termination" = 'Solder Pads',
  "Type" = 'General Purpose'
WHERE ("Part Number" = 'CMS-15113-076SP-67');

UPDATE "Audio-Speakers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.cuidevices.com/product/resource/digikeypdf/cms-15113-078x-67.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/cui-devices/CMS-15113-078SP-67/102-5001-ND/9561103',
  "Description" = 'SPEAKER, 15 X 11 MM, 3 MM DEEP,',
  "Efficiency - dBA" = '91.00',
  "Efficiency - Testing" = '700mW/100mm',
  "Efficiency - Type" = 'Sound Pressure Level (SPL)',
  "Footprint Path" = 'footprints/Audio/PCB - AUDIO - CUI CMS-15113-078SP.PcbLib',
  "Footprint Ref" = 'CUI CMS-15113-078SP',
  "Frequency Range" = '100Hz ~ 20kHz',
  "Frequency - Self Resonant" = '700Hz',
  "Height - Seated (Max)" = '0.118" (3.00mm)',
  "Impedance" = '8 Ohms',
  "Ingress Protection" = 'IP67 - Dust Tight, Waterproof',
  "LastUpdated" = '2020-09-06T11:52:13.353',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'CUI Devices',
  "Part Number" = 'CMS-15113-078SP-67',
  "Material - Cone" = 'Polyester, Polyethylene Terephthalate (PET)',
  "Material - Magnet" = 'Nd-Fe-B',
  "Minimum Order" = '1',
  "Packaging" = 'Tray',
  "Part Status" = 'Active',
  "Port Location" = 'Top',
  "Power - Max" = '1W',
  "Power - Rated" = '700mW',
  "Price" = '2.17',
  "Series" = 'CMS',
  "Shape" = 'Rectangular',
  "Size / Dimension" = '0.591" L x 0.433" W (15.00mm x 11.00mm)',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '102-5001-ND',
  "Library Path" = 'symbols/Audio/SCH - AUDIO - SPEAKER 2 PIN.SCHLIB',
  "Library Ref" = 'SPEAKER 2 PIN',
  "Technology" = 'Magnetic',
  "Termination" = 'Solder Pads',
  "Type" = 'General Purpose'
WHERE ("Part Number" = 'CMS-15113-078SP-67');

UPDATE "Audio-Speakers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.cuidevices.com/product/resource/digikeypdf/cms-15113-078x.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/cui-devices/CMS-15113-078SP/102-5644-ND/8581915',
  "Description" = 'SPEAKER, 15 X 11 MM, 3 MM DEEP,',
  "Efficiency - dBA" = '91.00',
  "Efficiency - Testing" = '700mW/100mm',
  "Efficiency - Type" = 'Sound Pressure Level (SPL)',
  "Footprint Path" = 'footprints/Audio/PCB - AUDIO - CUI CMS-15113-078SP.PcbLib',
  "Footprint Ref" = 'CUI CMS-15113-078SP',
  "Frequency Range" = '100Hz ~ 20kHz',
  "Frequency - Self Resonant" = '700Hz',
  "Height - Seated (Max)" = '0.118" (3.00mm)',
  "Impedance" = '8 Ohms',
  "LastUpdated" = '2020-09-06T11:52:25.680',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'CUI Devices',
  "Part Number" = 'CMS-15113-078SP',
  "Material - Cone" = 'Polyester, Polyethylene Terephthalate (PET)',
  "Material - Magnet" = 'Nd-Fe-B',
  "Minimum Order" = '1',
  "Packaging" = 'Unknown',
  "Part Status" = 'Active',
  "Port Location" = 'Top',
  "Power - Max" = '1W',
  "Power - Rated" = '700mW',
  "Price" = '2.04',
  "Series" = 'CMS',
  "Shape" = 'Rectangular',
  "Size / Dimension" = '0.591" L x 0.433" W (15.00mm x 11.00mm)',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '102-5644-ND',
  "Library Path" = 'symbols/Audio/SCH - AUDIO - SPEAKER 2 PIN.SCHLIB',
  "Library Ref" = 'SPEAKER 2 PIN',
  "Technology" = 'Magnetic',
  "Termination" = 'Solder Pads',
  "Type" = 'General Purpose'
WHERE ("Part Number" = 'CMS-15113-078SP');

