--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

UPDATE "Audio-AlarmsBuzzersAndSirens"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.cuidevices.com/product/resource/digikeypdf/ct-1205h-smt-tr.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/cui-devices/CT-1205H-SMT-TR/102-1266-1-ND/610974',
  "Current - Supply" = '60mA',
  "Description" = 'AUDIO MAGNETIC XDCR 3-7V SMD',
  "Driver Circuitry" = 'Transducer, Externally Driven',
  "Footprint Path" = 'footprints/Buzzer/PCB - BUZZER - CUI CT-1205H-SMT-TR.PCBLIB',
  "Footprint Ref" = 'CUI CT-1205H-SMT-TR',
  "Frequency" = '2.4kHz',
  "Height - Seated (Max)" = '0.406" (10.30mm)',
  "Input Type" = 'Zero-Peak Signal',
  "LastUpdated" = '2020-04-24T00:37:20.420',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'CUI Devices',
  "Part Number" = 'CT-1205H-SMT-TR',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Operating Mode" = 'Single Tone',
  "Operating Temperature" = '-30°C ~ 70°C',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Port Location" = 'Top',
  "Price" = '0.95',
  "Ratings" = 'Washable',
  "Series" = 'CT',
  "Size / Dimension" = '0.504" L x 0.504" W (12.80mm x 12.80mm)',
  "Sound Pressure Level (SPL)" = '88dB @ 5V, 10cm',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '102-1266-1-ND',
  "Library Path" = 'symbols/Buzzer/SCH - BUZZER - Buzzer 2 pin.SCHLIB',
  "Library Ref" = 'Buzzer 2 pin',
  "Technology" = 'Magnetic',
  "Termination" = 'Solder Pads',
  "Voltage Range" = '3 ~ 7V',
  "Voltage - Rated" = '5V'
WHERE ("Part Number" = 'CT-1205H-SMT-TR');

UPDATE "Audio-AlarmsBuzzersAndSirens"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.puiaudio.com/pdf/SMT-0827-S-2-R.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/pui-audio-inc/SMT-0827-S-2-R/668-1072-1-ND/1464939',
  "Current - Supply" = '90mA',
  "Description" = 'AUDIO MAGNETIC XDCR 2.5-4.5V SMD',
  "Driver Circuitry" = 'Transducer, Externally Driven',
  "Footprint Path" = 'footprints/Buzzer/PCB - BUZZER - PUI Audio SMT-0827-S-2-R.PCBLIB',
  "Footprint Ref" = 'PUI Audio SMT-0827-S-2-R',
  "Frequency" = '2.7kHz',
  "Height - Seated (Max)" = '0.177" (4.50mm)',
  "Input Type" = 'Zero-Peak Signal',
  "LastUpdated" = '2020-04-24T00:38:09.327',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'PUI Audio, Inc.',
  "Part Number" = 'SMT-0827-S-2-R',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Operating Mode" = 'Single Tone',
  "Operating Temperature" = '-30°C ~ 70°C',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Port Location" = 'Side',
  "Price" = '2.03',
  "Series" = 'SMT',
  "Size / Dimension" = '0.335" L x 0.335" W (8.50mm x 8.50mm)',
  "Sound Pressure Level (SPL)" = '92dB @ 3.6V, 10cm',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '668-1072-1-ND',
  "Library Path" = 'symbols/Buzzer/SCH - BUZZER - Buzzer 2 pin.SCHLIB',
  "Library Ref" = 'Buzzer 2 pin',
  "Technology" = 'Magnetic',
  "Termination" = 'Solder Pads',
  "Voltage Range" = '2.5 ~ 4.5V',
  "Voltage - Rated" = '3.6V'
WHERE ("Part Number" = 'SMT-0827-S-2-R');

UPDATE "Audio-AlarmsBuzzersAndSirens"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.puiaudio.com/pdf/SMI-1027-TW-5V-R.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/pui-audio-inc/SMI-1027-TW-5V-R/668-1537-1-ND/6021768',
  "Current - Supply" = '30mA',
  "Description" = 'AUDIO MAGNETIC IND 4-7V SMD',
  "Driver Circuitry" = 'Indicator, Internally Driven',
  "Footprint Path" = 'footprints/Buzzer/PCB - BUZZER - PUI Audio SMI-1027-TW-5V-R.PCBLIB',
  "Footprint Ref" = 'PUI Audio SMI-1027-TW-5V-R',
  "Frequency" = '2.7kHz',
  "Height - Seated (Max)" = '0.209" (5.30mm)',
  "Input Type" = 'DC',
  "LastUpdated" = '2020-04-24T00:38:53.563',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'PUI Audio, Inc.',
  "Part Number" = 'SMI-1027-TW-5V-R',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Operating Mode" = 'Single Tone',
  "Operating Temperature" = '-40°C ~ 85°C',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Port Location" = 'Top',
  "Price" = '2.15',
  "Ratings" = 'Washable',
  "Series" = 'SMI',
  "Size / Dimension" = '0.378" L x 0.378" W (9.60mm x 9.60mm)',
  "Sound Pressure Level (SPL)" = '80dB @ 5V, 10cm',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '668-1537-1-ND',
  "Library Path" = 'symbols/Buzzer/SCH - BUZZER - Buzzer 2 pin.SCHLIB',
  "Library Ref" = 'Buzzer 2 pin',
  "Technology" = 'Magnetic',
  "Termination" = 'Solder Pads',
  "Voltage Range" = '4 ~ 7V',
  "Voltage - Rated" = '5V'
WHERE ("Part Number" = 'SMI-1027-TW-5V-R');

UPDATE "Audio-AlarmsBuzzersAndSirens"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.cuidevices.com/product/resource/digikeypdf/css-0575a-smt-tr.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/cui-devices/CSS-0575A-SMT-TR/102-2201-1-ND/2364650',
  "Current - Supply" = '95mA',
  "Description" = 'AUDIO MAGNETIC XDCR 2-4V SMD',
  "Driver Circuitry" = 'Transducer, Externally Driven',
  "Footprint Path" = 'footprints/Buzzer/PCB - BUZZER - CUI CSS-0575A-SMT-TR.PCBLIB',
  "Footprint Ref" = 'CUI CSS-0575A-SMT-TR',
  "Frequency" = '4kHz',
  "Height - Seated (Max)" = '0.094" (2.40mm)',
  "Input Type" = 'Zero-Peak Signal',
  "LastUpdated" = '2020-04-24T00:39:31.310',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'CUI Devices',
  "Part Number" = 'CSS-0575A-SMT-TR',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Operating Mode" = 'Single Tone',
  "Operating Temperature" = '-30°C ~ 70°C',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Port Location" = 'Top',
  "Price" = '1.50',
  "Series" = 'CSS',
  "Size / Dimension" = '0.197" L x 0.197" W (5.00mm x 5.00mm)',
  "Sound Pressure Level (SPL)" = '76dB @ 3V, 10cm',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '102-2201-1-ND',
  "Library Path" = 'symbols/Buzzer/SCH - BUZZER - Buzzer 2 pin.SCHLIB',
  "Library Ref" = 'Buzzer 2 pin',
  "Technology" = 'Magnetic',
  "Termination" = 'Solder Pads',
  "Voltage Range" = '2 ~ 4V',
  "Voltage - Rated" = '3V'
WHERE ("Part Number" = 'CSS-0575A-SMT-TR');

