--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

UPDATE "PowerDistribution-SwitchesAndLoadDrivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en579487',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/microchip-technology/MIC2007YM6-TR/576-1460-1-ND/966334',
  "Current - Output (Max)" = '2A',
  "Description" = 'IC PWR SWITCH P-CHAN 1:1 SOT23-6',
  "Device Package" = 'SOT-23-6',
  "Fault Protection" = 'Current Limiting (Adjustable), Over Temperature',
  "Features" = 'Load Discharge, Slew Rate Controlled',
  "Footprint Path" = 'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - MICROCHIP SOT-23-6 M6.PCBLIB',
  "Footprint Ref" = 'MICROCHIP SOT-23-6 M6',
  "Input Type" = 'Non-Inverting',
  "Interface" = 'On/Off',
  "LastUpdated" = '2020-03-30T15:31:54.127',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Microchip Technology',
  "Part Number" = 'MIC2007YM6-TR',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Outputs" = '1',
  "Operating Temperature" = '-40°C ~ 85°C (TA)',
  "Output Configuration" = 'High Side',
  "Output Type" = 'P-Channel',
  "Package / Case" = 'SOT-23-6',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '0.35',
  "Ratio - Input:Output" = '1:1',
  "Rds On (Typ)" = '70mOhm',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '576-1460-1-ND',
  "Supplier Device Package" = 'SOT-23-6',
  "Switch Type" = 'General Purpose',
  "Library Path" = 'symbols/Driver - Load/SCH - DRIVER - LOAD - MICROCHIP MIC2007YM6-TR.SCHLIB',
  "Library Ref" = 'MICROCHIP MIC2007YM6-TR',
  "Voltage - Load" = '2.5V ~ 5.5V',
  "Voltage - Supply (Vcc/Vdd)" = 'Not Required'
WHERE ("Part Number" = 'MIC2007YM6-TR');

UPDATE "PowerDistribution-SwitchesAndLoadDrivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.st.com/content/ccc/resource/technical/document/datasheet/1a/8c/51/d8/96/28/4d/63/CD00002878.pdf/files/CD00002878.pdf/jcr:content/translations/en.CD00002878.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/stmicroelectronics/ST890CDR/497-6543-1-ND/1865325',
  "Current - Output (Max)" = '1.2A',
  "Description" = 'IC PWR SWITCH P-CHANNEL 1:1 8SO',
  "Device Package" = '8-SOIC (0.154", 3.90mm Width)',
  "Fault Protection" = 'Current Limiting (Adjustable), Over Temperature',
  "Footprint Path" = 'footprints/Leaded - SOIC/PCB - LEADED - SOIC - ST SOIC-8N.PCBLIB',
  "Footprint Ref" = 'ST SOIC-8N',
  "Input Type" = 'Non-Inverting',
  "Interface" = 'On/Off',
  "LastUpdated" = '2020-05-24T21:33:44.640',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'STMicroelectronics',
  "Part Number" = 'ST890CDR',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Outputs" = '1',
  "Operating Temperature" = '-40°C ~ 85°C (TA)',
  "Output Configuration" = 'High Side',
  "Output Type" = 'P-Channel',
  "Package / Case" = '8-SOIC (0.154", 3.90mm Width)',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '0.47',
  "Ratio - Input:Output" = '1:1',
  "Rds On (Typ)" = '75mOhm',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '497-6543-1-ND',
  "Supplier Device Package" = '8-SO',
  "Switch Type" = 'General Purpose',
  "Library Path" = 'symbols/Driver - Load/SCH - DRIVER - LOAD - ST ST890CDR.SCHLIB',
  "Library Ref" = 'ST ST890CDR',
  "Voltage - Load" = '2.7V ~ 5.5V',
  "Voltage - Supply (Vcc/Vdd)" = 'Not Required'
WHERE ("Part Number" = 'ST890CDR');

