--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Inductors-Power" (
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Current Rating (Amps)",
  "DC Resistance (DCR)",
  "Description",
  "Device Package",
  "Footprint Path",
  "Footprint Ref",
  "Frequency - Self Resonant",
  "Height - Seated (Max)",
  "Inductance",
  "Inductance Frequency - Test",
  "LastUpdated",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Minimum Order",
  "Mounting Type",
  "Operating Temperature",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Q @ Freq",
  "Series",
  "Shielding",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Library Path",
  "Library Ref",
  "Tolerance",
  "Type",
  "Value"
)
VALUES (
  '=Value', 
  'Datasheet', 
  'https://search.murata.co.jp/Ceramy/image/img/P02/JELF243A-0100.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/murata-electronics/LQW15AN2N5B80D/4905911', 
  '2.1 A', 
  '30mOhm Max', 
  'FIXED IND 2.5NH 2.1A 30 MOHM SMD', 
  '0402 (1005 Metric)', 
  'footprints/Passives/PCB - PASSIVES - IND 0402_1005.PCBLIB', 
  'IND 0402_1005', 
  '15.5GHz', 
  '0.024" (0.60mm)', 
  '2.5 nH', 
  '100 MHz', 
  '2023-02-03T21:02:59.657', 
  'Active', 
  'Murata Electronics', 
  'LQW15AN2N5B80D', 
  '1', 
  'Surface Mount', 
  '-55°C ~ 125°C', 
  '0402 (1005 Metric)', 
  'TapeAndReel', 
  '6227', 
  'Active', 
  '0.07', 
  '30 @ 250MHz', 
  'LQW15', 
  'Unshielded', 
  '0.039" L x 0.024" W (1.00mm x 0.60mm)', 
  'DigiKey', 
  '490-LQW15AN2N5B80DCT-ND', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'INDUCTOR', 
  '±0.1nH', 
  'Wirewound', 
  '2.5 nH'
);

INSERT INTO "Inductors-Power" (
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Current Rating (Amps)",
  "DC Resistance (DCR)",
  "Description",
  "Device Package",
  "Footprint Path",
  "Footprint Ref",
  "Frequency - Self Resonant",
  "Height - Seated (Max)",
  "Inductance",
  "Inductance Frequency - Test",
  "LastUpdated",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Material - Core",
  "Minimum Order",
  "Mounting Type",
  "Operating Temperature",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Q @ Freq",
  "Series",
  "Shielding",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Supplier Device Package",
  "Library Path",
  "Library Ref",
  "Tolerance",
  "Type",
  "Value"
)
VALUES (
  '=Value', 
  'Datasheet', 
  'https://search.murata.co.jp/Ceramy/image/img/P02/JELF243A-0100.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/murata-electronics/LQW15AN4N3G80D/10703431', 
  '1.8 A', 
  '44mOhm Max', 
  'FIXED IND', 
  '0402 (1005 Metric)', 
  'footprints/Passives/PCB - PASSIVES - IND 0402_1005.PCBLIB', 
  'IND 0402_1005', 
  '9.6GHz', 
  '0.024" (0.60mm)', 
  '4.3 nH', 
  '100 MHz', 
  '2023-02-03T21:02:59.670', 
  'Active', 
  'Murata Electronics', 
  'LQW15AN4N3G80D', 
  'Non-Magnetic', 
  '1', 
  'Surface Mount', 
  '-55°C ~ 125°C', 
  '0402 (1005 Metric)', 
  'TapeAndReel', 
  '6228', 
  'Active', 
  '0.07', 
  '32 @ 250MHz', 
  'LQW15', 
  'Unshielded', 
  '0.039" L x 0.024" W (1.00mm x 0.60mm)', 
  'DigiKey', 
  '490-LQW15AN4N3G80DCT-ND', 
  '0402', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'INDUCTOR', 
  '±2%', 
  'Wirewound', 
  '4.3 nH'
);

INSERT INTO "Inductors-Power" (
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Current Rating (Amps)",
  "DC Resistance (DCR)",
  "Description",
  "Device Package",
  "Footprint Path",
  "Footprint Ref",
  "Frequency - Self Resonant",
  "Height - Seated (Max)",
  "Inductance",
  "Inductance Frequency - Test",
  "LastUpdated",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Material - Core",
  "Minimum Order",
  "Mounting Type",
  "Operating Temperature",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Q @ Freq",
  "Series",
  "Shielding",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Supplier Device Package",
  "Library Path",
  "Library Ref",
  "Tolerance",
  "Type",
  "Value"
)
VALUES (
  '=Value', 
  'Datasheet', 
  'https://www.chilisin.com/upload/media/product/rf/file/BSCH_Series.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/pulse-electronics/BSCH001005055N6SCS/16500805', 
  '400 mA', 
  '200mOhm Max', 
  'INDUCTOR RF', 
  '0402 (1005 Metric)', 
  'footprints/Passives/PCB - PASSIVES - IND 0402_1005.PCBLIB', 
  'IND 0402_1005', 
  '5.1GHz', 
  '0.024" (0.60mm)', 
  '5.6 nH', 
  '100 MHz', 
  '2023-02-03T21:02:59.867', 
  'Active', 
  'Chilisin Electronics', 
  'BSCH001005055N6SCS', 
  'Ceramic', 
  '1', 
  'Surface Mount', 
  '-55°C ~ 125°C', 
  '0402 (1005 Metric)', 
  'TapeAndReel', 
  '6229', 
  'Active', 
  '0.01', 
  '8 @ 100MHz', 
  'BSCH', 
  'Unshielded', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  'DigiKey', 
  '553-BSCH001005055N6SCSCT-ND', 
  '0402', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'INDUCTOR', 
  '±0.3nH', 
  'Multilayer', 
  '5.6 nH'
);

