--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Gain Bandwidth Product",
  "Current - Input Bias",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Voltage - Supply, Single/Dual (±)",
  "ComponentLink2Description",
  "Current - Output / Channel",
  "Footprint Path"
)
VALUES (
  'IC TRANSIMPEDANCE 1 CIRC 8VSSOP', 
  'OPA380AIDGKR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/OPA380AIDGKR/1572636', 
  '90 MHz', 
  '3 pA', 
  '8-VSSOP', 
  '8-TSSOP, 8-MSOP (0.118", 3.00mm Width)', 
  'TI OPA380', 
  '296-38195-1-ND', 
  'Active', 
  'Texas Instruments', 
  '2025-11-02T07:24:58.923', 
  '1', 
  'Transimpedance', 
  '102', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Fopa380', 
  'TI VSSOP-8 DGK', 
  'Datasheet', 
  '80V/µs', 
  'DigiKey', 
  '7.5mA', 
  'Surface Mount', 
  '1', 
  '4 µV', 
  '-', 
  '2.56', 
  'symbols/Opamp/SCH - OPAMP - TI OPA380.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2.7V ~ 5.5V', 
  'DigiKey Link', 
  '150 mA', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - TI VSSOP-8 DGK.PCBLIB'
);

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Gain Bandwidth Product",
  "Current - Input Bias",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Voltage - Supply, Single/Dual (±)",
  "ComponentLink2Description",
  "Current - Output / Channel",
  "Footprint Path"
)
VALUES (
  'IC TRANSIMPEDANCE 1 CIRC 8VSSOP', 
  'OPA380AIDGKT', 
  'https://www.digikey.com/en/products/detail/texas-instruments/OPA380AIDGKT/639561', 
  '90 MHz', 
  '3 pA', 
  '8-VSSOP', 
  '8-TSSOP, 8-MSOP (0.118", 3.00mm Width)', 
  'TI OPA380', 
  '296-16860-1-ND', 
  'Active', 
  'Texas Instruments', 
  '2025-11-02T07:25:10.923', 
  '1', 
  'Transimpedance', 
  '103', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Fopa380', 
  'TI VSSOP-8 DGK', 
  'Datasheet', 
  '80V/µs', 
  'DigiKey', 
  '7.5mA', 
  'Surface Mount', 
  '1', 
  '4 µV', 
  '-', 
  '3.07', 
  'symbols/Opamp/SCH - OPAMP - TI OPA380.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2.7V ~ 5.5V', 
  'DigiKey Link', 
  '150 mA', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - TI VSSOP-8 DGK.PCBLIB'
);

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Gain Bandwidth Product",
  "Current - Input Bias",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Voltage - Supply, Single/Dual (±)",
  "ComponentLink2Description",
  "Current - Output / Channel",
  "Footprint Path"
)
VALUES (
  'IC TRANSIMPEDANCE 2 CIRC 8VSSOP', 
  'OPA2380AIDGKT', 
  'https://www.digikey.com/en/products/detail/texas-instruments/OPA2380AIDGKT/659663', 
  '90 MHz', 
  '3 pA', 
  '8-VSSOP', 
  '8-TSSOP, 8-MSOP (0.118", 3.00mm Width)', 
  'TI OPA2380', 
  '296-17046-1-ND', 
  'Active', 
  'Texas Instruments', 
  '2025-11-02T07:25:47.963', 
  '1', 
  'Transimpedance', 
  '104', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Fopa380', 
  'TI VSSOP-8 DGK', 
  'Datasheet', 
  '80V/µs', 
  'DigiKey', 
  '7.5mA (x2 Channels)', 
  'Surface Mount', 
  '2', 
  '4 µV', 
  '-', 
  '4.11', 
  'symbols/Opamp/SCH - OPAMP - TI OPA2380.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2.7V ~ 5.5V', 
  'DigiKey Link', 
  '150 mA', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - TI VSSOP-8 DGK.PCBLIB'
);

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Gain Bandwidth Product",
  "Current - Input Bias",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Voltage - Supply, Single/Dual (±)",
  "ComponentLink2Description",
  "Current - Output / Channel",
  "Footprint Path"
)
VALUES (
  'IC TRANSIMPEDANCE 2 CIRC 8VSSOP', 
  'OPA2380AIDGKR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/OPA2380AIDGKR/1572271', 
  '90 MHz', 
  '3 pA', 
  '8-VSSOP', 
  '8-TSSOP, 8-MSOP (0.118", 3.00mm Width)', 
  'TI OPA2380', 
  '296-48627-1-ND', 
  'Active', 
  'Texas Instruments', 
  '2025-11-02T07:25:59.287', 
  '1', 
  'Transimpedance', 
  '105', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.ti.com/lit/pdf/slyt701', 
  'TI VSSOP-8 DGK', 
  'Datasheet', 
  '80V/µs', 
  'DigiKey', 
  '7.5mA (x2 Channels)', 
  'Surface Mount', 
  '2', 
  '4 µV', 
  '-', 
  '3.40', 
  'symbols/Opamp/SCH - OPAMP - TI OPA2380.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2.7V ~ 5.5V', 
  'DigiKey Link', 
  '150 mA', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - TI VSSOP-8 DGK.PCBLIB'
);

