--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 9.1PF 25V NP0 0201', 
  'QLCD250Q9R1B1GV001T', 
  'https://www.digikey.com/en/products/detail/johanson-technology-inc/QLCD250Q9R1B1GV001T/1919305', 
  '0201 (0603 Metric)', 
  '25V', 
  'C0G, NP0', 
  '0201 (0603 Metric)', 
  'CAPACITOR', 
  '712-QLCD250Q9R1B1GV001TCT-ND', 
  'Active', 
  'Johanson Technology Inc.', 
  'High Q, Low Loss', 
  '2023-07-10T19:57:43.963', 
  '1', 
  '4659', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://www.johansontechnology.com/downloads/catalog/johanson-technology-multi-layer-high-q-capacitors.pdf', 
  'CAP 0201_0603 RF', 
  'Datasheet', 
  '±0.1pF', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'L', 
  '0.013" (0.33mm)', 
  '0.06', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '9.1 pF', 
  '9.1 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0201_0603 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 1.9PF 25V NP0 0201', 
  'GJM0335C1E1R9WB01D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GJM0335C1E1R9WB01D/2592544', 
  '0201 (0603 Metric)', 
  '25V', 
  'C0G, NP0', 
  '0201 (0603 Metric)', 
  'CAPACITOR', 
  '490-GJM0335C1E1R9WB01DCT-ND', 
  'Active', 
  'Murata Electronics', 
  'High Q, Low Loss', 
  '2023-07-10T19:57:43.983', 
  '1', 
  '4660', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GJM0335C1E1R9WB01-01.pdf', 
  'CAP 0201_0603 RF', 
  'Datasheet', 
  '±0.05pF', 
  'DigiKey', 
  'Surface Mount', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  'GJM', 
  '0.013" (0.33mm)', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1.9 pF', 
  '1.9 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0201_0603 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 13PF 200V C0G/NP0 0402', 
  'VJ0402D130FXCAJ', 
  'https://www.digikey.com/en/products/detail/vishay-vitramon/VJ0402D130FXCAJ/5099855', 
  '0402 (1005 Metric)', 
  '200V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '720-VJ0402D130FXCAJCT-ND', 
  'Active', 
  'Vishay Vitramon', 
  'High Q, Low Loss', 
  '2023-07-10T19:59:36.357', 
  '1', 
  '4661', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://www.vishay.com/docs/45258/vjhifreqseries.pdf', 
  'CAP 0402_1005 RF', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.040" L x 0.020" W (1.02mm x 0.51mm)', 
  'VJ HIFREQ', 
  '0.024" (0.61mm)', 
  '0.88', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '13 pF', 
  '13 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 8PF 200V NP0 0402', 
  'GQM1555C2D8R0BB01D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GQM1555C2D8R0BB01D/5882180', 
  '0402 (1005 Metric)', 
  '200V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '490-GQM1555C2D8R0BB01DCT-ND', 
  'Active', 
  'Murata Electronics', 
  'High Q, Low Loss', 
  '2023-07-10T19:59:36.570', 
  '1', 
  '4662', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GQM1555C2D8R0BB01-01A.pdf', 
  'CAP 0402_1005 RF', 
  'Datasheet', 
  '±0.1pF', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  'GQM', 
  '0.022" (0.55mm)', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '8 pF', 
  '8 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 8.2PF 200V C0G/NP0 0402', 
  'VJ0402D8R2CXCAJ', 
  'https://www.digikey.com/en/products/detail/vishay-vitramon/VJ0402D8R2CXCAJ/3280874', 
  '0402 (1005 Metric)', 
  '200V', 
  'C0G, NP0', 
  '0402 (1005 Metric)', 
  'CAPACITOR', 
  '720-VJ0402D8R2CXCAJCT-ND', 
  'Active', 
  'Vishay Vitramon', 
  'High Q, Low Loss', 
  '2023-07-10T20:00:45.393', 
  '1', 
  '4663', 
  '=Part Number', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'http://www.vishay.com/docs/45071/vjhifreq.pdf', 
  'CAP 0402_1005 RF', 
  'Datasheet', 
  '±0.25pF', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.040" L x 0.020" W (1.02mm x 0.51mm)', 
  'VJ HIFREQ', 
  '0.024" (0.61mm)', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '8.2 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0402_1005 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 1.2PF 250V NP0 0603', 
  'GQM1875C2E1R2BB12D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GQM1875C2E1R2BB12D/2593395', 
  '0603 (1608 Metric)', 
  '250V', 
  'C0G, NP0', 
  '0603 (1608 Metric)', 
  'CAPACITOR', 
  '490-GQM1875C2E1R2BB12DCT-ND', 
  'Active', 
  'Murata Electronics', 
  'High Q, Low Loss', 
  '2023-07-10T20:03:13.967', 
  '1', 
  '4664', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GQM1875C2E1R2BB12-01.pdf', 
  'CAP 0603_1608 RF', 
  'Datasheet', 
  '±0.1pF', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  'GQM', 
  '0.031" (0.80mm)', 
  '0.07', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1.2 pF', 
  '1.2 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0603_1608 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 33PF 250V C0G/NP0 0603', 
  'VJ0603D330FXPAJ', 
  'https://www.digikey.com/en/products/detail/vishay-vitramon/VJ0603D330FXPAJ/5096828', 
  '0603 (1608 Metric)', 
  '250V', 
  'C0G, NP0', 
  '0603 (1608 Metric)', 
  'CAPACITOR', 
  '720-VJ0603D330FXPAJCT-ND', 
  'Active', 
  'Vishay Vitramon', 
  'High Q, Low Loss', 
  '2023-07-10T20:03:13.973', 
  '1', 
  '4665', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://www.vishay.com/docs/45258/vjhifreqseries.pdf', 
  'CAP 0603_1608 RF', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  'VJ HIFREQ', 
  '0.037" (0.94mm)', 
  '0.77', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '33 pF', 
  '33 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0603_1608 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 15PF 250V C0G/NP0 0603', 
  'VJ0603D150FXPAJ', 
  'https://www.digikey.com/en/products/detail/vishay-vitramon/VJ0603D150FXPAJ/5093998', 
  '0603 (1608 Metric)', 
  '250V', 
  'C0G, NP0', 
  '0603 (1608 Metric)', 
  'CAPACITOR', 
  '720-VJ0603D150FXPAJCT-ND', 
  'Active', 
  'Vishay Vitramon', 
  'High Q, Low Loss', 
  '2023-07-10T20:03:14.377', 
  '1', 
  '4666', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://www.vishay.com/docs/45258/vjhifreqseries.pdf', 
  'CAP 0603_1608 RF', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  'VJ HIFREQ', 
  '0.037" (0.94mm)', 
  '0.74', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '15 pF', 
  '15 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0603_1608 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CERAMIC CAP MLCC HIGH-Q 125C', 
  'GQM1875C2E4R0WB12D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GQM1875C2E4R0WB12D/13401856', 
  '0603 (1608 Metric)', 
  '250V', 
  'C0G, NP0', 
  '0603 (1608 Metric)', 
  'CAPACITOR', 
  '490-GQM1875C2E4R0WB12DCT-ND', 
  'Active', 
  'Murata Electronics', 
  'High Q, Low Loss', 
  '2023-07-10T20:03:14.620', 
  '1', 
  '4667', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GQM1875C2E4R0WB12-01.pdf', 
  'CAP 0603_1608 RF', 
  'Datasheet', 
  '±0.05pF', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  'GQM', 
  '0.031" (0.80mm)', 
  '0.10', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '4 pF', 
  '4 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0603_1608 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER MLCC', 
  'GQM1875C2E510FB12D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GQM1875C2E510FB12D/10696242', 
  '0603 (1608 Metric)', 
  '250V', 
  'C0G, NP0', 
  '0603 (1608 Metric)', 
  'CAPACITOR', 
  '490-GQM1875C2E510FB12DCT-ND', 
  'Active', 
  'Murata Electronics', 
  'High Q, Low Loss', 
  '2023-07-10T20:03:14.647', 
  '1', 
  '4668', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GQM1875C2E510FB12-01A.pdf', 
  'CAP 0603_1608 RF', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  'GQM', 
  '0.031" (0.80mm)', 
  '0.11', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '51 pF', 
  '51 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0603_1608 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER MLCC', 
  'GQM1875C2E820FB12D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GQM1875C2E820FB12D/10692092', 
  '0603 (1608 Metric)', 
  '250V', 
  'C0G, NP0', 
  '0603 (1608 Metric)', 
  'CAPACITOR', 
  '490-GQM1875C2E820FB12DCT-ND', 
  'Active', 
  'Murata Electronics', 
  'High Q, Low Loss', 
  '2023-07-10T20:03:14.670', 
  '1', 
  '4669', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GQM1875C2E820FB12-01A.pdf', 
  'CAP 0603_1608 RF', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  'GQM', 
  '0.031" (0.80mm)', 
  '0.11', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '82 pF', 
  '82 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0603_1608 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER MLCC', 
  'GQM1875C2E101FB12D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GQM1875C2E101FB12D/10696316', 
  '0603 (1608 Metric)', 
  '250V', 
  'C0G, NP0', 
  '0603 (1608 Metric)', 
  'CAPACITOR', 
  '490-GQM1875C2E101FB12DCT-ND', 
  'Active', 
  'Murata Electronics', 
  'High Q, Low Loss', 
  '2023-07-10T20:03:14.677', 
  '1', 
  '4670', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GQM1875C2E101FB12-01A.pdf', 
  'CAP 0603_1608 RF', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  'GQM', 
  '0.031" (0.80mm)', 
  '0.11', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '100 pF', 
  '100 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0603_1608 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 22PF 250V NP0 0805', 
  'GQM2195C2E220GB12D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GQM2195C2E220GB12D/2042735', 
  '0805 (2012 Metric)', 
  '250V', 
  'C0G, NP0', 
  '0805 (2012 Metric)', 
  'CAPACITOR', 
  '490-GQM2195C2E220GB12DCT-ND', 
  'Active', 
  'Murata Electronics', 
  'High Q, Low Loss', 
  '2023-07-10T20:06:22.607', 
  '1', 
  '4671', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GQM2195C2E220GB12-01.pdf', 
  'CAP 0805_2012 RF', 
  'Datasheet', 
  '±2%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  'GQM', 
  '0.039" (1.00mm)', 
  '0.33', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '22 pF', 
  '22 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0805_2012 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 27PF 250V NP0 0805', 
  'GQM2195C2E270GB12D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GQM2195C2E270GB12D/2042736', 
  '0805 (2012 Metric)', 
  '250V', 
  'C0G, NP0', 
  '0805 (2012 Metric)', 
  'CAPACITOR', 
  '490-GQM2195C2E270GB12DCT-ND', 
  'Active', 
  'Murata Electronics', 
  'High Q, Low Loss', 
  '2023-07-10T20:06:22.617', 
  '1', 
  '4672', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GQM2195C2E270GB12-01.pdf', 
  'CAP 0805_2012 RF', 
  'Datasheet', 
  '±2%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  'GQM', 
  '0.039" (1.00mm)', 
  '0.33', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '27 pF', 
  '27 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0805_2012 RF.PCBLIB'
);

INSERT INTO "Capacitors-Ceramic-RF" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER 1.2PF 250V NP0 0805', 
  'GQM2195C2E1R2WB12D', 
  'https://www.digikey.com/en/products/detail/murata-electronics/GQM2195C2E1R2WB12D/4420023', 
  '0805 (2012 Metric)', 
  '250V', 
  'C0G, NP0', 
  '0805 (2012 Metric)', 
  'CAPACITOR', 
  '490-GQM2195C2E1R2WB12DCT-ND', 
  'Active', 
  'Murata Electronics', 
  'High Q, Low Loss', 
  '2023-07-10T20:06:22.623', 
  '1', 
  '4673', 
  '=Value', 
  '-55°C ~ 125°C', 
  'RF, Microwave, High Frequency', 
  'https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GQM2195C2E1R2WB12-01.pdf', 
  'CAP 0805_2012 RF', 
  'Datasheet', 
  '±0.05pF', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  'GQM', 
  '0.037" (0.95mm)', 
  '0.22', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1.2 pF', 
  '1.2 pF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0805_2012 RF.PCBLIB'
);

