--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 12K OHM 1% 1/10W 0603', 
  'CRCW060312K0FKTA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/CRCW060312K0FKTA/1221658', 
  '0.020" (0.50mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-CRCW060312K0FKTACT-ND', 
  'Active', 
  'Vishay Dale', 
  'Automotive AEC-Q200', 
  '2023-07-10T19:31:32.443', 
  '1', 
  '78491', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.vishay.com/docs/20008/dcrcw.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.033" W (1.60mm x 0.85mm)', 
  '12 kOhms', 
  '0.1W, 1/10W', 
  'CRCW', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '12 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 22 OHM 1% 1/5W 0603', 
  'RC0603FR-7W22RL', 
  'https://www.digikey.com/en/products/detail/yageo/RC0603FR-7W22RL/17021550', 
  '0.022" (0.55mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0603', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '13-RC0603FR-7W22RLCT-ND', 
  'Active', 
  'Yageo', 
  'Moisture Resistant', 
  '2023-07-10T19:31:32.497', 
  '1', 
  '78493', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.yageo.com/upload/media/product/productsearch/datasheet/rchip/PYu-RC_Group_51_RoHS_L_12.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  '22 Ohms', 
  '0.2W, 1/5W', 
  'RC_L', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '22 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "Footprint Ref",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'THICK FILM LOW OHMIC CHIP RESIST', 
  'UCR03EVPFLR820', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/UCR03EVPFLR820/19531155', 
  '0.024" (0.60mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '0/ +150ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '511-UCR03EVPFLR820CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Automotive AEC-Q200, Current Sense', 
  '2023-07-10T19:31:32.520', 
  '1', 
  '78494', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'RES 0603_1608', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.034" W (1.60mm x 0.87mm)', 
  '820 mOhms', 
  '0.2W, 1/5W', 
  'UCR', 
  '0.13', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '820 mOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 220 OHM 5% 1/10W 0603', 
  'RCG0603220RJNEA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/RCG0603220RJNEA/4172406', 
  '0.020" (0.50mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0603', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-RCG0603220RJNEACT-ND', 
  'Active', 
  'Vishay Dale', 
  '2023-07-10T19:31:32.547', 
  '5000', 
  '78495', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.vishay.com/docs/20047/rcge3.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.061" L x 0.033" W (1.55mm x 0.85mm)', 
  '220 Ohms', 
  '0.1W, 1/10W', 
  'RCG e3', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '220 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 19.6K OHM 0.1% 1/10W 0603', 
  'RN73R1JTTD1962B25', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RN73R1JTTD1962B25/10011994', 
  '0.022" (0.55mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±25ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '2019-RN73R1JTTD1962B25CT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant', 
  '2023-07-10T19:31:32.567', 
  '1000', 
  '78496', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.koaspeer.com/pdfs/RN73R.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±0.1%', 
  'DigiKey', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  '19.6 kOhms', 
  '0.1W, 1/10W', 
  'RN73R', 
  '0.05', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '19.6 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 105K OHM 1% 1/10W 0603', 
  'CRCW0603105KFKTA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/CRCW0603105KFKTA/1221621', 
  '0.020" (0.50mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-CRCW0603105KFKTACT-ND', 
  'Active', 
  'Vishay Dale', 
  'Automotive AEC-Q200', 
  '2023-07-10T19:31:32.587', 
  '1', 
  '78497', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.vishay.com/docs/20008/dcrcw.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.033" W (1.60mm x 0.85mm)', 
  '105 kOhms', 
  '0.1W, 1/10W', 
  'CRCW', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '105 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 24.3K OHM 1% 1/10W 0603', 
  'CRCW060324K3FKTA', 
  'https://www.digikey.com/en/products/detail/vishay-dale/CRCW060324K3FKTA/1221885', 
  '0.020" (0.50mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-CRCW060324K3FKTACT-ND', 
  'Active', 
  'Vishay Dale', 
  'Automotive AEC-Q200', 
  '2023-07-10T19:31:32.600', 
  '1', 
  '78498', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.vishay.com/docs/20008/dcrcw.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.033" W (1.60mm x 0.85mm)', 
  '24.3 kOhms', 
  '0.1W, 1/10W', 
  'CRCW', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '24.3 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 100 OHM 1% 1/10W 0603', 
  'CRCW0603100RFHEAP', 
  'https://www.digikey.com/en/products/detail/vishay-dale/CRCW0603100RFHEAP/5070644', 
  '0.020" (0.50mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±50ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-CRCW0603100RFHEAPCT-ND', 
  'Active', 
  'Vishay Dale', 
  'Automotive AEC-Q200', 
  '2023-07-10T19:31:32.620', 
  '1', 
  '78499', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://media.digikey.com/pdf/Data%20Sheets/Vishay%20Dale%20PDFs/D_CRCW-P_e3_Series.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.033" W (1.60mm x 0.85mm)', 
  '100 Ohms', 
  '0.1W, 1/10W', 
  'CRCW-P', 
  '0.03', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '100 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 27K OHM 1% 1/10W 0603', 
  'CRCW060327K0FHEAP', 
  'https://www.digikey.com/en/products/detail/vishay-dale/CRCW060327K0FHEAP/5071751', 
  '0.020" (0.50mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±50ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-CRCW060327K0FHEAPCT-ND', 
  'Active', 
  'Vishay Dale', 
  'Automotive AEC-Q200', 
  '2023-07-10T19:31:32.647', 
  '1', 
  '78500', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://media.digikey.com/pdf/Data%20Sheets/Vishay%20Dale%20PDFs/D_CRCW-P_e3_Series.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.033" W (1.60mm x 0.85mm)', 
  '27 kOhms', 
  '0.1W, 1/10W', 
  'CRCW-P', 
  '0.03', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '27 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 154K OHM 1% 1/3W 0603', 
  'CRCW0603154KFKEAHP', 
  'https://www.digikey.com/en/products/detail/vishay-dale/CRCW0603154KFKEAHP/2226414', 
  '0.022" (0.55mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-CRCW0603154KFKEAHPCT-ND', 
  'Active', 
  'Vishay Dale', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-07-10T19:31:32.657', 
  '1', 
  '78501', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.vishay.com/docs/20043/crcwhpe3.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.033" W (1.60mm x 0.85mm)', 
  '154 kOhms', 
  '0.333W, 1/3W', 
  'CRCW-HP', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '154 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 2K OHM 1% 1/10W 0603', 
  'CRCW06032K00FHEAP', 
  'https://www.digikey.com/en/products/detail/vishay-dale/CRCW06032K00FHEAP/5071814', 
  '0.020" (0.50mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±50ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-CRCW06032K00FHEAPCT-ND', 
  'Active', 
  'Vishay Dale', 
  'Automotive AEC-Q200', 
  '2023-07-10T19:31:32.680', 
  '1', 
  '78502', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://media.digikey.com/pdf/Data%20Sheets/Vishay%20Dale%20PDFs/D_CRCW-P_e3_Series.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.033" W (1.60mm x 0.85mm)', 
  '2 kOhms', 
  '0.1W, 1/10W', 
  'CRCW-P', 
  '0.03', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0603" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 18K OHM 1% 1/10W 0603', 
  'CRCW060318K0FHEAP', 
  'https://www.digikey.com/en/products/detail/vishay-dale/CRCW060318K0FHEAP/5071117', 
  '0.020" (0.50mm)', 
  '0603 (1608 Metric)', 
  '2', 
  '±50ppm/°C', 
  '0603', 
  'AEC-Q200', 
  '0603 (1608 Metric)', 
  'RESISTOR', 
  '541-CRCW060318K0FHEAPCT-ND', 
  'Active', 
  'Vishay Dale', 
  'Automotive AEC-Q200', 
  '2023-07-10T19:31:32.700', 
  '1', 
  '78503', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://media.digikey.com/pdf/Data%20Sheets/Vishay%20Dale%20PDFs/D_CRCW-P_e3_Series.pdf', 
  'RES 0603_1608', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.063" L x 0.033" W (1.60mm x 0.85mm)', 
  '18 kOhms', 
  '0.1W, 1/10W', 
  'CRCW-P', 
  '0.03', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '18 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0603_1608.PCBLIB'
);

