--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."RF-Balun" (
  "Frequency Range",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Insertion Loss (Max)",
  "Comment",
  "ComponentLink1URL",
  "Impedance - Unbalanced/Balanced",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '100MHz ~ 1GHz', 
  'BALUN 100MHZ-1GHZ 50/50 0805', 
  'DXW21HN5011BL', 
  'https://www.digikey.com/en/products/detail/murata-electronics/DXW21HN5011BL/8323482', 
  '0805 (2012 Metric)', 
  '0805 (2012 Metric)', 
  'MURATA DXW21HN', 
  '490-17670-1-ND', 
  'Active', 
  'Murata Electronics', 
  '2025-07-16T01:48:54.213', 
  '1', 
  '1.0dB', 
  '=Part Number', 
  'https://www.murata.com/en-us/products/productdata/8796776759326/EFKA0005.pdf', 
  '50 / 50Ohm', 
  'MURATA DXW21HN', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '-', 
  '0.41', 
  'symbols/RF - Balun/SCH - RF - BALUN - MURATA DXW21HN.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/RF Balun/PCB - RF BALUN - MURATA DXW21HN.PcbLib'
);

