--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Fsn65hvd78',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/texas-instruments/SN65HVD78DR/296-36714-1-ND/4341340',
  "Data Rate" = '50Mbps',
  "Description" = 'IC TRANSCEIVER HALF 1/1 8SOIC',
  "Duplex" = 'Half',
  "Footprint Path" = 'footprints/Leaded - SOIC/PCB - LEADED - SOIC - TI SOIC-8 D.PCBLIB',
  "Footprint Ref" = 'TI SOIC-8 D',
  "LastUpdated" = '2023-01-02T21:08:08.900',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Texas Instruments',
  "Part Number" = 'SN65HVD78DR',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '1/1',
  "Operating Temperature" = '-40°C ~ 125°C',
  "Package / Case" = '8-SOIC (0.154", 3.90mm Width)',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '1.34',
  "Protocol" = 'RS422, RS485',
  "Receiver Hysteresis" = '80mV',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '296-36714-1-ND',
  "Supplier Device Package" = '8-SOIC',
  "Library Path" = 'symbols/Interface/SCH - INTERFACE - TI SN65HVD7X.SCHLIB',
  "Library Ref" = 'TI SN65HVD7X',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '3V ~ 3.6V'
WHERE (id = 1);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Fsn65hvd72',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/texas-instruments/SN65HVD72DR/296-39179-1-ND/5143186',
  "Data Rate" = '250kbps',
  "Description" = 'IC TRANSCEIVER HALF 1/1 8SOIC',
  "Duplex" = 'Half',
  "Footprint Path" = 'footprints/Leaded - SOIC/PCB - LEADED - SOIC - TI SOIC-8 D.PCBLIB',
  "Footprint Ref" = 'TI SOIC-8 D',
  "LastUpdated" = '2023-01-02T21:08:08.917',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Texas Instruments',
  "Part Number" = 'SN65HVD72DR',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '1/1',
  "Operating Temperature" = '-40°C ~ 125°C',
  "Package / Case" = '8-SOIC (0.154", 3.90mm Width)',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '1.13',
  "Protocol" = 'RS422, RS485',
  "Receiver Hysteresis" = '80mV',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '296-39179-1-ND',
  "Supplier Device Package" = '8-SOIC',
  "Library Path" = 'symbols/Interface/SCH - INTERFACE - TI SN65HVD7X.SCHLIB',
  "Library Ref" = 'TI SN65HVD7X',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '3V ~ 3.6V'
WHERE (id = 2);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Fsn65hvd75',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/texas-instruments/SN65HVD75DR/296-38570-1-ND/5034448',
  "Data Rate" = '20Mbps',
  "Description" = 'IC TRANSCEIVER HALF 1/1 8SOIC',
  "Duplex" = 'Half',
  "Footprint Path" = 'footprints/Leaded - SOIC/PCB - LEADED - SOIC - TI SOIC-8 D.PCBLIB',
  "Footprint Ref" = 'TI SOIC-8 D',
  "LastUpdated" = '2023-01-02T21:08:08.937',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Texas Instruments',
  "Part Number" = 'SN65HVD75DR',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '1/1',
  "Operating Temperature" = '-40°C ~ 125°C',
  "Package / Case" = '8-SOIC (0.154", 3.90mm Width)',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '1.13',
  "Protocol" = 'RS422, RS485',
  "Receiver Hysteresis" = '80mV',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '296-38570-1-ND',
  "Supplier Device Package" = '8-SOIC',
  "Library Path" = 'symbols/Interface/SCH - INTERFACE - TI SN65HVD7X.SCHLIB',
  "Library Ref" = 'TI SN65HVD7X',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '3V ~ 3.6V'
WHERE (id = 3);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Fsn65hvd1785',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/texas-instruments/SN65HVD1787DR/296-50388-1-ND/9685527',
  "Data Rate" = '10Mbps',
  "Description" = 'IC TRANSCEIVER HALF 1/1 8SOIC',
  "Duplex" = 'Half',
  "Footprint Path" = 'footprints/Leaded - SOIC/PCB - LEADED - SOIC - TI SOIC-8 D.PCBLIB',
  "Footprint Ref" = 'TI SOIC-8 D',
  "LastUpdated" = '2023-01-02T21:08:09.073',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Texas Instruments',
  "Part Number" = 'SN65HVD1787DR',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '1/1',
  "Operating Temperature" = '-40°C ~ 105°C',
  "Package / Case" = '8-SOIC (0.154", 3.90mm Width)',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '2.03',
  "Protocol" = 'RS422, RS485',
  "Receiver Hysteresis" = '50mV',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '296-50388-1-ND',
  "Supplier Device Package" = '8-SOIC',
  "Library Path" = 'symbols/Interface/SCH - INTERFACE - TI SN65HVD178X.SCHLIB',
  "Library Ref" = 'TI SN65HVD178X',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '4.5V ~ 5.5V'
WHERE (id = 4);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Fsn65hvd1785',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/texas-instruments/SN65HVD1786DR/296-41388-1-ND/5222885',
  "Data Rate" = '1Mbps',
  "Description" = 'IC TRANSCEIVER HALF 1/1 8SOIC',
  "Duplex" = 'Half',
  "Footprint Path" = 'footprints/Leaded - SOIC/PCB - LEADED - SOIC - TI SOIC-8 D.PCBLIB',
  "Footprint Ref" = 'TI SOIC-8 D',
  "LastUpdated" = '2023-01-02T21:08:09.087',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Texas Instruments',
  "Part Number" = 'SN65HVD1786DR',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '1/1',
  "Operating Temperature" = '-40°C ~ 105°C',
  "Package / Case" = '8-SOIC (0.154", 3.90mm Width)',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '1.63',
  "Protocol" = 'RS422, RS485',
  "Receiver Hysteresis" = '50mV',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '296-41388-1-ND',
  "Supplier Device Package" = '8-SOIC',
  "Library Path" = 'symbols/Interface/SCH - INTERFACE - TI SN65HVD178X.SCHLIB',
  "Library Ref" = 'TI SN65HVD178X',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '4.5V ~ 5.5V'
WHERE (id = 5);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Fsn65hvd1785',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/texas-instruments/SN65HVD1785DR/296-39174-1-ND/5143182',
  "Data Rate" = '115Kbps',
  "Description" = 'IC TRANSCEIVER HALF 1/1 8SOIC',
  "Duplex" = 'Half',
  "Footprint Path" = 'footprints/Leaded - SOIC/PCB - LEADED - SOIC - TI SOIC-8 D.PCBLIB',
  "Footprint Ref" = 'TI SOIC-8 D',
  "LastUpdated" = '2023-01-02T21:08:09.100',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Texas Instruments',
  "Part Number" = 'SN65HVD1785DR',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '1/1',
  "Operating Temperature" = '-40°C ~ 105°C',
  "Package / Case" = '8-SOIC (0.154", 3.90mm Width)',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '1.63',
  "Protocol" = 'RS422, RS485',
  "Receiver Hysteresis" = '50mV',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '296-39174-1-ND',
  "Supplier Device Package" = '8-SOIC',
  "Library Path" = 'symbols/Interface/SCH - INTERFACE - TI SN65HVD178X.SCHLIB',
  "Library Ref" = 'TI SN65HVD178X',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '4.5V ~ 5.5V'
WHERE (id = 6);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Fsn65hvd1780',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/texas-instruments/SN65HVD1780DR/296-23800-1-ND/1957756',
  "Data Rate" = '115Kbps',
  "Description" = 'IC TRANSCEIVER HALF 1/1 8SOIC',
  "Duplex" = 'Half',
  "Footprint Path" = 'footprints/Leaded - SOIC/PCB - LEADED - SOIC - TI SOIC-8 D.PCBLIB',
  "Footprint Ref" = 'TI SOIC-8 D',
  "LastUpdated" = '2023-01-02T21:08:09.113',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Texas Instruments',
  "Part Number" = 'SN65HVD1780DR',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '1/1',
  "Operating Temperature" = '-40°C ~ 125°C',
  "Package / Case" = '8-SOIC (0.154", 3.90mm Width)',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '2.08',
  "Protocol" = 'RS422, RS485',
  "Receiver Hysteresis" = '50mV',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '296-23800-1-ND',
  "Supplier Device Package" = '8-SOIC',
  "Library Path" = 'symbols/Interface/SCH - INTERFACE - TI SN65HVD178X.SCHLIB',
  "Library Ref" = 'TI SN65HVD178X',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '3.15V ~ 5.5V'
WHERE (id = 7);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Fsn65hvd1781',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/texas-instruments/SN65HVD1781DR/296-23118-1-ND/1805641',
  "Data Rate" = '1Mbps',
  "Description" = 'IC TRANSCEIVER HALF 1/1 8SOIC',
  "Duplex" = 'Half',
  "Footprint Path" = 'footprints/Leaded - SOIC/PCB - LEADED - SOIC - TI SOIC-8 D.PCBLIB',
  "Footprint Ref" = 'TI SOIC-8 D',
  "LastUpdated" = '2023-01-02T21:08:09.123',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Texas Instruments',
  "Part Number" = 'SN65HVD1781DR',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '1/1',
  "Operating Temperature" = '-40°C ~ 125°C',
  "Package / Case" = '8-SOIC (0.154", 3.90mm Width)',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '2.08',
  "Protocol" = 'RS422, RS485',
  "Receiver Hysteresis" = '50mV',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '296-23118-1-ND',
  "Supplier Device Package" = '8-SOIC',
  "Library Path" = 'symbols/Interface/SCH - INTERFACE - TI SN65HVD178X.SCHLIB',
  "Library Ref" = 'TI SN65HVD178X',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '3.15V ~ 5.5V'
WHERE (id = 8);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Fsn65hvd1780',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/texas-instruments/SN65HVD1782DR/296-23802-1-ND/1957757',
  "Data Rate" = '10Mbps',
  "Description" = 'IC TRANSCEIVER HALF 1/1 8SOIC',
  "Duplex" = 'Half',
  "Footprint Path" = 'footprints/Leaded - SOIC/PCB - LEADED - SOIC - TI SOIC-8 D.PCBLIB',
  "Footprint Ref" = 'TI SOIC-8 D',
  "LastUpdated" = '2023-01-02T21:08:09.137',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Texas Instruments',
  "Part Number" = 'SN65HVD1782DR',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '1/1',
  "Operating Temperature" = '-40°C ~ 125°C',
  "Package / Case" = '8-SOIC (0.154", 3.90mm Width)',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '2.03',
  "Protocol" = 'RS422, RS485',
  "Receiver Hysteresis" = '50mV',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '296-23802-1-ND',
  "Supplier Device Package" = '8-SOIC',
  "Library Path" = 'symbols/Interface/SCH - INTERFACE - TI SN65HVD178X.SCHLIB',
  "Library Ref" = 'TI SN65HVD178X',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '3.15V ~ 5.5V'
WHERE (id = 9);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.st.com/content/ccc/resource/technical/document/datasheet/be/f4/e5/fd/b0/df/40/72/CD00003137.pdf/files/CD00003137.pdf/jcr:content/translations/en.CD00003137.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/stmicroelectronics/ST3485ECDR/497-6540-1-ND/1865351',
  "Data Rate" = '15Mbps',
  "Description" = 'IC TRANSCEIVER HALF 1/1 8SO',
  "Duplex" = 'Half',
  "Footprint Path" = 'footprints/Leaded - SOIC/PCB - LEADED - SOIC - ST SOIC-8N.PCBLIB',
  "Footprint Ref" = 'ST SOIC-8N',
  "LastUpdated" = '2023-01-02T21:08:09.297',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'STMicroelectronics',
  "Part Number" = 'ST3485ECDR',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '1/1',
  "Package / Case" = '8-SOIC (0.154", 3.90mm Width)',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '0.68',
  "Protocol" = 'RS422, RS485',
  "Receiver Hysteresis" = '70mV',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '497-6540-1-ND',
  "Supplier Device Package" = '8-SO',
  "Library Path" = 'symbols/Interface/SCH - INTERFACE - ST ST3485EX.SCHLIB',
  "Library Ref" = 'ST ST3485EX',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '3V ~ 3.6V'
WHERE (id = 11);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.st.com/content/ccc/resource/technical/document/datasheet/be/f4/e5/fd/b0/df/40/72/CD00003137.pdf/files/CD00003137.pdf/jcr:content/translations/en.CD00003137.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'https://www.digikey.com/en/products/detail/stmicroelectronics/ST3485EIYDT/6006101',
  "Data Rate" = '15Mbps',
  "Description" = 'IC TRANSCEIVER HALF 1/1 8SO',
  "Duplex" = 'Half',
  "Footprint Path" = 'footprints/Leaded - SOIC/PCB - LEADED - SOIC - ST SOIC-8N.PCBLIB',
  "Footprint Ref" = 'ST SOIC-8N',
  "LastUpdated" = '2023-01-02T21:08:09.317',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'STMicroelectronics',
  "Part Number" = 'ST3485EIYDT',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '1/1',
  "Operating Temperature" = '-40°C ~ 125°C',
  "Package / Case" = '8-SOIC (0.154", 3.90mm Width)',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '2.07',
  "Protocol" = 'RS422, RS485',
  "Receiver Hysteresis" = '70 mV',
  "Series" = 'Automotive, AEC-Q100',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '497-16528-1-ND',
  "Supplier Device Package" = '8-SOIC',
  "Library Path" = 'symbols/Interface/SCH - INTERFACE - ST ST3485EX.SCHLIB',
  "Library Ref" = 'ST ST3485EX',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '3V ~ 3.6V'
WHERE (id = 12);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.st.com/content/ccc/resource/technical/document/datasheet/be/f4/e5/fd/b0/df/40/72/CD00003137.pdf/files/CD00003137.pdf/jcr:content/translations/en.CD00003137.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'https://www.digikey.com/en/products/detail/stmicroelectronics/ST3485EIDT/6192768',
  "Data Rate" = '15Mbps',
  "Description" = 'IC TRANSCEIVER HALF 1/1 8SO',
  "Duplex" = 'Half',
  "Footprint Path" = 'footprints/Leaded - SOIC/PCB - LEADED - SOIC - ST SOIC-8N.PCBLIB',
  "Footprint Ref" = 'ST SOIC-8N',
  "LastUpdated" = '2023-01-02T21:08:09.330',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'STMicroelectronics',
  "Part Number" = 'ST3485EIDT',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '1/1',
  "Operating Temperature" = '-40°C ~ 125°C',
  "Package / Case" = '8-SOIC (0.154", 3.90mm Width)',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '1.19',
  "Protocol" = 'RS422, RS485',
  "Receiver Hysteresis" = '70 mV',
  "Series" = 'Automotive, AEC-Q100',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '497-16693-1-ND',
  "Supplier Device Package" = '8-SOIC',
  "Library Path" = 'symbols/Interface/SCH - INTERFACE - ST ST3485EX.SCHLIB',
  "Library Ref" = 'ST ST3485EX',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '3V ~ 3.6V'
WHERE (id = 13);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.st.com/content/ccc/resource/technical/document/datasheet/be/f4/e5/fd/b0/df/40/72/CD00003137.pdf/files/CD00003137.pdf/jcr:content/translations/en.CD00003137.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'https://www.digikey.com/en/products/detail/stmicroelectronics/ST3485EBDR/599328',
  "Data Rate" = '15Mbps',
  "Description" = 'IC TRANSCEIVER HALF 1/1 8SO',
  "Duplex" = 'Half',
  "Footprint Path" = 'footprints/Leaded - SOIC/PCB - LEADED - SOIC - ST SOIC-8N.PCBLIB',
  "Footprint Ref" = 'ST SOIC-8N',
  "LastUpdated" = '2023-01-02T21:08:09.347',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'STMicroelectronics',
  "Part Number" = 'ST3485EBDR',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '1/1',
  "Operating Temperature" = '-40°C ~ 85°C',
  "Package / Case" = '8-SOIC (0.154", 3.90mm Width)',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '1.34',
  "Protocol" = 'RS422, RS485',
  "Receiver Hysteresis" = '70 mV',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '497-2080-1-ND',
  "Supplier Device Package" = '8-SOIC',
  "Library Path" = 'symbols/Interface/SCH - INTERFACE - ST ST3485EX.SCHLIB',
  "Library Ref" = 'ST ST3485EX',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '3V ~ 3.6V'
WHERE (id = 14);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = '//media.digikey.com/pdf/Data%20Sheets/ST%20Microelectronics%20PDFS/ST1480AB_C_Rev_4.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/stmicroelectronics/ST1480ABDR/497-2046-1-ND/599132',
  "Data Rate" = '15Mbps',
  "Description" = 'IC TRANSCEIVER HALF 1/1 8SO',
  "Duplex" = 'Half',
  "Footprint Path" = 'footprints/Leaded - SOIC/PCB - LEADED - SOIC - ST SOIC-8N.PCBLIB',
  "Footprint Ref" = 'ST SOIC-8N',
  "LastUpdated" = '2023-01-02T21:08:09.477',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'STMicroelectronics',
  "Part Number" = 'ST1480ABDR',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '1/1',
  "Operating Temperature" = '-40°C ~ 85°C',
  "Package / Case" = '8-SOIC (0.154", 3.90mm Width)',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '0.66',
  "Protocol" = 'RS422, RS485',
  "Receiver Hysteresis" = '30µV',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '497-2046-1-ND',
  "Supplier Device Package" = '8-SO',
  "Library Path" = 'symbols/Interface/SCH - INTERFACE - ST ST1480AX.SCHLIB',
  "Library Ref" = 'ST ST1480AX',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '3V ~ 3.6V'
WHERE (id = 15);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = '//media.digikey.com/pdf/Data%20Sheets/ST%20Microelectronics%20PDFS/ST1480AB_C_Rev_4.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/stmicroelectronics/ST1480ACDR/497-3726-1-ND/686444',
  "Data Rate" = '15Mbps',
  "Description" = 'IC TRANSCEIVER HALF 1/1 8SO',
  "Duplex" = 'Half',
  "Footprint Path" = 'footprints/Leaded - SOIC/PCB - LEADED - SOIC - ST SOIC-8N.PCBLIB',
  "Footprint Ref" = 'ST SOIC-8N',
  "LastUpdated" = '2023-01-02T21:08:09.490',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'STMicroelectronics',
  "Part Number" = 'ST1480ACDR',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '1/1',
  "Package / Case" = '8-SOIC (0.154", 3.90mm Width)',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '0.63',
  "Protocol" = 'RS422, RS485',
  "Receiver Hysteresis" = '30µV',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '497-3726-1-ND',
  "Supplier Device Package" = '8-SO',
  "Library Path" = 'symbols/Interface/SCH - INTERFACE - ST ST1480AX.SCHLIB',
  "Library Ref" = 'ST ST1480AX',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '3V ~ 3.6V'
WHERE (id = 16);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en586588',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/microchip-technology/LAN8720AI-CP/638-1084-ND/2166036',
  "Description" = 'IC TRANSCEIVER FULL 2/2 24QFN',
  "Duplex" = 'Full',
  "Footprint Path" = 'footprints/Leadless - QFN/PCB - LEADLESS - QFN - SMSC QFN-24 4X4MM.PCBLIB',
  "Footprint Ref" = 'SMSC QFN-24 4X4MM',
  "LastUpdated" = '2023-01-02T21:08:09.643',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Microchip Technology',
  "Part Number" = 'LAN8720AI-CP',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '2/2',
  "Operating Temperature" = '-40°C ~ 85°C',
  "Package / Case" = '24-VFQFN Exposed Pad',
  "Packaging" = 'Tray',
  "Part Status" = 'Active',
  "Price" = '1.45',
  "Protocol" = 'RMII',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '638-1084-ND',
  "Supplier Device Package" = '24-QFN-EP (4x4)',
  "Library Path" = 'symbols/Ethernet/SCH - ETHERNET - SMSC LAN8720.SCHLIB',
  "Library Ref" = 'SMSC LAN8720',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '1.6V ~ 3.6V'
WHERE (id = 21);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en586588',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/microchip-technology/LAN8720A-CP/638-1080-ND/2051556',
  "Description" = 'IC TRANSCEIVER FULL 2/2 24QFN',
  "Duplex" = 'Full',
  "Footprint Path" = 'footprints/Leadless - QFN/PCB - LEADLESS - QFN - SMSC QFN-24 4X4MM.PCBLIB',
  "Footprint Ref" = 'SMSC QFN-24 4X4MM',
  "LastUpdated" = '2023-01-02T21:08:09.660',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Microchip Technology',
  "Part Number" = 'LAN8720A-CP',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '2/2',
  "Package / Case" = '24-VFQFN Exposed Pad',
  "Packaging" = 'Tray',
  "Part Status" = 'Active',
  "Price" = '1.16',
  "Protocol" = 'RMII',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '638-1080-ND',
  "Supplier Device Package" = '24-QFN-EP (4x4)',
  "Library Path" = 'symbols/Ethernet/SCH - ETHERNET - SMSC LAN8720.SCHLIB',
  "Library Ref" = 'SMSC LAN8720',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '1.6V ~ 3.6V'
WHERE (id = 22);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en586588',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/microchip-technology/LAN8720AI-CP-TR/LAN8720AI-CP-CT-ND/5011022',
  "Description" = 'IC TRANSCEIVER FULL 2/2 24QFN',
  "Duplex" = 'Full',
  "Footprint Path" = 'footprints/Leadless - QFN/PCB - LEADLESS - QFN - SMSC QFN-24 4X4MM.PCBLIB',
  "Footprint Ref" = 'SMSC QFN-24 4X4MM',
  "LastUpdated" = '2023-01-02T21:08:09.673',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Microchip Technology',
  "Part Number" = 'LAN8720AI-CP-TR',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '2/2',
  "Operating Temperature" = '-40°C ~ 85°C',
  "Package / Case" = '24-VFQFN Exposed Pad',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '1.16',
  "Protocol" = 'RMII',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'LAN8720AI-CP-CT-ND',
  "Supplier Device Package" = '24-SQFN (4x4)',
  "Library Path" = 'symbols/Ethernet/SCH - ETHERNET - SMSC LAN8720.SCHLIB',
  "Library Ref" = 'SMSC LAN8720',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '1.6V ~ 3.6V'
WHERE (id = 23);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en586588',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/microchip-technology/LAN8720A-CP-TR/LAN8720A-CP-CT-ND/4307900',
  "Description" = 'IC TRANSCEIVER FULL 2/2 24QFN',
  "Duplex" = 'Full',
  "Footprint Path" = 'footprints/Leadless - QFN/PCB - LEADLESS - QFN - SMSC QFN-24 4X4MM.PCBLIB',
  "Footprint Ref" = 'SMSC QFN-24 4X4MM',
  "LastUpdated" = '2023-01-02T21:08:09.687',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Microchip Technology',
  "Part Number" = 'LAN8720A-CP-TR',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '2/2',
  "Package / Case" = '24-VFQFN Exposed Pad',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '0.94',
  "Protocol" = 'RMII',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'LAN8720A-CP-CT-ND',
  "Supplier Device Package" = '24-QFN (4x4)',
  "Library Path" = 'symbols/Ethernet/SCH - ETHERNET - SMSC LAN8720.SCHLIB',
  "Library Ref" = 'SMSC LAN8720',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '1.6V ~ 3.6V'
WHERE (id = 24);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en586588',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/microchip-technology/LAN8720A-CP-TR-ABC/LAN8720A-CP-TR-ABCCT-ND/9168867',
  "Description" = 'IC TRANSCEIVER FULL 2/2 24SQFN',
  "Duplex" = 'Full',
  "Footprint Path" = 'footprints/Leadless - QFN/PCB - LEADLESS - QFN - SMSC QFN-24 4X4MM.PCBLIB',
  "Footprint Ref" = 'SMSC QFN-24 4X4MM',
  "LastUpdated" = '2023-01-02T21:08:09.707',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Microchip Technology',
  "Part Number" = 'LAN8720A-CP-TR-ABC',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '2/2',
  "Package / Case" = '24-VFQFN Exposed Pad',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '0.81',
  "Protocol" = 'RMII',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'LAN8720A-CP-TR-ABCCT-ND',
  "Supplier Device Package" = '24-SQFN (4x4)',
  "Library Path" = 'symbols/Ethernet/SCH - ETHERNET - SMSC LAN8720.SCHLIB',
  "Library Ref" = 'SMSC LAN8720',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '1.6V ~ 3.6V'
WHERE (id = 25);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en586588',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/microchip-technology/LAN8720AI-CP-ABC/LAN8720AI-CP-ABC-ND/4790014',
  "Description" = 'IC TRANSCEIVER FULL 2/2 24SQFN',
  "Duplex" = 'Full',
  "Footprint Path" = 'footprints/Leadless - QFN/PCB - LEADLESS - QFN - SMSC QFN-24 4X4MM.PCBLIB',
  "Footprint Ref" = 'SMSC QFN-24 4X4MM',
  "LastUpdated" = '2023-01-02T21:08:09.727',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Microchip Technology',
  "Part Number" = 'LAN8720AI-CP-ABC',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '2/2',
  "Operating Temperature" = '-40°C ~ 85°C',
  "Package / Case" = '24-VFQFN Exposed Pad',
  "Packaging" = 'Tray',
  "Part Status" = 'Active',
  "Price" = '1.26',
  "Protocol" = 'RMII',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'LAN8720AI-CP-ABC-ND',
  "Supplier Device Package" = '24-SQFN (4x4)',
  "Library Path" = 'symbols/Ethernet/SCH - ETHERNET - SMSC LAN8720.SCHLIB',
  "Library Ref" = 'SMSC LAN8720',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '1.6V ~ 3.6V'
WHERE (id = 26);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en586588',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/microchip-technology/LAN8720AI-CP-TR-ABC/LAN8720AI-CP-TR-ABCCT-ND/9643672',
  "Description" = 'IC TRANSCEIVER FULL 2/2 24SQFN',
  "Duplex" = 'Full',
  "Footprint Path" = 'footprints/Leadless - QFN/PCB - LEADLESS - QFN - SMSC QFN-24 4X4MM.PCBLIB',
  "Footprint Ref" = 'SMSC QFN-24 4X4MM',
  "LastUpdated" = '2023-01-02T21:08:09.753',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Microchip Technology',
  "Part Number" = 'LAN8720AI-CP-TR-ABC',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '2/2',
  "Operating Temperature" = '-40°C ~ 85°C',
  "Package / Case" = '24-VFQFN Exposed Pad',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Price" = '1.01',
  "Protocol" = 'RMII',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'LAN8720AI-CP-TR-ABCCT-ND',
  "Supplier Device Package" = '24-SQFN (4x4)',
  "Library Path" = 'symbols/Ethernet/SCH - ETHERNET - SMSC LAN8720.SCHLIB',
  "Library Ref" = 'SMSC LAN8720',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '1.6V ~ 3.6V'
WHERE (id = 27);

UPDATE "Interface-DriversReceiversTransceivers"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en586588',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/microchip-technology/LAN8720A-CP-ABC/LAN8720A-CP-ABC-ND/6192901',
  "Description" = 'IC TRANSCEIVER FULL 2/2 24SQFN',
  "Duplex" = 'Full',
  "Footprint Path" = 'footprints/Leadless - QFN/PCB - LEADLESS - QFN - SMSC QFN-24 4X4MM.PCBLIB',
  "Footprint Ref" = 'SMSC QFN-24 4X4MM',
  "LastUpdated" = '2023-01-02T21:08:09.780',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Microchip Technology',
  "Part Number" = 'LAN8720A-CP-ABC',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Number of Drivers/Receivers" = '2/2',
  "Package / Case" = '24-VFQFN Exposed Pad',
  "Packaging" = 'Tray',
  "Part Status" = 'Active',
  "Price" = '1.01',
  "Protocol" = 'RMII',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'LAN8720A-CP-ABC-ND',
  "Supplier Device Package" = '24-SQFN (4x4)',
  "Library Path" = 'symbols/Ethernet/SCH - ETHERNET - SMSC LAN8720.SCHLIB',
  "Library Ref" = 'SMSC LAN8720',
  "Type" = 'Transceiver',
  "Voltage - Supply" = '1.6V ~ 3.6V'
WHERE (id = 28);

