--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

UPDATE "MOSFET-Arrays-P-Ch"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://assets.nexperia.com/documents/data-sheet/BSS84AKS.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/nexperia-usa-inc/BSS84AKS115/1727-6480-1-ND/2763928',
  "Current - Continuous Drain (Id) @ 25°C" = '160mA',
  "Description" = 'MOSFET 2P-CH 50V 0.16A 6TSSOP',
  "Drain to Source Voltage (Vdss)" = '50V',
  "FET Feature" = 'Logic Level Gate',
  "FET Type" = '2 P-Channel (Dual)',
  "Footprint Path" = 'footprints/Leaded - SOT/PCB - LEADED - SOT - NXP SOT-363.PCBLIB',
  "Footprint Ref" = 'NXP SOT-363',
  "Gate Charge (Qg) (Max) @ Vgs" = '0.35nC @ 5V',
  "Input Capacitance (Ciss) (Max) @ Vds" = '36pF @ 25V',
  "LastUpdated" = '2023-01-02T21:10:58.380',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Nexperia USA Inc.',
  "Part Number" = 'BSS84AKS,115',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Operating Temperature" = '-55°C ~ 150°C (TJ)',
  "Package / Case" = '6-TSSOP, SC-88, SOT-363',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Power - Max" = '445mW',
  "Price" = '0.08',
  "Rds On (Max) @ Id, Vgs" = '7.5Ohm @ 100mA, 10V',
  "Series" = 'Automotive, AEC-Q101, TrenchMOS™',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '1727-6480-1-ND',
  "Supplier Device Package" = '6-TSSOP',
  "Library Path" = 'symbols/FET - P-CH/SCH - FET - P-CH - NXP DUAL MOSFET P-CH SOT-363.SCHLIB',
  "Library Ref" = 'NXP DUAL MOSFET P-CH SOT-363',
  "Vgs(th) (Max) @ Id" = '2.1V @ 250µA'
WHERE (id = 1);

UPDATE "MOSFET-Arrays-P-Ch"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://assets.nexperia.com/documents/data-sheet/NX3008PBKS.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/nexperia-usa-inc/NX3008PBKS115/1727-1282-1-ND/4386085',
  "Current - Continuous Drain (Id) @ 25°C" = '200mA',
  "Description" = 'MOSFET 2P-CH 30V 0.2A 6TSSOP',
  "Drain to Source Voltage (Vdss)" = '30V',
  "FET Feature" = 'Logic Level Gate',
  "FET Type" = '2 P-Channel (Dual)',
  "Footprint Path" = 'footprints/Leaded - SOT/PCB - LEADED - SOT - NXP SOT-363.PCBLIB',
  "Footprint Ref" = 'NXP SOT-363',
  "Gate Charge (Qg) (Max) @ Vgs" = '0.75nC @ 4.5V',
  "Input Capacitance (Ciss) (Max) @ Vds" = '46pF @ 15V',
  "LastUpdated" = '2023-01-02T21:10:58.407',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Nexperia USA Inc.',
  "Part Number" = 'NX3008PBKS,115',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Operating Temperature" = '-55°C ~ 150°C (TJ)',
  "Package / Case" = '6-TSSOP, SC-88, SOT-363',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Power - Max" = '445mW',
  "Price" = '0.07',
  "Rds On (Max) @ Id, Vgs" = '4.1Ohm @ 200mA, 4.5V',
  "Series" = 'Automotive, AEC-Q101, TrenchMOS™',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = '1727-1282-1-ND',
  "Supplier Device Package" = '6-TSSOP',
  "Library Path" = 'symbols/FET - P-CH/SCH - FET - P-CH - NXP DUAL MOSFET P-CH SOT-363.SCHLIB',
  "Library Ref" = 'NXP DUAL MOSFET P-CH SOT-363',
  "Vgs(th) (Max) @ Id" = '1.1V @ 250µA'
WHERE (id = 2);

UPDATE "MOSFET-Arrays-P-Ch"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.onsemi.com/pub/Collateral/FDG6304P-D.PDF',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/on-semiconductor/FDG6304P/FDG6304PCT-ND/965595',
  "Current - Continuous Drain (Id) @ 25°C" = '410mA',
  "Description" = 'MOSFET 2P-CH 25V 0.41A SC70-6',
  "Drain to Source Voltage (Vdss)" = '25V',
  "FET Feature" = 'Logic Level Gate',
  "FET Type" = '2 P-Channel (Dual)',
  "Footprint Path" = 'footprints/Leaded - SOT/PCB - LEADED - SOT - ON SEMI SOT-363.PCBLIB',
  "Footprint Ref" = 'ON SEMI SOT-363',
  "Gate Charge (Qg) (Max) @ Vgs" = '1.5nC @ 4.5V',
  "Input Capacitance (Ciss) (Max) @ Vds" = '62pF @ 10V',
  "LastUpdated" = '2023-01-02T21:11:00.363',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'ON Semiconductor',
  "Part Number" = 'FDG6304P',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Operating Temperature" = '-55°C ~ 150°C (TJ)',
  "Package / Case" = '6-TSSOP, SC-88, SOT-363',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Power - Max" = '300mW',
  "Price" = '0.15',
  "Rds On (Max) @ Id, Vgs" = '1.1Ohm @ 410mA, 4.5V',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'FDG6304PCT-ND',
  "Supplier Device Package" = 'SC-88 (SC-70-6)',
  "Library Path" = 'symbols/FET - P-CH/SCH - FET - P-CH - ON SEMI DUAL MOSFET P-CH SOT-363.SCHLIB',
  "Library Ref" = 'ON SEMI DUAL MOSFET P-CH SOT-363',
  "Vgs(th) (Max) @ Id" = '1.5V @ 250µA'
WHERE (id = 3);

UPDATE "MOSFET-Arrays-P-Ch"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.onsemi.com/pub/Collateral/FDG6316P-D.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/on-semiconductor/FDG6316P/FDG6316PCT-ND/1849905',
  "Current - Continuous Drain (Id) @ 25°C" = '700mA',
  "Description" = 'MOSFET 2P-CH 12V 0.7A SC70-6',
  "Drain to Source Voltage (Vdss)" = '12V',
  "FET Feature" = 'Logic Level Gate',
  "FET Type" = '2 P-Channel (Dual)',
  "Footprint Path" = 'footprints/Leaded - SOT/PCB - LEADED - SOT - ON SEMI SOT-363.PCBLIB',
  "Footprint Ref" = 'ON SEMI SOT-363',
  "Gate Charge (Qg) (Max) @ Vgs" = '2.4nC @ 4.5V',
  "Input Capacitance (Ciss) (Max) @ Vds" = '146pF @ 6V',
  "LastUpdated" = '2023-01-02T21:11:00.390',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'ON Semiconductor',
  "Part Number" = 'FDG6316P',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Operating Temperature" = '-55°C ~ 150°C (TJ)',
  "Package / Case" = '6-TSSOP, SC-88, SOT-363',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Power - Max" = '300mW',
  "Price" = '0.12',
  "Rds On (Max) @ Id, Vgs" = '270mOhm @ 700mA, 4.5V',
  "Series" = 'PowerTrench®',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'FDG6316PCT-ND',
  "Supplier Device Package" = 'SC-88 (SC-70-6)',
  "Library Path" = 'symbols/FET - P-CH/SCH - FET - P-CH - ON SEMI DUAL MOSFET P-CH SOT-363.SCHLIB',
  "Library Ref" = 'ON SEMI DUAL MOSFET P-CH SOT-363',
  "Vgs(th) (Max) @ Id" = '1.5V @ 250µA'
WHERE (id = 4);

UPDATE "MOSFET-Arrays-P-Ch"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.onsemi.com/pub/Collateral/FDG6318PZ-D.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/on-semiconductor/FDG6318PZ/FDG6318PZCT-ND/3907933',
  "Current - Continuous Drain (Id) @ 25°C" = '500mA',
  "Description" = 'MOSFET 2P-CH 20V 0.5A SC70-6',
  "Drain to Source Voltage (Vdss)" = '20V',
  "FET Feature" = 'Logic Level Gate',
  "FET Type" = '2 P-Channel (Dual)',
  "Footprint Path" = 'footprints/Leaded - SOT/PCB - LEADED - SOT - ON SEMI SOT-363.PCBLIB',
  "Footprint Ref" = 'ON SEMI SOT-363',
  "Gate Charge (Qg) (Max) @ Vgs" = '1.62nC @ 4.5V',
  "Input Capacitance (Ciss) (Max) @ Vds" = '85.4pF @ 10V',
  "LastUpdated" = '2023-01-02T21:11:00.413',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'ON Semiconductor',
  "Part Number" = 'FDG6318PZ',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Operating Temperature" = '-55°C ~ 150°C (TJ)',
  "Package / Case" = '6-TSSOP, SC-88, SOT-363',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Power - Max" = '300mW',
  "Price" = '0.15',
  "Rds On (Max) @ Id, Vgs" = '780mOhm @ 500mA, 4.5V',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'FDG6318PZCT-ND',
  "Supplier Device Package" = 'SC-88 (SC-70-6)',
  "Library Path" = 'symbols/FET - P-CH/SCH - FET - P-CH - ON SEMI DUAL MOSFET P-CH SOT-363.SCHLIB',
  "Library Ref" = 'ON SEMI DUAL MOSFET P-CH SOT-363',
  "Vgs(th) (Max) @ Id" = '1.5V @ 250µA'
WHERE (id = 5);

UPDATE "MOSFET-Arrays-P-Ch"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.onsemi.com/pub/Collateral/NTJD4152P-D.PDF',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/on-semiconductor/NTJD4152PT2G/NTJD4152PT2GOSCT-ND/9087555',
  "Current - Continuous Drain (Id) @ 25°C" = '880mA',
  "Description" = 'MOSFET 2P-CH 20V 0.88A SC88-6',
  "Drain to Source Voltage (Vdss)" = '20V',
  "FET Feature" = 'Standard',
  "FET Type" = '2 P-Channel (Dual)',
  "Footprint Path" = 'footprints/Leaded - SOT/PCB - LEADED - SOT - ON SEMI SOT-363.PCBLIB',
  "Footprint Ref" = 'ON SEMI SOT-363',
  "Gate Charge (Qg) (Max) @ Vgs" = '2.2nC @ 4.5V',
  "Input Capacitance (Ciss) (Max) @ Vds" = '155pF @ 20V',
  "LastUpdated" = '2023-01-02T21:11:00.433',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'ON Semiconductor',
  "Part Number" = 'NTJD4152PT2G',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Operating Temperature" = '-55°C ~ 150°C (TJ)',
  "Package / Case" = '6-TSSOP, SC-88, SOT-363',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Power - Max" = '272mW',
  "Price" = '0.11',
  "Rds On (Max) @ Id, Vgs" = '260mOhm @ 880mA, 4.5V',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'NTJD4152PT2GOSCT-ND',
  "Supplier Device Package" = 'SC-88/SC70-6/SOT-363',
  "Library Path" = 'symbols/FET - P-CH/SCH - FET - P-CH - ON SEMI DUAL MOSFET P-CH SOT-363.SCHLIB',
  "Library Ref" = 'ON SEMI DUAL MOSFET P-CH SOT-363',
  "Vgs(th) (Max) @ Id" = '1.2V @ 250µA'
WHERE (id = 6);

UPDATE "MOSFET-Arrays-P-Ch"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.onsemi.com/pub/Collateral/FDG6308P-D.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/on-semiconductor/FDG6308P/FDG6308PCT-ND/3042789',
  "Current - Continuous Drain (Id) @ 25°C" = '600mA',
  "Description" = 'MOSFET 2P-CH 20V 0.6A SC70-6',
  "Drain to Source Voltage (Vdss)" = '20V',
  "FET Feature" = 'Logic Level Gate',
  "FET Type" = '2 P-Channel (Dual)',
  "Footprint Path" = 'footprints/Leaded - SOT/PCB - LEADED - SOT - ON SEMI SOT-363.PCBLIB',
  "Footprint Ref" = 'ON SEMI SOT-363',
  "Gate Charge (Qg) (Max) @ Vgs" = '2.5nC @ 4.5V',
  "Input Capacitance (Ciss) (Max) @ Vds" = '153pF @ 10V',
  "LastUpdated" = '2023-01-02T21:11:00.457',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'ON Semiconductor',
  "Part Number" = 'FDG6308P',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Operating Temperature" = '-55°C ~ 150°C (TJ)',
  "Package / Case" = '6-TSSOP, SC-88, SOT-363',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Power - Max" = '300mW',
  "Price" = '0.15',
  "Rds On (Max) @ Id, Vgs" = '400mOhm @ 600mA, 4.5V',
  "Series" = 'PowerTrench®',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'FDG6308PCT-ND',
  "Supplier Device Package" = 'SC-88 (SC-70-6)',
  "Library Path" = 'symbols/FET - P-CH/SCH - FET - P-CH - ON SEMI DUAL MOSFET P-CH SOT-363.SCHLIB',
  "Library Ref" = 'ON SEMI DUAL MOSFET P-CH SOT-363',
  "Vgs(th) (Max) @ Id" = '1.5V @ 250µA'
WHERE (id = 7);

UPDATE "MOSFET-Arrays-P-Ch"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.onsemi.com/pub/Collateral/FDG6306P-D.PDF',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/on-semiconductor/FDG6306P/FDG6306PCT-ND/1849904',
  "Current - Continuous Drain (Id) @ 25°C" = '600mA',
  "Description" = 'MOSFET 2P-CH 20V 0.6A SC70-6',
  "Drain to Source Voltage (Vdss)" = '20V',
  "FET Feature" = 'Logic Level Gate',
  "FET Type" = '2 P-Channel (Dual)',
  "Footprint Path" = 'footprints/Leaded - SOT/PCB - LEADED - SOT - ON SEMI SOT-363.PCBLIB',
  "Footprint Ref" = 'ON SEMI SOT-363',
  "Gate Charge (Qg) (Max) @ Vgs" = '2nC @ 4.5V',
  "Input Capacitance (Ciss) (Max) @ Vds" = '114pF @ 10V',
  "LastUpdated" = '2023-01-02T21:11:00.480',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'ON Semiconductor',
  "Part Number" = 'FDG6306P',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Operating Temperature" = '-55°C ~ 150°C (TJ)',
  "Package / Case" = '6-TSSOP, SC-88, SOT-363',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Power - Max" = '300mW',
  "Price" = '0.14',
  "Rds On (Max) @ Id, Vgs" = '420mOhm @ 600mA, 4.5V',
  "Series" = 'PowerTrench®',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'FDG6306PCT-ND',
  "Supplier Device Package" = 'SC-88 (SC-70-6)',
  "Library Path" = 'symbols/FET - P-CH/SCH - FET - P-CH - ON SEMI DUAL MOSFET P-CH SOT-363.SCHLIB',
  "Library Ref" = 'ON SEMI DUAL MOSFET P-CH SOT-363',
  "Vgs(th) (Max) @ Id" = '1.5V @ 250µA'
WHERE (id = 8);

UPDATE "MOSFET-Arrays-P-Ch"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'http://www.onsemi.com/pub/Collateral/NTJD4152P-D.PDF',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/on-semiconductor/NTJD4152PT1G/NTJD4152PT1GOSCT-ND/687124',
  "Current - Continuous Drain (Id) @ 25°C" = '880mA',
  "Description" = 'MOSFET 2P-CH 20V 0.88A SOT-363',
  "Drain to Source Voltage (Vdss)" = '20V',
  "FET Feature" = 'Logic Level Gate',
  "FET Type" = '2 P-Channel (Dual)',
  "Footprint Path" = 'footprints/Leaded - SOT/PCB - LEADED - SOT - ON SEMI SOT-363.PCBLIB',
  "Footprint Ref" = 'ON SEMI SOT-363',
  "Gate Charge (Qg) (Max) @ Vgs" = '2.2nC @ 4.5V',
  "Input Capacitance (Ciss) (Max) @ Vds" = '155pF @ 20V',
  "LastUpdated" = '2023-01-02T21:11:00.497',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'ON Semiconductor',
  "Part Number" = 'NTJD4152PT1G',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Operating Temperature" = '-55°C ~ 150°C (TJ)',
  "Package / Case" = '6-TSSOP, SC-88, SOT-363',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Power - Max" = '272mW',
  "Price" = '0.10',
  "Rds On (Max) @ Id, Vgs" = '260mOhm @ 880mA, 4.5V',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'NTJD4152PT1GOSCT-ND',
  "Supplier Device Package" = 'SC-88/SC70-6/SOT-363',
  "Library Path" = 'symbols/FET - P-CH/SCH - FET - P-CH - ON SEMI DUAL MOSFET P-CH SOT-363.SCHLIB',
  "Library Ref" = 'ON SEMI DUAL MOSFET P-CH SOT-363',
  "Vgs(th) (Max) @ Id" = '1.2V @ 250µA'
WHERE (id = 9);

UPDATE "MOSFET-Arrays-P-Ch"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.diodes.com/assets/Datasheets/DMP2200UDW.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/diodes-incorporated/DMP2200UDW-7/DMP2200UDW-7DICT-ND/5223248',
  "Current - Continuous Drain (Id) @ 25°C" = '900mA',
  "Description" = 'MOSFET 2P-CH 20V 0.9A SOT363',
  "Drain to Source Voltage (Vdss)" = '20V',
  "FET Feature" = 'Standard',
  "FET Type" = '2 P-Channel (Dual)',
  "Footprint Path" = 'footprints/Leaded - SOT/PCB - LEADED - SOT - DIODES SOT-363.PCBLIB',
  "Footprint Ref" = 'DIODES SOT-363',
  "Gate Charge (Qg) (Max) @ Vgs" = '2.1nC @ 4.5V',
  "Input Capacitance (Ciss) (Max) @ Vds" = '184pF @ 10V',
  "LastUpdated" = '2023-01-02T21:11:00.703',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Diodes Incorporated',
  "Part Number" = 'DMP2200UDW-7',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Operating Temperature" = '-55°C ~ 150°C (TJ)',
  "Package / Case" = '6-TSSOP, SC-88, SOT-363',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Power - Max" = '450mW',
  "Price" = '0.07',
  "Rds On (Max) @ Id, Vgs" = '260mOhm @ 880mA, 4.5V',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'DMP2200UDW-7DICT-ND',
  "Supplier Device Package" = 'SOT-363',
  "Library Path" = 'symbols/FET - P-CH/SCH - FET - P-CH - DIODES DUAL MOSFET P-CH SOT-363.SCHLIB',
  "Library Ref" = 'DIODES DUAL MOSFET P-CH SOT-363',
  "Vgs(th) (Max) @ Id" = '1.2V @ 250µA'
WHERE (id = 10);

UPDATE "MOSFET-Arrays-P-Ch"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.diodes.com/assets/Datasheets/DMP2200UDW.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/diodes-incorporated/DMP2200UDW-13/DMP2200UDW-13DICT-ND/8283870',
  "Current - Continuous Drain (Id) @ 25°C" = '900mA',
  "Description" = 'MOSFET 2P-CH 20V 0.9A SOT363',
  "Drain to Source Voltage (Vdss)" = '20V',
  "FET Feature" = 'Standard',
  "FET Type" = '2 P-Channel (Dual)',
  "Footprint Path" = 'footprints/Leaded - SOT/PCB - LEADED - SOT - DIODES SOT-363.PCBLIB',
  "Footprint Ref" = 'DIODES SOT-363',
  "Gate Charge (Qg) (Max) @ Vgs" = '2.1nC @ 4.5V',
  "Input Capacitance (Ciss) (Max) @ Vds" = '184pF @ 10V',
  "LastUpdated" = '2023-01-02T21:11:00.727',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Diodes Incorporated',
  "Part Number" = 'DMP2200UDW-13',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Operating Temperature" = '-55°C ~ 150°C (TJ)',
  "Package / Case" = '6-TSSOP, SC-88, SOT-363',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Power - Max" = '450mW',
  "Price" = '0.06',
  "Rds On (Max) @ Id, Vgs" = '260mOhm @ 880mA, 4.5V',
  "Series" = '-',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'DMP2200UDW-13DICT-ND',
  "Supplier Device Package" = 'SOT-363',
  "Library Path" = 'symbols/FET - P-CH/SCH - FET - P-CH - DIODES DUAL MOSFET P-CH SOT-363.SCHLIB',
  "Library Ref" = 'DIODES DUAL MOSFET P-CH SOT-363',
  "Vgs(th) (Max) @ Id" = '1.2V @ 250µA'
WHERE (id = 11);

UPDATE "MOSFET-Arrays-P-Ch"
SET
  "Comment" = '=Part Number',
  "ComponentLink1Description" = 'Datasheet',
  "ComponentLink1URL" = 'https://www.diodes.com/assets/Datasheets/ds30204.pdf',
  "ComponentLink2Description" = 'DigiKey Link',
  "ComponentLink2URL" = 'http://digikey.com/product-detail/en/diodes-incorporated/BSS84DW-7-F/BSS84DW-FDICT-ND/717845',
  "Current - Continuous Drain (Id) @ 25°C" = '130mA',
  "Description" = 'MOSFET 2P-CH 50V 0.13A SC70-6',
  "Drain to Source Voltage (Vdss)" = '50V',
  "FET Feature" = 'Logic Level Gate',
  "FET Type" = '2 P-Channel (Dual)',
  "Footprint Path" = 'footprints/Leaded - SOT/PCB - LEADED - SOT - DIODES SOT-363.PCBLIB',
  "Footprint Ref" = 'DIODES SOT-363',
  "Input Capacitance (Ciss) (Max) @ Vds" = '45pF @ 25V',
  "LastUpdated" = '2023-01-02T21:11:00.750',
  "Lifecycle Status" = 'Active',
  "Manufacturer" = 'Diodes Incorporated',
  "Part Number" = 'BSS84DW-7-F',
  "Minimum Order" = '1',
  "Mounting Type" = 'Surface Mount',
  "Operating Temperature" = '-55°C ~ 150°C (TJ)',
  "Package / Case" = '6-TSSOP, SC-88, SOT-363',
  "Packaging" = 'TapeAndReel',
  "Part Status" = 'Active',
  "Power - Max" = '300mW',
  "Price" = '0.10',
  "Rds On (Max) @ Id, Vgs" = '10Ohm @ 100mA, 5V',
  "Supplier 1" = 'DigiKey',
  "Supplier Part Number 1" = 'BSS84DW-FDICT-ND',
  "Supplier Device Package" = 'SOT-363',
  "Library Path" = 'symbols/FET - P-CH/SCH - FET - P-CH - DIODES DUAL MOSFET P-CH SOT-363.SCHLIB',
  "Library Ref" = 'DIODES DUAL MOSFET P-CH SOT-363',
  "Vgs(th) (Max) @ Id" = '2V @ 1mA'
WHERE (id = 12);

