--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."LED-Indication" (
  "ComponentLink4URL",
  "Wavelength - Dominant",
  "Configuration",
  "Device Package",
  "ComponentLink5Description",
  "Library Ref",
  "Supplier 6",
  "Package / Case",
  "Supplier 4",
  "Lifecycle Status",
  "Supplier 5",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "Minimum Order",
  "LastUpdated",
  "ComponentLink4Description",
  "ComponentLink3URL",
  "Footprint Ref",
  "Color",
  "ComponentLink1Description",
  "Current - Test",
  "Size / Dimension",
  "Mounting Type",
  "Price",
  "Packaging",
  "Value",
  "Lens Color",
  "Footprint Path",
  "ComponentLink2Description",
  "Description",
  "ComponentLink6URL",
  "Part Number",
  "Lens Transparency",
  "ComponentLink2URL",
  "Viewing Angle",
  "Millicandela Rating",
  "ComponentLink3Description",
  "Supplier Device Package",
  "Supplier Part Number 4",
  "Lens Style",
  "Supplier Part Number 5",
  "Supplier Part Number 2",
  "Supplier Part Number 3",
  "Supplier Part Number 1",
  "Features",
  "Wavelength - Peak",
  "Supplier Part Number 6",
  "Lens Size",
  "Comment",
  "ComponentLink5URL",
  "ComponentLink1URL",
  "Supplier 2",
  "Supplier 3",
  "Footprint Ref 2",
  "Footprint Ref 3",
  "Supplier 1",
  "Height (Max)",
  "Series",
  "Type",
  "Library Path",
  "Part Status",
  "ComponentLink6Description"
)
VALUES (
  'https://www.digikey.com/ptm/l/lumex-optocomponents-inc/leds', 
  '-', 
  'Common Cathode', 
  'Radial - 3 Leads', 
  'Environmental Information', 
  'BICOLOR RG TH CC', 
  NULL, 
  'Radial - 3 Leads', 
  NULL, 
  'Active', 
  NULL, 
  'Lumex Opto/Components Inc.', 
  '2.2V Green, 2V Red', 
  '1', 
  '2023-10-30T13:13:00.2651762', 
  'Product Training Modules', 
  'https://www.digikey.com/ptm/l/lumex-optocomponents-inc/benefits-of-custom-led-and-lcd-technology', 
  'LED BICOLOR TH 3MM', 
  'Green, Red', 
  'Datasheet', 
  '20mA Green, 20mA Red', 
  '-', 
  'Through Hole', 
  '0.61', 
  'Bulk', 
  NULL, 
  'White', 
  'footprints/Diodes/PCB - DIODES - LED BICOLOR TH 3MM.PcbLib', 
  'Product Photos', 
  'LED GRN/RED DIFF T-3MM TRI T/H', 
  'https://www.digikey.com/htmldatasheets/production/82215/0/0/1/ssl-lx3059igw.html', 
  'SSL-LX3059IGW', 
  'Diffused', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/images/836/SSL-LX3059GYW,SSL-LX3059IGW,SSL-LX3059IYW.jpg', 
  '60°', 
  '30mcd Green, 30mcd Red', 
  'Product Training Modules', 
  'T-3mm TRI-LEADED', 
  NULL, 
  'Round with Domed Top', 
  NULL, 
  NULL, 
  NULL, 
  '67-1327-ND', 
  '-', 
  '565nm Green, 635nm Red', 
  NULL, 
  '3mm, T-1', 
  '=Part Number', 
  'https://www.lumex.com/attachment/RoHS%203%20&%20REACH%20197%20CoC.pdf', 
  'https://www.lumex.com/spec/SSL-LX3059IGW.pdf', 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  'DigiKey', 
  '7.03mm', 
  '-', 
  NULL, 
  'symbols/Diodes/SCH - DIODES - BICOLOR RG TH CC.SchLib', 
  'Active', 
  'HTML Datasheet'
);

