--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "VoltageRegulators-DC-DC-SwitchingRegulators" (
  "ComponentLink4URL",
  "Device Package",
  "ComponentLink5Description",
  "Voltage - Input (Min)",
  "Library Ref",
  "Supplier 6",
  "Package / Case",
  "Supplier 4",
  "Lifecycle Status",
  "Supplier 5",
  "Manufacturer",
  "Minimum Order",
  "LastUpdated",
  "ComponentLink4Description",
  "Operating Temperature",
  "ComponentLink3URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Topology",
  "Mounting Type",
  "Price",
  "Packaging",
  "Value",
  "Footprint Path",
  "ComponentLink2Description",
  "Description",
  "ComponentLink6URL",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "ComponentLink3Description",
  "Supplier Device Package",
  "Supplier Part Number 4",
  "Supplier Part Number 5",
  "Function",
  "Supplier Part Number 2",
  "Supplier Part Number 3",
  "Supplier Part Number 1",
  "Frequency - Switching",
  "Voltage - Output (Min/Fixed)",
  "Supplier Part Number 6",
  "Comment",
  "Number Of Outputs",
  "Synchronous Rectifier",
  "ComponentLink5URL",
  "ComponentLink1URL",
  "Supplier 2",
  "Supplier 3",
  "Footprint Ref 2",
  "Footprint Ref 3",
  "Supplier 1",
  "Voltage - Output (Max)",
  "Series",
  "Type",
  "Library Path",
  "Part Status",
  "ComponentLink6Description"
)
VALUES (
  'https://app.ultralibrarian.com/details/DC372BB8-E59F-11EC-9C51-0A34D6323D74/Texas-Instruments/TPS62A01ADRLR?ref=digikey', 
  'SOT-563, SOT-666', 
  NULL, 
  '2.5V', 
  'TI TPS62A01ADRLR', 
  NULL, 
  'SOT-563, SOT-666', 
  NULL, 
  'Active', 
  NULL, 
  'Texas Instruments', 
  '1', 
  '2023-10-13T22:03:50.5779278', 
  'EDA Models', 
  '-40°C ~ 125°C (TJ)', 
  'https://www.digikey.com/product-highlight/t/texas-instruments/tps62a0x-series-synchronous-buck-converter', 
  'TI SOT-563 DRL', 
  'Datasheets', 
  'Buck', 
  'Surface Mount', 
  '0.48', 
  'Cut Tape (CT)', 
  NULL, 
  'footprints/Leaded - SOT/PCB - LEADED - SOT - TI SOT-563 DRL.PCBLIB', 
  'Product Photos', 
  'IC REG BUCK ADJ 1A SOT563', 
  NULL, 
  'TPS62A01ADRLR', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/images/4017/MFG_TPS62A01ADRLR.jpg', 
  'Adjustable', 
  '5.5V', 
  '1A', 
  'Positive', 
  'Featured Product', 
  'SOT-563', 
  NULL, 
  NULL, 
  'Step-Down', 
  NULL, 
  NULL, 
  '296-TPS62A01ADRLRCT-ND', 
  '2.4MHz', 
  '0.6V', 
  NULL, 
  '=Part Number', 
  '1', 
  'Yes', 
  NULL, 
  'https://www.ti.com/lit/ds/symlink/tps62a01.pdf?ts=1651767199227&ref_url=https%253A%252F%252Fwww.ti.com%252Fsitesearch%252Fen-us%252Fdocs%252Funiversalsearch.tsp%253FlangPref%253Den-US%2526searchTerm%253DTPS62A01DRLR%2526nr%253D7', 
  NULL, 
  NULL, 
  NULL, 
  NULL, 
  'DigiKey', 
  '5.5V', 
  '-', 
  NULL, 
  'symbols/Power - Switchmode/SCH - POWER - SWITCHMODE - TI TPS62A01ADRLR.SchLib', 
  'Active', 
  NULL
);

