--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Capacitors-Aluminum-Electrolytic-TH" (
  "Polarization",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Lead Spacing",
  "Voltage - Rated",
  "Ripple Current @ Low Frequency",
  "Ratings",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "Impedance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'Polar', 
  'CAP ALUM 22UF 20% 100V RADIAL', 
  'EEU-FC2A220BJ', 
  'https://www.digikey.com/en/products/detail/panasonic-electronic-components/EEU-FC2A220BJ/2689810', 
  '0.492" (12.50mm)', 
  '0.138" (3.50mm)', 
  '100 V', 
  '169 mA @ 120 Hz', 
  'AEC-Q200', 
  'POLARISED CAPACITOR', 
  '10-EEU-FC2A220BJCT-ND', 
  'Active', 
  'Panasonic Electronic Components', 
  '2023-03-25T20:24:43.870', 
  '1', 
  '28091', 
  '=Value', 
  '-55°C ~ 105°C', 
  'Automotive', 
  'https://industrial.panasonic.com/ww/products/pt/aluminum-cap-lead/models/EEUFC2A220B', 
  'CAP AL TH D8 L3.5 H12.5', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  'Through Hole', 
  '0.315" Dia (8.00mm)', 
  '2000 Hrs @ 105°C', 
  'FC', 
  '0.11', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndBox', 
  'Active', 
  '22 µF', 
  '22 µF', 
  '680 mOhms', 
  'DigiKey Link', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP AL TH D8 L3.5 H12.5.PCBLIB'
);

