--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 24V 500MW SOD123', 
  'DDZ24C-7', 
  'https://www.digikey.com/en/products/detail/diodes-incorporated/DDZ24C-7/700108', 
  'SOD-123', 
  'SOD-123', 
  'DIODE ZENER', 
  'DDZ24CDICT-ND', 
  'Active', 
  'Diodes Incorporated', 
  '2023-03-25T20:16:33.927', 
  '1', 
  '4254', 
  '=Part Number', 
  '-65°C ~ 150°C', 
  'https://www.diodes.com/assets/Datasheets/Ds30407.pdf', 
  'SOD-123', 
  'Datasheet', 
  '±3%', 
  'DigiKey', 
  'Surface Mount', 
  '50 nA @ 19 V', 
  '-', 
  '0.03', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '500 mW', 
  '900 mV @ 10 mA', 
  'TapeAndReel', 
  'Active', 
  '24 V', 
  '35 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD-123.PCBLIB'
);

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 6.8V 310MW SOD323F', 
  'PZU6.8B2,115', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/PZU6-8B2-115/1163019', 
  'SOD-323F', 
  'SC-90, SOD-323F', 
  'DIODE ZENER', 
  '1727-3760-1-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-03-25T20:16:59.433', 
  '1', 
  '4255', 
  '=Part Number', 
  '-65°C ~ 150°C', 
  'https://assets.nexperia.com/documents/data-sheet/PZUXB_SER.pdf', 
  'SOD323F', 
  'Datasheet', 
  '±2%', 
  'DigiKey', 
  'Surface Mount', 
  '500 nA @ 3.5 V', 
  'Automotive, AEC-Q100', 
  '0.05', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '310 mW', 
  '1.1 V @ 100 mA', 
  'TapeAndReel', 
  'Active', 
  '6.8 V', 
  '20 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD323F.PCBLIB'
);

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 75V 550MW SOD323F', 
  'BZX84J-B75,115', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/BZX84J-B75-115/2034266', 
  'SOD-323F', 
  'SC-90, SOD-323F', 
  'DIODE ZENER', 
  '1727-BZX84J-B75115CT-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-03-25T20:16:59.463', 
  '1', 
  '4256', 
  '=Part Number', 
  '-65°C ~ 150°C', 
  'https://assets.nexperia.com/documents/data-sheet/BZX84J_SER.pdf', 
  'SOD323F', 
  'Datasheet', 
  '±2%', 
  'DigiKey', 
  'Surface Mount', 
  '50 nA @ 52.5 V', 
  'Automotive, AEC-Q101', 
  '0.04', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '550 mW', 
  '1.1 V @ 100 mA', 
  'TapeAndReel', 
  'Active', 
  '75 V', 
  '175 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD323F.PCBLIB'
);

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 12V 310MW SOD323F', 
  'PZU12B,115', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/PZU12B-115/1162943', 
  'SOD-323F', 
  'SC-90, SOD-323F', 
  'DIODE ZENER', 
  '1727-3685-1-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-03-25T20:16:59.477', 
  '3000', 
  '4257', 
  '=Part Number', 
  '-65°C ~ 150°C', 
  'https://assets.nexperia.com/documents/data-sheet/PZUXB_SER.pdf', 
  'SOD323F', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  'Surface Mount', 
  '100 nA @ 9 V', 
  'Automotive, AEC-Q100', 
  '0.04', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '310 mW', 
  '1.1 V @ 100 mA', 
  'TapeAndReel', 
  'Active', 
  '12 V', 
  '10 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD323F.PCBLIB'
);

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 9.1V 320MW SOD323', 
  'PZU9.1B2A,115', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/PZU9-1B2A-115/2120069', 
  'SOD-323', 
  'SC-76, SOD-323', 
  'DIODE ZENER', 
  '1727-PZU9.1B2A,115CT-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-03-25T20:33:34.293', 
  '1', 
  '4258', 
  '=Part Number', 
  '-55°C ~ 150°C', 
  'https://assets.nexperia.com/documents/data-sheet/PZUXBA_SER.pdf', 
  'SOD323', 
  'Datasheet', 
  '±2%', 
  'DigiKey', 
  'Surface Mount', 
  '500 nA @ 6 V', 
  '-', 
  '0.03', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '320 mW', 
  '1.1 V @ 100 mA', 
  'TapeAndReel', 
  'Active', 
  '9.1 V', 
  '10 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD323.PCBLIB'
);

