--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Capacitors-Aluminum-Polymer-TH" (
  "Applications",
  "Capacitance",
  "comment",
  "componentlink1description",
  "componentlink1url",
  "componentlink2description",
  "componentlink2url",
  "description",
  "ESR (Equivalent Series Resistance)",
  "Footprint Path",
  "Footprint Ref",
  "Height - Seated (Max)",
  "lastupdated",
  "Lead Spacing",
  "Lifecycle Status",
  "Lifetime @ Temp.",
  "manufacturer",
  "Part Number",
  "Minimum Order",
  "Mounting Type",
  "Operating Temperature",
  "packaging",
  "partid",
  "Part Status",
  "price",
  "Ripple Current @ High Frequency",
  "series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Library Path",
  "Library Ref",
  "Tolerance",
  "Type",
  "value",
  "Voltage - Rated"
)
VALUES (
  'General Purpose', 
  '390 µF', 
  '=Value', 
  'Datasheet', 
  'https://media.digikey.com/pdf/Data%20Sheets/United%20Chemi-Con%20PDFs/PS%20Series.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/united-chemi-con/APS-6R3ELL391MHB5S/758468', 
  'CAP ALUM POLY 390UF 20% 6.3V T/H', 
  '12mOhm', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP TH ALPOLY D8.00mm S3.50mm H13.00mm.PCBLIB', 
  'CAP TH ALPOLY D8.00mm S3.50mm H13.00mm', 
  '0.512" (13.00mm)', 
  '2023-02-04T21:03:52.513', 
  '0.138" (3.50mm)', 
  'Active', 
  '2000 Hrs @ 105°C', 
  'United Chemi-Con', 
  'APS-6R3ELL391MHB5S', 
  '1', 
  'Through Hole', 
  '-55°C ~ 105°C', 
  'Bulk', 
  '5468', 
  'Active', 
  '0.32', 
  '4.77 A @ 100 kHz', 
  'NPCAP™-PS', 
  '0.315" Dia (8.00mm)', 
  'DigiKey', 
  '565-APS-6R3ELL391MHB5S-ND', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'POLARISED CAPACITOR', 
  '±20%', 
  'Polymer', 
  '390 µF', 
  '6.3 V'
);

INSERT INTO "Capacitors-Aluminum-Polymer-TH" (
  "Applications",
  "Capacitance",
  "comment",
  "componentlink1description",
  "componentlink1url",
  "componentlink2description",
  "componentlink2url",
  "description",
  "ESR (Equivalent Series Resistance)",
  "Footprint Path",
  "Footprint Ref",
  "Height - Seated (Max)",
  "lastupdated",
  "Lead Spacing",
  "Lifecycle Status",
  "Lifetime @ Temp.",
  "manufacturer",
  "Part Number",
  "Minimum Order",
  "Mounting Type",
  "Operating Temperature",
  "packaging",
  "partid",
  "Part Status",
  "price",
  "Ripple Current @ High Frequency",
  "series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Library Path",
  "Library Ref",
  "Tolerance",
  "Type",
  "value",
  "Voltage - Rated"
)
VALUES (
  'General Purpose', 
  '560 µF', 
  '=Value', 
  'Datasheet', 
  'https://www.chemi-con.co.jp/products/relatedfiles/capacitor/catalog/PSGLL-e.PDF', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/united-chemi-con/APSG160ELL561MHB5J/5822364', 
  'CAP ALUM POLY 560UF 20% 16V T/H', 
  '8mOhm', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP TH ALPOLY D8.00mm S3.50mm H13.00mm.PCBLIB', 
  'CAP TH ALPOLY D8.00mm S3.50mm H13.00mm', 
  '0.512" (13.00mm)', 
  '2023-02-04T21:03:52.530', 
  '0.138" (3.50mm)', 
  'Active', 
  '20000 Hrs @ 105°C', 
  'United Chemi-Con', 
  'APSG160ELL561MHB5J', 
  '1', 
  'Through Hole', 
  '-55°C ~ 105°C', 
  'Bulk', 
  '5469', 
  'Active', 
  '0.45', 
  '6.1 A @ 100 kHz', 
  'NPCAP™-PSG', 
  '0.315" Dia (8.00mm)', 
  'DigiKey', 
  '565-APSG160ELL561MHB5J-ND', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'POLARISED CAPACITOR', 
  '±20%', 
  'Polymer', 
  '560 µF', 
  '16 V'
);

INSERT INTO "Capacitors-Aluminum-Polymer-TH" (
  "Applications",
  "Capacitance",
  "comment",
  "componentlink1description",
  "componentlink1url",
  "componentlink2description",
  "componentlink2url",
  "description",
  "ESR (Equivalent Series Resistance)",
  "Footprint Path",
  "Footprint Ref",
  "Height - Seated (Max)",
  "lastupdated",
  "Lead Spacing",
  "Lifecycle Status",
  "Lifetime @ Temp.",
  "manufacturer",
  "Part Number",
  "Minimum Order",
  "Mounting Type",
  "Operating Temperature",
  "packaging",
  "partid",
  "Part Status",
  "price",
  "Ripple Current @ High Frequency",
  "Ripple Current @ Low Frequency",
  "series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Library Path",
  "Library Ref",
  "Tolerance",
  "Type",
  "value",
  "Voltage - Rated"
)
VALUES (
  'General Purpose', 
  '270 µF', 
  '=Value', 
  'Datasheet', 
  'https://datasheets.kyocera-avx.com/rha-series.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/RHA0809271M016B/17634428', 
  'CAP ALUM POLY HYB 270UF 16V T/H', 
  '26mOhm', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP TH ALPOLY D8.00mm S3.50mm H11.00mm.PCBLIB', 
  'CAP TH ALPOLY D8.00mm S3.50mm H11.00mm', 
  '0.433" (11.00mm)', 
  '2023-02-04T21:04:03.980', 
  '0.138" (3.50mm)', 
  'Active', 
  '10000 Hrs @ 105°C', 
  'KYOCERA AVX', 
  'RHA0809271M016B', 
  '1', 
  'Through Hole', 
  '-55°C ~ 105°C', 
  'Bulk', 
  '5470', 
  'Active', 
  '0.77', 
  '2 A @ 100 kHz', 
  '200 mA @ 100 Hz', 
  'RHA', 
  '0.315" Dia (8.00mm)', 
  'DigiKey', 
  '478-RHA0809271M016B-ND', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'POLARISED CAPACITOR', 
  '±20%', 
  'Hybrid', 
  '270 µF', 
  '16 V'
);

INSERT INTO "Capacitors-Aluminum-Polymer-TH" (
  "Applications",
  "Capacitance",
  "comment",
  "componentlink1description",
  "componentlink1url",
  "componentlink2description",
  "componentlink2url",
  "description",
  "ESR (Equivalent Series Resistance)",
  "Footprint Path",
  "Footprint Ref",
  "Height - Seated (Max)",
  "lastupdated",
  "Lead Spacing",
  "Lifecycle Status",
  "Lifetime @ Temp.",
  "manufacturer",
  "Part Number",
  "Minimum Order",
  "Mounting Type",
  "Operating Temperature",
  "packaging",
  "partid",
  "Part Status",
  "price",
  "Ripple Current @ High Frequency",
  "Ripple Current @ Low Frequency",
  "series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Library Path",
  "Library Ref",
  "Tolerance",
  "Type",
  "value",
  "Voltage - Rated"
)
VALUES (
  'General Purpose', 
  '56 µF', 
  '=Value', 
  'Datasheet', 
  'https://datasheets.kyocera-avx.com/rha-series.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/RHA1011560M063B/17634429', 
  'CAP ALUM POLY HYB 56UF 63V T/H', 
  '22mOhm', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP TH ALPOLY D10.00mm S5.00mm H13.00mm.PCBLIB', 
  'CAP TH ALPOLY D10.00mm S5.00mm H13.00mm', 
  '0.512" (13.00mm)', 
  '2023-02-04T21:04:52.557', 
  '0.197" (5.00mm)', 
  'Active', 
  '10000 Hrs @ 105°C', 
  'KYOCERA AVX', 
  'RHA1011560M063B', 
  '1', 
  'Through Hole', 
  '-55°C ~ 105°C', 
  'Bulk', 
  '5471', 
  'Active', 
  '1.57', 
  '2.4 A @ 100 kHz', 
  '240 mA @ 100 Hz', 
  'RHA', 
  '0.394" Dia (10.00mm)', 
  'DigiKey', 
  '478-RHA1011560M063B-ND', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'POLARISED CAPACITOR', 
  '±20%', 
  'Hybrid', 
  '56 µF', 
  '63 V'
);

