--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."VoltageRegulators-DC-DC-SwitchingRegulators" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Voltage - Input (Min)",
  "Function",
  "Package / Case",
  "Library Ref",
  "Frequency - Switching",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Synchronous Rectifier",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Topology",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG BUCK ADJ 2A 6VSON', 
  'TPS62825DMQT', 
  'https://www.digikey.com/en/products/detail/texas-instruments/TPS62825DMQT/9861431', 
  'Adjustable', 
  '5.5V', 
  '2A', 
  'Positive', 
  '6-VSON-HR (1.5x1.5)', 
  '2.4V', 
  'Step-Down', 
  '6-VFDFN', 
  'TI TPS62825DMQ', 
  '2.2MHz', 
  '296-53226-1-ND', 
  'Active', 
  'Texas Instruments', 
  '0.6V', 
  '2024-11-01T11:58:59.450', 
  '1', 
  '=Part Number', 
  '1', 
  '-40°C ~ 125°C (TJ)', 
  'Yes', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Ftps62825', 
  'TI - VSON-6 DMQ0006A', 
  'Datasheet', 
  'DigiKey', 
  'Buck', 
  'Surface Mount', 
  '4V', 
  '-', 
  '1.58', 
  'symbols/Power - Switchmode/SCH - POWER - SWITCHMODE - TI TPS62825DMQ.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - SON/PCB - LEADLESS - SON - TI - VSON-6 DMQ0006A.PcbLib'
);

INSERT INTO "altium"."VoltageRegulators-DC-DC-SwitchingRegulators" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Voltage - Input (Min)",
  "Function",
  "Package / Case",
  "Library Ref",
  "Frequency - Switching",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Synchronous Rectifier",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Topology",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG BUCK ADJ 2A 6VSON', 
  'TPS62825DMQR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/TPS62825DMQR/9428259', 
  'Adjustable', 
  '5.5V', 
  '2A', 
  'Positive', 
  '6-VSON-HR (1.5x1.5)', 
  '2.4V', 
  'Step-Down', 
  '6-VFDFN', 
  'TI TPS62825DMQ', 
  '2.2MHz', 
  '296-49521-1-ND', 
  'Active', 
  'Texas Instruments', 
  '0.6V', 
  '2024-11-01T11:59:09.833', 
  '1', 
  '=Part Number', 
  '1', 
  '-40°C ~ 125°C (TJ)', 
  'Yes', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Ftps62825', 
  'TI - VSON-6 DMQ0006A', 
  'Datasheet', 
  'DigiKey', 
  'Buck', 
  'Surface Mount', 
  '4V', 
  '-', 
  '0.45', 
  'symbols/Power - Switchmode/SCH - POWER - SWITCHMODE - TI TPS62825DMQ.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - SON/PCB - LEADLESS - SON - TI - VSON-6 DMQ0006A.PcbLib'
);

INSERT INTO "altium"."VoltageRegulators-DC-DC-SwitchingRegulators" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Voltage - Input (Min)",
  "Function",
  "Package / Case",
  "Library Ref",
  "Frequency - Switching",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Synchronous Rectifier",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Topology",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG BUCK ADJ 3A 6VSON', 
  'TPS62826DMQR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/TPS62826DMQR/9428261', 
  'Adjustable', 
  '5.5V', 
  '3A', 
  'Positive', 
  '6-VSON-HR (1.5x1.5)', 
  '2.4V', 
  'Step-Down', 
  '6-VFDFN', 
  'TI TPS62826DMQ', 
  '2.2MHz', 
  '296-49523-1-ND', 
  'Active', 
  'Texas Instruments', 
  '0.6V', 
  '2024-11-01T11:59:53.250', 
  '1', 
  '=Part Number', 
  '1', 
  '-40°C ~ 125°C (TJ)', 
  'Yes', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Ftps62826', 
  'TI - VSON-6 DMQ0006A', 
  'Datasheet', 
  'DigiKey', 
  'Buck', 
  'Surface Mount', 
  '4V', 
  '-', 
  '0.52', 
  'symbols/Power - Switchmode/SCH - POWER - SWITCHMODE - TI TPS62826DMQ.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - SON/PCB - LEADLESS - SON - TI - VSON-6 DMQ0006A.PcbLib'
);

INSERT INTO "altium"."VoltageRegulators-DC-DC-SwitchingRegulators" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Voltage - Input (Min)",
  "Function",
  "Package / Case",
  "Library Ref",
  "Frequency - Switching",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Synchronous Rectifier",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Topology",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG BUCK ADJ 3A 6VSON', 
  'TPS62826DMQT', 
  'https://www.digikey.com/en/products/detail/texas-instruments/TPS62826DMQT/9861433', 
  'Adjustable', 
  '5.5V', 
  '3A', 
  'Positive', 
  '6-VSON-HR (1.5x1.5)', 
  '2.4V', 
  'Step-Down', 
  '6-VFDFN', 
  'TI TPS62826DMQ', 
  '2.2MHz', 
  '296-53228-1-ND', 
  'Active', 
  'Texas Instruments', 
  '0.6V', 
  '2024-11-01T12:00:03.290', 
  '1', 
  '=Part Number', 
  '1', 
  '-40°C ~ 125°C (TJ)', 
  'Yes', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Ftps62826', 
  'TI - VSON-6 DMQ0006A', 
  'Datasheet', 
  'DigiKey', 
  'Buck', 
  'Surface Mount', 
  '4V', 
  '-', 
  '0.81', 
  'symbols/Power - Switchmode/SCH - POWER - SWITCHMODE - TI TPS62826DMQ.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - SON/PCB - LEADLESS - SON - TI - VSON-6 DMQ0006A.PcbLib'
);

INSERT INTO "altium"."VoltageRegulators-DC-DC-SwitchingRegulators" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Voltage - Input (Min)",
  "Function",
  "Package / Case",
  "Library Ref",
  "Frequency - Switching",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Synchronous Rectifier",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Topology",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG BUCK ADJ 4A 6VSON', 
  'TPS62827DMQR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/TPS62827DMQR/10434669', 
  'Adjustable', 
  '5.5V', 
  '4A', 
  'Positive', 
  '6-VSON-HR (1.5x1.5)', 
  '2.5V', 
  'Step-Down', 
  '6-VFDFN', 
  'TI TPS62827DMQ', 
  '2.2MHz', 
  '296-TPS62827DMQRCT-ND', 
  'Active', 
  'Texas Instruments', 
  '0.6V', 
  '2024-11-01T12:00:21.537', 
  '1', 
  '=Part Number', 
  '1', 
  '-40°C ~ 125°C (TJ)', 
  'Yes', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Ftps62827', 
  'TI - VSON-6 DMQ0006A', 
  'Datasheet', 
  'DigiKey', 
  'Buck', 
  'Surface Mount', 
  '4V', 
  '-', 
  '0.58', 
  'symbols/Power - Switchmode/SCH - POWER - SWITCHMODE - TI TPS62827DMQ.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - SON/PCB - LEADLESS - SON - TI - VSON-6 DMQ0006A.PcbLib'
);

INSERT INTO "altium"."VoltageRegulators-DC-DC-SwitchingRegulators" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Voltage - Input (Min)",
  "Function",
  "Package / Case",
  "Library Ref",
  "Frequency - Switching",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Synchronous Rectifier",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Topology",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG BUCK ADJ 4A 6VSON', 
  'TPS62827DMQT', 
  'https://www.digikey.com/en/products/detail/texas-instruments/TPS62827DMQT/10434688', 
  'Adjustable', 
  '5.5V', 
  '4A', 
  'Positive', 
  '6-VSON-HR (1.5x1.5)', 
  '2.5V', 
  'Step-Down', 
  '6-VFDFN', 
  'TI TPS62827DMQ', 
  '2.2MHz', 
  '296-TPS62827DMQTCT-ND', 
  'Active', 
  'Texas Instruments', 
  '0.6V', 
  '2024-11-01T12:00:32.303', 
  '1', 
  '=Part Number', 
  '1', 
  '-40°C ~ 125°C (TJ)', 
  'Yes', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Ftps62827', 
  'TI - VSON-6 DMQ0006A', 
  'Datasheet', 
  'DigiKey', 
  'Buck', 
  'Surface Mount', 
  '4V', 
  '-', 
  '0.98', 
  'symbols/Power - Switchmode/SCH - POWER - SWITCHMODE - TI TPS62827DMQ.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - SON/PCB - LEADLESS - SON - TI - VSON-6 DMQ0006A.PcbLib'
);

INSERT INTO "altium"."VoltageRegulators-DC-DC-SwitchingRegulators" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Voltage - Input (Min)",
  "Function",
  "Library Ref",
  "Frequency - Switching",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Synchronous Rectifier",
  "Footprint Ref",
  "Supplier 1",
  "Topology",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG BUCK ADJ 1A 6VSON', 
  'TPS62824ADMQR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/TPS62824ADMQR/14004408', 
  'Adjustable', 
  '5.5V', 
  '1A', 
  'Positive', 
  '6-VSON-HR (1.5x1.5)', 
  '2.4V', 
  'Step-Down', 
  'TI TPS62824ADMQ', 
  '2.2MHz', 
  '296-TPS62824ADMQRCT-ND', 
  'Active', 
  'Texas Instruments', 
  '0.6V', 
  '2024-11-01T12:01:18.840', 
  '1', 
  '=Part Number', 
  '1', 
  '-40°C ~ 125°C (TJ)', 
  'Yes', 
  'TI - VSON-6 DMQ0006A', 
  'DigiKey', 
  'Buck', 
  'Surface Mount', 
  '4V', 
  '-', 
  '0.39', 
  'symbols/Power - Switchmode/SCH - POWER - SWITCHMODE - TI TPS62824ADMQ.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - SON/PCB - LEADLESS - SON - TI - VSON-6 DMQ0006A.PcbLib'
);

INSERT INTO "altium"."VoltageRegulators-DC-DC-SwitchingRegulators" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Voltage - Input (Min)",
  "Function",
  "Library Ref",
  "Frequency - Switching",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Synchronous Rectifier",
  "Footprint Ref",
  "Supplier 1",
  "Topology",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG BUCK ADJ 2A 6VSON', 
  'TPS62825ADMQR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/TPS62825ADMQR/13627220', 
  'Adjustable', 
  '5.5V', 
  '2A', 
  'Positive', 
  '6-VSON-HR (1.5x1.5)', 
  '2.4V', 
  'Step-Down', 
  'TI TPS62825ADMQ', 
  '2.2MHz', 
  '296-TPS62825ADMQRCT-ND', 
  'Active', 
  'Texas Instruments', 
  '0.6V', 
  '2024-11-01T12:01:51.433', 
  '1', 
  '=Part Number', 
  '1', 
  '-40°C ~ 125°C (TJ)', 
  'Yes', 
  'TI - VSON-6 DMQ0006A', 
  'DigiKey', 
  'Buck', 
  'Surface Mount', 
  '4V', 
  '-', 
  '0.44', 
  'symbols/Power - Switchmode/SCH - POWER - SWITCHMODE - TI TPS62825ADMQ.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - SON/PCB - LEADLESS - SON - TI - VSON-6 DMQ0006A.PcbLib'
);

INSERT INTO "altium"."VoltageRegulators-DC-DC-SwitchingRegulators" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Voltage - Input (Min)",
  "Function",
  "Library Ref",
  "Frequency - Switching",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Synchronous Rectifier",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Topology",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG BUCK ADJ 3A 6VSON', 
  'TPS62826ADMQR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/TPS62826ADMQR/13627085', 
  'Adjustable', 
  '5.5V', 
  '3A', 
  'Positive', 
  '6-VSON-HR (1.5x1.5)', 
  '2.4V', 
  'Step-Down', 
  'TI TPS62826ADMQ', 
  '2.2MHz', 
  '296-TPS62826ADMQRCT-ND', 
  'Active', 
  'Texas Instruments', 
  '0.6V', 
  '2024-11-01T12:02:19.030', 
  '1', 
  '=Part Number', 
  '1', 
  '-40°C ~ 125°C (TJ)', 
  'Yes', 
  'https://www.ti.com/lit/ds/symlink/tps62825.pdf', 
  'TI - VSON-6 DMQ0006A', 
  'Datasheet', 
  'DigiKey', 
  'Buck', 
  'Surface Mount', 
  '4V', 
  '-', 
  '0.52', 
  'symbols/Power - Switchmode/SCH - POWER - SWITCHMODE - TI TPS62826ADMQ.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - SON/PCB - LEADLESS - SON - TI - VSON-6 DMQ0006A.PcbLib'
);

INSERT INTO "altium"."VoltageRegulators-DC-DC-SwitchingRegulators" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Voltage - Input (Min)",
  "Function",
  "Library Ref",
  "Frequency - Switching",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Synchronous Rectifier",
  "Footprint Ref",
  "Supplier 1",
  "Topology",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG BUCK ADJ 4A 6VSON', 
  'TPS62827ADMQR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/TPS62827ADMQR/14004348', 
  'Adjustable', 
  '5.5V', 
  '4A', 
  'Positive', 
  '6-VSON-HR (1.5x1.5)', 
  '2.4V', 
  'Step-Down', 
  'TI TPS62827ADMQ', 
  '2.2MHz', 
  '296-TPS62827ADMQRCT-ND', 
  'Active', 
  'Texas Instruments', 
  '0.6V', 
  '2024-11-01T12:02:52.210', 
  '1', 
  '=Part Number', 
  '1', 
  '-40°C ~ 125°C (TJ)', 
  'Yes', 
  'TI - VSON-6 DMQ0006A', 
  'DigiKey', 
  'Buck', 
  'Surface Mount', 
  '4V', 
  '-', 
  '0.59', 
  'symbols/Power - Switchmode/SCH - POWER - SWITCHMODE - TI TPS62827ADMQ.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - SON/PCB - LEADLESS - SON - TI - VSON-6 DMQ0006A.PcbLib'
);

