--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Connectors-RectangularHeadersMalePins" (
  "Description",
  "Insulation Height",
  "Part Number",
  "ComponentLink2URL",
  "Number Of Positions Loaded",
  "Contact Finish Thickness - Mating",
  "Number Of Rows",
  "Contact Type",
  "Material Flammability Rating",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Connector Type",
  "Contact Material",
  "Manufacturer",
  "Style",
  "Pitch - Mating",
  "LastUpdated",
  "Minimum Order",
  "Contact Length - Mating",
  "PartId",
  "Contact Finish - Mating",
  "Comment",
  "Operating Temperature",
  "Footprint Ref",
  "Termination",
  "Supplier 1",
  "Fastening Type",
  "Mounting Type",
  "Insulation Material",
  "Number Of Positions",
  "Contact Shape",
  "Series",
  "Row Spacing - Mating",
  "Price",
  "Library Path",
  "Contact Finish - Post",
  "Insulation Color",
  "Packaging",
  "Part Status",
  "Contact Length - Post",
  "Shrouding",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CONN HEADER R/A 15POS 2.54MM', 
  '0.320" (8.13mm)', 
  'TSW-105-08-G-T-RA', 
  'https://www.digikey.com/en/products/detail/samtec-inc/TSW-105-08-G-T-RA/7865351', 
  'All', 
  '10.0µin (0.25µm)', 
  '3', 
  'Male Pin', 
  'UL94 V-0', 
  'SAMTEC TSW-105-08-G-T-RA', 
  'TSW-105-08-G-T-RA-ND', 
  'Active', 
  'Header', 
  'Phosphor Bronze', 
  'Samtec Inc.', 
  'Board to Board or Cable', 
  '0.100" (2.54mm)', 
  '2026-03-11T19:53:10.077', 
  '1', 
  '0.230" (5.84mm)', 
  '194', 
  'Gold', 
  '=Part Number', 
  '-55°C ~ 125°C', 
  'SAMTEC TSW-105-08-G-T-RA', 
  'Solder', 
  'DigiKey', 
  'Push-Pull', 
  'Through Hole, Right Angle', 
  'Polybutylene Terephthalate (PBT)', 
  '15', 
  'Square', 
  'TSW', 
  '0.100" (2.54mm)', 
  '1.54', 
  'symbols/Connectors/SCH - CONNECTORS - SAMTEC TSW-105-08-G-T-RA.SchLib', 
  'Gold', 
  'Black', 
  'Bulk', 
  'Active', 
  '0.090" (2.29mm)', 
  'Unshrouded', 
  'DigiKey Link', 
  'footprints/Connector - Samtec/PCB - CONNECTOR - SAMTEC - SAMTEC TSW-105-08-G-T-RA.PcbLib'
);

INSERT INTO "altium"."Connectors-RectangularHeadersMalePins" (
  "Description",
  "Insulation Height",
  "Part Number",
  "ComponentLink2URL",
  "Number Of Positions Loaded",
  "Contact Finish Thickness - Mating",
  "Number Of Rows",
  "Contact Type",
  "Material Flammability Rating",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Connector Type",
  "Contact Material",
  "Manufacturer",
  "Style",
  "Pitch - Mating",
  "LastUpdated",
  "Minimum Order",
  "Contact Length - Mating",
  "PartId",
  "Contact Finish - Mating",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Termination",
  "Supplier 1",
  "Fastening Type",
  "Mounting Type",
  "Insulation Material",
  "Number Of Positions",
  "Contact Shape",
  "Series",
  "Row Spacing - Mating",
  "Price",
  "Library Path",
  "Contact Finish - Post",
  "Insulation Color",
  "Packaging",
  "Part Status",
  "Contact Length - Post",
  "Shrouding",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CONN HEADER R/A 12POS 2.54MM', 
  '0.320" (8.13mm)', 
  'TSW-104-08-G-T-RA', 
  'https://www.digikey.com/en/products/detail/samtec-inc/TSW-104-08-G-T-RA/6692237', 
  'All', 
  '10.0µin (0.25µm)', 
  '3', 
  'Male Pin', 
  'UL94 V-0', 
  'SAMTEC TSW-104-08-G-T-RA', 
  'SAM12312-ND', 
  'Active', 
  'Header', 
  'Phosphor Bronze', 
  'Samtec Inc.', 
  'Board to Board or Cable', 
  '0.100" (2.54mm)', 
  '2026-03-12T00:32:39.713', 
  '1', 
  '0.230" (5.84mm)', 
  '195', 
  'Gold', 
  '=Part Number', 
  '-55°C ~ 125°C', 
  'http://suddendocs.samtec.com/prints/tsw-xxx-xx-x-x-xx-xxx-footprint.pdf', 
  'SAMTEC TSW-104-08-G-T-RA', 
  'Datasheet', 
  'Solder', 
  'DigiKey', 
  'Push-Pull', 
  'Through Hole, Right Angle', 
  'Polybutylene Terephthalate (PBT)', 
  '12', 
  'Square', 
  'TSW', 
  '0.100" (2.54mm)', 
  '1.23', 
  'symbols/Connectors/SCH - CONNECTORS - SAMTEC TSW-104-08-G-T-RA.SchLib', 
  'Gold', 
  'Black', 
  'Bulk', 
  'Active', 
  '0.090" (2.29mm)', 
  'Unshrouded', 
  'DigiKey Link', 
  'footprints/Connector - Samtec/PCB - CONNECTOR - SAMTEC - SAMTEC TSW-104-08-G-T-RA.PcbLib'
);

