--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Ratings",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 220NH 53A 0.6 MOHM SMD', 
  'ASPIAIG-F1265-R22M-T', 
  'https://www.digikey.com/en/products/detail/abracon-llc/ASPIAIG-F1265-R22M-T/8259794', 
  '0.256" (6.50mm)', 
  '53 A', 
  '1265', 
  'AEC-Q200', 
  '220 nH', 
  'INDUCTOR', 
  '535-ASPIAIG-F1265-R22M-TCT-ND', 
  'Active', 
  'Abracon LLC', 
  '2026-03-11T20:19:28.797', 
  '1', 
  '8406', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100 kHz', 
  'https://media.digikey.com/pdf/Data%20Sheets/Abracon%20Corp%20PDFs/ASPIAIG-F.pdf', 
  'ABRACON ASPIAIG-F1265', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.492" W (13.50mm x 12.50mm)', 
  '0.6mOhm Max', 
  'ASPIAIG-F1', 
  'Molded', 
  '1.25', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  '220 nH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - ABRACON ASPIAIG-F1265.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Ratings",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 47UH 6.5A 90 MOHM SMD', 
  'ASPIAIG-F1265-470M-T', 
  'https://www.digikey.com/en/products/detail/abracon-llc/ASPIAIG-F1265-470M-T/8259787', 
  '0.256" (6.50mm)', 
  '6.5 A', 
  '1265', 
  'AEC-Q200', 
  '47 µH', 
  'INDUCTOR', 
  '535-ASPIAIG-F1265-470M-TCT-ND', 
  'Active', 
  'Abracon LLC', 
  '2026-03-11T20:19:28.813', 
  '1', 
  '8407', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100 kHz', 
  'https://media.digikey.com/pdf/Data%20Sheets/Abracon%20Corp%20PDFs/ASPIAIG-F.pdf', 
  'ABRACON ASPIAIG-F1265', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.492" W (13.50mm x 12.50mm)', 
  '90mOhm Max', 
  'ASPIAIG-F1', 
  'Molded', 
  '1.25', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '47 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - ABRACON ASPIAIG-F1265.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Ratings",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 22UH 9A 37 MOHM SMD', 
  'ASPIAIG-F1265-220M-T', 
  'https://www.digikey.com/en/products/detail/abracon-llc/ASPIAIG-F1265-220M-T/8259783', 
  '0.256" (6.50mm)', 
  '9 A', 
  '1265', 
  'AEC-Q200', 
  '22 µH', 
  'INDUCTOR', 
  '535-ASPIAIG-F1265-220M-TCT-ND', 
  'Active', 
  'Abracon LLC', 
  '2026-03-11T20:19:28.820', 
  '1', 
  '8408', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100 kHz', 
  'https://media.digikey.com/pdf/Data%20Sheets/Abracon%20Corp%20PDFs/ASPIAIG-F.pdf', 
  'ABRACON ASPIAIG-F1265', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.492" W (13.50mm x 12.50mm)', 
  '37mOhm Max', 
  'ASPIAIG-F1', 
  'Molded', 
  '1.25', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '22 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - ABRACON ASPIAIG-F1265.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Ratings",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 3.3UH 18A 6.8 MOHM SMD', 
  'ASPIAIG-F1265-3R3M-T', 
  'https://www.digikey.com/en/products/detail/abracon-llc/ASPIAIG-F1265-3R3M-T/8259786', 
  '0.256" (6.50mm)', 
  '18 A', 
  '1265', 
  'AEC-Q200', 
  '3.3 µH', 
  'INDUCTOR', 
  '535-ASPIAIG-F1265-3R3M-TCT-ND', 
  'Active', 
  'Abracon LLC', 
  '2026-03-11T20:19:28.830', 
  '1', 
  '8409', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100 kHz', 
  'https://media.digikey.com/pdf/Data%20Sheets/Abracon%20Corp%20PDFs/ASPIAIG-F.pdf', 
  'ABRACON ASPIAIG-F1265', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.492" W (13.50mm x 12.50mm)', 
  '6.8mOhm Max', 
  'ASPIAIG-F1', 
  'Molded', 
  '1.25', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '3.3 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - ABRACON ASPIAIG-F1265.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Ratings",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 33UH 8A 58 MOHM SMD', 
  'ASPIAIG-F1265-330M-T', 
  'https://www.digikey.com/en/products/detail/abracon-llc/ASPIAIG-F1265-330M-T/8259785', 
  '0.256" (6.50mm)', 
  '8 A', 
  '1265', 
  'AEC-Q200', 
  '33 µH', 
  'INDUCTOR', 
  '535-ASPIAIG-F1265-330M-TCT-ND', 
  'Active', 
  'Abracon LLC', 
  '2026-03-11T20:19:28.837', 
  '1', 
  '8410', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100 kHz', 
  'https://media.digikey.com/pdf/Data%20Sheets/Abracon%20Corp%20PDFs/ASPIAIG-F.pdf', 
  'ABRACON ASPIAIG-F1265', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.492" W (13.50mm x 12.50mm)', 
  '58mOhm Max', 
  'ASPIAIG-F1', 
  'Molded', 
  '1.37', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '33 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - ABRACON ASPIAIG-F1265.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Ratings",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 4.7UH 13.5A 8.4MOHM SM', 
  'ASPIAIG-F1265-4R7M-T', 
  'https://www.digikey.com/en/products/detail/abracon-llc/ASPIAIG-F1265-4R7M-T/8259788', 
  '0.256" (6.50mm)', 
  '13.5 A', 
  '1265', 
  'AEC-Q200', 
  '4.7 µH', 
  'INDUCTOR', 
  '535-ASPIAIG-F1265-4R7M-TCT-ND', 
  'Active', 
  'Abracon LLC', 
  '2026-03-11T20:19:28.843', 
  '1', 
  '8411', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100 kHz', 
  'https://media.digikey.com/pdf/Data%20Sheets/Abracon%20Corp%20PDFs/ASPIAIG-F.pdf', 
  'ABRACON ASPIAIG-F1265', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.492" W (13.50mm x 12.50mm)', 
  '8.4mOhm Max', 
  'ASPIAIG-F1', 
  'Molded', 
  '1.25', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '4.7 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - ABRACON ASPIAIG-F1265.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Ratings",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 6.8UH 11.5A 11.5 MOHM', 
  'ASPIAIG-F1265-6R8M-T', 
  'https://www.digikey.com/en/products/detail/abracon-llc/ASPIAIG-F1265-6R8M-T/8259790', 
  '0.256" (6.50mm)', 
  '11.5 A', 
  '1265', 
  'AEC-Q200', 
  '6.8 µH', 
  'INDUCTOR', 
  '535-ASPIAIG-F1265-6R8M-TCT-ND', 
  'Active', 
  'Abracon LLC', 
  '2026-03-11T20:19:28.850', 
  '1', 
  '8412', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100 kHz', 
  'https://abracon.com/Magnetics/power/ASPIAIG-F1x.pdf', 
  'ABRACON ASPIAIG-F1265', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.492" W (13.50mm x 12.50mm)', 
  '11.5mOhm Max', 
  'ASPIAIG-F1', 
  'Molded', 
  '1.25', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '6.8 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - ABRACON ASPIAIG-F1265.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Supplier Device Package",
  "Ratings",
  "Inductance",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'FIXED IND 10UH 10A 16.5 MOHM SMD', 
  'ASPIAIG-F1265-100M-T', 
  'https://www.digikey.com/en/products/detail/abracon-llc/ASPIAIG-F1265-100M-T/8259776', 
  '0.256" (6.50mm)', 
  '10 A', 
  '1265', 
  'AEC-Q200', 
  '10 µH', 
  'INDUCTOR', 
  '535-ASPIAIG-F1265-100M-TCT-ND', 
  'Active', 
  'Abracon LLC', 
  '2026-03-11T20:19:28.860', 
  '1', 
  '8413', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100 kHz', 
  'https://abracon.com/Magnetics/power/ASPIAIG-F1x.pdf', 
  'ABRACON ASPIAIG-F1265', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.492" W (13.50mm x 12.50mm)', 
  '16.5mOhm Max', 
  'ASPIAIG-F1', 
  'Molded', 
  '1.25', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '10 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - ABRACON ASPIAIG-F1265.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '9.5A', 
  'FIXED IND 47UH 6.5A 90 MOHM SMD', 
  'MGV1207470M-10', 
  'https://www.digikey.com/en/products/detail/laird-signal-integrity-products/MGV1207470M-10/9558746', 
  '0.256" (6.50mm)', 
  '6.5 A', 
  'Nonstandard', 
  '47 µH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-3198-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.697', 
  '1', 
  'Nonstandard', 
  '8414', 
  '=Value', 
  '-55°C ~ 125°C', 
  '100 kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '90mOhm Max', 
  'MGV', 
  'Molded', 
  '1.33', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '47 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '12A', 
  'FIXED IND 22UH 9A 37MOHM SMD', 
  'MGV1207220M-10', 
  'http://digikey.com/product-detail/en/laird-signal-integrity-products/MGV1207220M-10/240-3196-1-ND/9558868', 
  '0.256" (6.50mm)', 
  '9A', 
  'Nonstandard', 
  '22µH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-3196-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.707', 
  '1', 
  'Nonstandard', 
  '8415', 
  '=Value', 
  '-55°C ~ 125°C', 
  '100kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '37mOhm Max', 
  'MGV', 
  'Molded', 
  '1.03', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '22µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '11A', 
  'FIXED IND 33UH 8A 58 MOHM SMD', 
  'MGV1207330M-10', 
  'https://www.digikey.com/en/products/detail/laird-signal-integrity-products/MGV1207330M-10/9558745', 
  '0.256" (6.50mm)', 
  '8 A', 
  'Nonstandard', 
  '33 µH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-MGV1207330M-10CT-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.720', 
  '1', 
  'Nonstandard', 
  '8416', 
  '=Value', 
  '-55°C ~ 125°C', 
  '100 kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '58mOhm Max', 
  'MGV', 
  'Molded', 
  '1.22', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '33 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '12.5A', 
  'FIXED IND 15UH 9A 28MOHM SMD', 
  'MGV1207150M-10', 
  'http://digikey.com/product-detail/en/laird-signal-integrity-products/MGV1207150M-10/240-3195-1-ND/9558867', 
  '0.256" (6.50mm)', 
  '9A', 
  'Nonstandard', 
  '15µH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-3195-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.730', 
  '1', 
  'Nonstandard', 
  '8417', 
  '=Value', 
  '-55°C ~ 125°C', 
  '100kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '28mOhm Max', 
  'MGV', 
  'Molded', 
  '1.03', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '15µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '16A', 
  'POWER INDUCTOR SMD', 
  'MGV12078R2M-10', 
  'http://digikey.com/product-detail/en/laird-signal-integrity-products/MGV12078R2M-10/240-2950-1-ND/5270005', 
  '0.256" (6.50mm)', 
  '10.5A', 
  'Nonstandard', 
  '8.2µH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-2950-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.743', 
  '1', 
  'Nonstandard', 
  '8418', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '15.5mOhm Max', 
  'MGV', 
  'Molded', 
  '0.98', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '8.2µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '32A', 
  'POWER INDUCTOR SMD', 
  'MGV12075R6M-10', 
  'http://digikey.com/product-detail/en/laird-signal-integrity-products/MGV12075R6M-10/240-2948-1-ND/5270003', 
  '0.256" (6.50mm)', 
  '13.5A', 
  'Nonstandard', 
  '5.6µH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-2948-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.753', 
  '1', 
  'Nonstandard', 
  '8419', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '10mOhm Max', 
  'MGV', 
  'Molded', 
  '0.98', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '5.6µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '15.5A', 
  'FIXED IND 10UH 10A 17.2 MOHM SMD', 
  'MGV1207100M-10', 
  'http://digikey.com/product-detail/en/laird-signal-integrity-products/MGV1207100M-10/240-2947-1-ND/5270002', 
  '0.256" (6.50mm)', 
  '10A', 
  'Nonstandard', 
  '10µH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-2947-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.760', 
  '1', 
  'Nonstandard', 
  '8420', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '17.2mOhm Max', 
  'MGV', 
  'Molded', 
  '0.98', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '10µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '63A', 
  'POWER INDUCTOR SMD', 
  'MGV1207R47M-10', 
  'http://digikey.com/product-detail/en/laird-signal-integrity-products/MGV1207R47M-10/240-2865-1-ND/5269114', 
  '0.256" (6.50mm)', 
  '41A', 
  'Nonstandard', 
  '470nH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-2865-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.770', 
  '1', 
  'Nonstandard', 
  '8421', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '1.2mOhm Max', 
  'MGV', 
  'Molded', 
  '0.98', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '470nH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '72A', 
  'POWER INDUCTOR SMD', 
  'MGV1207R30M-10', 
  'http://digikey.com/product-detail/en/laird-signal-integrity-products/MGV1207R30M-10/240-2862-1-ND/5269111', 
  '0.256" (6.50mm)', 
  '48A', 
  'Nonstandard', 
  '300nH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-2862-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.780', 
  '1', 
  'Nonstandard', 
  '8422', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '0.8mOhm Max', 
  'MGV', 
  'Molded', 
  '0.98', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '300nH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '32A', 
  'POWER INDUCTOR SMD', 
  'MGV12074R7M-10', 
  'http://digikey.com/product-detail/en/laird-signal-integrity-products/MGV12074R7M-10/240-2858-1-ND/5269107', 
  '0.256" (6.50mm)', 
  '13.5A', 
  'Nonstandard', 
  '4.7µH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-2858-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.787', 
  '1', 
  'Nonstandard', 
  '8423', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '8.7mOhm Max', 
  'MGV', 
  'Molded', 
  '0.98', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '4.7µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '40A', 
  'POWER INDUCTOR SMD', 
  'MGV12072R2M-10', 
  'http://digikey.com/product-detail/en/laird-signal-integrity-products/MGV12072R2M-10/240-2856-1-ND/5269105', 
  '0.256" (6.50mm)', 
  '22A', 
  'Nonstandard', 
  '2.2µH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-2856-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.797', 
  '1', 
  'Nonstandard', 
  '8424', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '4.2mOhm Max', 
  'MGV', 
  'Molded', 
  '0.98', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '2.2µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '41A', 
  'POWER INDUCTOR SMD', 
  'MGV12071R8M-10', 
  'http://digikey.com/product-detail/en/laird-signal-integrity-products/MGV12071R8M-10/240-2855-1-ND/5269104', 
  '0.256" (6.50mm)', 
  '24A', 
  'Nonstandard', 
  '1.8µH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-2855-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.803', 
  '1', 
  'Nonstandard', 
  '8425', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '3.2mOhm Max', 
  'MGV', 
  'Molded', 
  '0.98', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1.8µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '45A', 
  'POWER INDUCTOR SMD', 
  'MGV12071R5M-10', 
  'http://digikey.com/product-detail/en/laird-signal-integrity-products/MGV12071R5M-10/240-2854-1-ND/5269103', 
  '0.256" (6.50mm)', 
  '27A', 
  'Nonstandard', 
  '1.5µH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-2854-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.807', 
  '1', 
  'Nonstandard', 
  '8426', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '3mOhm Max', 
  'MGV', 
  'Molded', 
  '0.98', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1.5µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '49A', 
  'POWER INDUCTOR SMD', 
  'MGV12071R0M-10', 
  'http://digikey.com/product-detail/en/laird-signal-integrity-products/MGV12071R0M-10/240-2852-1-ND/5269101', 
  '0.256" (6.50mm)', 
  '32A', 
  'Nonstandard', 
  '1µH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-2852-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.820', 
  '1', 
  'Nonstandard', 
  '8427', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '2mOhm Max', 
  'MGV', 
  'Molded', 
  '0.98', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '16.5A', 
  'FIXED IND 6.8UH 11.5A 14 MOHM', 
  'MGV12076R8M-10', 
  'http://digikey.com/product-detail/en/laird-signal-integrity-products/MGV12076R8M-10/240-2949-1-ND/5270004', 
  '0.256" (6.50mm)', 
  '11.5A', 
  'Nonstandard', 
  '6.8µH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-2949-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.837', 
  '1', 
  'Nonstandard', 
  '8428', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/Catalog_FERRITE%20CORES%200717.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '14mOhm Max', 
  'MGV', 
  'Molded', 
  '0.98', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '6.8µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '50A', 
  'POWER INDUCTOR SMD', 
  'MGV1207R82M-10', 
  'http://digikey.com/product-detail/en/laird-signal-integrity-products/MGV1207R82M-10/240-2868-1-ND/5269117', 
  '0.256" (6.50mm)', 
  '33A', 
  'Nonstandard', 
  '820nH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-2868-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.850', 
  '1', 
  'Nonstandard', 
  '8429', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '1.9mOhm Max', 
  'MGV', 
  'Molded', 
  '0.98', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '820nH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '60A', 
  'POWER INDUCTOR SMD', 
  'MGV1207R68M-10', 
  'http://digikey.com/product-detail/en/laird-signal-integrity-products/MGV1207R68M-10/240-2867-1-ND/5269116', 
  '0.256" (6.50mm)', 
  '35A', 
  'Nonstandard', 
  '680nH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-2867-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.857', 
  '1', 
  'Nonstandard', 
  '8430', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '1.6mOhm Max', 
  'MGV', 
  'Molded', 
  '0.98', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '680nH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '62A', 
  'POWER INDUCTOR SMD', 
  'MGV1207R56M-10', 
  'http://digikey.com/product-detail/en/laird-signal-integrity-products/MGV1207R56M-10/240-2866-1-ND/5269115', 
  '0.256" (6.50mm)', 
  '37A', 
  'Nonstandard', 
  '560nH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-2866-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.863', 
  '1', 
  'Nonstandard', 
  '8431', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '1.4mOhm Max', 
  'MGV', 
  'Molded', 
  '0.98', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '560nH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '64A', 
  'POWER INDUCTOR SMD', 
  'MGV1207R40M-10', 
  'http://digikey.com/product-detail/en/laird-signal-integrity-products/MGV1207R40M-10/240-2864-1-ND/5269113', 
  '0.256" (6.50mm)', 
  '44A', 
  'Nonstandard', 
  '400nH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-2864-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.873', 
  '1', 
  'Nonstandard', 
  '8432', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '1mOhm Max', 
  'MGV', 
  'Molded', 
  '0.98', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '400nH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '65A', 
  'POWER INDUCTOR SMD', 
  'MGV1207R33M-10', 
  'http://digikey.com/product-detail/en/laird-signal-integrity-products/MGV1207R33M-10/240-2863-1-ND/5269112', 
  '0.256" (6.50mm)', 
  '46A', 
  'Nonstandard', 
  '330nH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-2863-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.883', 
  '1', 
  'Nonstandard', 
  '8433', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '0.9mOhm Max', 
  'MGV', 
  'Molded', 
  '0.98', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '330nH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '112A', 
  'POWER INDUCTOR SMD', 
  'MGV1207R22M-10', 
  'http://digikey.com/product-detail/en/laird-signal-integrity-products/MGV1207R22M-10/240-2861-1-ND/5269110', 
  '0.256" (6.50mm)', 
  '53A', 
  'Nonstandard', 
  '220nH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-2861-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.893', 
  '1', 
  'Nonstandard', 
  '8434', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '0.7mOhm Max', 
  'MGV', 
  'Molded', 
  '0.98', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '220nH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '118A', 
  'POWER INDUCTOR SMD', 
  'MGV1207R15M-10', 
  'http://digikey.com/product-detail/en/laird-signal-integrity-products/MGV1207R15M-10/240-2860-1-ND/5269109', 
  '0.256" (6.50mm)', 
  '55A', 
  'Nonstandard', 
  '150nH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-2860-1-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.913', 
  '1', 
  'Nonstandard', 
  '8435', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '0.6mOhm Max', 
  'MGV', 
  'Molded', 
  '0.98', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '150nH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

INSERT INTO "altium"."Inductors-Power" (
  "Current - Saturation",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Current Rating (Amps)",
  "Device Package",
  "Inductance",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Material - Core",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Inductance Frequency - Test",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Shielding",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "DC Resistance (DCR)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '35A', 
  'FIXED IND 3.3UH 18A 6.8 MOHM SMD', 
  'MGV12073R3M-10', 
  'https://www.digikey.com/en/products/detail/laird-signal-integrity-products/MGV12073R3M-10/5269039', 
  '0.256" (6.50mm)', 
  '18 A', 
  'Nonstandard', 
  '3.3 µH', 
  'Nonstandard', 
  'INDUCTOR', 
  '240-2857-2-ND', 
  'Active', 
  'Laird-Signal Integrity Products', 
  '2026-03-11T20:21:55.920', 
  '500', 
  'Nonstandard', 
  '8436', 
  '=Value', 
  '-40°C ~ 125°C', 
  '100 kHz', 
  'https://assets.lairdtech.com/home/brandworld/files/MGV1207%20series%20approve%20sheet.pdf', 
  'LAIRD MGV1207', 
  'Datasheet', 
  '±20%', 
  'Shielded', 
  'DigiKey', 
  'Surface Mount', 
  '0.531" L x 0.496" W (13.50mm x 12.60mm)', 
  '6.8mOhm Max', 
  'MGV', 
  'Molded', 
  '1.27', 
  'symbols/Passives/SCH - PASSIVES - INDUCTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '3.3 µH', 
  'DigiKey Link', 
  'footprints/Power Inductors/PCB - POWER INDUCTORS - LAIRD MGV1207.PcbLib'
);

