--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."BatteryChargers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Charge Current - Max",
  "Current - Charging",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Voltage - Supply (Max)",
  "Lifecycle Status",
  "Battery Chemistry",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Programmable Features",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Battery Pack Voltage",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Number Of Cells",
  "Series",
  "Fault Protection",
  "Price",
  "Library Path",
  "Packaging",
  "ComponentLink2Description",
  "Footprint Path",
  "Interface"
)
VALUES (
  '1A ADVANCED SINGLE CELL, FULLY I', 
  'MCP73833-96I/MF', 
  'https://www.digikey.com/en/products/detail/microchip-technology/MCP73833-96I-MF/28139198', 
  '1.1A', 
  'Constant - Programmable', 
  '10-DFN (3x3)', 
  'MICROCHIP MCP73833', 
  '150-MCP73833-96I/MF-ND', 
  '6V', 
  'Active', 
  'Lithium Ion/Polymer', 
  'Microchip Technology', 
  '2026-03-29T20:25:00.417', 
  '1', 
  'Current', 
  '55', 
  '=Part Number', 
  '-40°C ~ 125°C (TA)', 
  '4.45V', 
  'https://ww1.microchip.com/downloads/aemDocuments/documents/APID/ProductDocuments/DataSheets/MCP73833-4-Stand-Alone-Linear-Li-Ion-Li-Polymer-Charge-Management-Controller-DS20002005.pdf', 
  'MICROCHIP DFN-10 3MMX3MM MF', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '1', 
  '-', 
  'Over Temperature', 
  '0.85', 
  'symbols/Charger/SCH - CHARGER - MICROCHIP MCP73833.SCHLIB', 
  'Tube', 
  'DigiKey Link', 
  'footprints/Leadless - DFN/PCB - LEADLESS - DFN - MICROCHIP DFN-10 3MMX3MM MF.PCBLIB', 
  'USB'
);

