--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."PowerSupplies-BoardMount-DC-DC-Converters" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Voltage - Input (Max)",
  "Current - Output (Max)",
  "Voltage - Input (Min)",
  "Library Ref",
  "Efficiency",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "Voltage - Isolation",
  "ComponentLink1Description",
  "Supplier 1",
  "Voltage - Output 1",
  "Mounting Type",
  "Size / Dimension",
  "Power (Watts)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DC DC CONVERTER 5V 2W', 
  'NXE2S0505MC-R13', 
  'https://www.digikey.com/en/products/detail/murata-power-solutions-inc/NXE2S0505MC-R13/6009751', 
  '5.5V', 
  '400mA', 
  '4.5V', 
  'MURATA NXE', 
  '72%', 
  '811-NXE2S0505MC-R13CT-ND', 
  'Active', 
  'Murata Power Solutions Inc.', 
  'SCP', 
  '2026-03-29T20:24:58.557', 
  '1', 
  '100', 
  '=Part Number', 
  '1', 
  '-40°C ~ 85°C', 
  'ITE (Commercial)', 
  'https://www.murata.com/products/productdata/8807031898142/kdc-nxe2.pdf', 
  'MURATA NXE', 
  '3 kV', 
  'Datasheet', 
  'DigiKey', 
  '5V', 
  'Surface Mount', 
  '0.50" L x 0.40" W x 0.17" H (12.7mm x 10.4mm x 4.4mm)', 
  '2 W', 
  'NXE2 (2W)', 
  'Isolated Module', 
  '3.13', 
  'symbols/Power - Module/SCH - POWER - MODULE - MURATA NXE.SCHLIB', 
  'TapeAndReel', 
  'DigiKey Link', 
  'footprints/Power Module/PCB - POWER MODULE - MURATA NXE.PCBLIB'
);

INSERT INTO "altium"."PowerSupplies-BoardMount-DC-DC-Converters" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Voltage - Input (Max)",
  "Current - Output (Max)",
  "Voltage - Input (Min)",
  "Library Ref",
  "Efficiency",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "Voltage - Isolation",
  "ComponentLink1Description",
  "Supplier 1",
  "Voltage - Output 1",
  "Mounting Type",
  "Size / Dimension",
  "Power (Watts)",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DC DC CONVERTER 9V 1W', 
  'MEJ1S2409SC', 
  'https://www.digikey.com/en/products/detail/murata-power-solutions-inc/MEJ1S2409SC/4037166', 
  '26.4V', 
  '111mA', 
  '21.6V', 
  'MURATA MEJ1 SINGLE', 
  '77%', 
  'MEJ1S2409SC-ND', 
  'Active', 
  'Murata Power Solutions Inc.', 
  'SCP', 
  '2026-03-29T20:45:55.823', 
  '1', 
  '101', 
  '=Part Number', 
  '1', 
  '-40°C ~ 85°C', 
  'ITE (Commercial), Medical', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/8389/KDC_MEJ1_PDF_ISOLATEDDCDCCONVERTER.pdf', 
  'MURATA MEJ1 SINGLE', 
  '5.2 kV', 
  'Datasheet', 
  'DigiKey', 
  '9V', 
  'Through Hole', 
  '0.77" L x 0.39" W x 0.50" H (19.7mm x 10.0mm x 12.7mm)', 
  '1 W', 
  'MEJ1 (1W)', 
  'Isolated Module', 
  '6.26', 
  'symbols/Power - Module/SCH - POWER - MODULE - MURATA MEJ1 SINGLE.SCHLIB', 
  'Tube', 
  'DigiKey Link', 
  'footprints/Power Module/PCB - POWER MODULE - MURATA MEJ1 SINGLE.PCBLIB'
);

