--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 500 OHM 0.5W PC PIN TOP', 
  '3362P-1-501', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3362P-1-501/85104', 
  '±100ppm/°C', 
  '1.0', 
  'POTENTIOMETER', 
  '3362P-501-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2026-03-29T20:45:44.857', 
  '1', 
  '381', 
  'Top Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/Product-Datasheets/3362.pdf', 
  'BOURNS TRIMPOT 3362P-1', 
  'PC Pins', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Through Hole', 
  'Rectangular - 0.275" x 0.260" Face (6.99mm x 6.60mm)', 
  '500 Ohms', 
  '0.5W, 1/2W', 
  'Trimpot® 3362 - Sealed', 
  '0.89', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'Tube', 
  '500 Ohms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3362P-1.PCBLIB'
);

INSERT INTO "altium"."Resistors-TrimmerPotentiometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Temperature Coefficient",
  "Number Of Turns",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Resistive Material",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Adjustment Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'TRIMMER 10K OHM 0.5W PC PIN SIDE', 
  '3299P-1-103', 
  'https://www.digikey.com/en/products/detail/bourns-inc/3299P-1-103/84305', 
  '±100ppm/°C', 
  '25.0', 
  'POTENTIOMETER', 
  '3299P-103-ND', 
  'Active', 
  'Bourns Inc.', 
  'Cermet', 
  '2026-03-29T20:46:06.050', 
  '1', 
  '382', 
  'Side Adjustment', 
  '=Value', 
  'https://www.bourns.com/docs/Product-Datasheets/3299.pdf', 
  'BOURNS TRIMPOT 3299P', 
  'PC Pins', 
  'Datasheet', 
  '±10%', 
  'DigiKey', 
  'Through Hole', 
  'Rectangular - 0.240" x 0.375" Face (6.10mm x 9.53mm)', 
  '10 kOhms', 
  '0.5W, 1/2W', 
  'Trimpot® 3299 - Sealed', 
  '2.66', 
  'symbols/Passives/SCH - PASSIVES - POTENTIOMETER.SCHLIB', 
  'Tube', 
  '10 kOhms', 
  'DigiKey Link', 
  'footprints/Potentiometer/PCB - POTENTIOMETER - BOURNS TRIMPOT 3299P.PCBLIB'
);

