--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "LED-Indication" (
  "Color",
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Current - Test",
  "Description",
  "Device Package",
  "Footprint Path",
  "Footprint Ref",
  "Height (Max)",
  "LastUpdated",
  "Lens Style",
  "Lens Transparency",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Millicandela Rating",
  "Minimum Order",
  "Mounting Type",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Supplier Device Package",
  "Library Path",
  "Library Ref",
  "Value",
  "Viewing Angle",
  "Voltage - Forward (Vf) (Typ)",
  "Wavelength - Dominant",
  "Wavelength - Peak"
)
VALUES (
  'Green', 
  '=Value', 
  'Datasheet', 
  'https://www.inolux-corp.com/datasheet/SMDLED/Mono%20Color%20Top%20View/IN-P18ATG_V1.0.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/inolux/IN-P18ATG/16964892', 
  '20mA', 
  'TOP VIEW / 1808 PLCC / 1.8 X 0.8', 
  '0603 (1608 Metric)', 
  'footprints/LED/PCB - LED - LED 0603_1608 GREEN.PCBLIB', 
  'LED 0603_1608 GREEN', 
  '0.65mm', 
  '2023-02-05T20:55:27.067', 
  'Oval with Flat Top', 
  'Clear', 
  'Active', 
  'Inolux', 
  'IN-P18ATG', 
  '1000mcd', 
  '1', 
  'Surface Mount', 
  '0603 (1608 Metric)', 
  'TapeAndReel', 
  '1270', 
  'Active', 
  '0.06', 
  '-', 
  '1.80mm L x 0.80mm W', 
  'DigiKey', 
  '1830-IN-P18ATGCT-ND', 
  '2-PLCC', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'LED', 
  'Green', 
  '120°', 
  '3.2V', 
  '521nm', 
  '515nm'
);

INSERT INTO "LED-Indication" (
  "Color",
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Configuration",
  "Current - Test",
  "Description",
  "Device Package",
  "Footprint Path",
  "Footprint Ref",
  "Height (Max)",
  "LastUpdated",
  "Lens Color",
  "Lens Transparency",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Millicandela Rating",
  "Minimum Order",
  "Mounting Type",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Supplier Device Package",
  "Library Path",
  "Library Ref",
  "Value",
  "Viewing Angle",
  "Voltage - Forward (Vf) (Typ)",
  "Wavelength - Dominant",
  "Wavelength - Peak"
)
VALUES (
  'Green', 
  '=Value', 
  'Datasheet', 
  'https://sunledusa.com/products/spec/XZDG55W-2.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/sunled/XZDG55W-2/15203886', 
  'Standard', 
  '20mA', 
  'LED GREEN CLEAR 1206 SMD', 
  '1206 (3216 Metric)', 
  'footprints/LED/PCB - LED - LED 1206_3216 GREEN.PCBLIB', 
  'LED 1206_3216 GREEN', 
  '1.25mm', 
  '2023-02-05T20:55:39.367', 
  'Colorless', 
  'Clear', 
  'Active', 
  'SunLED', 
  'XZDG55W-2', 
  '447mcd', 
  '2000', 
  'Surface Mount', 
  '1206 (3216 Metric)', 
  'TapeAndReel', 
  '1271', 
  'Active', 
  '0.25', 
  '-', 
  '3.20mm L x 1.60mm W', 
  'DigiKey', 
  '1497-XZDG55W-2TR-ND', 
  'Chip LED', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'LED', 
  'Green', 
  '120°', 
  '3.3V', 
  '525nm', 
  '515nm'
);

INSERT INTO "LED-Indication" (
  "Color",
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Configuration",
  "Current - Test",
  "Description",
  "Device Package",
  "Footprint Path",
  "Footprint Ref",
  "Height (Max)",
  "LastUpdated",
  "Lens Color",
  "Lens Size",
  "Lens Style",
  "Lens Transparency",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Millicandela Rating",
  "Minimum Order",
  "Mounting Type",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Supplier Device Package",
  "Library Path",
  "Library Ref",
  "Value",
  "Viewing Angle",
  "Voltage - Forward (Vf) (Typ)",
  "Wavelength - Dominant",
  "Wavelength - Peak"
)
VALUES (
  'Green', 
  '=Value', 
  'Datasheet', 
  'https://www.stanley-components.com/php/downloaddatafile.php?rp=h1105w_e.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/stanley-electric-co/HPY1105W-TR/428725', 
  'Standard', 
  '20mA', 
  'LED GREEN CLEAR 3216 SMD', 
  '1206 (3216 Metric)', 
  'footprints/LED/PCB - LED - LED 1206_3216 GREEN.PCBLIB', 
  'LED 1206_3216 GREEN', 
  '2.05mm', 
  '2023-02-05T20:55:39.407', 
  'Colorless', 
  '1.60mm Dia', 
  'Round with Domed Top', 
  'Clear', 
  'Active', 
  'Stanley Electric Co', 
  'HPY1105W-TR', 
  '50mcd', 
  '2000', 
  'Surface Mount', 
  '1206 (3216 Metric)', 
  'TapeAndReel', 
  '1272', 
  'Active', 
  '0.09', 
  '1105W', 
  '3.20mm L x 1.60mm W', 
  'DigiKey', 
  '404-1036-2-ND', 
  '3216 Type', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'LED', 
  'Green', 
  '40°', 
  '2.1V', 
  '572nm', 
  '570nm'
);

INSERT INTO "LED-Indication" (
  "Color",
  "Comment",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Configuration",
  "Current - Test",
  "Description",
  "Device Package",
  "Footprint Path",
  "Footprint Ref",
  "Height (Max)",
  "LastUpdated",
  "Lens Size",
  "Lens Style",
  "Lens Transparency",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Millicandela Rating",
  "Minimum Order",
  "Mounting Type",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Supplier Device Package",
  "Library Path",
  "Library Ref",
  "Value",
  "Viewing Angle",
  "Voltage - Forward (Vf) (Typ)",
  "Wavelength - Dominant",
  "Wavelength - Peak"
)
VALUES (
  'Red', 
  '=Value', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/liteon/LTST-C191KEKT/388523', 
  'Standard', 
  '20mA', 
  'LED RED CLEAR THIN 0603 SMD', 
  '0603 (1608 Metric)', 
  'footprints/LED/PCB - LED - LED 0603_1608 RED.PCBLIB', 
  'LED 0603_1608 RED', 
  '0.55mm', 
  '2023-02-05T20:55:55.900', 
  '1.10mm x 0.80mm', 
  'Rectangle', 
  'Clear', 
  'Active', 
  'Lite-On Inc.', 
  'LTST-C191KEKT', 
  '50mcd', 
  '1', 
  'Surface Mount', 
  '0603 (1608 Metric)', 
  'TapeAndReel', 
  '1273', 
  'Active', 
  '0.09', 
  '-', 
  '1.60mm L x 0.80mm W', 
  'DigiKey', 
  '160-LTST-C191KEKTCT-ND', 
  'Chip LED', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'LED', 
  'Red', 
  '130°', 
  '2V', 
  '624nm', 
  '624nm'
);

INSERT INTO "LED-Indication" (
  "Color",
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Current - Test",
  "Description",
  "Device Package",
  "Footprint Path",
  "Footprint Ref",
  "Height (Max)",
  "LastUpdated",
  "Lens Color",
  "Lens Size",
  "Lens Style",
  "Lens Transparency",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Millicandela Rating",
  "Minimum Order",
  "Mounting Type",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Supplier Device Package",
  "Library Path",
  "Library Ref",
  "Value",
  "Voltage - Forward (Vf) (Typ)",
  "Wavelength - Dominant"
)
VALUES (
  'Red', 
  '=Value', 
  'Datasheet', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/opto/led/chip_mono/csl0903ut1(c)-e.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/CSL0903UT1C/16808176', 
  '20mA', 
  'HIGH BRIGHTNESS LENS TYPE, RED C', 
  '0603 (1608 Metric)', 
  'footprints/LED/PCB - LED - LED 0603_1608 RED.PCBLIB', 
  'LED 0603_1608 RED', 
  '1.34mm', 
  '2023-02-05T20:55:55.843', 
  'Colorless', 
  '1.14mm Dia', 
  'Round with Domed Top', 
  'Clear', 
  'Active', 
  'Rohm Semiconductor', 
  'CSL0903UT1C', 
  '1200mcd', 
  '1', 
  'Surface Mount', 
  '0603 (1608 Metric)', 
  'TapeAndReel', 
  '1274', 
  'Active', 
  '0.17', 
  '-', 
  '1.60mm L x 0.80mm W', 
  'DigiKey', 
  '846-CSL0903UT1CCT-ND', 
  '0603', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'LED', 
  'Red', 
  '2.1V', 
  '620nm'
);

INSERT INTO "LED-Indication" (
  "Color",
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Current - Test",
  "Description",
  "Device Package",
  "Footprint Path",
  "Footprint Ref",
  "Height (Max)",
  "LastUpdated",
  "Lens Style",
  "Lens Transparency",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Millicandela Rating",
  "Minimum Order",
  "Mounting Type",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Supplier Device Package",
  "Library Path",
  "Library Ref",
  "Value",
  "Viewing Angle",
  "Voltage - Forward (Vf) (Typ)",
  "Wavelength - Dominant",
  "Wavelength - Peak"
)
VALUES (
  'Red', 
  '=Value', 
  'Datasheet', 
  'https://www.inolux-corp.com/datasheet/SMDLED/Mono%20Color%20Top%20View/IN-P18ATR_V1.0.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/inolux/IN-P18ATR/16963764', 
  '20mA', 
  'TOP VIEW / 1808 PLCC / 1.8 X 0.8', 
  '0603 (1608 Metric)', 
  'footprints/LED/PCB - LED - LED 0603_1608 RED.PCBLIB', 
  'LED 0603_1608 RED', 
  '0.65mm', 
  '2023-02-05T20:55:55.927', 
  'Oval with Flat Top', 
  'Clear', 
  'Active', 
  'Inolux', 
  'IN-P18ATR', 
  '230mcd', 
  '1', 
  'Surface Mount', 
  '0603 (1608 Metric)', 
  'TapeAndReel', 
  '1275', 
  'Active', 
  '0.05', 
  '-', 
  '1.80mm L x 0.80mm W', 
  'DigiKey', 
  '1830-IN-P18ATRCT-ND', 
  '2-PLCC', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'LED', 
  'Red', 
  '120°', 
  '2.2V', 
  '620nm', 
  '630nm'
);

INSERT INTO "LED-Indication" (
  "Color",
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Current - Test",
  "Description",
  "Device Package",
  "Footprint Path",
  "Footprint Ref",
  "Height (Max)",
  "LastUpdated",
  "Lens Color",
  "Lens Size",
  "Lens Style",
  "Lens Transparency",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Millicandela Rating",
  "Minimum Order",
  "Mounting Type",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Supplier Device Package",
  "Library Path",
  "Library Ref",
  "Value",
  "Voltage - Forward (Vf) (Typ)",
  "Wavelength - Dominant"
)
VALUES (
  'Red', 
  '=Value', 
  'Datasheet', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/opto/led/chip_mono/csl0903ut1-e.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/CSL0903UT1/16808223', 
  '20mA', 
  'HIGH BRIGHTNESS LENS TYPE, RED C', 
  '0603 (1608 Metric)', 
  'footprints/LED/PCB - LED - LED 0603_1608 RED.PCBLIB', 
  'LED 0603_1608 RED', 
  '1.34mm', 
  '2023-02-05T20:55:56.097', 
  'Colorless', 
  '1.14mm Dia', 
  'Round with Domed Top', 
  'Clear', 
  'Active', 
  'Rohm Semiconductor', 
  'CSL0903UT1', 
  '1200mcd', 
  '1', 
  'Surface Mount', 
  '0603 (1608 Metric)', 
  'TapeAndReel', 
  '1276', 
  'Active', 
  '0.16', 
  '-', 
  '1.60mm L x 0.80mm W', 
  'DigiKey', 
  '846-CSL0903UT1CT-ND', 
  '0603', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'LED', 
  'Red', 
  '2.1V', 
  '620nm'
);

INSERT INTO "LED-Indication" (
  "Color",
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Configuration",
  "Current - Test",
  "Description",
  "Device Package",
  "Footprint Path",
  "Footprint Ref",
  "Height (Max)",
  "LastUpdated",
  "Lens Size",
  "Lens Style",
  "Lens Transparency",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Millicandela Rating",
  "Minimum Order",
  "Mounting Type",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Library Path",
  "Library Ref",
  "Value",
  "Viewing Angle",
  "Voltage - Forward (Vf) (Typ)",
  "Wavelength - Dominant",
  "Wavelength - Peak"
)
VALUES (
  'Green', 
  '=Value', 
  'Datasheet', 
  'https://media.digikey.com/pdf/Data%20Sheets/Lite-On%20PDFs/LTST-C170FKT.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/liteon/LTST-C170FKT/269220', 
  'Standard', 
  '20mA', 
  'LED BRITE GREEN CLEAR 0805 SMD', 
  '0805 (2012 Metric)', 
  'footprints/LED/PCB - LED - LED 0805_2012 GREEN.PCBLIB', 
  'LED 0805_2012 GREEN', 
  '1.10mm', 
  '2023-02-05T20:56:16.167', 
  '1.40mm x 1.25mm', 
  'Rectangle with Flat Top', 
  'Clear', 
  'Active', 
  'Lite-On Inc.', 
  'LTST-C170FKT', 
  '14.2mcd', 
  '1', 
  'Surface Mount', 
  '0805 (2012 Metric)', 
  'TapeAndReel', 
  '1277', 
  'Active', 
  '0.10', 
  '-', 
  '2.00mm L x 1.25mm W', 
  'DigiKey', 
  '160-1173-1-ND', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'LED', 
  'Green', 
  '130°', 
  '2.1V', 
  '569nm', 
  '565nm'
);

INSERT INTO "LED-Indication" (
  "Color",
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Configuration",
  "Current - Test",
  "Description",
  "Device Package",
  "Footprint Path",
  "Footprint Ref",
  "Height (Max)",
  "LastUpdated",
  "Lens Color",
  "Lens Size",
  "Lens Style",
  "Lens Transparency",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Millicandela Rating",
  "Minimum Order",
  "Mounting Type",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Supplier Device Package",
  "Library Path",
  "Library Ref",
  "Value",
  "Viewing Angle",
  "Voltage - Forward (Vf) (Typ)",
  "Wavelength - Dominant",
  "Wavelength - Peak"
)
VALUES (
  'Red', 
  '=Value', 
  'Datasheet', 
  'https://everlightamericas.com/index.php?controller=attachment&id_attachment=1062', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/everlight-electronics-co-ltd/EAST3015RA3/5142468', 
  'Standard', 
  '20mA', 
  'LED RED CLEAR 2SMD', 
  '1206 (3216 Metric)', 
  'footprints/LED/PCB - LED - LED 1206_3216 RED.PCBLIB', 
  'LED 1206_3216 RED', 
  '1.60mm', 
  '2023-02-05T20:56:24.047', 
  'Colorless', 
  '1.10mm Dia', 
  'Round with Flat Top', 
  'Clear', 
  'Active', 
  'Everlight Electronics Co Ltd', 
  'EAST3015RA3', 
  '102mcd', 
  '2000', 
  'Surface Mount', 
  '1206 (3216 Metric)', 
  'TapeAndReel', 
  '1278', 
  'Active', 
  '0.04', 
  '-', 
  '3.00mm L x 1.50mm W', 
  'DigiKey', 
  'EAST3015RA3-ND', 
  '2-SMD', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'LED', 
  'Red', 
  '60°', 
  '2V', 
  '624nm', 
  '632nm'
);

INSERT INTO "LED-Indication" (
  "Color",
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Current - Test",
  "Description",
  "Device Package",
  "Footprint Path",
  "Footprint Ref",
  "Height (Max)",
  "LastUpdated",
  "Lens Color",
  "Lens Size",
  "Lens Style",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Millicandela Rating",
  "Minimum Order",
  "Mounting Type",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Supplier Device Package",
  "Library Path",
  "Library Ref",
  "Value",
  "Viewing Angle",
  "Voltage - Forward (Vf) (Typ)"
)
VALUES (
  'White', 
  '=Value', 
  'Datasheet', 
  'https://optoelectronics.liteon.com/upload/download/DS35-2019-0142/LTST-T180UWET.PDF', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/liteon/LTST-T180UWET/17126183', 
  '20mA', 
  'LED SMD', 
  '0603 (1608 Metric)', 
  'footprints/LED/PCB - LED - LED 0603_1608.PCBLIB', 
  'LED 0603_1608', 
  '0.75mm', 
  '2023-02-05T20:59:16.197', 
  'Yellow', 
  '1.34mm x 0.60mm', 
  'Rectangle with Flat Top', 
  'Active', 
  'Lite-On Inc.', 
  'LTST-T180UWET', 
  '2275mcd', 
  '1', 
  'Surface Mount', 
  '0603 (1608 Metric)', 
  'TapeAndReel', 
  '1279', 
  'Active', 
  '0.05', 
  '-', 
  '1.60mm L x 0.80mm W', 
  'DigiKey', 
  '160-LTST-T180UWETCT-ND', 
  '0603', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'LED', 
  'White', 
  '120°', 
  '2.85V'
);

INSERT INTO "LED-Indication" (
  "Color",
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Configuration",
  "Current - Test",
  "Description",
  "Device Package",
  "Footprint Path",
  "Footprint Ref",
  "Height (Max)",
  "LastUpdated",
  "Lens Size",
  "Lens Style",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Millicandela Rating",
  "Minimum Order",
  "Mounting Type",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Library Path",
  "Library Ref",
  "Value",
  "Voltage - Forward (Vf) (Typ)",
  "Wavelength - Dominant"
)
VALUES (
  'Green', 
  '=Value', 
  'Datasheet', 
  'https://ce.citizen.co.jp/up_img/product/l3DSeGGaYefr/CL-195_e.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/citizen/CL-195YG-CD-T/6005903', 
  'Standard', 
  '20mA', 
  'LED GREEN SMD', 
  '0603 (1608 Metric)', 
  'footprints/LED/PCB - LED - LED 0603_1608 GREEN.PCBLIB', 
  'LED 0603_1608 GREEN', 
  '0.80mm', 
  '2023-02-05T20:55:26.707', 
  '1.60mm x 0.80mm', 
  'Rectangle with Flat Top', 
  'Active', 
  'Citizen', 
  'CL-195YG-CD-T', 
  '18mcd', 
  '1', 
  'Surface Mount', 
  '0603 (1608 Metric)', 
  'TapeAndReel', 
  '1280', 
  'Active', 
  '0.06', 
  'CL-195', 
  '1.60mm L x 0.80mm W', 
  'DigiKey', 
  '1642-1491-1-ND', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'LED', 
  'Green', 
  '2.2V', 
  '575nm'
);

INSERT INTO "LED-Indication" (
  "Color",
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Configuration",
  "Current - Test",
  "Description",
  "Device Package",
  "Footprint Path",
  "Footprint Ref",
  "Height (Max)",
  "LastUpdated",
  "Lens Color",
  "Lens Size",
  "Lens Style",
  "Lens Transparency",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Millicandela Rating",
  "Minimum Order",
  "Mounting Type",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Supplier Device Package",
  "Library Path",
  "Library Ref",
  "Value",
  "Voltage - Forward (Vf) (Typ)",
  "Wavelength - Dominant"
)
VALUES (
  'Red', 
  '=Value', 
  'Datasheet', 
  'https://www.rohm.com/datasheet/SML-P12DT(R)', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SML-P12VTT86R/4862237', 
  'Standard', 
  '20mA', 
  'LED RED CLEAR 0402 SMD', 
  '0402 (1005 Metric)', 
  'footprints/LED/PCB - LED - LED 0402_1005 RED.PCBLIB', 
  'LED 0402_1005 RED', 
  '0.25mm', 
  '2023-02-05T20:55:45.187', 
  'Colorless', 
  '0.60mm', 
  'Square with Flat Top', 
  'Clear', 
  'Active', 
  'Rohm Semiconductor', 
  'SML-P12VTT86R', 
  '60mcd', 
  '1', 
  'Surface Mount', 
  '0402 (1005 Metric)', 
  'TapeAndReel', 
  '1281', 
  'Active', 
  '0.07', 
  'PicoLED™', 
  '1.00mm L x 0.60mm W', 
  'DigiKey', 
  '846-1168-1-ND', 
  '1006 (0402)', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'LED', 
  'Red', 
  '2V', 
  '630nm'
);

INSERT INTO "LED-Indication" (
  "Color",
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Configuration",
  "Current - Test",
  "Description",
  "Device Package",
  "Footprint Path",
  "Footprint Ref",
  "Height (Max)",
  "LastUpdated",
  "Lens Color",
  "Lens Size",
  "Lens Style",
  "Lens Transparency",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Millicandela Rating",
  "Minimum Order",
  "Mounting Type",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Supplier Device Package",
  "Library Path",
  "Library Ref",
  "Value",
  "Viewing Angle",
  "Voltage - Forward (Vf) (Typ)",
  "Wavelength - Dominant",
  "Wavelength - Peak"
)
VALUES (
  'Yellow', 
  '=Value', 
  'Datasheet', 
  'https://www.KingbrightUSA.com/images/catalog/SPEC/APT3216LSYCK-J3-PRV.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/kingbright/APT3216LSYCK-J3-PRV/5177443', 
  'Standard', 
  '2mA', 
  'LED YELLOW CLEAR 2SMD', 
  '1206 (3216 Metric)', 
  'footprints/LED/PCB - LED - LED 1206_3216 YELLOW.PCBLIB', 
  'LED 1206_3216 YELLOW', 
  '0.75mm', 
  '2023-02-05T20:56:53.113', 
  'Colorless', 
  '1.90mm x 1.60mm', 
  'Rectangle with Flat Top', 
  'Clear', 
  'Active', 
  'Kingbright', 
  'APT3216LSYCK/J3-PRV', 
  '25mcd', 
  '1', 
  'Surface Mount', 
  '1206 (3216 Metric)', 
  'TapeAndReel', 
  '1282', 
  'Active', 
  '0.11', 
  'HELI2', 
  '3.20mm L x 1.60mm W', 
  'DigiKey', 
  '754-1942-1-ND', 
  '2-SMD', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'LED', 
  'Yellow', 
  '120°', 
  '1.85V', 
  '590nm', 
  '590nm'
);

INSERT INTO "LED-Indication" (
  "Color",
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Current - Test",
  "Description",
  "Device Package",
  "Footprint Path",
  "Footprint Ref",
  "Height (Max)",
  "LastUpdated",
  "Lens Color",
  "Lens Size",
  "Lens Style",
  "Lens Transparency",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Millicandela Rating",
  "Minimum Order",
  "Mounting Type",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Supplier Device Package",
  "Library Path",
  "Library Ref",
  "Value",
  "Voltage - Forward (Vf) (Typ)",
  "Wavelength - Dominant"
)
VALUES (
  'Red', 
  '=Value', 
  'Datasheet', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/opto/led/chip_mono/sml-d12l8wt86-e.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SML-D12L8WT86/17050309', 
  '20mA', 
  'EXCELED SERIES CHIP LED: ROHM''S', 
  '0603 (1608 Metric)', 
  'footprints/LED/PCB - LED - LED 0603_1608 RED.PCBLIB', 
  'LED 0603_1608 RED', 
  '0.65mm', 
  '2023-02-05T20:55:55.303', 
  'White', 
  '1.20mm x 0.80mm', 
  'Rectangle with Flat Top', 
  'Diffused', 
  'Active', 
  'Rohm Semiconductor', 
  'SML-D12L8WT86', 
  '16mcd', 
  '1', 
  'Surface Mount', 
  '0603 (1608 Metric)', 
  'TapeAndReel', 
  '1283', 
  'Active', 
  '0.09', 
  '-', 
  '1.60mm L x 0.80mm W', 
  'DigiKey', 
  '846-SML-D12L8WT86CT-ND', 
  '0603', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'LED', 
  'Red', 
  '2V', 
  '635nm'
);

