--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Capacitors-Tantalum" (
  "Capacitance",
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Description",
  "Device Package",
  "ESR (Equivalent Series Resistance)",
  "Features",
  "Footprint Path",
  "Footprint Ref",
  "Height - Seated (Max)",
  "LastUpdated",
  "Lifecycle Status",
  "Lifetime @ Temp.",
  "Manufacturer",
  "Part Number",
  "Manufacturer Size Code",
  "Minimum Order",
  "Mounting Type",
  "Operating Temperature",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Ratings",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Library Path",
  "Library Ref",
  "Tolerance",
  "Type",
  "Value",
  "Voltage - Rated"
)
VALUES (
  '1 µF', 
  '=Value', 
  'Datasheet', 
  'https://datasheets.kyocera-avx.com/TAJ_AUTO.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/TAJB105K035TNJ/11201827', 
  'CAP TANT 1UF 10% 35V 1411', 
  '1411 (3528 Metric)', 
  '6.5Ohm @ 100kHz', 
  'Automotive', 
  'footprints/Capacitor - Tantalum/PCB - CAPACITOR - TANTALUM - CAP POL 1411_3528.PCBLIB', 
  'CAP POL 1411_3528', 
  '0.083" (2.10mm)', 
  '2023-02-05T20:42:51.240', 
  'Active', 
  '2000 Hrs @ 125°C', 
  'KYOCERA AVX', 
  'TAJB105K035TNJ', 
  'B', 
  '2000', 
  'Surface Mount', 
  '-55°C ~ 125°C', 
  '1411 (3528 Metric)', 
  'TapeAndReel', 
  '5339', 
  'Active', 
  '0.11', 
  'AEC-Q200', 
  'TAJ', 
  '0.138" L x 0.110" W (3.50mm x 2.80mm)', 
  'DigiKey', 
  '478-TAJB105K035TNJTR-ND', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'POLARISED CAPACITOR', 
  '±10%', 
  'Molded', 
  '1 µF', 
  '35 V'
);

INSERT INTO "Capacitors-Tantalum" (
  "Capacitance",
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Description",
  "Device Package",
  "ESR (Equivalent Series Resistance)",
  "Features",
  "Footprint Path",
  "Footprint Ref",
  "Height - Seated (Max)",
  "LastUpdated",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Manufacturer Size Code",
  "Minimum Order",
  "Mounting Type",
  "Operating Temperature",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Library Path",
  "Library Ref",
  "Tolerance",
  "Type",
  "Value",
  "Voltage - Rated"
)
VALUES (
  '3.3 µF', 
  '=Value', 
  'Datasheet', 
  'https://www.vishay.com/docs/40002/293d.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/vishay-sprague/293D335X5016A2TE3/1578825', 
  'CAP TANT 3.3UF 5% 16V 1206', 
  '1206 (3216 Metric)', 
  '5Ohm', 
  'General Purpose', 
  'footprints/Capacitor - Tantalum/PCB - CAPACITOR - TANTALUM - CAP POL 1206_3216.PCBLIB', 
  'CAP POL 1206_3216', 
  '0.071" (1.80mm)', 
  '2023-02-05T20:43:17.930', 
  'Active', 
  'Vishay Sprague', 
  '293D335X5016A2TE3', 
  'A', 
  '2000', 
  'Surface Mount', 
  '-55°C ~ 125°C', 
  '1206 (3216 Metric)', 
  'TapeAndReel', 
  '5340', 
  'Active', 
  '0.19', 
  'TANTAMOUNT®, 293D', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  'DigiKey', 
  '293D335X5016A2TE3-ND', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'POLARISED CAPACITOR', 
  '±5%', 
  'Molded', 
  '3.3 µF', 
  '16 V'
);

INSERT INTO "Capacitors-Tantalum" (
  "Capacitance",
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Description",
  "Device Package",
  "ESR (Equivalent Series Resistance)",
  "Features",
  "Footprint Path",
  "Footprint Ref",
  "Height - Seated (Max)",
  "LastUpdated",
  "Lifecycle Status",
  "Manufacturer",
  "Part Number",
  "Manufacturer Size Code",
  "Minimum Order",
  "Mounting Type",
  "Operating Temperature",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Library Path",
  "Library Ref",
  "Tolerance",
  "Type",
  "Value",
  "Voltage - Rated"
)
VALUES (
  '22 µF', 
  '=Value', 
  'Datasheet', 
  'https://datasheets.kyocera-avx.com/TPS.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/TPSD226K035R0300/1473130', 
  'CAP TANT 22UF 10% 35V 2917', 
  '2917 (7343 Metric)', 
  '300mOhm', 
  'General Purpose', 
  'footprints/Capacitor - Tantalum/PCB - CAPACITOR - TANTALUM - CAP POL 2917_7343.PCBLIB', 
  'CAP POL 2917_7343', 
  '0.122" (3.10mm)', 
  '2023-02-05T20:43:51.187', 
  'Active', 
  'KYOCERA AVX', 
  'TPSD226K035R0300', 
  'D', 
  '1', 
  'Surface Mount', 
  '-55°C ~ 125°C', 
  '2917 (7343 Metric)', 
  'TapeAndReel', 
  '5342', 
  'Active', 
  '1.44', 
  'TPS', 
  '0.287" L x 0.169" W (7.30mm x 4.30mm)', 
  'DigiKey', 
  '478-TPSD226K035R0300CT-ND', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'POLARISED CAPACITOR', 
  '±10%', 
  'Molded', 
  '22 µF', 
  '35 V'
);

INSERT INTO "Capacitors-Tantalum" (
  "Capacitance",
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Description",
  "Device Package",
  "ESR (Equivalent Series Resistance)",
  "Features",
  "Footprint Path",
  "Footprint Ref",
  "Height - Seated (Max)",
  "LastUpdated",
  "Lifecycle Status",
  "Lifetime @ Temp.",
  "Manufacturer",
  "Part Number",
  "Manufacturer Size Code",
  "Minimum Order",
  "Mounting Type",
  "Operating Temperature",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Library Path",
  "Library Ref",
  "Tolerance",
  "Type",
  "Value",
  "Voltage - Rated"
)
VALUES (
  '6.8 µF', 
  '=Value', 
  'Datasheet', 
  'https://api.kemet.com/component-edge/download/datasheet/T491D685K035AH.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/kemet/T491D685K035AH/2336352', 
  'CAP TANT 6.8UF 10% 35V 2917', 
  '2917 (7343 Metric)', 
  '1.3Ohm', 
  'General Purpose', 
  'footprints/Capacitor - Tantalum/PCB - CAPACITOR - TANTALUM - CAP POL 2917_7343.PCBLIB', 
  'CAP POL 2917_7343', 
  '0.122" (3.10mm)', 
  '2023-02-05T20:43:51.210', 
  'Active', 
  '2000 Hrs @ 125°C', 
  'KEMET', 
  'T491D685K035AH', 
  'D', 
  '500', 
  'Surface Mount', 
  '-55°C ~ 125°C', 
  '2917 (7343 Metric)', 
  'TapeAndReel', 
  '5343', 
  'Active', 
  '0.52', 
  'T491', 
  '0.287" L x 0.169" W (7.30mm x 4.30mm)', 
  'DigiKey', 
  'T491D685K035AH-ND', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'POLARISED CAPACITOR', 
  '±10%', 
  'Molded', 
  '6.8 µF', 
  '35 V'
);

INSERT INTO "Capacitors-Tantalum" (
  "Capacitance",
  "Comment",
  "ComponentLink1Description",
  "ComponentLink1URL",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Description",
  "Device Package",
  "ESR (Equivalent Series Resistance)",
  "Features",
  "Footprint Path",
  "Footprint Ref",
  "Height - Seated (Max)",
  "LastUpdated",
  "Lifecycle Status",
  "Lifetime @ Temp.",
  "Manufacturer",
  "Part Number",
  "Manufacturer Size Code",
  "Minimum Order",
  "Mounting Type",
  "Operating Temperature",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Library Path",
  "Library Ref",
  "Tolerance",
  "Type",
  "Value",
  "Voltage - Rated"
)
VALUES (
  '100 µF', 
  '=Value', 
  'Datasheet', 
  'https://api.kemet.com/component-edge/download/datasheet/T494D107K010AH.pdf', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/kemet/T494D107K010AH/9452608', 
  'CAP TANT 100UF 10% 10V 2917', 
  '2917 (7343 Metric)', 
  '150mOhm @ 100kHz', 
  'General Purpose', 
  'footprints/Capacitor - Tantalum/PCB - CAPACITOR - TANTALUM - CAP POL 2917_7343.PCBLIB', 
  'CAP POL 2917_7343', 
  '0.122" (3.10mm)', 
  '2023-02-05T20:43:51.223', 
  'Active', 
  '2000 Hrs @ 125°C', 
  'KEMET', 
  'T494D107K010AH', 
  'D', 
  '500', 
  'Surface Mount', 
  '-55°C ~ 125°C', 
  '2917 (7343 Metric)', 
  'TapeAndReel', 
  '5344', 
  'Active', 
  '0.93', 
  'T494', 
  '0.287" L x 0.169" W (7.30mm x 4.30mm)', 
  'DigiKey', 
  'T494D107K010AH-ND', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'POLARISED CAPACITOR', 
  '±10%', 
  'Molded', 
  '100 µF', 
  '10 V'
);

INSERT INTO "Capacitors-Tantalum" (
  "Capacitance",
  "Comment",
  "ComponentLink2Description",
  "ComponentLink2URL",
  "Description",
  "Device Package",
  "ESR (Equivalent Series Resistance)",
  "Features",
  "Footprint Path",
  "Footprint Ref",
  "Height - Seated (Max)",
  "LastUpdated",
  "Lifecycle Status",
  "Lifetime @ Temp.",
  "Manufacturer",
  "Part Number",
  "Manufacturer Size Code",
  "Minimum Order",
  "Mounting Type",
  "Operating Temperature",
  "Package / Case",
  "Packaging",
  "PartId",
  "Part Status",
  "Price",
  "Series",
  "Size / Dimension",
  "Supplier 1",
  "Supplier Part Number 1",
  "Library Path",
  "Library Ref",
  "Tolerance",
  "Type",
  "Value",
  "Voltage - Rated"
)
VALUES (
  '10 µF', 
  '=Value', 
  'DigiKey Link', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/TPSD106K050R0500/11266866', 
  'CAP TANT', 
  '2917 (7343 Metric)', 
  '500mOhm @ 100kHz', 
  'General Purpose', 
  'footprints/Capacitor - Tantalum/PCB - CAPACITOR - TANTALUM - CAP POL 2917_7343.PCBLIB', 
  'CAP POL 2917_7343', 
  '0.122" (3.10mm)', 
  '2023-02-05T20:43:51.613', 
  'Active', 
  '2000 Hrs @ 125°C', 
  'KYOCERA AVX', 
  'TPSD106K050R0500', 
  'D', 
  '1', 
  'Surface Mount', 
  '-55°C ~ 125°C', 
  '2917 (7343 Metric)', 
  'TapeAndReel', 
  '5345', 
  'Active', 
  '1.89', 
  'TPS', 
  '0.287" L x 0.169" W (7.30mm x 4.30mm)', 
  'DigiKey', 
  '478-TPSD106K050R0500CT-ND', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'POLARISED CAPACITOR', 
  '±10%', 
  'Molded', 
  '10 µF', 
  '50 V'
);

