--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

CREATE TABLE IF NOT EXISTS "Resistors-RotaryPotentiometers" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Temperature Coefficient" varchar(255) NULL,
  "Part Number" varchar(255) NULL,
  "Description" varchar(255) NULL,
  "Supplier Part Number 1" varchar(255) NULL,
  "Supplier Part Number 2" varchar(255) NULL,
  "Actuator Length" varchar(255) NULL,
  "Resistance (Ohms)" varchar(255) NULL,
  "Supplier Part Number 5" varchar(255) NULL,
  "Resistive Material" varchar(255) NULL,
  "Supplier Part Number 6" varchar(255) NULL,
  "Supplier Part Number 3" varchar(255) NULL,
  "ComponentLink1Description" varchar(255) NULL,
  "Supplier Part Number 4" varchar(255) NULL,
  "Bushing Thread" varchar(255) NULL,
  "ComponentLink6URL" varchar(255) NULL,
  "ComponentLink2URL" varchar(255) NULL,
  "ComponentLink1URL" varchar(255) NULL,
  "Comment" varchar(255) NULL,
  "Number of Gangs" varchar(255) NULL,
  "Rotation" varchar(255) NULL,
  "Supplier 5" varchar(255) NULL,
  "Supplier 6" varchar(255) NULL,
  "Supplier 3" varchar(255) NULL,
  "Supplier 4" varchar(255) NULL,
  "Tolerance" varchar(255) NULL,
  "Footprint Ref 3" varchar(255) NULL,
  "Supplier 1" varchar(255) NULL,
  "Supplier 2" varchar(255) NULL,
  "Number of Turns" varchar(255) NULL,
  "Footprint Path 3" varchar(255) NULL,
  "Series" varchar(255) NULL,
  "Footprint Path 2" varchar(255) NULL,
  "Library Path" varchar(255) NULL,
  "ComponentLink6Description" varchar(255) NULL,
  "Part Status" varchar(255) NULL,
  "Type" varchar(255) NULL,
  "ComponentLink5URL" varchar(255) NULL,
  "ComponentLink2Description" varchar(255) NULL,
  "Device Package" varchar(255) NULL,
  "Manufacturer" varchar(255) NULL,
  "Packaging" varchar(255) NULL,
  "ComponentLink5Description" varchar(255) NULL,
  "Built in Switch" varchar(255) NULL,
  "Minimum Order" varchar(255) NULL,
  "Footprint Ref 2" varchar(255) NULL,
  "Library Ref" varchar(255) NULL,
  "Actuator Diameter" varchar(255) NULL,
  "Actuator Type" varchar(255) NULL,
  "Adjustment Type" varchar(255) NULL,
  "Lifecycle Status" varchar(255) NULL,
  "LastUpdated" varchar(255) NULL,
  "ComponentLink4URL" varchar(255) NULL,
  "Termination Style" varchar(255) NULL,
  "ComponentLink4Description" varchar(255) NULL,
  "Value" varchar(255) NULL,
  "Taper" varchar(255) NULL,
  "Mounting Type" varchar(255) NULL,
  "Power (Watts)" varchar(255) NULL,
  "ComponentLink3Description" varchar(255) NULL,
  "Price" varchar(255) NULL,
  "Footprint Path" varchar(255) NULL,
  "Footprint Ref" varchar(255) NULL,
  "ComponentLink3URL" varchar(255) NULL,
  "Resistance" varchar(255) NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "c73ef434-2c78-4b46-93cd-e198d05c641a" ON "Resistors-RotaryPotentiometers"("Tolerance");

CREATE INDEX "347f04ef-3ede-40bc-a535-6d0269116505" ON "Resistors-RotaryPotentiometers"("Value");

CREATE INDEX "4fbdd45f-9398-4f5e-bde6-9927547c8ee0" ON "Resistors-RotaryPotentiometers"("Mounting Type");

CREATE INDEX "30bb29ce-1e86-4f12-9d40-e90bfa50d63c" ON "Resistors-RotaryPotentiometers"("Power (Watts)");

CREATE INDEX "1c14346a-3dd8-40b7-9765-0b84e2d786ec" ON "Resistors-RotaryPotentiometers"("Resistance");

