--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Capacitors-Aluminum-Polymer-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Surface Mount Land Size",
  "Voltage - Rated",
  "Ripple Current @ Low Frequency",
  "Ratings",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Ripple Current @ High Frequency",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP ALUM HYB 270UF 20% 25V SMD', 
  'A780KN277M1ELAS030', 
  'https://www.digikey.com/en/products/detail/kemet/A780KN277M1ELAS030/17737704', 
  '0.394" (10.00mm)', 
  '0.327" L x 0.327" W (8.30mm x 8.30mm)', 
  '25 V', 
  '620 mA @ 100 Hz', 
  'AEC-Q200', 
  'POLARISED CAPACITOR', 
  '399-A780KN277M1ELAS030CT-ND', 
  'Active', 
  'KEMET', 
  '2023-08-09T21:46:37.340', 
  '1', 
  '5712', 
  '=Value', 
  '-55°C ~ 125°C', 
  'Automotive', 
  'https://connect.kemet.com:7667/gateway/IntelliData-ComponentDocumentation/1.0/download/datasheet/A780KN277M1ELAS030', 
  'CAP ALSMD POLY 8.3MM H10.0MM', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '30mOhm', 
  'Surface Mount', 
  '0.315" Dia (8.00mm)', 
  '4000 Hrs @ 125°C', 
  'A780', 
  'Hybrid', 
  '0.25', 
  '1.55 A @ 100 kHz', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '270 µF', 
  '270 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP ALSMD POLY 8.3MM H10.0MM.PCBLIB'
);

INSERT INTO "Capacitors-Aluminum-Polymer-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Surface Mount Land Size",
  "Voltage - Rated",
  "Ripple Current @ Low Frequency",
  "Ratings",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Ripple Current @ High Frequency",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP ALUM HYB 150UF 20% 35V SMD', 
  'A780KN157M1VLAS030', 
  'https://www.digikey.com/en/products/detail/kemet/A780KN157M1VLAS030/17737715', 
  '0.394" (10.00mm)', 
  '0.327" L x 0.327" W (8.30mm x 8.30mm)', 
  '35 V', 
  '620 mA @ 100 Hz', 
  'AEC-Q200', 
  'POLARISED CAPACITOR', 
  '399-A780KN157M1VLAS030CT-ND', 
  'Active', 
  'KEMET', 
  '2023-08-09T21:46:37.357', 
  '1', 
  '5713', 
  '=Value', 
  '-55°C ~ 125°C', 
  'Automotive', 
  'https://connect.kemet.com:7667/gateway/IntelliData-ComponentDocumentation/1.0/download/datasheet/A780KN157M1VLAS030', 
  'CAP ALSMD POLY 8.3MM H10.0MM', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '30mOhm', 
  'Surface Mount', 
  '0.315" Dia (8.00mm)', 
  '4000 Hrs @ 125°C', 
  'A780', 
  'Hybrid', 
  '0.25', 
  '1.55 A @ 100 kHz', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '150 µF', 
  '150 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP ALSMD POLY 8.3MM H10.0MM.PCBLIB'
);

