--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Capacitors-Ceramic-0805" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Voltage - Rated",
  "Temperature Coefficient",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Thickness (Max)",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP CER', 
  'KGM21AS61C226MU', 
  'https://www.digikey.com/en/products/detail/kyocera-avx/KGM21AS61C226MU/17827473', 
  '0805 (2012 Metric)', 
  '16V', 
  'X6S', 
  '0805 (2012 Metric)', 
  'CAPACITOR', 
  '478-KGM21AS61C226MUCT-ND', 
  'Active', 
  'KYOCERA AVX', 
  '2023-06-03T19:15:31.113', 
  '1', 
  '52516', 
  '=Value', 
  '-55°C ~ 105°C', 
  'General Purpose', 
  'https://media.digikey.com/pdf/Data%20Sheets/AVX%20PDFs/CM03_CM05_CM105_CM21_CM316_Spec.pdf', 
  'CAP 0805_2012', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  'Surface Mount, MLCC', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  'CM', 
  '0.057" (1.45mm)', 
  '0.12', 
  'symbols/Passives/SCH - PASSIVES - CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '22 µF', 
  '22 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - MLCC/PCB - CAPACITOR - MLCC - CAP 0805_2012.PCBLIB'
);

