--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LINEAR 1.8V 150MA SOT23-5', 
  'TPS73118DBVT', 
  'https://www.digikey.com/en/products/detail/texas-instruments/TPS73118DBVT/604385', 
  'Fixed', 
  '5.5V', 
  '150mA', 
  '750 µA', 
  'Positive', 
  'SOT-23-5', 
  '1', 
  'SC-74A, SOT-753', 
  'TI TPS73118-EP_DBV_5', 
  '296-15802-1-ND', 
  'Active', 
  'Texas Instruments', 
  '1.8V', 
  '2023-09-11T23:55:50.943', 
  '1', 
  '0.1V @ 150mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Ftps731', 
  '550 µA', 
  'TI SOT-23-5 DBV', 
  '58dB ~ 37dB (100Hz ~ 10kHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  'Enable', 
  '-', 
  '0.62', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - TI TPS73118-EP_DBV_5.SchLib', 
  'Over Current, Over Temperature, Short Circuit, Reverse Polarity', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-5 DBV.PCBLIB'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LINEAR 1.8V 150MA SOT23-5', 
  'TPS73118DBVR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/TPS73118DBVR/1672846', 
  'Fixed', 
  '5.5V', 
  '150mA', 
  '750 µA', 
  'Positive', 
  'SOT-23-5', 
  '1', 
  'SC-74A, SOT-753', 
  'TI TPS73118-EP_DBV_5', 
  '296-27059-1-ND', 
  'Active', 
  'Texas Instruments', 
  '1.8V', 
  '2023-09-11T23:56:39.037', 
  '1', 
  '0.1V @ 150mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Ftps731', 
  '550 µA', 
  'TI SOT-23-5 DBV', 
  '58dB ~ 37dB (100Hz ~ 10kHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  'Enable', 
  '-', 
  '0.42', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - TI TPS73118-EP_DBV_5.SchLib', 
  'Over Current, Over Temperature, Short Circuit, Reverse Polarity', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-5 DBV.PCBLIB'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LINEAR 3.3V 100MA SOT23-5', 
  'TPS79133DBVR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/TPS79133DBVR/382225', 
  'Fixed', 
  '5.5V', 
  '100mA', 
  'Positive', 
  'SOT-23-5', 
  '1', 
  'SC-74A, SOT-753', 
  'TI TPS79133-EP_DBV_5', 
  '296-11866-1-ND', 
  'Active', 
  'Texas Instruments', 
  '3.3V', 
  '2023-09-12T20:15:40.383', 
  '1', 
  '0.9V @ 100mA', 
  '=Part Number', 
  '-40°C ~ 85°C', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Ftps791', 
  '250 µA', 
  'TI SOT-23-5 DBV', 
  '70dB ~ 37dB (100Hz ~ 100kHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  'Enable', 
  '-', 
  '0.64', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - TI TPS79133-EP_DBV_5.SchLib', 
  'Over Current, Over Temperature, Reverse Polarity, Under Voltage Lockout (UVLO)', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-5 DBV.PCBLIB'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LINEAR 3.3V 100MA SOT23-5', 
  'TPS79133DBVT', 
  'https://www.digikey.com/en/products/detail/texas-instruments/TPS79133DBVT/1908372', 
  'Fixed', 
  '5.5V', 
  '100mA', 
  'Positive', 
  'SOT-23-5', 
  '1', 
  'SC-74A, SOT-753', 
  'TI TPS79133-EP_DBV_5', 
  '296-27096-1-ND', 
  'Active', 
  'Texas Instruments', 
  '3.3V', 
  '2023-09-12T20:15:25.790', 
  '1', 
  '0.9V @ 100mA', 
  '=Part Number', 
  '-40°C ~ 85°C', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Ftps791', 
  '250 µA', 
  'TI SOT-23-5 DBV', 
  '70dB ~ 37dB (100Hz ~ 100kHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  'Enable', 
  '-', 
  '0.77', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - TI TPS79133-EP_DBV_5.SchLib', 
  'Over Current, Over Temperature, Reverse Polarity, Under Voltage Lockout (UVLO)', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-5 DBV.PCBLIB'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LIN NEG ADJ 200MA 8HVSSOP', 
  'TPS7A3001DGNR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/TPS7A3001DGNR/2361060', 
  'Adjustable', 
  '-35V', 
  '200mA', 
  '950 µA', 
  'Negative', 
  '8-HVSSOP', 
  '1', 
  '8-TSSOP, 8-MSOP (0.118", 3.00mm Width) Exposed Pad', 
  'TI TPS7A3001-EP_DGN_8', 
  '296-27750-1-ND', 
  'Active', 
  'Texas Instruments', 
  '-1.18V', 
  '2023-09-12T00:43:52.417', 
  '1', 
  '0.6V @ 200mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Ftps7a30', 
  '100 µA', 
  'TI MSOP-8 DGN', 
  '72dB (120Hz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '-33V', 
  'Enable, Soft Start', 
  '-', 
  '2.54', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - TI TPS7A3001-EP_DGN_8.SchLib', 
  'Over Current, Over Temperature', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - TI MSOP-8 DGN.PCBLIB'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LIN NEG ADJ 200MA 8HVSSOP', 
  'TPS7A3001DGNT', 
  'https://www.digikey.com/en/products/detail/texas-instruments/TPS7A3001DGNT/2360835', 
  'Adjustable', 
  '-35V', 
  '200mA', 
  '950 µA', 
  'Negative', 
  '8-HVSSOP', 
  '1', 
  '8-TSSOP, 8-MSOP (0.118", 3.00mm Width) Exposed Pad', 
  'TI TPS7A3001-EP_DGN_8', 
  '296-27744-1-ND', 
  'Active', 
  'Texas Instruments', 
  '-1.18V', 
  '2023-09-12T00:44:08.043', 
  '1', 
  '0.6V @ 200mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Ftps7a30', 
  '100 µA', 
  'TI MSOP-8 DGN', 
  '72dB (120Hz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '-33V', 
  'Enable, Soft Start', 
  '-', 
  '2.41', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - TI TPS7A3001-EP_DGN_8.SchLib', 
  'Over Current, Over Temperature', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - TI MSOP-8 DGN.PCBLIB'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LIN POS ADJ 100MA SOT23-6', 
  'TPS79101DBVT', 
  'https://www.digikey.com/en/products/detail/texas-instruments/TPS79101DBVT/1673704', 
  'Adjustable', 
  '5.5V', 
  '100mA', 
  'Positive', 
  'SOT-23-6', 
  '1', 
  'SOT-23-6', 
  'TI TPS79101-EP_DBV_6', 
  '296-27094-1-ND', 
  'Active', 
  'Texas Instruments', 
  '1.2V', 
  '2023-09-12T03:57:41.827', 
  '1', 
  '=Part Number', 
  '-40°C ~ 85°C', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Ftps791', 
  '250 µA', 
  'TI SOT-23-6 DBV', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '5.5V', 
  'Enable', 
  '-', 
  '0.87', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - TI TPS79101-EP_DBV_6.SchLib', 
  'Over Current, Over Temperature, Reverse Polarity, Under Voltage Lockout (UVLO)', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-6 DBV.PCBLIB'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LIN POS ADJ 100MA SOT23-6', 
  'TPS79101DBVR', 
  'http://digikey.com/product-detail/en/texas-instruments/TPS79101DBVR/296-11864-1-ND/381450', 
  'Adjustable', 
  '5.5V', 
  '100mA', 
  'Positive', 
  'SOT-23-6', 
  '1', 
  'SOT-23-6', 
  'TI TPS79101-EP_DBV_6', 
  '296-11864-1-ND', 
  'Active', 
  'Texas Instruments', 
  '1.2V', 
  '2023-09-12T03:58:07.240', 
  '1', 
  '=Part Number', 
  '-40°C ~ 85°C', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Ftps791', 
  '250µA', 
  'TI SOT-23-6 DBV', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '5.5V', 
  'Enable', 
  '-', 
  '0.53', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - TI TPS79101-EP_DBV_6.SchLib', 
  'Over Current, Over Temperature, Reverse Polarity, Under Voltage Lockout (UVLO)', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOT-23/PCB - LEADED - SOT-23 - TI SOT-23-6 DBV.PCBLIB'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '-20V, 500MA ULTRALOW NOISE/PSRR', 
  'LT3094HMSE#PBF', 
  'http://digikey.com/product-detail/en/linear-technology-analog-devices/LT3094HMSE-PBF/LT3094HMSE-PBF-ND/9990338', 
  'Adjustable', 
  '-2.3V', 
  '500mA', 
  '23mA', 
  'Negative', 
  '12-MSOP', 
  '1', 
  '12-TSSOP (0.118", 3.00mm Width) Exposed Pad', 
  'AD LT3094 MSE', 
  'LT3094HMSE#PBF-ND', 
  'Active', 
  'Linear Technology/Analog Devices', 
  '2023-09-12T20:37:44.953', 
  '1', 
  '0.41V @ 500mA', 
  '=Part Number', 
  '-40°C ~ 150°C (TJ)', 
  'https://www.analog.com/media/en/technical-documentation/data-sheets/LT3094.pdf', 
  '2.35mA', 
  'AD MSOP-12 4x3MM MSE', 
  '108dB ~ 28dB (120Hz ~ 10MHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '-19.5V', 
  'Enable, Power Good, Soft Start', 
  '-', 
  '8.97', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - AD LT3094 MSE.SchLib', 
  'Over Current, Over Temperature, Short Circuit, Under Voltage Lockout (UVLO)', 
  'Tube', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - MSOP/PCB - LEADED - MSOP - AD MSOP-12 4x3MM MSE.PcbLib'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '-20V, 500MA ULTRALOW NOISE/PSRR', 
  'LT3094HDD#PBF', 
  'http://digikey.com/product-detail/en/linear-technology-analog-devices/LT3094HDD-PBF/LT3094HDD-PBF-ND/9990348', 
  'Adjustable', 
  '-2.3V', 
  '500mA', 
  '23mA', 
  'Negative', 
  '12-DFN (3x3)', 
  '1', 
  '12-WFDFN Exposed Pad', 
  'AD LT3094 DD', 
  'LT3094HDD#PBF-ND', 
  'Active', 
  'Linear Technology/Analog Devices', 
  '2023-09-12T20:38:05.010', 
  '1', 
  '0.41V @ 500mA', 
  '=Part Number', 
  '-40°C ~ 150°C (TJ)', 
  'https://www.analog.com/media/en/technical-documentation/data-sheets/LT3094.pdf', 
  '2.35mA', 
  'AD DFN-12 3X3MM DD', 
  '108dB ~ 28dB (120Hz ~ 10MHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '-19.5V', 
  'Enable, Power Good, Soft Start', 
  '-', 
  '8.97', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - AD LT3094 DD.SchLib', 
  'Over Current, Over Temperature, Short Circuit, Under Voltage Lockout (UVLO)', 
  'Tube', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - DFN/PCB - LEADLESS - DFN - AD DFN-12 3X3MM DD.PcbLib'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LIN NEG ADJ 500MA 12DFN', 
  'LT3094IDD#PBF', 
  'http://digikey.com/product-detail/en/linear-technology-analog-devices/LT3094IDD-PBF/LT3094IDD-PBF-ND/9607278', 
  'Adjustable', 
  '-2.3V', 
  '500mA', 
  '23mA', 
  'Negative', 
  '12-DFN (3x3)', 
  '1', 
  '12-WFDFN Exposed Pad', 
  'AD LT3094 DD', 
  'LT3094IDD#PBF-ND', 
  'Active', 
  'Linear Technology/Analog Devices', 
  '2023-09-12T20:38:25.310', 
  '1', 
  '0.41V @ 500mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://www.analog.com/media/en/technical-documentation/data-sheets/LT3094.pdf', 
  '2.35mA', 
  'AD DFN-12 3X3MM DD', 
  '108dB ~ 28dB (120Hz ~ 10MHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '-19.5V', 
  'Enable, Power Good, Soft Start', 
  '-', 
  '8.11', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - AD LT3094 DD.SchLib', 
  'Over Current, Over Temperature, Short Circuit, Under Voltage Lockout (UVLO)', 
  'Tube', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - DFN/PCB - LEADLESS - DFN - AD DFN-12 3X3MM DD.PcbLib'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LIN NEG ADJ 500MA 12MSOP', 
  'LT3094IMSE#PBF', 
  'http://digikey.com/product-detail/en/linear-technology-analog-devices/LT3094IMSE-PBF/LT3094IMSE-PBF-ND/9607269', 
  'Adjustable', 
  '-2.3V', 
  '500mA', 
  '23mA', 
  'Negative', 
  '12-MSOP', 
  '1', 
  '12-TSSOP (0.118", 3.00mm Width) Exposed Pad', 
  'AD LT3094 MSE', 
  'LT3094IMSE#PBF-ND', 
  'Active', 
  'Linear Technology/Analog Devices', 
  '2023-09-12T20:38:41.577', 
  '1', 
  '0.41V @ 500mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://www.analog.com/media/en/technical-documentation/data-sheets/LT3094.pdf', 
  '2.35mA', 
  'AD MSOP-12 4x3MM MSE', 
  '108dB ~ 28dB (120Hz ~ 10MHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '-19.5V', 
  'Enable, Power Good, Soft Start', 
  '-', 
  '8.11', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - AD LT3094 MSE.SchLib', 
  'Over Current, Over Temperature, Short Circuit, Under Voltage Lockout (UVLO)', 
  'Tube', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - MSOP/PCB - LEADED - MSOP - AD MSOP-12 4x3MM MSE.PcbLib'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LIN NEG ADJ 500MA 12DFN', 
  'LT3094EDD#PBF', 
  'http://digikey.com/product-detail/en/linear-technology-analog-devices/LT3094EDD-PBF/LT3094EDD-PBF-ND/9607277', 
  'Adjustable', 
  '-2.3V', 
  '500mA', 
  '23mA', 
  'Negative', 
  '12-DFN (3x3)', 
  '1', 
  '12-WFDFN Exposed Pad', 
  'AD LT3094 DD', 
  'LT3094EDD#PBF-ND', 
  'Active', 
  'Linear Technology/Analog Devices', 
  '2023-09-12T20:39:00.937', 
  '1', 
  '0.41V @ 500mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://www.analog.com/media/en/technical-documentation/data-sheets/LT3094.pdf', 
  '2.35mA', 
  'AD DFN-12 3X3MM DD', 
  '108dB ~ 28dB (120Hz ~ 10MHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '-19.5V', 
  'Enable, Power Good, Soft Start', 
  '-', 
  '6.98', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - AD LT3094 DD.SchLib', 
  'Over Current, Over Temperature, Short Circuit, Under Voltage Lockout (UVLO)', 
  'Tube', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - DFN/PCB - LEADLESS - DFN - AD DFN-12 3X3MM DD.PcbLib'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Current - Supply (Max)",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Current - Quiescent (Iq)",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LIN NEG ADJ 500MA 12MSOP', 
  'LT3094EMSE#PBF', 
  'http://digikey.com/product-detail/en/linear-technology-analog-devices/LT3094EMSE-PBF/LT3094EMSE-PBF-ND/9607268', 
  'Adjustable', 
  '-2.3V', 
  '500mA', 
  '23mA', 
  'Negative', 
  '12-MSOP', 
  '1', 
  '12-TSSOP (0.118", 3.00mm Width) Exposed Pad', 
  'AD LT3094 MSE', 
  'LT3094EMSE#PBF-ND', 
  'Active', 
  'Linear Technology/Analog Devices', 
  '2023-09-12T20:39:14.333', 
  '1', 
  '0.41V @ 500mA', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://www.analog.com/media/en/technical-documentation/data-sheets/LT3094.pdf', 
  '2.35mA', 
  'AD MSOP-12 4x3MM MSE', 
  '108dB ~ 28dB (120Hz ~ 10MHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '-19.5V', 
  'Enable, Power Good, Soft Start', 
  '-', 
  '6.98', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - AD LT3094 MSE.SchLib', 
  'Over Current, Over Temperature, Short Circuit, Under Voltage Lockout (UVLO)', 
  'Tube', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - MSOP/PCB - LEADED - MSOP - AD MSOP-12 4x3MM MSE.PcbLib'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LIN POS ADJ 200MA 10DFN', 
  'LT3042EDD#TRPBF', 
  'http://digikey.com/product-detail/en/linear-technology-analog-devices/LT3042EDD-TRPBF/LT3042EDD-TRPBFCT-ND/8124036', 
  'Adjustable', 
  '20V', 
  '200mA', 
  'Positive', 
  '10-DFN (3x3)', 
  '1', 
  '10-WFDFN Exposed Pad', 
  'AD LT3042', 
  'LT3042EDD#TRPBFCT-ND', 
  'Active', 
  'Linear Technology/Analog Devices', 
  '2023-09-13T05:13:51.277', 
  '1', 
  '0.35V @ 200mA (Typ)', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.linear.com/docs/46159', 
  'ANALOG DEV DFN-10 3X3MM DD', 
  '117dB ~ 56dB (120Hz ~ 10MHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '15V', 
  'Current Limit, Enable, Power Good', 
  '-', 
  '2.85', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - AD LT3042.SchLib', 
  'Over Temperature, Reverse Polarity', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - DFN/PCB - LEADLESS - DFN - ANALOG DEV DFN-10 3X3MM DD.PCBLIB'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LIN POS ADJ 200MA 10DFN', 
  'LT3042MPDD#PBF', 
  'http://digikey.com/product-detail/en/linear-technology-analog-devices/LT3042MPDD-PBF/LT3042MPDD-PBF-ND/5233153', 
  'Adjustable', 
  '20V', 
  '200mA', 
  'Positive', 
  '10-DFN (3x3)', 
  '1', 
  '10-WFDFN Exposed Pad', 
  'AD LT3042', 
  'LT3042MPDD#PBF-ND', 
  'Active', 
  'Linear Technology/Analog Devices', 
  '2023-09-13T05:14:15.090', 
  '1', 
  '0.35V @ 200mA (Typ)', 
  '=Part Number', 
  '-55°C ~ 150°C', 
  'http://www.linear.com/docs/46159', 
  'ANALOG DFN-10 3x3MM DD', 
  '117dB ~ 56dB (120Hz ~ 10MHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '15V', 
  'Current Limit, Enable, Power Good', 
  '-', 
  '14.05', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - AD LT3042.SchLib', 
  'Over Temperature, Reverse Polarity', 
  'Tube', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - DFN/ANALOG DFN-10 3x3MM DD.PCBLIB'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LIN POS ADJ 200MA 10DFN', 
  'LT3042HDD#TRPBF', 
  'http://digikey.com/product-detail/en/linear-technology-analog-devices/LT3042HDD-TRPBF/LT3042HDD-TRPBFCT-ND/8635799', 
  'Adjustable', 
  '20V', 
  '200mA', 
  'Positive', 
  '10-DFN (3x3)', 
  '1', 
  '10-WFDFN Exposed Pad', 
  'AD LT3042', 
  'LT3042HDD#TRPBFCT-ND', 
  'Active', 
  'Linear Technology/Analog Devices', 
  '2023-09-13T05:14:26.287', 
  '1', 
  '0.35V @ 200mA (Typ)', 
  '=Part Number', 
  '-40°C ~ 150°C', 
  'http://www.linear.com/docs/46159', 
  'ANALOG DFN-10 3x3MM DD', 
  '117dB ~ 56dB (120Hz ~ 10MHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '15V', 
  'Current Limit, Enable, Power Good', 
  '-', 
  '3.54', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - AD LT3042.SchLib', 
  'Over Temperature, Reverse Polarity', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - DFN/ANALOG DFN-10 3x3MM DD.PCBLIB'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LIN POS ADJ 200MA 10DFN', 
  'LT3042IDD#TRPBF', 
  'http://digikey.com/product-detail/en/linear-technology-analog-devices/LT3042IDD-TRPBF/LT3042IDD-TRPBFCT-ND/8024408', 
  'Adjustable', 
  '20V', 
  '200mA', 
  'Positive', 
  '10-DFN (3x3)', 
  '1', 
  '10-WFDFN Exposed Pad', 
  'AD LT3042', 
  'LT3042IDD#TRPBFCT-ND', 
  'Active', 
  'Linear Technology/Analog Devices', 
  '2023-09-13T05:14:37.163', 
  '1', 
  '0.35V @ 200mA (Typ)', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.linear.com/docs/46159', 
  'ANALOG DFN-10 3x3MM DD', 
  '117dB ~ 56dB (120Hz ~ 10MHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '15V', 
  'Current Limit, Enable, Power Good', 
  '-', 
  '3.25', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - AD LT3042.SchLib', 
  'Over Temperature, Reverse Polarity', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - DFN/ANALOG DFN-10 3x3MM DD.PCBLIB'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LIN POS ADJ 200MA 10DFN', 
  'LT3042EDD#PBF', 
  'http://digikey.com/product-detail/en/linear-technology-analog-devices/LT3042EDD-PBF/LT3042EDD-PBF-ND/5230600', 
  'Adjustable', 
  '20V', 
  '200mA', 
  'Positive', 
  '10-DFN (3x3)', 
  '1', 
  '10-WFDFN Exposed Pad', 
  'AD LT3042', 
  'LT3042EDD#PBF-ND', 
  'Active', 
  'Linear Technology/Analog Devices', 
  '2023-09-13T05:14:51.747', 
  '1', 
  '0.35V @ 200mA (Typ)', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.linear.com/docs/46159', 
  'ANALOG DFN-10 3x3MM DD', 
  '117dB ~ 56dB (120Hz ~ 10MHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '15V', 
  'Current Limit, Enable, Power Good', 
  '-', 
  '5.46', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - AD LT3042.SchLib', 
  'Over Temperature, Reverse Polarity', 
  'Tube', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - DFN/ANALOG DFN-10 3x3MM DD.PCBLIB'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LIN POS ADJ 200MA 10DFN', 
  'LT3042IDD#PBF', 
  'http://digikey.com/product-detail/en/linear-technology-analog-devices/LT3042IDD-PBF/LT3042IDD-PBF-ND/5231264', 
  'Adjustable', 
  '20V', 
  '200mA', 
  'Positive', 
  '10-DFN (3x3)', 
  '1', 
  '10-WFDFN Exposed Pad', 
  'AD LT3042', 
  'LT3042IDD#PBF-ND', 
  'Active', 
  'Linear Technology/Analog Devices', 
  '2023-09-13T05:15:04.703', 
  '1', 
  '0.35V @ 200mA (Typ)', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.linear.com/docs/46159', 
  'ANALOG DFN-10 3x3MM DD', 
  '117dB ~ 56dB (120Hz ~ 10MHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '15V', 
  'Current Limit, Enable, Power Good', 
  '-', 
  '6.24', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - AD LT3042.SchLib', 
  'Over Temperature, Reverse Polarity', 
  'Tube', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - DFN/ANALOG DFN-10 3x3MM DD.PCBLIB'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LIN POS ADJ 200MA 10DFN', 
  'LT3042HDD#PBF', 
  'http://digikey.com/product-detail/en/linear-technology-analog-devices/LT3042HDD-PBF/LT3042HDD-PBF-ND/5231263', 
  'Adjustable', 
  '20V', 
  '200mA', 
  'Positive', 
  '10-DFN (3x3)', 
  '1', 
  '10-WFDFN Exposed Pad', 
  'AD LT3042', 
  'LT3042HDD#PBF-ND', 
  'Active', 
  'Linear Technology/Analog Devices', 
  '2023-09-13T05:15:16.843', 
  '1', 
  '0.35V @ 200mA (Typ)', 
  '=Part Number', 
  '-40°C ~ 150°C', 
  'http://www.linear.com/docs/46159', 
  'ANALOG DFN-10 3x3MM DD', 
  '117dB ~ 56dB (120Hz ~ 10MHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '15V', 
  'Current Limit, Enable, Power Good', 
  '-', 
  '6.78', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - AD LT3042.SchLib', 
  'Over Temperature, Reverse Polarity', 
  'Tube', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - DFN/ANALOG DFN-10 3x3MM DD.PCBLIB'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LIN POS ADJ 200MA 10MSOP', 
  'LT3042EMSE#TRPBF', 
  'http://digikey.com/product-detail/en/linear-technology-analog-devices/LT3042EMSE-TRPBF/LT3042EMSE-TRPBFCT-ND/7804171', 
  'Adjustable', 
  '20V', 
  '200mA', 
  'Positive', 
  '10-MSOP-EP', 
  '1', 
  '10-TFSOP, 10-MSOP (0.118", 3.00mm Width) Exposed Pad', 
  'AD LT3042', 
  'LT3042EMSE#TRPBFCT-ND', 
  'Active', 
  'Linear Technology/Analog Devices', 
  '2023-09-13T05:15:51.093', 
  '1', 
  '0.35V @ 200mA (Typ)', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.linear.com/docs/46159', 
  'ANALOG MSOP-10', 
  '117dB ~ 56dB (120Hz ~ 10MHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '15V', 
  'Current Limit, Enable, Power Good', 
  '-', 
  '2.85', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - AD LT3042.SchLib', 
  'Over Temperature, Reverse Polarity', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - ANALOG MSOP-10.PcbLib'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LIN POS ADJ 200MA 10MSOP', 
  'LT3042EMSE#PBF', 
  'http://digikey.com/product-detail/en/linear-technology-analog-devices/LT3042EMSE-PBF/LT3042EMSE-PBF-ND/5231262', 
  'Adjustable', 
  '20V', 
  '200mA', 
  'Positive', 
  '10-MSOP-EP', 
  '1', 
  '10-TFSOP, 10-MSOP (0.118", 3.00mm Width) Exposed Pad', 
  'AD LT3042', 
  'LT3042EMSE#PBF-ND', 
  'Active', 
  'Linear Technology/Analog Devices', 
  '2023-09-13T05:16:04.707', 
  '1', 
  '0.35V @ 200mA (Typ)', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.linear.com/docs/46159', 
  'ANALOG MSOP-10', 
  '117dB ~ 56dB (120Hz ~ 10MHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '15V', 
  'Current Limit, Enable, Power Good', 
  '-', 
  '5.46', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - AD LT3042.SchLib', 
  'Over Temperature, Reverse Polarity', 
  'Tube', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - ANALOG MSOP-10.PcbLib'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LIN POS ADJ 200MA 10MSOP', 
  'LT3042IMSE#PBF', 
  'http://digikey.com/product-detail/en/linear-technology-analog-devices/LT3042IMSE-PBF/LT3042IMSE-PBF-ND/5231265', 
  'Adjustable', 
  '20V', 
  '200mA', 
  'Positive', 
  '10-MSOP-EP', 
  '1', 
  '10-TFSOP, 10-MSOP (0.118", 3.00mm Width) Exposed Pad', 
  'AD LT3042', 
  'LT3042IMSE#PBF-ND', 
  'Active', 
  'Linear Technology/Analog Devices', 
  '2023-09-13T05:16:15.653', 
  '1', 
  '0.35V @ 200mA (Typ)', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.linear.com/docs/46159', 
  'ANALOG MSOP-10', 
  '117dB ~ 56dB (120Hz ~ 10MHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '15V', 
  'Current Limit, Enable, Power Good', 
  '-', 
  '6.07', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - AD LT3042.SchLib', 
  'Over Temperature, Reverse Polarity', 
  'Tube', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - ANALOG MSOP-10.PcbLib'
);

INSERT INTO "VoltageRegulators-Linear" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Number Of Regulators",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Voltage Dropout (Max)",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "PSRR",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Control Features",
  "Series",
  "Price",
  "Library Path",
  "Protection Features",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC REG LIN POS ADJ 200MA 10MSOP', 
  'LT3042IMSE#TRPBF', 
  'https://www.digikey.com/en/products/detail/analog-devices-inc/LT3042IMSE-TRPBF/5233186', 
  'Adjustable', 
  '20V', 
  '200mA', 
  'Positive', 
  '10-MSOP-EP', 
  '1', 
  'AD LT3042', 
  'LT3042IMSE#TRPBFCT-ND', 
  'Active', 
  'Analog Devices Inc.', 
  '0V', 
  '2023-09-13T05:16:26.930', 
  '1', 
  '0.35V @ 200mA (Typ)', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'https://www.analog.com/media/en/technical-documentation/data-sheets/3042fb.pdf', 
  'ANALOG MSOP-10', 
  '117dB ~ 56dB (120Hz ~ 10MHz)', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '15V', 
  'Current Limit, Enable, Power Good', 
  '-', 
  '3.97', 
  'symbols/Power - Linear VReg/SCH - POWER - LINEAR VREG - AD LT3042.SchLib', 
  'Over Temperature, Reverse Polarity', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - ANALOG MSOP-10.PcbLib'
);

