--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Capacitors-Tantalum-Polymer" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Manufacturer Size Code",
  "Height - Seated (Max)",
  "Device Package",
  "Voltage - Rated",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP TANT POLY 4.7UF 63V 2917', 
  'T55D475M063C0100', 
  'https://www.digikey.com/en/products/detail/vishay-polytech/T55D475M063C0100/16571768', 
  'D', 
  '0.122" (3.10mm)', 
  '2917 (7343 Metric)', 
  '63 V', 
  '2917 (7343 Metric)', 
  'POLARISED CAPACITOR', 
  '3581-T55D475M063C0100CT-ND', 
  'Active', 
  'Vishay Polytech', 
  'General Purpose', 
  '2023-04-19T19:54:22.707', 
  '1', 
  '6570', 
  '=Value', 
  '-55°C ~ 125°C', 
  'https://www.vishay.com/docs/40174/t55.pdf', 
  'CAP POL 2917_7343', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '100mOhm @ 100kHz', 
  'Surface Mount', 
  '0.287" L x 0.169" W (7.30mm x 4.30mm)', 
  'vPolyTan™ T55', 
  'Molded', 
  '0.65', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '4.7 µF', 
  '4.7 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Tantalum/PCB - CAPACITOR - TANTALUM - CAP POL 2917_7343.PCBLIB'
);

