--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Capacitors-Aluminum-Electrolytic-SMT" (
  "Polarization",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Surface Mount Land Size",
  "Voltage - Rated",
  "Ripple Current @ Low Frequency",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Price",
  "Ripple Current @ High Frequency",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "Impedance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'Polar', 
  'CAP ALUM 10UF 20% 50V SMD', 
  'EEE-HD1H100P', 
  'https://www.digikey.com/en/products/detail/panasonic-electronic-components/EEE-HD1H100P/1985154', 
  '0.240" (6.10mm)', 
  'Radial, Can - SMD', 
  '0.260" L x 0.260" W (6.60mm x 6.60mm)', 
  '50 V', 
  '33 mA @ 120 Hz', 
  'AEC-Q200', 
  'Radial, Can - SMD', 
  'POLARISED CAPACITOR', 
  'PCE4976CT-ND', 
  'Active', 
  'Panasonic Electronic Components', 
  '2023-03-31T20:09:46.667', 
  '1', 
  '28125', 
  '=Value', 
  '-40°C ~ 105°C', 
  'Automotive, High Temperature Reflow', 
  'http://industrial.panasonic.com/www-cgi/jvcr13pz.cgi?E+PZ+4+ABA0100+EEEHD1H100P+8+WW', 
  'CAP ALSMD 6.6MM H6.1MM', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  'Surface Mount', 
  '0.248" Dia (6.30mm)', 
  '5000 Hrs @ 105°C', 
  'HD', 
  '0.12', 
  '56.1 mA @ 10 kHz', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '10 µF', 
  '10 µF', 
  '4 Ohms', 
  'DigiKey Link', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP ALSMD 6.6MM H6.1MM.PCBLIB'
);

INSERT INTO "Capacitors-Aluminum-Electrolytic-SMT" (
  "Polarization",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Surface Mount Land Size",
  "Voltage - Rated",
  "Ripple Current @ Low Frequency",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Price",
  "Ripple Current @ High Frequency",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "Impedance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'Polar', 
  'CAP ALUM 56UF 20% 35V SMD', 
  'UWD1V560MCL1GS', 
  'https://www.digikey.com/en/products/detail/nichicon/UWD1V560MCL1GS/2550638', 
  '0.303" (7.70mm)', 
  'Radial, Can - SMD', 
  '0.260" L x 0.260" W (6.60mm x 6.60mm)', 
  '35 V', 
  '140 mA @ 120 Hz', 
  'Radial, Can - SMD', 
  'POLARISED CAPACITOR', 
  '493-9694-1-ND', 
  'Active', 
  'Nichicon', 
  '2023-03-31T20:09:54.773', 
  '1', 
  '28126', 
  '=Value', 
  '-55°C ~ 105°C', 
  'General Purpose', 
  'http://nichicon-us.com/english/products/pdfs/e-uwd.pdf', 
  'CAP ALSMD 6.6MM H7.7MM', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  'Surface Mount', 
  '0.248" Dia (6.30mm)', 
  '2000 Hrs @ 105°C', 
  'UWD', 
  '0.14', 
  '280 mA @ 100 kHz', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '56 µF', 
  '56 µF', 
  '340 mOhms', 
  'DigiKey Link', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP ALSMD 6.6MM H7.7MM.PCBLIB'
);

INSERT INTO "Capacitors-Aluminum-Electrolytic-SMT" (
  "Polarization",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Surface Mount Land Size",
  "Voltage - Rated",
  "Ripple Current @ Low Frequency",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Price",
  "Ripple Current @ High Frequency",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'Polar', 
  'CAP ALUM 330UF 20% 6.3V SMD', 
  'EEE-FT0J331AP', 
  'https://www.digikey.com/en/products/detail/panasonic-electronic-components/EEE-FT0J331AP/2796888', 
  '0.240" (6.10mm)', 
  'Radial, Can - SMD', 
  '0.260" L x 0.260" W (6.60mm x 6.60mm)', 
  '6.3 V', 
  '195 mA @ 120 Hz', 
  'AEC-Q200', 
  'Radial, Can - SMD', 
  'POLARISED CAPACITOR', 
  'P15080CT-ND', 
  'Active', 
  'Panasonic Electronic Components', 
  '2023-03-31T20:09:47.177', 
  '1', 
  '28127', 
  '=Value', 
  '-55°C ~ 105°C', 
  'Automotive', 
  'https://na.industrial.panasonic.com/file-download/3112', 
  'CAP ALSMD 6.6MM H6.1MM', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '260mOhm @ 100kHz', 
  'Surface Mount', 
  '0.248" Dia (6.30mm)', 
  '2000 Hrs @ 105°C', 
  'FT', 
  '0.19', 
  '300 mA @ 100 kHz', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '330 µF', 
  '330 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP ALSMD 6.6MM H6.1MM.PCBLIB'
);

INSERT INTO "Capacitors-Aluminum-Electrolytic-SMT" (
  "Polarization",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Surface Mount Land Size",
  "Voltage - Rated",
  "Ripple Current @ Low Frequency",
  "Ratings",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Price",
  "Ripple Current @ High Frequency",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "Impedance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'Polar', 
  'CAP ALUM 47UF 20% 63V SMD', 
  'EEE-FK1J470L', 
  'https://www.digikey.com/en/products/detail/panasonic-electronic-components/EEE-FK1J470L/12459440', 
  '0.413" (10.50mm)', 
  '0.327" L x 0.327" W (8.30mm x 8.30mm)', 
  '63 V', 
  '187.5 mA @ 120 Hz', 
  'AEC-Q200', 
  'POLARISED CAPACITOR', 
  '10-EEE-FK1J470LCT-ND', 
  'Active', 
  'Panasonic Electronic Components', 
  '2023-03-31T20:09:27.800', 
  '1', 
  '28128', 
  '=Value', 
  '-55°C ~ 105°C', 
  'Automotive', 
  'https://na.industrial.panasonic.com/file-download/19641', 
  'CAP ALSMD 8.3MM H10.5MM', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  'Surface Mount', 
  '0.315" Dia (8.00mm)', 
  '2000 Hrs @ 105°C', 
  'FK, Halogen Free', 
  '0.30', 
  '250 mA @ 100 kHz', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '47 µF', 
  '47 µF', 
  '650 mOhms', 
  'DigiKey Link', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP ALSMD 8.3MM H10.5MM.PCBLIB'
);

INSERT INTO "Capacitors-Aluminum-Electrolytic-SMT" (
  "Polarization",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Surface Mount Land Size",
  "Voltage - Rated",
  "Ripple Current @ Low Frequency",
  "Ratings",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Price",
  "Ripple Current @ High Frequency",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'Polar', 
  'CAP ALUM 33UF 20% 35V SMD', 
  'EEE-FP1V330AL', 
  'https://www.digikey.com/en/products/detail/panasonic-electronic-components/EEE-FP1V330AL/12459444', 
  '0.240" (6.10mm)', 
  '0.260" L x 0.260" W (6.60mm x 6.60mm)', 
  '35 V', 
  '195 mA @ 120 Hz', 
  'AEC-Q200', 
  'POLARISED CAPACITOR', 
  '10-EEE-FP1V330ALCT-ND', 
  'Active', 
  'Panasonic Electronic Components', 
  '2023-03-31T20:09:45.633', 
  '1', 
  '28129', 
  '=Value', 
  '-55°C ~ 105°C', 
  'Automotive', 
  'https://na.industrial.panasonic.com/file-download/19633', 
  'CAP ALSMD 6.6MM H6.1MM', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '260mOhm @ 100kHz', 
  'Surface Mount', 
  '0.248" Dia (6.30mm)', 
  '2000 Hrs @ 105°C', 
  'FP, Halogen Free', 
  '0.16', 
  '300 mA @ 100 kHz', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '33 µF', 
  '33 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP ALSMD 6.6MM H6.1MM.PCBLIB'
);

