--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Diodes-TVS" (
  "Current - Peak Pulse (10/1000µs)",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Voltage - Breakdown (Min)",
  "Power - Peak Pulse",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Voltage - Clamping (Max) @ Ipp",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Voltage - Reverse Standoff (Typ)",
  "Unidirectional Channels",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Power Line Protection",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '660mA', 
  'TVS DIODE 376VWM 602VC SMA', 
  'PSMAJ440A-13', 
  'https://www.digikey.com/en/products/detail/diodes-incorporated/PSMAJ440A-13/7725161', 
  '418V', 
  '400W', 
  'SMA', 
  'DO-214AC, SMA', 
  'DIODE TVS UNI', 
  '602V', 
  'PSMAJ440A-13DICT-ND', 
  'Active', 
  '376V', 
  '1', 
  'Diodes Incorporated', 
  '2023-03-26T19:57:09.720', 
  '1', 
  '11676', 
  'No', 
  '=Part Number', 
  '-55°C ~ 150°C (TJ)', 
  'General Purpose', 
  'https://www.diodes.com/assets/Datasheets/PSMAJ440A.pdf', 
  'DO214AC SMA', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '-', 
  'Zener', 
  '0.16', 
  'symbols/Diodes/SCH - DIODES - DIODE TVS UNI.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - DO214AC SMA.PCBLIB'
);

