--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."VoltageRegulators-DC-DC-SwitchingRegulators" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Voltage - Input (Max)",
  "Current - Output",
  "Output Configuration",
  "Supplier Device Package",
  "Voltage - Input (Min)",
  "Function",
  "Library Ref",
  "Frequency - Switching",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Output (Min/Fixed)",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "Number Of Outputs",
  "Operating Temperature",
  "Synchronous Rectifier",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Topology",
  "Mounting Type",
  "Voltage - Output (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '36V, 8A/10A  BUCK CONV QFN', 
  'MAX42410AFOB+', 
  'https://www.digikey.com/en/products/detail/analog-devices-inc-maxim-integrated/MAX42410AFOB/22168204', 
  'Adjustable', 
  '36V', 
  '10A', 
  'Positive', 
  '17-FC2QFN (3.5x3.75)', 
  '4.5V', 
  'Step-Down', 
  'AD MAX42410', 
  '1.5MHz', 
  '505-MAX42410AFOB+-ND', 
  'Active', 
  'Analog Devices Inc./Maxim Integrated', 
  '0.8V', 
  '2024-08-24T06:09:59.853', 
  '1', 
  '=Part Number', 
  '1', 
  '-40°C ~ 150°C (TJ)', 
  'Yes', 
  'https://www.analog.com/media/en/technical-documentation/data-sheets/max42408-max42410.pdf', 
  'AD FC2QFN-17 F173A3F+1F', 
  'Datasheet', 
  'DigiKey', 
  'Buck', 
  'Surface Mount, Wettable Flank', 
  '6V', 
  '-', 
  '2.78', 
  'symbols/Power - Switchmode/SCH - POWER - SWITCHMODE - AD MAX42410.SCHLIB', 
  'Tray', 
  'DigiKey Link', 
  'footprints/Leadless - QFN/PCB - LEADLESS - QFN - AD FC2QFN-17 F173A3F+1F.PCBLIB'
);

