--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

CREATE TABLE IF NOT EXISTS "Filters - Ferrite Beads and Chips" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  PRIMARY KEY ("id")
);

