--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

CREATE TABLE IF NOT EXISTS "Oscillators - Programmable Oscillators" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  PRIMARY KEY ("id")
);

