--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Capacitors-Aluminum-Polymer-SMT" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Surface Mount Land Size",
  "Voltage - Rated",
  "Ripple Current @ Low Frequency",
  "Ratings",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Ripple Current @ High Frequency",
  "Library Path",
  "Packaging",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP ALUM HYB 220UF 20% 35V SMD', 
  'EEH-ZT1V221UP', 
  'https://www.digikey.com/en/products/detail/panasonic-electronic-components/EEH-ZT1V221UP/19188161', 
  '0.413" (10.50mm)', 
  '0.327" L x 0.327" W (8.30mm x 8.30mm)', 
  '35 V', 
  '270 mA @ 100 Hz', 
  'AEC-Q200', 
  'POLARISED CAPACITOR', 
  '10-EEH-ZT1V221UPCT-ND', 
  'Active', 
  'Panasonic Electronic Components', 
  '2023-08-20T20:40:24.383', 
  '1', 
  '5721', 
  '=Value', 
  '-55°C ~ 135°C', 
  'Automotive', 
  'https://media.digikey.com/pdf/Data%20Sheets/Panasonic%20Corporation/ZTU_Series.pdf', 
  'CAP ALSMD POLY 8.3MM H10.5MM', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '22mOhm', 
  'Surface Mount', 
  '0.315" Dia (8.00mm)', 
  '4000 Hrs @ 135°C', 
  'ZTU', 
  'Hybrid', 
  '0.89', 
  '1.8 A @ 100 kHz', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'TapeAndReel', 
  '220 µF', 
  '220 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP ALSMD POLY 8.3MM H10.5MM.PCBLIB'
);

