--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."RF-Amplifiers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Voltage - Supply",
  "Test Frequency",
  "Manufacturer",
  "Noise Figure",
  "LastUpdated",
  "Minimum Order",
  "Rf Type",
  "Comment",
  "Footprint Ref",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Frequency",
  "P1db",
  "ComponentLink2Description",
  "Footprint Path",
  "Gain"
)
VALUES (
  '0.5-6.0 GHZ ULTRA LNA', 
  'QPL9058TR7', 
  'https://www.digikey.com/en/products/detail/qorvo/QPL9058TR7/24367382', 
  '8-DFN (2x2)', 
  'QORVO QPL9058', 
  '2312-QPL9058TR7CT-ND', 
  'Active', 
  '3.15V ~ 5.25V', 
  '500MHz ~ 6GHz', 
  'Qorvo', 
  '0.59dB', 
  '2024-08-09T09:17:03.643', 
  '1', 
  '5G, CDMA, FDD, GSM, LTE, TDD, W-CDMA', 
  '=Part Number', 
  'QORVO SON-8 QPL9058', 
  'DigiKey', 
  '54mA', 
  'Surface Mount', 
  '-', 
  '2.10', 
  'symbols/RF - Amplifier/SCH - RF - AMPLIFIER - QORVO QPL9058.SCHLIB', 
  'TapeAndReel', 
  '500MHz ~ 6GHz', 
  '20.6dBm', 
  'DigiKey Link', 
  'footprints/Leadless - SON/PCB - LEADLESS - SON - QORVO SON-8 QPL9058.PCBLIB', 
  '19.9dB'
);

INSERT INTO "altium"."RF-Amplifiers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Voltage - Supply",
  "Test Frequency",
  "Manufacturer",
  "Noise Figure",
  "LastUpdated",
  "Minimum Order",
  "Rf Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Frequency",
  "P1db",
  "ComponentLink2Description",
  "Footprint Path",
  "Gain"
)
VALUES (
  'IC AMP EDGE 400MHZ-8GHZ 12MCLP', 
  'PMA3-83MP+', 
  'https://www.digikey.com/en/products/detail/mini-circuits/PMA3-83MP/16515860', 
  '12-MCLP (3x3)', 
  'MINI-CIRCUITS PMA3-83MP+', 
  '3157-PMA3-83MP+CT-ND', 
  'Active', 
  '7.6V ~ 8.4V', 
  '2GHz', 
  'Mini-Circuits', 
  '3.3dB', 
  '2024-08-09T09:18:24.740', 
  '1', 
  'EDGE, LTE, Radar, SATCOM, W-CDMA, WiFi, WLAN', 
  '=Part Number', 
  'https://www.minicircuits.com/pdfs/PMA3-83MP+.pdf', 
  'MINI-CIRCUITS QFN-12 DQ1225', 
  'Datasheet', 
  'DigiKey', 
  '144mA', 
  'Surface Mount', 
  '-', 
  '8.39', 
  'symbols/RF - Amplifier/SCH - RF - AMPLIFIER - MINI-CIRCUITS PMA3-83MP+.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '400MHz ~ 8GHz', 
  '27.8dBm', 
  'DigiKey Link', 
  'footprints/Leadless - QFN/PCB - LEADLESS - QFN - MINI-CIRCUITS QFN-12 DQ1225.PcbLib', 
  '17.3dB'
);

INSERT INTO "altium"."RF-Amplifiers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Voltage - Supply",
  "Test Frequency",
  "Manufacturer",
  "Noise Figure",
  "LastUpdated",
  "Minimum Order",
  "Rf Type",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Frequency",
  "P1db",
  "ComponentLink2Description",
  "Footprint Path",
  "Gain"
)
VALUES (
  'IC RF AMP LTE 400MHZ-6GHZ 8DFN', 
  'SKY67183-396LF', 
  'https://www.digikey.com/en/products/detail/skyworks-solutions-inc/SKY67183-396LF/12179912', 
  '8-DFN (2x2)', 
  'SKYWORKS SKY67183-396LF', 
  '863-SKY67183-396LFCT-ND', 
  'Active', 
  '3.3V ~ 5.25V', 
  '4.9GHz', 
  'Skyworks Solutions Inc.', 
  '0.6dB', 
  '2024-08-09T09:19:48.890', 
  '1', 
  'LTE', 
  '=Part Number', 
  'https://www.skyworksinc.com/-/media/409D78A8622A4A0FAADB0D8E555209B6.pdf', 
  'SKYWORKS DFN-8 SKY67183-396LF', 
  'Datasheet', 
  'DigiKey', 
  '56mA', 
  'Surface Mount', 
  '-', 
  '1.13', 
  'symbols/RF - Amplifier/SCH - RF - AMPLIFIER - SKYWORKS SKY67183-396LF.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '400MHz ~ 6GHz', 
  '20dBm', 
  'DigiKey Link', 
  'footprints/Leadless - DFN/PCB - LEADLESS - DFN - SKYWORKS DFN-8 SKY67183-396LF.PCBLIB', 
  '17.7dB'
);

