--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."BatteryChargers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Charge Current - Max",
  "Current - Charging",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Voltage - Supply (Max)",
  "Lifecycle Status",
  "Battery Chemistry",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Programmable Features",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Battery Pack Voltage",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Number Of Cells",
  "Series",
  "Fault Protection",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'AUTOMOTIVE, 800-MA LINEAR BATTER', 
  'BQ25171QWDRCRQ1', 
  'https://www.digikey.com/en/products/detail/texas-instruments/BQ25171QWDRCRQ1/14004298', 
  '800mA', 
  'Constant - Programmable', 
  '10-VSON (3x3)', 
  'TI BQ25171-Q1', 
  '296-BQ25171QWDRCRQ1CT-ND', 
  '18V', 
  'Active', 
  'Lithium Ion/Polymer', 
  'Texas Instruments', 
  '2025-07-04T01:49:25.053', 
  '1', 
  'Current, Timer', 
  '54', 
  '=Part Number', 
  '-40°C ~ 125°C (TJ)', 
  '10.5V (Max)', 
  'https://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Fbq25171-q1', 
  'TI PVSON-10 3X3MM DRC', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount, Wettable Flank', 
  '1 ~ 6', 
  '-', 
  'Over Current, Over Temperature, Over Voltage, Short Circuit', 
  '0.81', 
  'symbols/Charger/SCH - CHARGER - TI BQ25171-Q1.SchLib', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - SON/PCB - LEADLESS - SON - TI PVSON-10 3X3MM DRC.PCBLIB'
);

