--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 3.6V 310MW SOD323F', 
  'PZU3.6B2,115', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/PZU3-6B2-115/1162990', 
  'SOD-323F', 
  'SC-90, SOD-323F', 
  'DIODE ZENER', 
  '1727-PZU3.6B2,115CT-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-05-18T20:21:09.050', 
  '1', 
  '4292', 
  '=Part Number', 
  '-65°C ~ 150°C', 
  'https://assets.nexperia.com/documents/data-sheet/PZUXB_SER.pdf', 
  'SOD323F', 
  'Datasheet', 
  '±2%', 
  'DigiKey', 
  'Surface Mount', 
  '5 µA @ 1 V', 
  'Automotive, AEC-Q100', 
  '0.04', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '310 mW', 
  '1.1 V @ 100 mA', 
  'TapeAndReel', 
  'Active', 
  '3.6 V', 
  '90 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD323F.PCBLIB'
);

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 11V 310MW SOD323F', 
  'PZU11B,115', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/PZU11B-115/1162939', 
  'SOD-323F', 
  'SC-90, SOD-323F', 
  'DIODE ZENER', 
  '1727-3681-1-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-05-18T20:21:09.150', 
  '1', 
  '4293', 
  '=Part Number', 
  '-65°C ~ 150°C', 
  'https://assets.nexperia.com/documents/data-sheet/PZUXB_SER.pdf', 
  'SOD323F', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  'Surface Mount', 
  '100 nA @ 8 V', 
  'Automotive, AEC-Q100', 
  '0.04', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '310 mW', 
  '1.1 V @ 100 mA', 
  'TapeAndReel', 
  'Active', 
  '11 V', 
  '10 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD323F.PCBLIB'
);

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 6.8V 300MW SOD523', 
  'BZX585-C6V8,135', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/BZX585-C6V8-135/1155867', 
  'SOD-523', 
  'SC-79, SOD-523', 
  'DIODE ZENER', 
  '1727-BZX585-C6V8,135CT-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-05-18T20:21:19.143', 
  '1', 
  '4294', 
  '=Part Number', 
  '-65°C ~ 150°C', 
  'https://assets.nexperia.com/documents/data-sheet/BZX585_SERIES.pdf', 
  'SOD523F', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  'Surface Mount', 
  '2 µA @ 4 V', 
  'Automotive, AEC-Q100', 
  '0.03', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '300 mW', 
  '1.1 V @ 100 mA', 
  'TapeAndReel', 
  'Active', 
  '6.8 V', 
  '15 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD523F.PCBLIB'
);

