--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "MOSFET-Single-N-Ch" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "FET Type",
  "Input Capacitance (Ciss) (Max) @ Vds",
  "Vgs(Th) (Max) @ Id",
  "Gate Charge (Qg) (Max) @ Vgs",
  "Supplier Device Package",
  "Power Dissipation (Max)",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Technology",
  "Lifecycle Status",
  "Manufacturer",
  "Drive Voltage (Max Rds On,  Min Rds On)",
  "Vgs (Max)",
  "LastUpdated",
  "Minimum Order",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Drain To Source Voltage (Vdss)",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Rds On (Max) @ Id, Vgs",
  "Series",
  "Price",
  "Library Path",
  "Current - Continuous Drain (Id) @ 25°C",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'MOSFET N-CH 30V 92A LFPAK56', 
  'PSMN4R1-30YLC,115', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/PSMN4R1-30YLC-115/2675450', 
  'N-Channel', 
  '1502 pF @ 15 V', 
  '1.95V @ 1mA', 
  '23 nC @ 10 V', 
  'LFPAK56, Power-SO8', 
  '67W (Tc)', 
  'SC-100, SOT-669', 
  'NEXPERIA PSMN LFPAK MOSFET N-CH', 
  '1727-PSMN4R1-30YLC,115CT-ND', 
  'MOSFET (Metal Oxide)', 
  'Active', 
  'Nexperia USA Inc.', 
  '4.5V, 10V', 
  '±20V', 
  '2023-05-27T20:47:20.463', 
  '1', 
  '=Part Number', 
  'https://assets.nexperia.com/documents/data-sheet/PSMN4R1-30YLC.pdf', 
  'NXP LFPAK56 SOT669', 
  '30 V', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '4.35mOhm @ 20A, 10V', 
  '-', 
  '0.25', 
  'symbols/FET - N-CH/SCH - FET - N-CH - NEXPERIA PSMN LFPAK MOSFET N-CH.SCHLIB', 
  '92A (Tc)', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - Misc/PCB - LEADED - MISC - NXP LFPAK56 SOT669.PCBLIB'
);

