--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 22V 320MW SOD323', 
  'PZU22B2A,115', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/PZU22B2A-115/2119981', 
  'SOD-323', 
  'SC-76, SOD-323', 
  'DIODE ZENER', 
  '1727-PZU22B2A,115CT-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-02-08T21:00:27.990', 
  '1', 
  '4246', 
  '=Part Number', 
  '-55°C ~ 150°C', 
  'https://assets.nexperia.com/documents/data-sheet/PZUXBA_SER.pdf', 
  'SOD323', 
  'Datasheet', 
  '±2%', 
  'DigiKey', 
  'Surface Mount', 
  '50 nA @ 17 V', 
  '-', 
  '0.03', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '320 mW', 
  '1.1 V @ 100 mA', 
  'TapeAndReel', 
  'Active', 
  '22 V', 
  '25 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD323.PCBLIB'
);

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 24V 320MW SOD323', 
  'PZU24B2A,115', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/PZU24B2A-115/2119987', 
  'SOD-323', 
  'SC-76, SOD-323', 
  'DIODE ZENER', 
  '1727-PZU24B2A,115CT-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-02-08T21:00:28.033', 
  '1', 
  '4247', 
  '=Part Number', 
  '-55°C ~ 150°C', 
  'https://assets.nexperia.com/documents/data-sheet/PZUXBA_SER.pdf', 
  'SOD323', 
  'Datasheet', 
  '±2%', 
  'DigiKey', 
  'Surface Mount', 
  '50 nA @ 19 V', 
  '-', 
  '0.03', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '320 mW', 
  '1.1 V @ 100 mA', 
  'TapeAndReel', 
  'Active', 
  '24 V', 
  '30 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD323.PCBLIB'
);

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 10V 320MW SOD323', 
  'PZU10B2A,115', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/PZU10B2A-115/2119924', 
  'SOD-323', 
  'SC-76, SOD-323', 
  'DIODE ZENER', 
  '1727-PZU10B2A,115CT-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-02-08T21:00:28.040', 
  '1', 
  '4248', 
  '=Part Number', 
  '-55°C ~ 150°C', 
  'https://assets.nexperia.com/documents/data-sheet/PZUXBA_SER.pdf', 
  'SOD323', 
  'Datasheet', 
  '±2%', 
  'DigiKey', 
  'Surface Mount', 
  '100 nA @ 7 V', 
  '-', 
  '0.03', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '320 mW', 
  '1.1 V @ 100 mA', 
  'TapeAndReel', 
  'Active', 
  '10 V', 
  '10 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD323.PCBLIB'
);

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 4.7V 400MW SOD323', 
  'PDZ4.7B,135', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/PDZ4-7B-135/2119820', 
  'SOD-323', 
  'SC-76, SOD-323', 
  'DIODE ZENER', 
  '1727-PDZ4.7B,135CT-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-02-08T21:00:28.097', 
  '1', 
  '4249', 
  '=Part Number', 
  '150°C (TJ)', 
  'https://assets.nexperia.com/documents/data-sheet/PDZ-B_SER.pdf', 
  'SOD323', 
  'Datasheet', 
  '±2%', 
  'DigiKey', 
  'Surface Mount', 
  '2 µA @ 1 V', 
  '-', 
  '0.02', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '400 mW', 
  '1.1 V @ 100 mA', 
  'TapeAndReel', 
  'Active', 
  '4.7 V', 
  '90 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD323.PCBLIB'
);

