--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Resistors-SurfaceMount-1206" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 27 OHM 5% 1/4W 1206', 
  'CR1206-JW-270ELF', 
  'https://www.digikey.com/en/products/detail/bourns-inc/CR1206-JW-270ELF/3785582', 
  '0.030" (0.75mm)', 
  '1206 (3216 Metric)', 
  '2', 
  '±200ppm/°C', 
  '1206', 
  '1206 (3216 Metric)', 
  'RESISTOR', 
  '118-CR1206-JW-270ELFCT-ND', 
  'Active', 
  'Bourns Inc.', 
  'Moisture Resistant', 
  '2023-04-03T19:36:58.143', 
  '1', 
  '69696', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.bourns.com/docs/product-datasheets/cr.pdf?sfvrsn=574d41f6_14', 
  'RES 1206_3216', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  '27 Ohms', 
  '0.25W, 1/4W', 
  'CR1206', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '27 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 1206_3216.PCBLIB'
);

