--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Current - Input Bias",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Footprint Ref",
  "-3db Bandwidth",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH BW CURR SENSE FOR 48V/12V D', 
  'AD8411AWBRMZ', 
  'https://www.digikey.com/en/products/detail/analog-devices-inc/AD8411AWBRMZ/19203203', 
  '178 µA', 
  '8-MSOP', 
  'ANALOG DEV AD8418WBRZ', 
  '505-AD8411AWBRMZ-ND', 
  'Active', 
  'Analog Devices Inc.', 
  '2025-04-10T17:44:52.007', 
  '1', 
  'Current Sense', 
  '91', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'ANALOG MSOP-8 RM-8', 
  '2.7 MHz', 
  '10V/µs', 
  'DigiKey', 
  '7.8mA', 
  'Surface Mount', 
  '1', 
  '200 µV', 
  '-', 
  '1.65', 
  'symbols/Opamp/SCH - OPAMP - ANALOG DEV AD8418WBRZ.SCHLIB', 
  'Tube', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - ANALOG MSOP-8 RM-8.PCBLIB'
);

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Current - Input Bias",
  "Supplier Device Package",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "-3db Bandwidth",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'HIGH BW CURR SENSE FOR 48V/12V D', 
  'AD8411AWBRZ', 
  'https://www.digikey.com/en/products/detail/analog-devices-inc/AD8411AWBRZ/21333810', 
  'Single-Ended', 
  '178 µA', 
  '8-SOIC', 
  'ANALOG DEV AD8418WBRZ', 
  '505-AD8411AWBRZ-ND', 
  'Active', 
  'Analog Devices Inc.', 
  '2025-04-10T17:45:24.663', 
  '1', 
  'Current Sense', 
  '92', 
  '=Part Number', 
  '-40°C ~ 125°C (TA)', 
  'https://www.analog.com/media/en/technical-documentation/data-sheets/ad8411a.pdf', 
  'ANALOG SO-8 R-8', 
  'Datasheet', 
  '2.7 MHz', 
  '10V/µs', 
  'DigiKey', 
  '7.8mA', 
  'Surface Mount', 
  '1', 
  '200 µV', 
  '-', 
  '1.65', 
  'symbols/Opamp/SCH - OPAMP - ANALOG DEV AD8418WBRZ.SCHLIB', 
  'Tube', 
  'DigiKey Link', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - ANALOG SO-8 R-8.PCBLIB'
);

