--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CURRENT SENSE RESISTOR', 
  'SR731HTTC5R60F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/SR731HTTC5R60F/12746968', 
  '0.010" (0.26mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '0/ +400ppm/°C', 
  '0201', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '2019-SR731HTTC5R60FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Current Sense, Moisture Resistant', 
  '2023-04-17T19:21:57.357', 
  '1', 
  '74870', 
  '=Value', 
  '-55°C ~ 125°C', 
  'Thick Film', 
  'https://www.koaspeer.com/catimages/Products/SR73/SR73.pdf', 
  'RES 0201_0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  '5.6 Ohms', 
  '0.1W, 1/10W', 
  'SR73', 
  '0.11', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '5.6 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 3.3 OHM 1% 1/20W 0201', 
  'RK73H1HTTC3R30F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RK73H1HTTC3R30F/9850485', 
  '0.010" (0.26mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '±400ppm/°C', 
  '0201', 
  'AEC-Q200', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '2019-RK73H1HTTC3R30FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant', 
  '2023-04-17T19:21:57.390', 
  '1', 
  '74872', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/RK73H.pdf', 
  'RES 0201_0603', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  '3.3 Ohms', 
  '0.05W, 1/20W', 
  'RK73H', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '3.3 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 49.9 OHM 0.5% 1/32W 0201', 
  'CPF0201D49R9E1', 
  'https://www.digikey.com/en/products/detail/te-connectivity-passive-product/CPF0201D49R9E1/4489547', 
  '0.011" (0.28mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '±25ppm/°C', 
  '0201', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '1712-CPF0201D49R9E1CT-ND', 
  'Active', 
  'TE Connectivity Passive Product', 
  '2023-04-17T19:21:57.407', 
  '1', 
  '74873', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=1773200&DocType=DS&DocLang=English', 
  'RES 0201_0603', 
  'Datasheet', 
  '±0.5%', 
  'DigiKey', 
  '0.023" L x 0.011" W (0.58mm x 0.29mm)', 
  '49.9 Ohms', 
  '0.03W, 1/32W', 
  'CPF, Neohm', 
  '0.09', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '49.9 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 47 OHM 5% 1/20W 0201', 
  'CRCW020147R0JNED', 
  'https://www.digikey.com/en/products/detail/vishay-dale/CRCW020147R0JNED/1178438', 
  '0.010" (0.26mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0201', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '541-CRCW020147R0JNEDCT-ND', 
  'Active', 
  'Vishay Dale', 
  '2023-04-17T19:21:57.420', 
  '1', 
  '74874', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.vishay.com/docs/20052/crcw0201e3.pdf', 
  'RES 0201_0603', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.024" L x 0.012" W (0.60mm x 0.30mm)', 
  '47 Ohms', 
  '0.05W, 1/20W', 
  'CRCW', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'CutTape', 
  'Active', 
  '47 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CPF 0201 4K32 0.1% 25PPM 1K RL', 
  'CPF0201B4K32E1', 
  'https://www.digikey.com/en/products/detail/te-connectivity-passive-product/CPF0201B4K32E1/14007199', 
  '0.011" (0.28mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '±25ppm/°C', 
  '0201', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '1712-CPF0201B4K32E1CT-ND', 
  'Active', 
  'TE Connectivity Passive Product', 
  '2023-04-17T19:21:57.430', 
  '1', 
  '74875', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=1773200&DocType=DS&DocLang=English', 
  'RES 0201_0603', 
  'Datasheet', 
  '±0.1%', 
  'DigiKey', 
  '0.023" L x 0.011" W (0.58mm x 0.29mm)', 
  '4.32 kOhms', 
  '0.03W, 1/32W', 
  'CPF', 
  '0.28', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '4.32 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 10K OHM 0.5% 1/32W 0201', 
  'CPF0201D10KC1', 
  'https://www.digikey.com/en/products/detail/te-connectivity-passive-product/CPF0201D10KC1/4489377', 
  '0.011" (0.28mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '±50ppm/°C', 
  '0201', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '1712-CPF0201D10KC1CT-ND', 
  'Active', 
  'TE Connectivity Passive Product', 
  '2023-04-17T19:21:57.443', 
  '1', 
  '74876', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=1773200&DocType=DS&DocLang=English', 
  'RES 0201_0603', 
  'Datasheet', 
  '±0.5%', 
  'DigiKey', 
  '0.023" L x 0.011" W (0.58mm x 0.29mm)', 
  '10 kOhms', 
  '0.03W, 1/32W', 
  'CPF, Neohm', 
  '0.08', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '10 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CPF 0201 14K7 0.1% 25PPM 1K RL', 
  'CPF0201B14K7E1', 
  'https://www.digikey.com/en/products/detail/te-connectivity-passive-product/CPF0201B14K7E1/14006803', 
  '0.011" (0.28mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '±25ppm/°C', 
  '0201', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '1712-CPF0201B14K7E1CT-ND', 
  'Active', 
  'TE Connectivity Passive Product', 
  '2023-04-17T19:21:57.460', 
  '1', 
  '74877', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=1773200&DocType=DS&DocLang=English', 
  'RES 0201_0603', 
  'Datasheet', 
  '±0.1%', 
  'DigiKey', 
  '0.023" L x 0.011" W (0.58mm x 0.29mm)', 
  '14.7 kOhms', 
  '0.03W, 1/32W', 
  'CPF', 
  '0.28', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '14.7 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CPF 0201 75K 0.1% 25PPM 1K RL', 
  'CPF0201B75KE1', 
  'https://www.digikey.com/en/products/detail/te-connectivity-passive-product/CPF0201B75KE1/14007144', 
  '0.011" (0.28mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '±25ppm/°C', 
  '0201', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '1712-CPF0201B75KE1CT-ND', 
  'Active', 
  'TE Connectivity Passive Product', 
  '2023-04-17T19:21:57.467', 
  '1', 
  '74878', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=1773200&DocType=DS&DocLang=English', 
  'RES 0201_0603', 
  'Datasheet', 
  '±0.1%', 
  'DigiKey', 
  '0.023" L x 0.011" W (0.58mm x 0.29mm)', 
  '75 kOhms', 
  '0.03W, 1/32W', 
  'CPF', 
  '0.28', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '75 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CPF 0201 33K2 0.1% 25PPM 1K RL', 
  'CPF0201B33K2E1', 
  'https://www.digikey.com/en/products/detail/te-connectivity-passive-product/CPF0201B33K2E1/14006842', 
  '0.011" (0.28mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '±25ppm/°C', 
  '0201', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '1712-CPF0201B33K2E1CT-ND', 
  'Active', 
  'TE Connectivity Passive Product', 
  '2023-04-17T19:21:57.483', 
  '1', 
  '74879', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=1773200&DocType=DS&DocLang=English', 
  'RES 0201_0603', 
  'Datasheet', 
  '±0.1%', 
  'DigiKey', 
  '0.023" L x 0.011" W (0.58mm x 0.29mm)', 
  '33.2 kOhms', 
  '0.03W, 1/32W', 
  'CPF', 
  '0.28', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '33.2 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0201" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES SMD 4.75KOHM 0.5% 1/32W 0201', 
  '9-2176073-2', 
  'https://www.digikey.com/en/products/detail/te-connectivity-passive-product/9-2176073-2/4489555', 
  '0.011" (0.28mm)', 
  '0201 (0603 Metric)', 
  '2', 
  '±25ppm/°C', 
  '0201', 
  '0201 (0603 Metric)', 
  'RESISTOR', 
  '1712-9-2176073-2CT-ND', 
  'Active', 
  'TE Connectivity Passive Product', 
  '2023-04-17T19:21:57.497', 
  '1', 
  '74880', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thin Film', 
  'https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=1773200&DocType=DS&DocLang=English', 
  'RES 0201_0603', 
  'Datasheet', 
  '±0.5%', 
  'DigiKey', 
  '0.023" L x 0.011" W (0.58mm x 0.29mm)', 
  '4.75 kOhms', 
  '0.03W, 1/32W', 
  'CPF, Neohm', 
  '0.09', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '4.75 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0201_0603.PCBLIB'
);

