--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Capacitors-Aluminum-Polymer-TH" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Lead Spacing",
  "Voltage - Rated",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Applications",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Esr (Equivalent Series Resistance)",
  "Mounting Type",
  "Size / Dimension",
  "Lifetime @ Temp.",
  "Series",
  "Type",
  "Price",
  "Ripple Current @ High Frequency",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Capacitance",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'CAP ALUM POLY 330UF 20% 16V T/H', 
  'APS-160EC3331MJC5S', 
  'https://www.digikey.com/en/products/detail/united-chemi-con/APS-160EC3331MJC5S/3998054', 
  '0.512" (13.00mm)', 
  'Radial, Can', 
  '0.138" (3.50mm)', 
  '16 V', 
  'Radial, Can', 
  'POLARISED CAPACITOR', 
  '565-APS-160EC3331MJC5S-ND', 
  'Active', 
  'United Chemi-Con', 
  '2023-02-17T21:10:48.680', 
  '1', 
  '5478', 
  '=Value', 
  '-55°C ~ 105°C', 
  'General Purpose', 
  'http://www.chemi-con.com/upload/files/5/7/11305061624d9b1a56ba94c.pdf', 
  'CAP TH ALPOLY D8.00mm S3.50mm H13.00mm', 
  'Datasheet', 
  '±20%', 
  'DigiKey', 
  '14mOhm', 
  'Through Hole', 
  '0.315" Dia (8.00mm)', 
  '2000 Hrs @ 105°C', 
  'NPCAP™-PS', 
  'Polymer', 
  '0.67', 
  '5.05 A @ 100 kHz', 
  'symbols/Passives/SCH - PASSIVES - POLARISED CAPACITOR.SCHLIB', 
  'Bulk', 
  'Active', 
  '330 µF', 
  '330 µF', 
  'DigiKey Link', 
  'footprints/Capacitor - Aluminium/PCB - CAPACITOR - ALUMINIUM - CAP TH ALPOLY D8.00mm S3.50mm H13.00mm.PCBLIB'
);

