--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Color",
  "ComponentLink1Description",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Lens Color",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '528nm', 
  'LED GREEN CLEAR 0402 SMD', 
  'LTST-C281TGKT-5A', 
  'https://www.digikey.com/en/products/detail/liteon/LTST-C281TGKT-5A/17879245', 
  'Clear', 
  '130°', 
  '0402 (1005 Metric)', 
  '154mcd', 
  '0402', 
  'Rectangle with Flat Top', 
  '0402 (1005 Metric)', 
  'LED', 
  '160-LTST-C281TGKT-5ACT-ND', 
  'Active', 
  'Lite-On Inc.', 
  '2.8V', 
  '2025-08-25T20:34:09.867', 
  '1', 
  '525nm', 
  '1507', 
  '1.60mm x 0.80mm', 
  '=Value', 
  'https://optoelectronics.liteon.com/upload/download/DS22-2012-0064/LTST-C281TGKT-5A.pdf', 
  'LED 0402_1005 GREEN', 
  'Green', 
  'Datasheet', 
  '5mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.00mm L x 0.50mm W', 
  '0.45mm', 
  '-', 
  '0.10', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'Colorless', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0402_1005 GREEN.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Configuration",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Lens Size",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Color",
  "ComponentLink1Description",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Lens Color",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '528nm', 
  '599 SMD LED 0402 0.35MM HEIGHT G', 
  'Independent', 
  '5991A80147F', 
  'https://www.digikey.com/en/products/detail/dialight/5991A80147F/25965523', 
  'Diffused', 
  '100°, 150°', 
  '0402 (1005 Metric)', 
  '270mcd', 
  '0402', 
  'Rectangle with Flat Top', 
  '0402 (1005 Metric)', 
  'LED', 
  '350-5991A80147FCT-ND', 
  'Active', 
  'Dialight', 
  '2.8V', 
  '2025-08-25T20:34:08.260', 
  '1', 
  '1508', 
  '1.00mm x 0.50mm', 
  '=Value', 
  'https://s3-us-west-2.amazonaws.com/catsy.557/C18789.pdf', 
  'LED 0402_1005 GREEN', 
  'Green', 
  'Datasheet', 
  '5mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.00mm L x 0.50mm W', 
  '0.38mm', 
  '599', 
  '0.07', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'Colorless', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0402_1005 GREEN.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Color",
  "ComponentLink1Description",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Lens Color",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '576.5nm', 
  'LED GREEN CLEAR 0402 SMD', 
  'LTST-C281KGKT-5A', 
  'https://www.digikey.com/en/products/detail/liteon/LTST-C281KGKT-5A/17879214', 
  'Clear', 
  '130°', 
  '0402 (1005 Metric)', 
  '16.25mcd', 
  '0402', 
  'Rectangle with Flat Top', 
  '0402 (1005 Metric)', 
  'LED', 
  '160-LTST-C281KGKT-5ACT-ND', 
  'Active', 
  'Lite-On Inc.', 
  '2V', 
  '2025-08-25T20:34:09.877', 
  '1', 
  '574nm', 
  '1509', 
  '1.00mm x 0.50mm', 
  '=Value', 
  'https://optoelectronics.liteon.com/upload/download/DS22-2009-0040/LTST-C281KGKT-5A.PDF', 
  'LED 0402_1005 GREEN', 
  'Green', 
  'Datasheet', 
  '5mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.00mm L x 0.50mm W', 
  '0.45mm', 
  '-', 
  '0.06', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'Colorless', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0402_1005 GREEN.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Device Package",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Color",
  "ComponentLink1Description",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Lens Color",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '530nm', 
  'LED GREEN DIFFUSED 0402 SMD', 
  'LT QH9G-Q2OO-25-2Z4Y-5-R18', 
  'https://www.digikey.com/en/products/detail/ams-osram-usa-inc/LT-QH9G-Q2OO-25-2Z4Y-5-R18/17629133', 
  'Diffused', 
  '115°', 
  '0402 (1005 Metric)', 
  '0402', 
  'Rectangle with Flat Top', 
  '0402 (1005 Metric)', 
  'LED', 
  '475-LTQH9G-Q2OO-25-2Z4Y-5-R18CT-ND', 
  'Active', 
  'ams-OSRAM USA Inc.', 
  '2.85V', 
  '2025-08-25T20:34:08.993', 
  '1', 
  '525nm', 
  '1510', 
  '1.10mm x 0.54mm', 
  '=Value', 
  'https://dammedia.osram.info/media/resource/hires/osram-dam-5171475/LT%20QH9G_EN.pdf', 
  'LED 0402_1005 GREEN', 
  'Green', 
  'Datasheet', 
  '5mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.00mm L x 1.20mm W', 
  '0.40mm', 
  'CHIPLED', 
  '0.08', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'White', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0402_1005 GREEN.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Configuration",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Color",
  "ComponentLink1Description",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '525nm', 
  '0402 PKG, TOP VIEW, TRUE GREEN,', 
  'Independent', 
  'QLSP23GA', 
  'https://www.digikey.com/en/products/detail/quelighting-corp/QLSP23GA/22311998', 
  'Clear', 
  '120°', 
  '0402 (1005 Metric)', 
  '250mcd', 
  '0402', 
  'Rectangle with Flat Top', 
  '0402 (1005 Metric)', 
  'LED', 
  '3970-QLSP23GACT-ND', 
  'Active', 
  'Quelighting Corp', 
  '2.65V', 
  '2025-08-25T20:34:09.847', 
  '1', 
  '525nm', 
  '1511', 
  '0.65mm x 0.55mm', 
  '=Value', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/6025/QLSP23GA.pdf', 
  'LED 0402_1005 GREEN', 
  'Green', 
  'Datasheet', 
  '5mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.05mm L x 0.55mm W', 
  '0.58mm', 
  '-', 
  '0.06', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0402_1005 GREEN.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Configuration",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Color",
  "ComponentLink1Description",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Lens Color",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '527nm', 
  'LED GREEN DIFFUSED 0603 SMD', 
  'Standard', 
  'KT EELP41.12-S2U1-25-2X4Y-5-R18', 
  'https://www.digikey.com/en/products/detail/ams-osram-usa-inc/KT-EELP41-12-S2U1-25-2X4Y-5-R18/24765233', 
  'Diffused', 
  '130°, 145°', 
  '0603 (1608 Metric)', 
  '392mcd', 
  '0603', 
  'Rectangle with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '475-KTEELP41.12-S2U1-25-2X4Y-5-R18CT-ND', 
  'Active', 
  'ams-OSRAM USA Inc.', 
  '2.5V', 
  '2025-08-25T20:34:59.173', 
  '1', 
  '522nm', 
  '1512', 
  '1.16mm x 0.80mm', 
  '=Value', 
  'https://look.ams-osram.com/m/4cbb1524123e38e9/original/KT-EELP41-12.pdf', 
  'LED 0603_1608 GREEN', 
  'Green', 
  'Datasheet', 
  '5mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '0.50mm', 
  'SMARTLED® 0603', 
  '0.03', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'Colorless', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 GREEN.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Configuration",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Millicandela Rating",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Lens Size",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Color",
  "ComponentLink1Description",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '575nm', 
  'LED GREEN SMD', 
  'Standard', 
  'CL-195YG-CD', 
  'https://www.digikey.com/en/products/detail/citizen/CL-195YG-CD/6005903', 
  '0603 (1608 Metric)', 
  '18mcd', 
  'Rectangle with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '1642-CL-195YG-CD-TCT-ND', 
  'Active', 
  'Citizen', 
  '2.2V', 
  '2025-08-25T20:34:59.193', 
  '1', 
  '1513', 
  '1.60mm x 0.80mm', 
  '=Value', 
  'https://ce.citizen.co.jp/up_img/product/l3DSeGGaYefr/CL-195_e.pdf', 
  'LED 0603_1608 GREEN', 
  'Green', 
  'Datasheet', 
  '20mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '0.80mm', 
  'CL-195', 
  '0.08', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 GREEN.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Configuration",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Millicandela Rating",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Lens Size",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Color",
  "ComponentLink1Description",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '575nm', 
  'LED GREEN SMD', 
  'Standard', 
  'CL-196YG-CD', 
  'https://www.digikey.com/en/products/detail/citizen/CL-196YG-CD/6005905', 
  '0603 (1608 Metric)', 
  '18mcd', 
  'Rectangle with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '1642-CL-196YG-CD-TCT-ND', 
  'Active', 
  'Citizen', 
  '2.2V', 
  '2025-08-25T20:34:59.213', 
  '1', 
  '1514', 
  '1.60mm x 0.80mm', 
  '=Value', 
  'https://ce.citizen.co.jp/up_img/product/zzOM8tpTLfGL/CL-196_e.pdf', 
  'LED 0603_1608 GREEN', 
  'Green', 
  'Datasheet', 
  '20mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '0.60mm', 
  'CL-196', 
  '0.05', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 GREEN.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Configuration",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "Footprint Ref",
  "Color",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Lens Color",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '527nm', 
  'LED GREEN DIFFUSED 0603 SMD', 
  'Standard', 
  'KT EELP41.12-S2U1-25-2X4X-5-R18', 
  'https://www.digikey.com/en/products/detail/ams-osram-usa-inc/KT-EELP41-12-S2U1-25-2X4X-5-R18/24765233', 
  'Diffused', 
  '130°, 145°', 
  '0603 (1608 Metric)', 
  '392mcd', 
  '0603', 
  'Rectangle with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '475-KTEELP41.12-S2U1-25-2X4X-5-R18CT-ND', 
  'Active', 
  'ams-OSRAM USA Inc.', 
  '2.5V', 
  '2025-08-25T20:34:59.237', 
  '1', 
  '522nm', 
  '1515', 
  '1.16mm x 0.80mm', 
  '=Value', 
  'LED 0603_1608 GREEN', 
  'Green', 
  '5mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '0.50mm', 
  'SMARTLED® 0603', 
  '0.03', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'Colorless', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 GREEN.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Configuration",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "Footprint Ref",
  "Color",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Lens Color",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '572nm', 
  'LED GREEN DIFFUSED 0603 SMD', 
  'Standard', 
  'KG EELP41.22-PHRH-35-A8J8-20-R18', 
  'https://www.digikey.com/en/products/detail/ams-osram-usa-inc/KG-EELP41-22-PHRH-35-A8J8-20-R18/24765242', 
  'Diffused', 
  '130°, 130°', 
  '0603 (1608 Metric)', 
  '101mcd', 
  '0603', 
  'Rectangle with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '475-KGEELP41.22-PHRH-35-A8J8-20-R18CT-ND', 
  'Active', 
  'ams-OSRAM USA Inc.', 
  '2.1V', 
  '2025-08-25T20:34:59.287', 
  '1', 
  '574nm', 
  '1516', 
  '1.16mm x 0.80mm', 
  '=Value', 
  'LED 0603_1608 GREEN', 
  'Green', 
  '20mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '0.50mm', 
  'SMARTLED® 0603', 
  '0.03', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'Colorless', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 GREEN.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Configuration",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "Footprint Ref",
  "Color",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Lens Color",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '565nm', 
  '1.6X0.8MM GREEN SMD LED', 
  'Independent', 
  'APT1608QGW', 
  'https://www.digikey.com/en/products/detail/kingbright/APT1608QGW/25807518', 
  'Diffused', 
  '120°', 
  '0603 (1608 Metric)', 
  '12mcd', 
  '0603', 
  'Rectangle with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '754-APT1608QGWCT-ND', 
  'Active', 
  'Kingbright', 
  '2.15V', 
  '2025-08-25T20:34:59.510', 
  '1', 
  '560nm', 
  '1517', 
  '1.60mm x 0.80mm', 
  '=Value', 
  'LED 0603_1608 GREEN', 
  'Green', 
  '20mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.85mm W', 
  '0.85mm', 
  '-', 
  '0.05', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'White', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 GREEN.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Configuration",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "Footprint Ref",
  "Color",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Lens Color",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '568nm', 
  '1.6X0.8MM GREEN SMD LED', 
  'Independent', 
  'APT1608SGD3', 
  'https://www.digikey.com/en/products/detail/kingbright/APT1608SGD3/25807473', 
  'Diffused', 
  '120°', 
  '0603 (1608 Metric)', 
  '8mcd', 
  '0603', 
  'Rectangle with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '754-APT1608SGD3CT-ND', 
  'Active', 
  'Kingbright', 
  '2.2V', 
  '2025-08-25T20:34:59.530', 
  '1', 
  '565nm', 
  '1518', 
  '1.20mm x 0.80mm', 
  '=Value', 
  'LED 0603_1608 GREEN', 
  'Green', 
  '20mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.85mm W', 
  '0.85mm', 
  '-', 
  '0.05', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'Green', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 GREEN.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Configuration",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "Footprint Ref",
  "Color",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Lens Color",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '568nm', 
  '1.6X0.8MM (0603) GREEN SMD LED', 
  'Independent', 
  'AP1608SGC', 
  'https://www.digikey.com/en/products/detail/kingbright/AP1608SGC/25807500', 
  'Clear', 
  '150°', 
  '0603 (1608 Metric)', 
  '12mcd', 
  '0603', 
  'Rectangle with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '754-AP1608SGCCT-ND', 
  'Active', 
  'Kingbright', 
  '2.2V', 
  '2025-08-25T20:34:59.547', 
  '1', 
  '565nm', 
  '1519', 
  '1.20mm x 0.80mm', 
  '=Value', 
  'LED 0603_1608 GREEN', 
  'Green', 
  '20mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '1.10mm', 
  '-', 
  '0.05', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'Colorless', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 GREEN.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Configuration",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "Footprint Ref",
  "Color",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Lens Color",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '568nm', 
  '1.6X0.8MM (0603) GREEN SMD LED', 
  'Independent', 
  'APHM1608SGCT', 
  'https://www.digikey.com/en/products/detail/kingbright/APHM1608SGCT/25807514', 
  'Clear', 
  '150°', 
  '0603 (1608 Metric)', 
  '12mcd', 
  '0603', 
  'Rectangle with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '754-APHM1608SGCT-ND', 
  'Active', 
  'Kingbright', 
  '2.2V', 
  '2025-08-25T20:34:59.567', 
  '1', 
  '565nm', 
  '1520', 
  '1.20mm x 0.80mm', 
  '=Value', 
  'LED 0603_1608 GREEN', 
  'Green', 
  '20mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '0.45mm', 
  '-', 
  '0.05', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'Colorless', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 GREEN.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Configuration",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Lens Size",
  "Comment",
  "Footprint Ref",
  "Color",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Lens Color",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '525nm', 
  'SMLED 0603 0.4MM GREEN 7"RL', 
  'Independent', 
  '5990080137F', 
  'https://www.digikey.com/en/products/detail/dialight/5990080137F/24786894', 
  'Clear', 
  '130°', 
  '0603 (1608 Metric)', 
  '725mcd', 
  '0603', 
  'Rectangle with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '350-5990080137FCT-ND', 
  'Active', 
  'Dialight', 
  '3.2V', 
  '2025-08-25T20:34:59.583', 
  '1', 
  '1521', 
  '1.00mm x 0.80mm', 
  '=Value', 
  'LED 0603_1608 GREEN', 
  'Green', 
  '20mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '0.53mm', 
  '599', 
  '0.07', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'Colorless', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 GREEN.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Lens Size",
  "Comment",
  "Footprint Ref",
  "Color",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'LED GREEN 0603 SMD 7" REEL', 
  '5988E80107F', 
  'https://www.digikey.com/en/products/detail/dialight/5988E80107F/18091602', 
  '60°', 
  '0603 (1608 Metric)', 
  '775mcd', 
  '0603', 
  'Round with Domed Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '350-5988E80107FCT-ND', 
  'Active', 
  'Dialight', 
  '2.4V', 
  '2025-08-25T20:35:03.317', 
  '1', 
  '1522', 
  '0.70mm Dia', 
  '=Value', 
  'LED 0603_1608 GREEN', 
  'Green', 
  '20mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '1.06mm', 
  '598', 
  '0.08', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 GREEN.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Configuration",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Color",
  "ComponentLink1Description",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Lens Color",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '570nm', 
  '1.6X0.8MM (0603) GREEN PLCC2 SMD', 
  'Independent', 
  'AA1608LCGSK', 
  'https://www.digikey.com/en/products/detail/kingbright/AA1608LCGSK/24632687', 
  'Clear', 
  '120°', 
  '0603 (1608 Metric)', 
  '6mcd', 
  '0603', 
  'Oval with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '754-AA1608LCGSKCT-ND', 
  'Active', 
  'Kingbright', 
  '1.9V', 
  '2025-08-25T20:35:04.130', 
  '1', 
  '574nm', 
  '1523', 
  '=Value', 
  'https://www.kingbrightusa.com/images/catalog/SPEC/AA1608LCGSK.pdf', 
  'LED 0603_1608 GREEN', 
  'Green', 
  'Datasheet', 
  '2mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '0.70mm', 
  '-', 
  '0.10', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'Colorless', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 GREEN.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Configuration",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Color",
  "ComponentLink1Description",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Lens Color",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '525nm', 
  '1.6X0.8MM (0603) GREEN PLCC2 SMD', 
  'Independent', 
  'AA1608LZGSK-295V', 
  'https://www.digikey.com/en/products/detail/kingbright/AA1608LZGSK-295V/24632684', 
  'Clear', 
  '120°', 
  '0603 (1608 Metric)', 
  '140mcd', 
  '0603', 
  'Oval with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '754-AA1608LZGSK-295VCT-ND', 
  'Active', 
  'Kingbright', 
  '2.65V', 
  '2025-08-25T20:35:04.153', 
  '1', 
  '515nm', 
  '1524', 
  '=Value', 
  'https://www.kingbrightusa.com/images/catalog/SPEC/AA1608LZGSK-295V.pdf', 
  'LED 0603_1608 GREEN', 
  'Green', 
  'Datasheet', 
  '2mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '0.70mm', 
  '-', 
  '0.17', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'Colorless', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 GREEN.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Lens Size",
  "Comment",
  "Footprint Ref",
  "Color",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '625nm', 
  'LED GREEN 0603 SMD 7" REEL', 
  '5988D80107F', 
  'https://www.digikey.com/en/products/detail/dialight/5988D80107F/18091217', 
  '140°', 
  '0603 (1608 Metric)', 
  '135mcd', 
  '0603', 
  'Rectangle with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '350-5988D80107FCT-ND', 
  'Active', 
  'Dialight', 
  '2.8V', 
  '2025-08-25T20:35:04.707', 
  '1', 
  '1525', 
  '1.23mm x 0.80mm', 
  '=Value', 
  'LED 0603_1608 GREEN', 
  'Green', 
  '20mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '1.11mm', 
  '598', 
  '0.07', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 GREEN.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Configuration",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Color",
  "ComponentLink1Description",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "Lens Color",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '557nm', 
  'LED GREEN CLEAR 0603 SMD', 
  'Standard', 
  'SM0603PGC', 
  'https://www.digikey.com/en/products/detail/bivar-inc/SM0603PGC/3095517', 
  'Clear', 
  '130°', 
  '0603 (1608 Metric)', 
  '4.5mcd', 
  '0603', 
  'Rectangle with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '492-SM0603PGCCT-ND', 
  'Active', 
  'Bivar Inc.', 
  '2V', 
  '2025-08-25T20:35:05.077', 
  '1', 
  '555nm', 
  '1526', 
  '1.00mm x 0.80mm', 
  '=Value', 
  'https://www.bivar.com/parts_content/Datasheets/SM0603PGC.pdf', 
  'LED 0603_1608 GREEN', 
  'Green', 
  'Datasheet', 
  '20mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '0.80mm', 
  '-', 
  '0.21', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'Colorless', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 GREEN.PCBLIB'
);

INSERT INTO "altium"."LED-Indication" (
  "Wavelength - Dominant",
  "Description",
  "Configuration",
  "Part Number",
  "ComponentLink2URL",
  "Lens Transparency",
  "Viewing Angle",
  "Device Package",
  "Millicandela Rating",
  "Supplier Device Package",
  "Lens Style",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Voltage - Forward (Vf) (Typ)",
  "LastUpdated",
  "Minimum Order",
  "Wavelength - Peak",
  "PartId",
  "Lens Size",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Color",
  "ComponentLink1Description",
  "Current - Test",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  '525nm', 
  '0603 PKG, TOP VIEW, TRUE GREEN,', 
  'Independent', 
  'QLSP1306GA', 
  'https://www.digikey.com/en/products/detail/quelighting-corp/QLSP1306GA/22311996', 
  'Clear', 
  '120°', 
  '0603 (1608 Metric)', 
  '315mcd', 
  '0603', 
  'Rectangle with Flat Top', 
  '0603 (1608 Metric)', 
  'LED', 
  '3970-QLSP1306GACT-ND', 
  'Active', 
  'Quelighting Corp', 
  '2.6V', 
  '2025-08-25T20:35:05.100', 
  '1', 
  '523nm', 
  '1527', 
  '1.10mm x 0.80mm', 
  '=Value', 
  'https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/6025/QLSP1306GA.pdf', 
  'LED 0603_1608 GREEN', 
  'Green', 
  'Datasheet', 
  '5mA', 
  'DigiKey', 
  'Surface Mount', 
  '1.60mm L x 0.80mm W', 
  '0.70mm', 
  '-', 
  '0.06', 
  'symbols/Diodes/SCH - DIODES - LED.SCHLIB', 
  'TapeAndReel', 
  'Green', 
  'DigiKey Link', 
  'footprints/LED/PCB - LED - LED 0603_1608 GREEN.PCBLIB'
);

