--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 510 OHM 1% 1/8W 0402', 
  'SG73P1ETTP5100F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/SG73P1ETTP5100F/10188314', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±100ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '2019-SG73P1ETTP5100FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-12T19:30:03.390', 
  '1', 
  '77365', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/SG73P.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '510 Ohms', 
  '0.125W, 1/8W', 
  'SG73P', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '510 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 1 OHM 1% 1/8W 0402', 
  'SG73P1ETTP1R00F', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/SG73P1ETTP1R00F/10188419', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '2019-SG73P1ETTP1R00FCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Pulse Withstanding', 
  '2023-05-12T19:30:03.397', 
  '1', 
  '77366', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/SG73P.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '1 Ohms', 
  '0.125W, 1/8W', 
  'SG73P', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 22 OHM 1% 1/16W 0402', 
  'RN73H1ETTP22R0F50', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RN73H1ETTP22R0F50/9914079', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±50ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '2019-RN73H1ETTP22R0F50CT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Automotive AEC-Q200, Moisture Resistant', 
  '2023-05-12T19:30:03.407', 
  '1', 
  '77367', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Metal Film', 
  'https://www.koaspeer.com/pdfs/RN73H.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±1%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '22 Ohms', 
  '0.063W, 1/16W', 
  'RN73H', 
  '0.06', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '22 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 100 OHM 5% 1/10W 0402', 
  'RK73B1ERTTP101J', 
  'https://www.digikey.com/en/products/detail/koa-speer-electronics-inc/RK73B1ERTTP101J/10714973', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0402', 
  'AEC-Q200', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '2019-RK73B1ERTTP101JCT-ND', 
  'Active', 
  'KOA Speer Electronics, Inc.', 
  'Anti-Sulfur, Automotive AEC-Q200', 
  '2023-05-12T19:30:03.413', 
  '1000', 
  '77368', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://www.koaspeer.com/pdfs/RK73-RT.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '100 Ohms', 
  '0.1W, 1/10W', 
  'RK73-RT', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '100 Ohms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

INSERT INTO "Resistors-SurfaceMount-0402" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height - Seated (Max)",
  "Device Package",
  "Number Of Terminations",
  "Temperature Coefficient",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Composition",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Size / Dimension",
  "Resistance",
  "Power (Watts)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'RES 5.1K OHM 5% 1/16W 0402', 
  'SFR01MZPJ512', 
  'https://www.digikey.com/en/products/detail/rohm-semiconductor/SFR01MZPJ512/6816514', 
  '0.016" (0.40mm)', 
  '0402 (1005 Metric)', 
  '2', 
  '±200ppm/°C', 
  '0402', 
  '0402 (1005 Metric)', 
  'RESISTOR', 
  '511-SFR01MZPJ512CT-ND', 
  'Active', 
  'Rohm Semiconductor', 
  'Anti-Sulfur', 
  '2023-05-12T19:30:03.420', 
  '1', 
  '77369', 
  '=Value', 
  '-55°C ~ 155°C', 
  'Thick Film', 
  'https://fscdn.rohm.com/en/products/databook/datasheet/passive/resistor/chip_resistor/sfr-e.pdf', 
  'RES 0402_1005', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  '0.039" L x 0.020" W (1.00mm x 0.50mm)', 
  '5.1 kOhms', 
  '0.063W, 1/16W', 
  'SFR', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - RESISTOR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '5.1 kOhms', 
  'DigiKey Link', 
  'footprints/Resistor - Chip/PCB - RESISTOR - CHIP - RES 0402_1005.PCBLIB'
);

