--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Current - Input Bias",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "-3db Bandwidth",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Voltage - Supply, Single/Dual (±)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC CURR SENSE 1 CIRCUIT 8TSSOP', 
  'INA240A2PWR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/INA240A2PWR/6562018', 
  '90 µA', 
  '8-TSSOP', 
  '8-TSSOP (0.173", 4.40mm Width)', 
  'TI INA240A2PW', 
  '296-45089-1-ND', 
  'Active', 
  'Texas Instruments', 
  '2024-11-26T09:20:54.140', 
  '1', 
  'Current Sense', 
  '83', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.ti.com/lit/pdf/slyb194', 
  'TI TSSOP-8 PW', 
  'Datasheet', 
  '400 kHz', 
  '2V/µs', 
  'DigiKey', 
  '1.8mA', 
  'Surface Mount', 
  '1', 
  '5 µV', 
  '-', 
  '1.62', 
  'symbols/Opamp/SCH - OPAMP - TI INA240A2PW.SchLib', 
  'TapeAndReel', 
  'Active', 
  '2.7V ~ 5.5V', 
  'DigiKey Link', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - TI TSSOP-8 PW.PCBLIB'
);

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Current - Input Bias",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "-3db Bandwidth",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Voltage - Supply, Single/Dual (±)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC CURR SENSE 1 CIRCUIT 8TSSOP', 
  'INA240A1PWR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/INA240A1PWR/6562017', 
  '90 µA', 
  '8-TSSOP', 
  '8-TSSOP (0.173", 4.40mm Width)', 
  'TI INA240A2PW', 
  '296-45088-1-ND', 
  'Active', 
  'Texas Instruments', 
  '2024-11-26T09:19:52.473', 
  '1', 
  'Current Sense', 
  '84', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.ti.com/lit/pdf/slyb194', 
  'TI TSSOP-8 PW', 
  'Datasheet', 
  '400 kHz', 
  '2V/µs', 
  'DigiKey', 
  '1.8mA', 
  'Surface Mount', 
  '1', 
  '5 µV', 
  '-', 
  '1.31', 
  'symbols/Opamp/SCH - OPAMP - TI INA240A2PW.SchLib', 
  'TapeAndReel', 
  'Active', 
  '2.7V ~ 5.5V', 
  'DigiKey Link', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - TI TSSOP-8 PW.PCBLIB'
);

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Current - Input Bias",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "-3db Bandwidth",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Voltage - Supply, Single/Dual (±)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC CURR SENSE 1 CIRCUIT 8TSSOP', 
  'INA240A3PWR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/INA240A3PWR/6562019', 
  '90 µA', 
  '8-TSSOP', 
  '8-TSSOP (0.173", 4.40mm Width)', 
  'TI INA240A2PW', 
  '296-45090-1-ND', 
  'Active', 
  'Texas Instruments', 
  '2024-11-26T09:20:13.183', 
  '1', 
  'Current Sense', 
  '85', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.ti.com/lit/pdf/slyb194', 
  'TI TSSOP-8 PW', 
  'Datasheet', 
  '400 kHz', 
  '2V/µs', 
  'DigiKey', 
  '1.8mA', 
  'Surface Mount', 
  '1', 
  '5 µV', 
  '-', 
  '1.62', 
  'symbols/Opamp/SCH - OPAMP - TI INA240A2PW.SchLib', 
  'TapeAndReel', 
  'Active', 
  '2.7V ~ 5.5V', 
  'DigiKey Link', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - TI TSSOP-8 PW.PCBLIB'
);

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Current - Input Bias",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "-3db Bandwidth",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Voltage - Supply, Single/Dual (±)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC CURR SENSE 1 CIRCUIT 8TSSOP', 
  'INA240A4PWR', 
  'https://www.digikey.com/en/products/detail/texas-instruments/INA240A4PWR/6562020', 
  '90 µA', 
  '8-TSSOP', 
  '8-TSSOP (0.173", 4.40mm Width)', 
  'TI INA240A2PW', 
  '296-45091-1-ND', 
  'Active', 
  'Texas Instruments', 
  '2024-11-26T09:21:07.247', 
  '1', 
  'Current Sense', 
  '86', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.ti.com/lit/pdf/slyb194', 
  'TI TSSOP-8 PW', 
  'Datasheet', 
  '400 kHz', 
  '2V/µs', 
  'DigiKey', 
  '1.8mA', 
  'Surface Mount', 
  '1', 
  '5 µV', 
  '-', 
  '1.62', 
  'symbols/Opamp/SCH - OPAMP - TI INA240A2PW.SchLib', 
  'TapeAndReel', 
  'Active', 
  '2.7V ~ 5.5V', 
  'DigiKey Link', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - TI TSSOP-8 PW.PCBLIB'
);

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Current - Input Bias",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "-3db Bandwidth",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Voltage - Supply, Single/Dual (±)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC CURR SENSE 1 CIRCUIT 8TSSOP', 
  'INA240A1QPWRQ1', 
  'https://www.digikey.com/en/products/detail/texas-instruments/INA240A1QPWRQ1/8322727', 
  '90 µA', 
  '8-TSSOP', 
  '8-TSSOP (0.173", 4.40mm Width)', 
  'TI INA240A2PW', 
  '296-50472-1-ND', 
  'Active', 
  'Texas Instruments', 
  '2024-11-26T09:21:53.207', 
  '1', 
  'Current Sense', 
  '87', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Fina240-q1', 
  'TI TSSOP-8 PW', 
  'Datasheet', 
  '400 kHz', 
  '2V/µs', 
  'DigiKey', 
  '1.8mA', 
  'Surface Mount', 
  '1', 
  '5 µV', 
  'Zero-Drift', 
  '1.50', 
  'symbols/Opamp/SCH - OPAMP - TI INA240A2PW.SchLib', 
  'TapeAndReel', 
  'Active', 
  '2.7V ~ 5.5V', 
  'DigiKey Link', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - TI TSSOP-8 PW.PCBLIB'
);

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Current - Input Bias",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "-3db Bandwidth",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Voltage - Supply, Single/Dual (±)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC CURR SENSE 1 CIRCUIT 8TSSOP', 
  'INA240A2QPWRQ1', 
  'https://www.digikey.com/en/products/detail/texas-instruments/INA240A2QPWRQ1/8322729', 
  '90 µA', 
  '8-TSSOP', 
  '8-TSSOP (0.173", 4.40mm Width)', 
  'TI INA240A2PW', 
  '296-50473-1-ND', 
  'Active', 
  'Texas Instruments', 
  '2024-11-26T09:22:26.743', 
  '1', 
  'Current Sense', 
  '88', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Fina240-q1', 
  'TI TSSOP-8 PW', 
  'Datasheet', 
  '400 kHz', 
  '2V/µs', 
  'DigiKey', 
  '1.8mA', 
  'Surface Mount', 
  '1', 
  '5 µV', 
  'Zero-Drift', 
  '1.92', 
  'symbols/Opamp/SCH - OPAMP - TI INA240A2PW.SchLib', 
  'TapeAndReel', 
  'Active', 
  '2.7V ~ 5.5V', 
  'DigiKey Link', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - TI TSSOP-8 PW.PCBLIB'
);

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Current - Input Bias",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "-3db Bandwidth",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Voltage - Supply, Single/Dual (±)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC CURR SENSE 1 CIRCUIT 8TSSOP', 
  'INA240A3QPWRQ1', 
  'https://www.digikey.com/en/products/detail/texas-instruments/INA240A3QPWRQ1/8322731', 
  '90 µA', 
  '8-TSSOP', 
  '8-TSSOP (0.173", 4.40mm Width)', 
  'TI INA240A2PW', 
  '296-51175-1-ND', 
  'Active', 
  'Texas Instruments', 
  '2024-11-26T09:22:37.530', 
  '1', 
  'Current Sense', 
  '89', 
  '=Part Number', 
  '-40°C ~ 125°C (TA)', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Fina240-q1', 
  'TI TSSOP-8 PW', 
  'Datasheet', 
  '400 kHz', 
  '2V/µs', 
  'DigiKey', 
  '1.8mA', 
  'Surface Mount', 
  '1', 
  '5 µV', 
  'Zero-Drift', 
  '1.92', 
  'symbols/Opamp/SCH - OPAMP - TI INA240A2PW.SchLib', 
  'TapeAndReel', 
  'Active', 
  '2.7V ~ 5.5V', 
  'DigiKey Link', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - TI TSSOP-8 PW.PCBLIB'
);

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Current - Input Bias",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "-3db Bandwidth",
  "Slew Rate",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Voltage - Input Offset",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Voltage - Supply, Single/Dual (±)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC CURR SENSE 1 CIRCUIT 8TSSOP', 
  'INA240A4QPWRQ1', 
  'https://www.digikey.com/en/products/detail/texas-instruments/INA240A4QPWRQ1/8538260', 
  '90 µA', 
  '8-TSSOP', 
  '8-TSSOP (0.173", 4.40mm Width)', 
  'TI INA240A2PW', 
  '296-51177-1-ND', 
  'Active', 
  'Texas Instruments', 
  '2024-11-26T09:22:52.583', 
  '1', 
  'Current Sense', 
  '90', 
  '=Part Number', 
  '-40°C ~ 125°C', 
  'http://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Fina240-q1', 
  'TI TSSOP-8 PW', 
  'Datasheet', 
  '400 kHz', 
  '2V/µs', 
  'DigiKey', 
  '1.8mA', 
  'Surface Mount', 
  '1', 
  '5 µV', 
  '-', 
  '1.78', 
  'symbols/Opamp/SCH - OPAMP - TI INA240A2PW.SchLib', 
  'TapeAndReel', 
  'Active', 
  '2.7V ~ 5.5V', 
  'DigiKey Link', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - TI TSSOP-8 PW.PCBLIB'
);

