--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Dc Resistance (Dcr) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD 220 OHM 0603 1LN', 
  '220 Ohms @ 100 MHz', 
  'MFBW1V1608-221-R', 
  'https://www.digikey.com/en/products/detail/eaton-electronics-division/MFBW1V1608-221-R/13161138', 
  '0603 (1608 Metric)', 
  '0603 (1608 Metric)', 
  'FERRITE CHIP', 
  '283-MFBW1V1608-221-RCT-ND', 
  '1A', 
  'Active', 
  'Eaton - Electronics Division', 
  '2023-02-25T20:48:49.053', 
  '1', 
  '3250', 
  '=Value', 
  '-40°C ~ 85°C', 
  'https://www.eaton.com/content/dam/eaton/products/electronic-components/resources/data-sheet/eaton-mfbw1v1608-high-impedance-multilayer-ferrite-chip-bead-data-sheet.pdf', 
  'FER 0603_1608', 
  'Datasheet', 
  '200mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.063" L x 0.031" W (1.60mm x 0.80mm)', 
  '0.039" (1.00mm)', 
  'MFBW1V1608', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '220 Ohms @ 100 MHz', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0603_1608.PCBLIB', 
  '1'
);

INSERT INTO "Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Footprint Ref",
  "Dc Resistance (Dcr) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD 1.2K OHM 0805 1LN', 
  '1.2 kOhms @ 100 MHz', 
  'BLM21HE122SH1L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/BLM21HE122SH1L/17184948', 
  '0805 (2012 Metric)', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'FERRITE CHIP', 
  '490-BLM21HE122SH1LCT-ND', 
  '1.6A', 
  'Active', 
  'Murata Electronics', 
  'Automotive', 
  '2023-02-25T20:49:13.217', 
  '1', 
  '3251', 
  '=Value', 
  '-55°C ~ 125°C', 
  'FER 0805_2012', 
  '110mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '0.057" (1.45mm)', 
  'BLM21H', 
  '0.10', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1.2 kOhms @ 100 MHz', 
  'Signal Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0805_2012.PCBLIB', 
  '1'
);

INSERT INTO "Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Dc Resistance (Dcr) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD 30 OHM 0805 1LN', 
  '30 Ohms @ 100 MHz', 
  'MFBW1V2012-300-R', 
  'https://www.digikey.com/en/products/detail/eaton-electronics-division/MFBW1V2012-300-R/13161158', 
  '0805 (2012 Metric)', 
  '0805 (2012 Metric)', 
  'FERRITE CHIP', 
  '283-MFBW1V2012-300-RCT-ND', 
  '3A', 
  'Active', 
  'Eaton - Electronics Division', 
  '2023-02-25T20:49:13.233', 
  '1', 
  '3252', 
  '=Value', 
  '-40°C ~ 85°C', 
  'https://www.eaton.com/content/dam/eaton/products/electronic-components/resources/data-sheet/eaton-mfbw1v2012-high-impedance-multilayer-ferrite-chip-bead-data-sheet.pdf', 
  'FER 0805_2012', 
  'Datasheet', 
  '50mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.047" W (2.00mm x 1.20mm)', 
  '0.043" (1.10mm)', 
  'MFBW1V2012', 
  '0.01', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '30 Ohms @ 100 MHz', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0805_2012.PCBLIB', 
  '1'
);

INSERT INTO "Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Footprint Ref",
  "Dc Resistance (Dcr) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD 4.7K OHM 0805 1LN', 
  '4.7 kOhms @ 100 MHz', 
  'BLM21HE472SH1L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/BLM21HE472SH1L/17184945', 
  '0805 (2012 Metric)', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'FERRITE CHIP', 
  '490-BLM21HE472SH1LCT-ND', 
  '850mA', 
  'Active', 
  'Murata Electronics', 
  'Automotive', 
  '2023-02-25T20:49:13.240', 
  '1', 
  '3253', 
  '=Value', 
  '-55°C ~ 125°C', 
  'FER 0805_2012', 
  '400mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '0.057" (1.45mm)', 
  'BLM21H', 
  '0.10', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '4.7 kOhms @ 100 MHz', 
  'Signal Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0805_2012.PCBLIB', 
  '1'
);

INSERT INTO "Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Footprint Ref",
  "Dc Resistance (Dcr) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD 4.7K OHM 0805 1LN', 
  '4.7 kOhms @ 100 MHz', 
  'BLM21HE472BH1L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/BLM21HE472BH1L/17184952', 
  '0805 (2012 Metric)', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'FERRITE CHIP', 
  '490-BLM21HE472BH1LCT-ND', 
  '850mA', 
  'Active', 
  'Murata Electronics', 
  'Automotive', 
  '2023-02-25T20:49:13.250', 
  '1', 
  '3254', 
  '=Value', 
  '-55°C ~ 125°C', 
  'FER 0805_2012', 
  '400mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '0.057" (1.45mm)', 
  'BLM21H', 
  '0.10', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '4.7 kOhms @ 100 MHz', 
  'Signal Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0805_2012.PCBLIB', 
  '1'
);

INSERT INTO "Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Footprint Ref",
  "Dc Resistance (Dcr) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD 1.2K OHM 0805 1LN', 
  '1.2 kOhms @ 100 MHz', 
  'BLM21HE122SN1L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/BLM21HE122SN1L/17184940', 
  '0805 (2012 Metric)', 
  '0805 (2012 Metric)', 
  'FERRITE CHIP', 
  '490-BLM21HE122SN1LCT-ND', 
  '1.6A', 
  'Active', 
  'Murata Electronics', 
  '2023-02-25T20:49:13.257', 
  '1', 
  '3255', 
  '=Value', 
  '-55°C ~ 125°C', 
  'FER 0805_2012', 
  '110mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '0.057" (1.45mm)', 
  'BLM21H', 
  '0.09', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1.2 kOhms @ 100 MHz', 
  'Signal Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0805_2012.PCBLIB', 
  '1'
);

INSERT INTO "Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Dc Resistance (Dcr) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD 4.7K OHM 0805 1LN', 
  '4.7 kOhms @ 100 MHz', 
  'BLM21HE472SN1L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/BLM21HE472SN1L/17184947', 
  '0805 (2012 Metric)', 
  '0805 (2012 Metric)', 
  'FERRITE CHIP', 
  '490-BLM21HE472SN1LCT-ND', 
  '850mA', 
  'Active', 
  'Murata Electronics', 
  '2023-02-25T20:49:13.267', 
  '1', 
  '3256', 
  '=Value', 
  '-55°C ~ 125°C', 
  'https://www.murata.com/products/productdata/8818051678238/ENFA0114.pdf', 
  'FER 0805_2012', 
  'Datasheet', 
  '400mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '0.057" (1.45mm)', 
  'BLM21H', 
  '0.09', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '4.7 kOhms @ 100 MHz', 
  'Signal Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0805_2012.PCBLIB', 
  '1'
);

INSERT INTO "Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Ratings",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "Footprint Ref",
  "Dc Resistance (Dcr) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD 1.2K OHM 0805 1LN', 
  '1.2 kOhms @ 100 MHz', 
  'BLM21HE122BH1L', 
  'https://www.digikey.com/en/products/detail/murata-electronics/BLM21HE122BH1L/17184950', 
  '0805 (2012 Metric)', 
  'AEC-Q200', 
  '0805 (2012 Metric)', 
  'FERRITE CHIP', 
  '490-BLM21HE122BH1LCT-ND', 
  '1.6A', 
  'Active', 
  'Murata Electronics', 
  'Automotive', 
  '2023-02-25T20:49:13.277', 
  '1', 
  '3257', 
  '=Value', 
  '-55°C ~ 125°C', 
  'FER 0805_2012', 
  '110mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.079" L x 0.049" W (2.00mm x 1.25mm)', 
  '0.057" (1.45mm)', 
  'BLM21H', 
  '0.10', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '1.2 kOhms @ 100 MHz', 
  'Signal Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 0805_2012.PCBLIB', 
  '1'
);

INSERT INTO "Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Dc Resistance (Dcr) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD 600 OHM 1206 1LN', 
  '600 Ohms @ 100 MHz', 
  'MFBM1V3216-601-R', 
  'https://www.digikey.com/en/products/detail/eaton-electronics-division/MFBM1V3216-601-R/13161228', 
  '1206 (3216 Metric)', 
  '1206 (3216 Metric)', 
  'FERRITE CHIP', 
  '283-MFBM1V3216-601-RCT-ND', 
  '2A', 
  'Active', 
  'Eaton - Electronics Division', 
  '2023-02-25T20:49:25.807', 
  '1', 
  '3258', 
  '=Value', 
  '-40°C ~ 85°C', 
  'https://www.eaton.com/content/dam/eaton/products/electronic-components/resources/data-sheet/eaton-mfbm1v3216-high-current-multilayer-ferrite-chip-bead-data-sheet.pdf', 
  'FER 1206_3216', 
  'Datasheet', 
  '100mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  '0.043" (1.10mm)', 
  'MFBM1V3216', 
  '0.03', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '600 Ohms @ 100 MHz', 
  'Power Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 1206_3216.PCBLIB', 
  '1'
);

INSERT INTO "Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Dc Resistance (Dcr) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD 50 OHM 1206 1LN', 
  '50 Ohms @ 100 MHz', 
  'MFBW1V3216-500-R', 
  'https://www.digikey.com/en/products/detail/eaton-electronics-division/MFBW1V3216-500-R/13161315', 
  '1206 (3216 Metric)', 
  '1206 (3216 Metric)', 
  'FERRITE CHIP', 
  '283-MFBW1V3216-500-RCT-ND', 
  '3A', 
  'Active', 
  'Eaton - Electronics Division', 
  '2023-02-25T20:49:25.823', 
  '1', 
  '3259', 
  '=Value', 
  '-40°C ~ 85°C', 
  'https://www.eaton.com/content/dam/eaton/products/electronic-components/resources/data-sheet/eaton-mfbw1v3216-high-impedance-multilayer-ferrite-chip-bead-data-sheet.pdf', 
  'FER 1206_3216', 
  'Datasheet', 
  '70mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  '0.043" (1.10mm)', 
  'MFBW1V3216', 
  '0.03', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '50 Ohms @ 100 MHz', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 1206_3216.PCBLIB', 
  '1'
);

INSERT INTO "Filters-FerriteBeadsAndChips" (
  "Description",
  "Impedance @ Frequency",
  "Part Number",
  "ComponentLink2URL",
  "Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Current Rating (Max)",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Dc Resistance (Dcr) (Max)",
  "Supplier 1",
  "Mounting Type",
  "Size / Dimension",
  "Height (Max)",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Value",
  "Filter Type",
  "ComponentLink2Description",
  "Footprint Path",
  "Number Of Lines"
)
VALUES (
  'FERRITE BEAD 300 OHM 1206 1LN', 
  '300 Ohms @ 100 MHz', 
  'MG3261-301Y', 
  'https://www.digikey.com/en/products/detail/bourns-inc/MG3261-301Y/2563308', 
  '1206 (3216 Metric)', 
  '1206 (3216 Metric)', 
  'FERRITE CHIP', 
  '118-MG3261-301YCT-ND', 
  '300mA', 
  'Active', 
  'Bourns Inc.', 
  '2023-02-25T20:49:27.130', 
  '1', 
  '3260', 
  '=Value', 
  '-55°C ~ 125°C', 
  '//media.digikey.com/pdf/Data%20Sheets/Bourns%20PDFs/mg,mu,mz.pdf', 
  'FER 1206_3216', 
  'Datasheet', 
  '300mOhm', 
  'DigiKey', 
  'Surface Mount', 
  '0.126" L x 0.063" W (3.20mm x 1.60mm)', 
  '0.051" (1.30mm)', 
  'MG', 
  '0.02', 
  'symbols/Passives/SCH - PASSIVES - FERRITE CHIP.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  '300 Ohms @ 100 MHz', 
  'Power, Signal Line', 
  'DigiKey Link', 
  'footprints/Ferrite - Chip/PCB - FERRITE - CHIP - FER 1206_3216.PCBLIB', 
  '1'
);

