--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Diodes-Rectifiers-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Diode Type",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Current - Average Rectified (Io)",
  "Operating Temperature - Junction",
  "PartId",
  "Comment",
  "Speed",
  "Capacitance @ Vr, F",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Reverse Recovery Time (Trr)",
  "Price",
  "Library Path",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - DC Reverse (Vr) (Max)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE GEN PURP 100V 250MA SOD523', 
  'BAS516,315', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/BAS516-315/2119384', 
  'Standard', 
  'SOD-523', 
  'SC-79, SOD-523', 
  'DIODE', 
  '1727-BAS516,315CT-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-04-04T20:02:08.353', 
  '1', 
  '250mA', 
  '150°C (Max)', 
  '3589', 
  '=Part Number', 
  'Fast Recovery =< 500ns, > 200mA (Io)', 
  '1pF @ 0V, 1MHz', 
  'https://assets.nexperia.com/documents/data-sheet/BAS16_SER.pdf', 
  'SOD-523', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '500 nA @ 80 V', 
  'Automotive, AEC-Q101, BAS16', 
  '4 ns', 
  '0.02', 
  'symbols/Diodes/SCH - DIODES - DIODE.SCHLIB', 
  '1.25 V @ 150 mA', 
  'TapeAndReel', 
  'Active', 
  '100 V', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD-523.PCBLIB'
);

