--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 27V 375MW SOD123F', 
  'BZT52H-C27,115', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/BZT52H-C27-115/1162848', 
  'SOD-123F', 
  'SOD-123F', 
  'DIODE ZENER', 
  '1727-BZT52H-C27,115CT-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-04-04T19:55:43.813', 
  '1', 
  '4261', 
  '=Part Number', 
  '-65°C ~ 150°C (TA)', 
  'https://assets.nexperia.com/documents/data-sheet/BZT52H_SER.pdf', 
  'SOD123F', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  'Surface Mount', 
  '50 nA @ 18.9 V', 
  'Automotive, AEC-Q101', 
  '0.02', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '375 mW', 
  '900 mV @ 10 mA', 
  'TapeAndReel', 
  'Active', 
  '27 V', 
  '40 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD123F.PCBLIB'
);

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 36V 310MW SOD323F', 
  'PZU36B,115', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/PZU36B-115/1162996', 
  'SOD-323F', 
  'SC-90, SOD-323F', 
  'DIODE ZENER', 
  '1727-3737-1-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-04-04T19:55:52.197', 
  '1', 
  '4262', 
  '=Part Number', 
  '-65°C ~ 150°C', 
  'https://assets.nexperia.com/documents/data-sheet/PZUXB_SER.pdf', 
  'SOD323F', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  'Surface Mount', 
  '50 nA @ 27 V', 
  'Automotive, AEC-Q100', 
  '0.04', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '310 mW', 
  '1.1 V @ 100 mA', 
  'TapeAndReel', 
  'Active', 
  '36 V', 
  '60 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD323F.PCBLIB'
);

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 13V 310MW SOD323F', 
  'PZU13B2,115', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/PZU13B2-115/1162949', 
  'SOD-323F', 
  'SC-90, SOD-323F', 
  'DIODE ZENER', 
  '1727-3691-1-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-04-04T19:55:52.217', 
  '1', 
  '4263', 
  '=Part Number', 
  '-65°C ~ 150°C', 
  'https://assets.nexperia.com/documents/data-sheet/PZUXB_SER.pdf', 
  'SOD323F', 
  'Datasheet', 
  '±2%', 
  'DigiKey', 
  'Surface Mount', 
  '100 nA @ 10 V', 
  'Automotive, AEC-Q100', 
  '0.04', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '310 mW', 
  '1.1 V @ 100 mA', 
  'TapeAndReel', 
  'Active', 
  '13 V', 
  '10 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD323F.PCBLIB'
);

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 5.6V 310MW SOD323F', 
  'PZU5.6B,115', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/PZU5-6B-115/1163009', 
  'SOD-323F', 
  'SC-90, SOD-323F', 
  'DIODE ZENER', 
  '1727-PZU5.6B,115CT-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-04-04T19:55:52.290', 
  '1', 
  '4264', 
  '=Part Number', 
  '-65°C ~ 150°C', 
  'https://assets.nexperia.com/documents/data-sheet/PZUXB_SER.pdf', 
  'SOD323F', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  'Surface Mount', 
  '1 µA @ 2.5 V', 
  'Automotive, AEC-Q100', 
  '0.04', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '310 mW', 
  '1.1 V @ 100 mA', 
  'TapeAndReel', 
  'Active', 
  '5.6 V', 
  '40 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD323F.PCBLIB'
);

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 18V 310MW SOD323F', 
  'PZU18B2,115', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/PZU18B2-115/1162963', 
  'SOD-323F', 
  'SC-90, SOD-323F', 
  'DIODE ZENER', 
  '1727-3704-1-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-04-04T19:55:52.317', 
  '1', 
  '4265', 
  '=Part Number', 
  '-65°C ~ 150°C', 
  'https://assets.nexperia.com/documents/data-sheet/PZUXB_SER.pdf', 
  'SOD323F', 
  'Datasheet', 
  '±2%', 
  'DigiKey', 
  'Surface Mount', 
  '50 nA @ 13 V', 
  'Automotive, AEC-Q100', 
  '0.04', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '310 mW', 
  '1.1 V @ 100 mA', 
  'TapeAndReel', 
  'Active', 
  '18 V', 
  '20 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD323F.PCBLIB'
);

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 18V 310MW SOD323F', 
  'PZU18B,115', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/PZU18B-115/1162961', 
  'SOD-323F', 
  'SC-90, SOD-323F', 
  'DIODE ZENER', 
  '1727-PZU18B,115CT-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-04-04T19:55:52.440', 
  '1', 
  '4266', 
  '=Part Number', 
  '-65°C ~ 150°C', 
  'https://assets.nexperia.com/documents/data-sheet/PZUXB_SER.pdf', 
  'SOD323F', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  'Surface Mount', 
  '50 nA @ 13 V', 
  'Automotive, AEC-Q100', 
  '0.04', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '310 mW', 
  '1.1 V @ 100 mA', 
  'TapeAndReel', 
  'Active', 
  '18 V', 
  '20 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD323F.PCBLIB'
);

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 2.7V 310MW SOD323F', 
  'PZU2.7B,115', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/PZU2-7B-115/1162966', 
  'SOD-323F', 
  'SC-90, SOD-323F', 
  'DIODE ZENER', 
  '1727-3707-1-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-04-04T19:55:52.460', 
  '1', 
  '4267', 
  '=Part Number', 
  '-65°C ~ 150°C', 
  'https://assets.nexperia.com/documents/data-sheet/PZUXB_SER.pdf', 
  'SOD323F', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  'Surface Mount', 
  '20 µA @ 1 V', 
  'Automotive, AEC-Q100', 
  '0.04', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '310 mW', 
  '1.1 V @ 100 mA', 
  'TapeAndReel', 
  'Active', 
  '2.7 V', 
  '100 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD323F.PCBLIB'
);

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 24V 310MW SOD323F', 
  'PZU24B,115', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/PZU24B-115/1162977', 
  'SOD-323F', 
  'SC-90, SOD-323F', 
  'DIODE ZENER', 
  '1727-3718-1-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-04-04T19:55:52.477', 
  '1', 
  '4268', 
  '=Part Number', 
  '-65°C ~ 150°C', 
  'https://assets.nexperia.com/documents/data-sheet/PZUXB_SER.pdf', 
  'SOD323F', 
  'Datasheet', 
  '±5%', 
  'DigiKey', 
  'Surface Mount', 
  '50 nA @ 19 V', 
  'Automotive, AEC-Q100', 
  '0.04', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '310 mW', 
  '1.1 V @ 100 mA', 
  'TapeAndReel', 
  'Active', 
  '24 V', 
  '30 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD323F.PCBLIB'
);

INSERT INTO "Diodes-Zener-Single" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Tolerance",
  "Supplier 1",
  "Mounting Type",
  "Current - Reverse Leakage @ Vr",
  "Series",
  "Price",
  "Library Path",
  "Power - Max",
  "Voltage - Forward (Vf) (Max) @ If",
  "Packaging",
  "Part Status",
  "Voltage - Zener (Nom) (Vz)",
  "Impedance (Max) (Zzt)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'DIODE ZENER 4.7V 300MW SOD523', 
  'BZX585-B4V7,135', 
  'https://www.digikey.com/en/products/detail/nexperia-usa-inc/BZX585-B4V7-135/1155814', 
  'SOD-523', 
  'SC-79, SOD-523', 
  'DIODE ZENER', 
  '1727-BZX585-B4V7,135CT-ND', 
  'Active', 
  'Nexperia USA Inc.', 
  '2023-04-04T19:56:02.163', 
  '1', 
  '4269', 
  '=Part Number', 
  '-65°C ~ 150°C', 
  'https://assets.nexperia.com/documents/data-sheet/BZX585_SERIES.pdf', 
  'SOD523F', 
  'Datasheet', 
  '±2%', 
  'DigiKey', 
  'Surface Mount', 
  '3 µA @ 2 V', 
  'Automotive, AEC-Q100', 
  '0.04', 
  'symbols/Diodes/SCH - DIODES - DIODE ZENER.SCHLIB', 
  '300 mW', 
  '1.1 V @ 100 mA', 
  'TapeAndReel', 
  'Active', 
  '4.7 V', 
  '80 Ohms', 
  'DigiKey Link', 
  'footprints/Diodes/PCB - DIODES - SOD523F.PCBLIB'
);

