--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Amplifiers-OP-AmpsAndBufferAmps" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Current - Input Bias",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "LastUpdated",
  "Minimum Order",
  "Amplifier Type",
  "PartId",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "-3db Bandwidth",
  "Supplier 1",
  "Current - Supply",
  "Mounting Type",
  "Number Of Circuits",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "Voltage - Supply, Single/Dual (±)",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'IC VARIABLE GAIN 1 CIRC 14TSSOP', 
  'AD8367ARUZ', 
  'https://www.digikey.com/en/products/detail/analog-devices-inc/AD8367ARUZ/819986', 
  '27 µA', 
  '14-TSSOP', 
  '14-TSSOP (0.173", 4.40mm Width)', 
  'AD AD8367', 
  '505-AD8367ARUZ-ND', 
  'Active', 
  'Analog Devices Inc.', 
  '2026-01-11T23:23:59.667', 
  '1', 
  'Variable Gain', 
  '106', 
  '=Part Number', 
  '-40°C ~ 85°C', 
  'https://www.analog.com/media/en/technical-documentation/data-sheets/AD8367.pdf', 
  'AD TSSOP-14 RU-14', 
  'Datasheet', 
  '500 MHz', 
  'DigiKey', 
  '26mA', 
  'Surface Mount', 
  '1', 
  'X-AMP®', 
  '7.78', 
  'symbols/VGA/SCH - VGA - AD AD8367.SchLib', 
  'Tube', 
  'Active', 
  '2.7V ~ 5.5V', 
  'DigiKey Link', 
  'footprints/Leaded - SOP/PCB - LEADED - SOP - AD TSSOP-14 RU-14.PcbLib'
);

