--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."Sensors-Motion-Accelerometers" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Output Type",
  "Supplier Device Package",
  "Package / Case",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Sensitivity (Lsb/G)",
  "Voltage - Supply",
  "Bandwidth",
  "Manufacturer",
  "Features",
  "LastUpdated",
  "Minimum Order",
  "Axis",
  "Comment",
  "Operating Temperature",
  "ComponentLink1URL",
  "Footprint Ref",
  "ComponentLink1Description",
  "Supplier 1",
  "Mounting Type",
  "Acceleration Range",
  "Series",
  "Type",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'ACCEL 2-16G I2C/SPI 12LGA', 
  'LIS2DW12TR', 
  'http://digikey.com/product-detail/en/stmicroelectronics/LIS2DW12TR/497-17718-1-ND/7914708', 
  'I²C, SPI', 
  '12-LGA (2x2)', 
  '12-WFLGA', 
  'ST LIS2DW12', 
  '497-17718-1-ND', 
  'Active', 
  '4098 (±2g) ~ 512 (±16g)', 
  '1.62V ~ 3.6V', 
  '400Hz', 
  'STMicroelectronics', 
  'Selectable Scale', 
  '2025-08-29T06:45:17.190', 
  '1', 
  'X, Y, Z', 
  '=Part Number', 
  '-40°C ~ 85°C', 
  'http://www.st.com/content/ccc/resource/technical/document/datasheet/group3/30/3a/4e/6b/68/16/4a/35/DM00323179/files/DM00323179.pdf/jcr:content/translations/en.DM00323179.pdf', 
  'ST LGA-12 2x2MM', 
  'Datasheet', 
  'DigiKey', 
  'Surface Mount', 
  '±2g, 4g, 8g, 16g', 
  '-', 
  'Digital', 
  '0.85', 
  'symbols/Sensor - Motion/SCH - SENSOR - MOTION - ST LIS2DW12.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Leadless - Misc/PCB - LEADLESS - MISC - ST LGA-12 2x2MM.PCBLIB'
);

