--liquibase formatted sql
--changeset Stanislav_Vodolagin:1

INSERT INTO "altium"."BatteryHoldersClipsContacts" (
  "Description",
  "Part Number",
  "ComponentLink2URL",
  "Height Above Board",
  "Battery Type, Function",
  "Library Ref",
  "Supplier Part Number 1",
  "Lifecycle Status",
  "Manufacturer",
  "Style",
  "LastUpdated",
  "Minimum Order",
  "PartId",
  "Comment",
  "ComponentLink1URL",
  "Footprint Ref",
  "Termination Style",
  "Battery Series",
  "ComponentLink1Description",
  "Battery Cell Size",
  "Supplier 1",
  "Mounting Type",
  "Number Of Cells",
  "Series",
  "Price",
  "Library Path",
  "Packaging",
  "Part Status",
  "ComponentLink2Description",
  "Footprint Path"
)
VALUES (
  'BATTERY RETAINER COIN 20MM SMD', 
  '3034TR', 
  'https://www.digikey.com/en/products/detail/keystone-electronics/3034TR/4499408', 
  '0.160" (4.06mm)', 
  'Coin Cell, Retainer', 
  'KEYSTONE 3034TR', 
  '36-3034CT-ND', 
  'Active', 
  'Keystone Electronics', 
  'Retainer', 
  '2025-08-29T03:23:39.483', 
  '1', 
  '8', 
  '=Part Number', 
  'http://keyelco.com/userAssets/file/M65p9.pdf', 
  'KEYSTONE 3034TR', 
  'SMD (SMT) Tab', 
  '2020, 2025, 2032', 
  'Datasheet', 
  'Coin, 20.0mm', 
  'DigiKey', 
  'PCB, Surface Mount', 
  '1', 
  '-', 
  '0.20', 
  'symbols/Battery/SCH - BATTERY - KEYSTONE 3034TR.SCHLIB', 
  'TapeAndReel', 
  'Active', 
  'DigiKey Link', 
  'footprints/Battery Holder/PCB - BATTERY HOLDER - KEYSTONE 3034TR.PCBLIB'
);

